#if !defined(RTE_CMDPWM_HOOK_H)
#define RTE_CMDPWM_HOOK_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains Rte hook declarations for the software component type CMDPWM
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.57
  * on Mon Nov 03 12:24:33 CET 2014. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#include <Rte_Cfg.h>         /* RTE VFB configuration header file */
#include <Rte_Type.h>     /* Rte type definitions header file */

/*==================[macros]=================================================*/

#if (!defined RTE_CORE) /* if included by software component */
#ifndef RTE_VFB_TRACE
#define RTE_VFB_TRACE (0)
#endif /* RTE_VFB_TRACE */
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Start)
#undef Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Start(P2VAR(dt_Cf_cooling_fan_equipment, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Return)
#undef Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Return(P2VAR(dt_Cf_cooling_fan_equipment, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Cf_cooling_fan_equipment_Cf_cooling_fan_equipment_Return */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Start)
#undef Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Start(P2VAR(dt_Commande_GMV_C, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Return)
#undef Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Return(P2VAR(dt_Commande_GMV_C, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_GMV_C_Commande_GMV_C_Return */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Start)
#undef Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Start(P2VAR(dt_Commande_vvt_ech_pwm_rco, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Return)
#undef Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Return(P2VAR(dt_Commande_vvt_ech_pwm_rco, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_vvt_ech_pwm_rco_Commande_vvt_ech_pwm_rco_Return */
#if defined(Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Start)
#undef Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Start(P2VAR(dt_Demande_inhibition_hbridge, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Return)
#undef Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Return(P2VAR(dt_Demande_inhibition_hbridge, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Demande_inhibition_hbridge_Demande_inhibition_hbridge_Return */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Start)
#undef Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Start(P2VAR(dt_Commande_purge_pwm_freq, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Return)
#undef Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Return(P2VAR(dt_Commande_purge_pwm_freq, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_freq_Commande_purge_pwm_freq_Return */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Start)
#undef Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Start(P2VAR(dt_Commande_purge_pwm_rco, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Return)
#undef Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Return(P2VAR(dt_Commande_purge_pwm_rco, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_purge_pwm_rco_Commande_purge_pwm_rco_Return */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Start)
#undef Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Start(P2VAR(dt_Commande_pompe_ess_pwm, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Return)
#undef Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Return(P2VAR(dt_Commande_pompe_ess_pwm, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_pompe_ess_pwm_Commande_pompe_ess_pwm_Return */
#if defined(Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Start)
#undef Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Start(P2VAR(dt_Ctrl_bAcv_FuTnkPmp, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Return)
#undef Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Return(P2VAR(dt_Ctrl_bAcv_FuTnkPmp, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_FuTnkPmp_Ctrl_bAcv_FuTnkPmp_Return */
#if defined(Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Start)
#undef Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Start(P2VAR(dt_ECU_bImmoUnlockWkuSt, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Start */
#if defined(Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Return)
#undef Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Return(P2VAR(dt_ECU_bImmoUnlockWkuSt, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_ECU_bImmoUnlockWkuSt_ECU_bImmoUnlockWkuSt_Return */
#if defined(Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Start)
#undef Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Start(P2VAR(DT_ECU_bWkuMain, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Start */
#if defined(Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Return)
#undef Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Return(P2VAR(DT_ECU_bWkuMain, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_ECU_bWkuMain_ECU_bWkuMain_Return */
#if defined(Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Start)
#undef Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Start(P2VAR(DT_UCE_bPwrlAcv, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Start */
#if defined(Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Return)
#undef Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Return(P2VAR(DT_UCE_bPwrlAcv, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_UCE_bPwrlAcv_UCE_bPwrlAcv_Return */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Start)
#undef Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Start(P2VAR(dt_Commande_bpm_pwm_rco, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Return)
#undef Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Return(P2VAR(dt_Commande_bpm_pwm_rco, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_bpm_pwm_rco_Commande_bpm_pwm_rco_Return */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Start)
#undef Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Start(P2VAR(dt_Commande_ectdrv_pwm_rco, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Return)
#undef Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Return(P2VAR(dt_Commande_ectdrv_pwm_rco, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_ectdrv_pwm_rco_Commande_ectdrv_pwm_rco_Return */
#if defined(Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Start)
#undef Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Start(P2VAR(dt_Ctrl_bAcv_ECTReq, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Return)
#undef Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Return(P2VAR(dt_Ctrl_bAcv_ECTReq, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Ctrl_bAcv_ECTReq_Ctrl_bAcv_ECTReq_Return */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Start
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Start)
#undef Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Start
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Start(P2VAR(dt_Commande_vvt_adm_pwm_rco, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Start(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Start */
#if defined(Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Return
#endif
#if defined(Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Return)
#undef Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Return
extern FUNC(void, RTE_APPL_CODE) Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Return(P2VAR(dt_Commande_vvt_adm_pwm_rco, AUTOMATIC, RTE_APPL_DATA) data);
#else
#define Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Return(data) ((void)0)
#endif /* Rte_ReadHook_CMDPWM_R_Commande_vvt_adm_pwm_rco_Commande_vvt_adm_pwm_rco_Return */
#if defined(Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Start
#endif
#if defined(Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Start)
#undef Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Start(void);
#else
#define Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Start() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Start */
#if defined(Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Return
#endif
#if defined(Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Return)
#undef Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Return(void);
#else
#define Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Return() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_CoFan_SdlMid_CmdPwmCoFan_Return */
#if defined(Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Start
#endif
#if defined(Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Start)
#undef Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Start(void);
#else
#define Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Start() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Start */
#if defined(Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Return
#endif
#if defined(Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Return)
#undef Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Return(void);
#else
#define Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Return() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActEx_Return */
#if defined(Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Start
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Start)
#undef Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Start(void);
#else
#define Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Start() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Start */
#if defined(Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Return
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Return)
#undef Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Return(void);
#else
#define Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Return() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Thr_SdlMid_CmdPwmThrCmd_Return */
#if defined(Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Start
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Start)
#undef Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Start(void);
#else
#define Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Start() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Start */
#if defined(Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Return
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Return)
#undef Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Return(void);
#else
#define Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Return() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Thr_EveRst_CmdPwmThrCmd_Return */
#if defined(Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Start
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Start)
#undef Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Start(void);
#else
#define Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Start() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Start */
#if defined(Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Return
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Return)
#undef Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Return(void);
#else
#define Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Return() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Cstr_EveRst_CmdPwmCstr_Return */
#if defined(Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Start
#endif
#if defined(Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Start)
#undef Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Start(void);
#else
#define Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Start() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Start */
#if defined(Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Return
#endif
#if defined(Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Return)
#undef Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Return(void);
#else
#define Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Return() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_FuPmp_SdlFast_CmdPwmPropFuPmp_Return */
#if defined(Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Start
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Start)
#undef Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Start(void);
#else
#define Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Start() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Start */
#if defined(Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Return
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Return)
#undef Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Return(void);
#else
#define Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Return() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Thr_EveClcnServo_CmdPwmThrCmd_Return */
#if defined(Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Start
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Start)
#undef Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Start(void);
#else
#define Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Start() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Start */
#if defined(Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Return
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Return)
#undef Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Return(void);
#else
#define Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Return() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Ext_EveRst_CmdPwm_Return */
#if defined(Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Start
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Start)
#undef Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Start(void);
#else
#define Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Start() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Start */
#if defined(Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Return
#endif
#if defined(Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Return)
#undef Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Return(void);
#else
#define Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Return() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_Cstr_SdlMid_CmdPwmCstr_Return */
#if defined(Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Start
#endif
#if defined(Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Start)
#undef Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Start(void);
#else
#define Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Start() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Start */
#if defined(Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Return
#endif
#if defined(Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Return)
#undef Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Return(void);
#else
#define Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Return() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_CoFan_SdlSlow_CmdPmwECTCmd_Return */
#if defined(Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Start
#endif
#if defined(Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Start)
#undef Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Start(void);
#else
#define Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Start() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Start */
#if defined(Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Return
#endif
#if defined(Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Return)
#undef Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Return(void);
#else
#define Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Return() ((void)0)
#endif /* Rte_Runnable_CMDPWM_RE_VlvAct_SdlFast_CmdPwmVlvActIn_Return */

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/
/** @} doxygen end group definition */
#endif /* !defined(RTE_CMDPWM_HOOK_H) */
/*==================[end of file]============================================*/

