#if !defined(RTE_ADVMAXT_H)
#define RTE_ADVMAXT_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains Rte component declarations for component type ADVMAXT
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.57
  * on Mon Nov 03 12:24:28 CET 2014. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <Rte_Intern_Application_Core1.h>
#include <Rte_Main.h>         /* RTE main header file */
#include <Rte_ADVMAXT_Type.h> /* RTE application types header file */
#include <Rte_Hook.h> /* RTE VFB trace hooks header file */

/*==================[macros]=================================================*/

#if (!defined RTE_CORE) /* if included by software component */

#if (!defined RTE_APPLICATION_HEADER_FILE_H) /* prevent double inclusion */
#define RTE_APPLICATION_HEADER_FILE_H
#else
#error Multiple application header files included.
#endif /* if !defined( RTE_APPLICATION_HEADER_FILE_H ) */

#endif

/*------------------[API mapping]--------------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
#if !defined(RTE_RUNNABLEAPI_RE_AdvMaxT_002_DRE)
#define Rte_Write_P_IgSys_agIgMaxWiPrevAdpMv_IgSys_agIgMaxWiPrevAdpMv(data) Rte_Write_ADVMAXT_P_IgSys_agIgMaxWiPrevAdpMv_IgSys_agIgMaxWiPrevAdpMv(data)

#define Rte_Write_P_IgSys_prm_agIgMaxWiPrevAdpCyl_IgSys_prm_agIgMaxWiPrevAdpCyl(data) Rte_Write_ADVMAXT_P_IgSys_prm_agIgMaxWiPrevAdpCyl_IgSys_prm_agIgMaxWiPrevAdpCyl(data)

#endif
#define Rte_Write_P_IgSys_agIgKnkAdpOfsMv_IgSys_agIgKnkAdpOfsMv(data) Rte_Write_ADVMAXT_P_IgSys_agIgKnkAdpOfsMv_IgSys_agIgKnkAdpOfsMv(data)

#define Rte_Write_P_IgSys_agIgMaxWiPrevMv_IgSys_agIgMaxWiPrevMv(data) Rte_Write_ADVMAXT_P_IgSys_agIgMaxWiPrevMv_IgSys_agIgMaxWiPrevMv(data)

#if !defined(RTE_RUNNABLEAPI_RE_AdvMaxT_001_MSE)
#define Rte_Read_R_IgSys_agIgMaxGas_IgSys_agIgMaxGas(data) Rte_Read_ADVMAXT_R_IgSys_agIgMaxGas_IgSys_agIgMaxGas(data)

#define Rte_IsUpdated_R_IgSys_agIgMaxGas_IgSys_agIgMaxGas() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1982.isUpdated)

#define Rte_Read_R_IgSys_rAirLdClc_IgSys_rAirLdClc(data) Rte_Read_ADVMAXT_R_IgSys_rAirLdClc_IgSys_rAirLdClc(data)

#define Rte_IsUpdated_R_IgSys_rAirLdClc_IgSys_rAirLdClc() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1977.isUpdated)

#define Rte_Read_R_IgSys_prm_agIgMaxWiPrevAdpCyl_IgSys_prm_agIgMaxWiPrevAdpCyl(data) Rte_Read_ADVMAXT_R_IgSys_prm_agIgMaxWiPrevAdpCyl_IgSys_prm_agIgMaxWiPrevAdpCyl(data)

#define Rte_IsUpdated_R_IgSys_prm_agIgMaxWiPrevAdpCyl_IgSys_prm_agIgMaxWiPrevAdpCyl() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1987.isUpdated)

#define Rte_Read_R_IgSys_prm_facFlex_IgSys_prm_facFlex(data) Rte_Read_ADVMAXT_R_IgSys_prm_facFlex_IgSys_prm_facFlex(data)

#define Rte_IsUpdated_R_IgSys_prm_facFlex_IgSys_prm_facFlex() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1980.isUpdated)

#define Rte_Read_R_IgSys_agIgCmbModOfsMax_IgSys_agIgCmbModOfsMax(data) Rte_Read_ADVMAXT_R_IgSys_agIgCmbModOfsMax_IgSys_agIgCmbModOfsMax(data)

#define Rte_IsUpdated_R_IgSys_agIgCmbModOfsMax_IgSys_agIgCmbModOfsMax() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1978.isUpdated)

#define Rte_Read_R_IgSys_prm_facGas_IgSys_prm_facGas(data) Rte_Read_ADVMAXT_R_IgSys_prm_facGas_IgSys_prm_facGas(data)

#define Rte_IsUpdated_R_IgSys_prm_facGas_IgSys_prm_facGas() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1981.isUpdated)

#define Rte_Read_R_Eng_stEru_Eng_stEru(data) Rte_Read_ADVMAXT_R_Eng_stEru_Eng_stEru(data)

#define Rte_IsUpdated_R_Eng_stEru_Eng_stEru() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1971.isUpdated)

#define Rte_Read_R_IgSys_agIgMaxFlex_IgSys_agIgMaxFlex(data) Rte_Read_ADVMAXT_R_IgSys_agIgMaxFlex_IgSys_agIgMaxFlex(data)

#define Rte_IsUpdated_R_IgSys_agIgMaxFlex_IgSys_agIgMaxFlex() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1979.isUpdated)

#define Rte_Read_R_KnkMgt_prm_agIgKnkAdpOfsCyl_KnkMgt_prm_agIgKnkAdpOfsCyl(data) Rte_Read_ADVMAXT_R_KnkMgt_prm_agIgKnkAdpOfsCyl_KnkMgt_prm_agIgKnkAdpOfsCyl(data)

#define Rte_IsUpdated_R_KnkMgt_prm_agIgKnkAdpOfsCyl_KnkMgt_prm_agIgKnkAdpOfsCyl() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1983.isUpdated)

#define Rte_Read_R_Ext_agCkOpInVlvEstimRef0_Ext_agCkOpInVlvEstimRef0(data) Rte_Read_ADVMAXT_R_Ext_agCkOpInVlvEstimRef0_Ext_agCkOpInVlvEstimRef0(data)

#define Rte_IsUpdated_R_Ext_agCkOpInVlvEstimRef0_Ext_agCkOpInVlvEstimRef0() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1973.isUpdated)

#define Rte_Read_R_IgSys_agIgMaxWiPrevMv_IgSys_agIgMaxWiPrevMv(data) Rte_Read_ADVMAXT_R_IgSys_agIgMaxWiPrevMv_IgSys_agIgMaxWiPrevMv(data)

#define Rte_IsUpdated_R_IgSys_agIgMaxWiPrevMv_IgSys_agIgMaxWiPrevMv() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1984.isUpdated)

#define Rte_Read_R_IgSys_agIgMaxWiPrevAdpMv_IgSys_agIgMaxWiPrevAdpMv(data) Rte_Read_ADVMAXT_R_IgSys_agIgMaxWiPrevAdpMv_IgSys_agIgMaxWiPrevAdpMv(data)

#define Rte_IsUpdated_R_IgSys_agIgMaxWiPrevAdpMv_IgSys_agIgMaxWiPrevAdpMv() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1985.isUpdated)

#define Rte_Read_R_IgSys_agIgKnkPrevOfs_IgSys_agIgKnkPrevOfs(data) Rte_Read_ADVMAXT_R_IgSys_agIgKnkPrevOfs_IgSys_agIgKnkPrevOfs(data)

#define Rte_IsUpdated_R_IgSys_agIgKnkPrevOfs_IgSys_agIgKnkPrevOfs() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1975.isUpdated)

#define Rte_Read_R_EngM_rAirLdCor_EngM_rAirLdCor(data) Rte_Read_ADVMAXT_R_EngM_rAirLdCor_EngM_rAirLdCor(data)

#define Rte_IsUpdated_R_EngM_rAirLdCor_EngM_rAirLdCor() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1972.isUpdated)

#define Rte_Read_R_Ext_nEng_Ext_nEng(data) Rte_Read_ADVMAXT_R_Ext_nEng_Ext_nEng(data)

#define Rte_IsUpdated_R_Ext_nEng_Ext_nEng() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1970.isUpdated)

#define Rte_Read_R_IgSys_agIgKnkAdpOfsMv_IgSys_agIgKnkAdpOfsMv(data) Rte_Read_ADVMAXT_R_IgSys_agIgKnkAdpOfsMv_IgSys_agIgKnkAdpOfsMv(data)

#define Rte_IsUpdated_R_IgSys_agIgKnkAdpOfsMv_IgSys_agIgKnkAdpOfsMv() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1986.isUpdated)

#define Rte_Read_R_Ext_agCkClsExVlvEstimRef0_Ext_agCkClsExVlvEstimRef0(data) Rte_Read_ADVMAXT_R_Ext_agCkClsExVlvEstimRef0_Ext_agCkClsExVlvEstimRef0(data)

#define Rte_IsUpdated_R_Ext_agCkClsExVlvEstimRef0_Ext_agCkClsExVlvEstimRef0() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1974.isUpdated)

#define Rte_Read_R_IgSys_bAirLdDynDet_IgSys_bAirLdDynDet(data) Rte_Read_ADVMAXT_R_IgSys_bAirLdDynDet_IgSys_bAirLdDynDet(data)

#define Rte_IsUpdated_R_IgSys_bAirLdDynDet_IgSys_bAirLdDynDet() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1976.isUpdated)

#define Rte_Read_R_EV_AdvMaxT_002_DRE_EV_AdvMaxT_002_DRE(data) Rte_Read_ADVMAXT_R_EV_AdvMaxT_002_DRE_EV_AdvMaxT_002_DRE(data)

#define Rte_IsUpdated_R_EV_AdvMaxT_002_DRE_EV_AdvMaxT_002_DRE() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1969.isUpdated)

#endif

#endif

/*------------------[port handle API mapping]--------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*------------------[application errors]-------------------------------------*/

/*------------------[init values]--------------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#define Rte_InitValue_P_IgSys_agIgMaxWiPrevMv_IgSys_agIgMaxWiPrevMv 255U
#define Rte_InitValue_P_IgSys_agIgMaxWiPrevAdpMv_IgSys_agIgMaxWiPrevAdpMv 255U
#define Rte_InitValue_P_IgSys_agIgKnkAdpOfsMv_IgSys_agIgKnkAdpOfsMv 96U
#define Rte_InitValue_R_EV_AdvMaxT_002_DRE_EV_AdvMaxT_002_DRE 0U
#define Rte_InitValue_R_Ext_nEng_Ext_nEng 0U
#define Rte_InitValue_R_Eng_stEru_Eng_stEru 1U
#define Rte_InitValue_R_EngM_rAirLdCor_EngM_rAirLdCor 0U
#define Rte_InitValue_R_Ext_agCkOpInVlvEstimRef0_Ext_agCkOpInVlvEstimRef0 -1024
#define Rte_InitValue_R_Ext_agCkClsExVlvEstimRef0_Ext_agCkClsExVlvEstimRef0 -1024
#define Rte_InitValue_R_IgSys_agIgKnkPrevOfs_IgSys_agIgKnkPrevOfs 96U
#define Rte_InitValue_R_IgSys_bAirLdDynDet_IgSys_bAirLdDynDet 0U
#define Rte_InitValue_R_IgSys_rAirLdClc_IgSys_rAirLdClc 0U
#define Rte_InitValue_R_IgSys_agIgCmbModOfsMax_IgSys_agIgCmbModOfsMax 96U
#define Rte_InitValue_R_IgSys_agIgMaxFlex_IgSys_agIgMaxFlex 96U
#define Rte_InitValue_R_IgSys_agIgMaxGas_IgSys_agIgMaxGas 96U
#define Rte_InitValue_R_IgSys_agIgMaxWiPrevMv_IgSys_agIgMaxWiPrevMv 255U
#define Rte_InitValue_R_IgSys_agIgMaxWiPrevAdpMv_IgSys_agIgMaxWiPrevAdpMv 255U
#define Rte_InitValue_R_IgSys_agIgKnkAdpOfsMv_IgSys_agIgKnkAdpOfsMv 96U

#endif

/*==================[type definitions]=======================================*/

/*------------------[instance handle type]-----------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
typedef CONSTP2CONST(Rte_CDS_ADVMAXT, RTE_CONST, RTE_CONST) Rte_Instance;
#endif

/*------------------[port handle types]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
#endif

/*------------------[per instance memory types]------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*==================[external function declarations]=========================*/

/*------------------[declaration of runnable entities]-----------------------*/

#define RTE_START_SEC_APPLICATION_CORE1_APPL_CODE
#include "MemMap.h"

extern FUNC(void, RTE_APPL_CODE) RE_AdvMaxT_001_MSE(void);

extern FUNC(void, RTE_APPL_CODE) RE_AdvMaxT_002_DRE(void);

#define RTE_STOP_SEC_APPLICATION_CORE1_APPL_CODE
#include "MemMap.h"

/*--------------[declaration of API functions provided by Rte]--------------*/

#define RTE_START_SEC_APPLICATION_CORE1_CODE
#include "MemMap.h"
#if (!defined(RTE_RUNNABLEAPI_RE_AdvMaxT_002_DRE))
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_ADVMAXT_P_IgSys_agIgMaxWiPrevAdpMv_IgSys_agIgMaxWiPrevAdpMv (DT_IgSys_agIgMaxWiPrevAdpMv data);

#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_ADVMAXT_P_IgSys_prm_agIgMaxWiPrevAdpCyl_IgSys_prm_agIgMaxWiPrevAdpCyl (P2CONST(rt_Array_UInt8_6_m2, AUTOMATIC, RTE_APPL_CONST) data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_ADVMAXT_P_IgSys_prm_agIgMaxWiPrevAdpCyl_IgSys_prm_agIgMaxWiPrevAdpCyl (P2CONST(DT_IgSys_prm_agIgMaxWiPrevAdpCyl, AUTOMATIC, RTE_APPL_CONST) data);
#endif

#endif
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_ADVMAXT_P_IgSys_agIgKnkAdpOfsMv_IgSys_agIgKnkAdpOfsMv (DT_IgSys_agIgKnkAdpOfsMv data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_ADVMAXT_P_IgSys_agIgMaxWiPrevMv_IgSys_agIgMaxWiPrevMv (DT_IgSys_agIgMaxWiPrevMv data);

#if (!defined(RTE_RUNNABLEAPI_RE_AdvMaxT_001_MSE))
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_agIgMaxGas_IgSys_agIgMaxGas (P2VAR(DT_IgSys_agIgMaxGas, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_rAirLdClc_IgSys_rAirLdClc (P2VAR(DT_IgSys_rAirLdClc, AUTOMATIC, RTE_APPL_DATA) data);

#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_prm_agIgMaxWiPrevAdpCyl_IgSys_prm_agIgMaxWiPrevAdpCyl (P2VAR(rt_Array_UInt8_6_m2, AUTOMATIC, RTE_APPL_DATA) data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_prm_agIgMaxWiPrevAdpCyl_IgSys_prm_agIgMaxWiPrevAdpCyl (P2VAR(DT_IgSys_prm_agIgMaxWiPrevAdpCyl, AUTOMATIC, RTE_APPL_DATA) data);
#endif

#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_prm_facFlex_IgSys_prm_facFlex (P2VAR(rt_Array_UInt8_10_m0, AUTOMATIC, RTE_APPL_DATA) data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_prm_facFlex_IgSys_prm_facFlex (P2VAR(DT_IgSys_prm_facFlex, AUTOMATIC, RTE_APPL_DATA) data);
#endif

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_agIgCmbModOfsMax_IgSys_agIgCmbModOfsMax (P2VAR(DT_IgSys_agIgCmbModOfsMax, AUTOMATIC, RTE_APPL_DATA) data);

#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_prm_facGas_IgSys_prm_facGas (P2VAR(rt_Array_UInt8_10_m1, AUTOMATIC, RTE_APPL_DATA) data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_prm_facGas_IgSys_prm_facGas (P2VAR(DT_IgSys_prm_facGas, AUTOMATIC, RTE_APPL_DATA) data);
#endif

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_Eng_stEru_Eng_stEru (P2VAR(DT_Eng_stEru, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_agIgMaxFlex_IgSys_agIgMaxFlex (P2VAR(DT_IgSys_agIgMaxFlex, AUTOMATIC, RTE_APPL_DATA) data);

#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_KnkMgt_prm_agIgKnkAdpOfsCyl_KnkMgt_prm_agIgKnkAdpOfsCyl (P2VAR(rt_Array_UInt8_6_m5, AUTOMATIC, RTE_APPL_DATA) data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_KnkMgt_prm_agIgKnkAdpOfsCyl_KnkMgt_prm_agIgKnkAdpOfsCyl (P2VAR(DT_KnkMgt_prm_agIgKnkAdpOfsCyl, AUTOMATIC, RTE_APPL_DATA) data);
#endif

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_Ext_agCkOpInVlvEstimRef0_Ext_agCkOpInVlvEstimRef0 (P2VAR(DT_Ext_agCkOpInVlvEstimRef0, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_agIgMaxWiPrevMv_IgSys_agIgMaxWiPrevMv (P2VAR(DT_IgSys_agIgMaxWiPrevMv, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_agIgMaxWiPrevAdpMv_IgSys_agIgMaxWiPrevAdpMv (P2VAR(DT_IgSys_agIgMaxWiPrevAdpMv, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_agIgKnkPrevOfs_IgSys_agIgKnkPrevOfs (P2VAR(DT_IgSys_agIgKnkPrevOfs, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_EngM_rAirLdCor_EngM_rAirLdCor (P2VAR(DT_EngM_rAirLdCor, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_Ext_nEng_Ext_nEng (P2VAR(DT_Ext_nEng, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_agIgKnkAdpOfsMv_IgSys_agIgKnkAdpOfsMv (P2VAR(DT_IgSys_agIgKnkAdpOfsMv, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_Ext_agCkClsExVlvEstimRef0_Ext_agCkClsExVlvEstimRef0 (P2VAR(DT_Ext_agCkClsExVlvEstimRef0, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_IgSys_bAirLdDynDet_IgSys_bAirLdDynDet (P2VAR(DT_IgSys_bAirLdDynDet, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ADVMAXT_R_EV_AdvMaxT_002_DRE_EV_AdvMaxT_002_DRE (P2VAR(DT_EV_AdvMaxT_002_DRE, AUTOMATIC, RTE_APPL_DATA) data);

#endif

#define RTE_STOP_SEC_APPLICATION_CORE1_CODE
#include "MemMap.h"

/*--------------[declaration of API functions provided by other Appl]--------*/

#define RTE_START_SEC_APPLICATION_CORE1_APPL_CODE
#include "MemMap.h"

#if (!defined RTE_CORE) /* if included by software component */

#endif /* (!defined RTE_CORE) */

#define RTE_STOP_SEC_APPLICATION_CORE1_APPL_CODE
#include "MemMap.h"

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*------------------[instance handle declaration]----------------------------*/
#define RTE_START_SEC_APPLICATION_CORE1_CONST_UNSPECIFIED
#include "MemMap.h"

extern CONSTP2CONST(Rte_CDS_ADVMAXT, RTE_CONST, RTE_CONST) Rte_Inst_ADVMAXT;

#define RTE_STOP_SEC_APPLICATION_CORE1_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(RTE_ADVMAXT_H) */
/*==================[end of file]============================================*/

