#if !defined(RTE_PRODELEM_TYPE_H)
#define RTE_PRODELEM_TYPE_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains the application-specific types for component type PRODELEM
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.57
  * on Mon Nov 03 12:24:30 CET 2014. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <Rte_Type.h>         /* RTE types header file */

/*==================[macros]=================================================*/

/*------------------[enumeration constants]----------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#ifndef BatMgt_stBattSoC_Nominal
#define BatMgt_stBattSoC_Nominal 0U
#endif /* BatMgt_stBattSoC_Nominal */

#ifndef BatMgt_stBattSoC_Degrade
#define BatMgt_stBattSoC_Degrade 1U
#endif /* BatMgt_stBattSoC_Degrade */

#ifndef BatMgt_stBattSoC_Defaut
#define BatMgt_stBattSoC_Defaut 2U
#endif /* BatMgt_stBattSoC_Defaut */

#ifndef BatMgt_stBattSoC_Invalide
#define BatMgt_stBattSoC_Invalide 3U
#endif /* BatMgt_stBattSoC_Invalide */

#ifndef ECU_bWkuMain_le_CMM_n_est_pas_en_reveil_principal_ou_reveil_principal_degrade
#define ECU_bWkuMain_le_CMM_n_est_pas_en_reveil_principal_ou_reveil_principal_degrade 0U
#endif /* ECU_bWkuMain_le_CMM_n_est_pas_en_reveil_principal_ou_reveil_principal_degrade */

#ifndef ECU_bWkuMain_le_CMM_est_en_reveil_principal_ou_reveil_principal_degrade
#define ECU_bWkuMain_le_CMM_est_en_reveil_principal_ou_reveil_principal_degrade 1U
#endif /* ECU_bWkuMain_le_CMM_est_en_reveil_principal_ou_reveil_principal_degrade */

#ifndef Ext_bAuthWupElMgt_Pas_Autorise
#define Ext_bAuthWupElMgt_Pas_Autorise 0U
#endif /* Ext_bAuthWupElMgt_Pas_Autorise */

#ifndef Ext_bAuthWupElMgt_Autorise
#define Ext_bAuthWupElMgt_Autorise 1U
#endif /* Ext_bAuthWupElMgt_Autorise */

#ifndef Ext_bNotAvl_rBattSoC_Information_disponible
#define Ext_bNotAvl_rBattSoC_Information_disponible 0U
#endif /* Ext_bNotAvl_rBattSoC_Information_disponible */

#ifndef Ext_bNotAvl_rBattSoC_Information_indisponible
#define Ext_bNotAvl_rBattSoC_Information_indisponible 1U
#endif /* Ext_bNotAvl_rBattSoC_Information_indisponible */

#ifndef Ext_bNotAvl_tBattMes_Disponible
#define Ext_bNotAvl_tBattMes_Disponible 0U
#endif /* Ext_bNotAvl_tBattMes_Disponible */

#ifndef Ext_bNotAvl_tBattMes_Indisponible
#define Ext_bNotAvl_tBattMes_Indisponible 1U
#endif /* Ext_bNotAvl_tBattMes_Indisponible */

#ifndef Ext_bSTTCf_STT_inhibe
#define Ext_bSTTCf_STT_inhibe 0U
#endif /* Ext_bSTTCf_STT_inhibe */

#ifndef Ext_bSTTCf_STT_actif
#define Ext_bSTTCf_STT_actif 1U
#endif /* Ext_bSTTCf_STT_actif */

#ifndef Ext_stElProdCf_Alternateur_standard
#define Ext_stElProdCf_Alternateur_standard 0U
#endif /* Ext_stElProdCf_Alternateur_standard */

#ifndef Ext_stElProdCf_Alternateur_pilote
#define Ext_stElProdCf_Alternateur_pilote 1U
#endif /* Ext_stElProdCf_Alternateur_pilote */

#ifndef Ext_stElProdCf_Alternateur_reversible
#define Ext_stElProdCf_Alternateur_reversible 2U
#endif /* Ext_stElProdCf_Alternateur_reversible */

#ifndef Ext_stElProdCf_Convertisseur_DC_div_DC
#define Ext_stElProdCf_Convertisseur_DC_div_DC 3U
#endif /* Ext_stElProdCf_Convertisseur_DC_div_DC */

#ifndef TqLimUH_bFrzReqTqVoltCtl_pas_de_demande
#define TqLimUH_bFrzReqTqVoltCtl_pas_de_demande 0U
#endif /* TqLimUH_bFrzReqTqVoltCtl_pas_de_demande */

#ifndef TqLimUH_bFrzReqTqVoltCtl_demande_de_figeage
#define TqLimUH_bFrzReqTqVoltCtl_demande_de_figeage 1U
#endif /* TqLimUH_bFrzReqTqVoltCtl_demande_de_figeage */

#ifndef TqLimUH_stDrivTyp_reserve_0
#define TqLimUH_stDrivTyp_reserve_0 0U
#endif /* TqLimUH_stDrivTyp_reserve_0 */

#ifndef TqLimUH_stDrivTyp_autoroute
#define TqLimUH_stDrivTyp_autoroute 1U
#endif /* TqLimUH_stDrivTyp_autoroute */

#ifndef TqLimUH_stDrivTyp_route
#define TqLimUH_stDrivTyp_route 2U
#endif /* TqLimUH_stDrivTyp_route */

#ifndef TqLimUH_stDrivTyp_ville
#define TqLimUH_stDrivTyp_ville 3U
#endif /* TqLimUH_stDrivTyp_ville */

#ifndef TqLimUH_stDrivTyp_warmup
#define TqLimUH_stDrivTyp_warmup 4U
#endif /* TqLimUH_stDrivTyp_warmup */

#ifndef TqLimUH_stDrivTyp_CdT
#define TqLimUH_stDrivTyp_CdT 5U
#endif /* TqLimUH_stDrivTyp_CdT */

#ifndef TqLimUH_stDrivTyp_reserve_6
#define TqLimUH_stDrivTyp_reserve_6 6U
#endif /* TqLimUH_stDrivTyp_reserve_6 */

#ifndef TqLimUH_stDrivTyp_reserve_7
#define TqLimUH_stDrivTyp_reserve_7 7U
#endif /* TqLimUH_stDrivTyp_reserve_7 */

#ifndef TqLimUH_stReqBlsVoltCtl_pas_de_demande
#define TqLimUH_stReqBlsVoltCtl_pas_de_demande 0U
#endif /* TqLimUH_stReqBlsVoltCtl_pas_de_demande */

#ifndef TqLimUH_stReqBlsVoltCtl_lestage_maximum
#define TqLimUH_stReqBlsVoltCtl_lestage_maximum 1U
#endif /* TqLimUH_stReqBlsVoltCtl_lestage_maximum */

#ifndef TqLimUH_stReqBlsVoltCtl_lestage_moyen
#define TqLimUH_stReqBlsVoltCtl_lestage_moyen 2U
#endif /* TqLimUH_stReqBlsVoltCtl_lestage_moyen */

#ifndef TqLimUH_stReqBlsVoltCtl_reserve_3
#define TqLimUH_stReqBlsVoltCtl_reserve_3 3U
#endif /* TqLimUH_stReqBlsVoltCtl_reserve_3 */

#ifndef TqLimUH_stReqUnBlsVoltCtl_pas_de_demande
#define TqLimUH_stReqUnBlsVoltCtl_pas_de_demande 0U
#endif /* TqLimUH_stReqUnBlsVoltCtl_pas_de_demande */

#ifndef TqLimUH_stReqUnBlsVoltCtl_delestage_Brio
#define TqLimUH_stReqUnBlsVoltCtl_delestage_Brio 1U
#endif /* TqLimUH_stReqUnBlsVoltCtl_delestage_Brio */

#ifndef TqLimUH_stReqUnBlsVoltCtl_delestage_anti_calage
#define TqLimUH_stReqUnBlsVoltCtl_delestage_anti_calage 2U
#endif /* TqLimUH_stReqUnBlsVoltCtl_delestage_anti_calage */

#ifndef TqLimUH_stReqUnBlsVoltCtl_demande_de_delestage_demarrage
#define TqLimUH_stReqUnBlsVoltCtl_demande_de_delestage_demarrage 3U
#endif /* TqLimUH_stReqUnBlsVoltCtl_demande_de_delestage_demarrage */

#ifndef TqLimUH_stReqUnBlsVoltCtl_delestage_opti_vide
#define TqLimUH_stReqUnBlsVoltCtl_delestage_opti_vide 4U
#endif /* TqLimUH_stReqUnBlsVoltCtl_delestage_opti_vide */

#ifndef Afts_bInhStSoCBatt_Pas_de_demande
#define Afts_bInhStSoCBatt_Pas_de_demande 0U
#endif /* Afts_bInhStSoCBatt_Pas_de_demande */

#ifndef Afts_bInhStSoCBatt_Demande
#define Afts_bInhStSoCBatt_Demande 1U
#endif /* Afts_bInhStSoCBatt_Demande */

#ifndef CoOptmEl_bAuthAntiAgiStra_Pas_d_autorisation
#define CoOptmEl_bAuthAntiAgiStra_Pas_d_autorisation 0U
#endif /* CoOptmEl_bAuthAntiAgiStra_Pas_d_autorisation */

#ifndef CoOptmEl_bAuthAntiAgiStra_recharge_forcee_possible
#define CoOptmEl_bAuthAntiAgiStra_recharge_forcee_possible 1U
#endif /* CoOptmEl_bAuthAntiAgiStra_recharge_forcee_possible */

#ifndef Ext_bArchiCf_Architecture_2004
#define Ext_bArchiCf_Architecture_2004 0U
#endif /* Ext_bArchiCf_Architecture_2004 */

#ifndef Ext_bArchiCf_Architecture_2010
#define Ext_bArchiCf_Architecture_2010 1U
#endif /* Ext_bArchiCf_Architecture_2010 */

#ifndef Ext_bNotAvl_iBattMes_Information_disponible
#define Ext_bNotAvl_iBattMes_Information_disponible 0U
#endif /* Ext_bNotAvl_iBattMes_Information_disponible */

#ifndef Ext_bNotAvl_iBattMes_Information_indisponible
#define Ext_bNotAvl_iBattMes_Information_indisponible 1U
#endif /* Ext_bNotAvl_iBattMes_Information_indisponible */

#ifndef Ext_bNotAvl_resBattIt_Information_disponible
#define Ext_bNotAvl_resBattIt_Information_disponible 0U
#endif /* Ext_bNotAvl_resBattIt_Information_disponible */

#ifndef Ext_bNotAvl_resBattIt_Information_indisponible
#define Ext_bNotAvl_resBattIt_Information_indisponible 1U
#endif /* Ext_bNotAvl_resBattIt_Information_indisponible */

#ifndef Ext_bNotAvl_uBattClc_Information_disponible
#define Ext_bNotAvl_uBattClc_Information_disponible 0U
#endif /* Ext_bNotAvl_uBattClc_Information_disponible */

#ifndef Ext_bNotAvl_uBattClc_Information_indisponible
#define Ext_bNotAvl_uBattClc_Information_indisponible 1U
#endif /* Ext_bNotAvl_uBattClc_Information_indisponible */

#ifndef Ext_bNotAvl_uBattOc_Information_disponible
#define Ext_bNotAvl_uBattOc_Information_disponible 0U
#endif /* Ext_bNotAvl_uBattOc_Information_disponible */

#ifndef Ext_bNotAvl_uBattOc_Information_indisponible
#define Ext_bNotAvl_uBattOc_Information_indisponible 1U
#endif /* Ext_bNotAvl_uBattOc_Information_indisponible */

#ifndef Ext_bNotAvl_uBattRstrt_valeur_disponible
#define Ext_bNotAvl_uBattRstrt_valeur_disponible 0U
#endif /* Ext_bNotAvl_uBattRstrt_valeur_disponible */

#ifndef Ext_bNotAvl_uBattRstrt_valeur_indisponible
#define Ext_bNotAvl_uBattRstrt_valeur_indisponible 1U
#endif /* Ext_bNotAvl_uBattRstrt_valeur_indisponible */

#ifndef Ext_stBattSoC_Estimation_SOC_nominale
#define Ext_stBattSoC_Estimation_SOC_nominale 0U
#endif /* Ext_stBattSoC_Estimation_SOC_nominale */

#ifndef Ext_stBattSoC_Estimation_SOC_degradee
#define Ext_stBattSoC_Estimation_SOC_degradee 1U
#endif /* Ext_stBattSoC_Estimation_SOC_degradee */

#ifndef Ext_stBattSoC_En_defaut
#define Ext_stBattSoC_En_defaut 2U
#endif /* Ext_stBattSoC_En_defaut */

#ifndef Ext_stBattSoC_Estimation_SOC_non_pertinente
#define Ext_stBattSoC_Estimation_SOC_non_pertinente 3U
#endif /* Ext_stBattSoC_Estimation_SOC_non_pertinente */

#ifndef Ext_stBattTypCf__42_Ah
#define Ext_stBattTypCf__42_Ah 0U
#endif /* Ext_stBattTypCf__42_Ah */

#ifndef Ext_stBattTypCf__50_Ah
#define Ext_stBattTypCf__50_Ah 1U
#endif /* Ext_stBattTypCf__50_Ah */

#ifndef Ext_stBattTypCf__55_Ah
#define Ext_stBattTypCf__55_Ah 2U
#endif /* Ext_stBattTypCf__55_Ah */

#ifndef Ext_stBattTypCf__60_Ah
#define Ext_stBattTypCf__60_Ah 3U
#endif /* Ext_stBattTypCf__60_Ah */

#ifndef Ext_stBattTypCf__64_Ah
#define Ext_stBattTypCf__64_Ah 4U
#endif /* Ext_stBattTypCf__64_Ah */

#ifndef Ext_stBattTypCf__70_Ah
#define Ext_stBattTypCf__70_Ah 5U
#endif /* Ext_stBattTypCf__70_Ah */

#ifndef Ext_stBattTypCf__75_Ah
#define Ext_stBattTypCf__75_Ah 6U
#endif /* Ext_stBattTypCf__75_Ah */

#ifndef Ext_stBattTypCf__80_Ah
#define Ext_stBattTypCf__80_Ah 7U
#endif /* Ext_stBattTypCf__80_Ah */

#ifndef Ext_stBattTypCf__82_Ah
#define Ext_stBattTypCf__82_Ah 8U
#endif /* Ext_stBattTypCf__82_Ah */

#ifndef Ext_stBattTypCf__90_Ah
#define Ext_stBattTypCf__90_Ah 9U
#endif /* Ext_stBattTypCf__90_Ah */

#ifndef Ext_stBattTypCf__95_Ah
#define Ext_stBattTypCf__95_Ah 10U
#endif /* Ext_stBattTypCf__95_Ah */

#ifndef Ext_stBattTypCf_reserve_11
#define Ext_stBattTypCf_reserve_11 11U
#endif /* Ext_stBattTypCf_reserve_11 */

#ifndef Ext_stBattTypCf_reserve_12
#define Ext_stBattTypCf_reserve_12 12U
#endif /* Ext_stBattTypCf_reserve_12 */

#ifndef Ext_stBattTypCf_reserve_13
#define Ext_stBattTypCf_reserve_13 13U
#endif /* Ext_stBattTypCf_reserve_13 */

#ifndef Ext_stBattTypCf_reserve_14
#define Ext_stBattTypCf_reserve_14 14U
#endif /* Ext_stBattTypCf_reserve_14 */

#ifndef Ext_stBattTypCf_reserve_15
#define Ext_stBattTypCf_reserve_15 15U
#endif /* Ext_stBattTypCf_reserve_15 */

#ifndef BatMgt_bBattAntiAgiAcvReq_Pas_de_demande
#define BatMgt_bBattAntiAgiAcvReq_Pas_de_demande 0U
#endif /* BatMgt_bBattAntiAgiAcvReq_Pas_de_demande */

#ifndef BatMgt_bBattAntiAgiAcvReq_Demande
#define BatMgt_bBattAntiAgiAcvReq_Demande 1U
#endif /* BatMgt_bBattAntiAgiAcvReq_Demande */

#ifndef BatMgt_bBattChProtAcvReq_Pas_de_demande
#define BatMgt_bBattChProtAcvReq_Pas_de_demande 0U
#endif /* BatMgt_bBattChProtAcvReq_Pas_de_demande */

#ifndef BatMgt_bBattChProtAcvReq_Demande
#define BatMgt_bBattChProtAcvReq_Demande 1U
#endif /* BatMgt_bBattChProtAcvReq_Demande */

#ifndef BatMgt_bBattSoCMinProtAcvReq_Pas_de_demande
#define BatMgt_bBattSoCMinProtAcvReq_Pas_de_demande 0U
#endif /* BatMgt_bBattSoCMinProtAcvReq_Pas_de_demande */

#ifndef BatMgt_bBattSoCMinProtAcvReq_Demande
#define BatMgt_bBattSoCMinProtAcvReq_Demande 1U
#endif /* BatMgt_bBattSoCMinProtAcvReq_Demande */

#ifndef BatMgt_bBattStopPrepAcvReq_Pas_de_demande
#define BatMgt_bBattStopPrepAcvReq_Pas_de_demande 0U
#endif /* BatMgt_bBattStopPrepAcvReq_Pas_de_demande */

#ifndef BatMgt_bBattStopPrepAcvReq_Demande
#define BatMgt_bBattStopPrepAcvReq_Demande 1U
#endif /* BatMgt_bBattStopPrepAcvReq_Demande */

#ifndef BatMgt_bBattTProtAcvReq_Pas_de_demande
#define BatMgt_bBattTProtAcvReq_Pas_de_demande 0U
#endif /* BatMgt_bBattTProtAcvReq_Pas_de_demande */

#ifndef BatMgt_bBattTProtAcvReq_Demande
#define BatMgt_bBattTProtAcvReq_Demande 1U
#endif /* BatMgt_bBattTProtAcvReq_Demande */

#ifndef BatMgt_stBattSoH_Bon
#define BatMgt_stBattSoH_Bon 0U
#endif /* BatMgt_stBattSoH_Bon */

#ifndef BatMgt_stBattSoH_Moyen
#define BatMgt_stBattSoH_Moyen 1U
#endif /* BatMgt_stBattSoH_Moyen */

#ifndef BatMgt_stBattSoH_Faible
#define BatMgt_stBattSoH_Faible 2U
#endif /* BatMgt_stBattSoH_Faible */

#ifndef BatMgt_stBattSoH_Indisponible
#define BatMgt_stBattSoH_Indisponible 3U
#endif /* BatMgt_stBattSoH_Indisponible */

#ifndef CoEmCkg_stStrtRstrtFbCmd_Authorized
#define CoEmCkg_stStrtRstrtFbCmd_Authorized 0U
#endif /* CoEmCkg_stStrtRstrtFbCmd_Authorized */

#ifndef CoEmCkg_stStrtRstrtFbCmd_Activated
#define CoEmCkg_stStrtRstrtFbCmd_Activated 1U
#endif /* CoEmCkg_stStrtRstrtFbCmd_Activated */

#ifndef CoEmCkg_stStrtRstrtFbCmd_Forbidden
#define CoEmCkg_stStrtRstrtFbCmd_Forbidden 2U
#endif /* CoEmCkg_stStrtRstrtFbCmd_Forbidden */

#ifndef CoEmCkg_stStrtRstrtFbCmd_Failure
#define CoEmCkg_stStrtRstrtFbCmd_Failure 3U
#endif /* CoEmCkg_stStrtRstrtFbCmd_Failure */

#ifndef CoEmSTT_bVSSAcvSt_maintien_inactif
#define CoEmSTT_bVSSAcvSt_maintien_inactif 0U
#endif /* CoEmSTT_bVSSAcvSt_maintien_inactif */

#ifndef CoEmSTT_bVSSAcvSt_maintien_actif
#define CoEmSTT_bVSSAcvSt_maintien_actif 1U
#endif /* CoEmSTT_bVSSAcvSt_maintien_actif */

#ifndef CoPt_noEgdGearCord_Neutre_ou_debraye
#define CoPt_noEgdGearCord_Neutre_ou_debraye 0U
#endif /* CoPt_noEgdGearCord_Neutre_ou_debraye */

#ifndef CoPt_noEgdGearCord_Rapport_1
#define CoPt_noEgdGearCord_Rapport_1 1U
#endif /* CoPt_noEgdGearCord_Rapport_1 */

#ifndef CoPt_noEgdGearCord_Rapport_2
#define CoPt_noEgdGearCord_Rapport_2 2U
#endif /* CoPt_noEgdGearCord_Rapport_2 */

#ifndef CoPt_noEgdGearCord_Rapport_3
#define CoPt_noEgdGearCord_Rapport_3 3U
#endif /* CoPt_noEgdGearCord_Rapport_3 */

#ifndef CoPt_noEgdGearCord_Rapport_4
#define CoPt_noEgdGearCord_Rapport_4 4U
#endif /* CoPt_noEgdGearCord_Rapport_4 */

#ifndef CoPt_noEgdGearCord_Rapport_5
#define CoPt_noEgdGearCord_Rapport_5 5U
#endif /* CoPt_noEgdGearCord_Rapport_5 */

#ifndef CoPt_noEgdGearCord_Rapport_6
#define CoPt_noEgdGearCord_Rapport_6 6U
#endif /* CoPt_noEgdGearCord_Rapport_6 */

#ifndef CoPt_noEgdGearCord_Marche_Arriere
#define CoPt_noEgdGearCord_Marche_Arriere 7U
#endif /* CoPt_noEgdGearCord_Marche_Arriere */

#ifndef CoPtSynt_stPwt_Coupe
#define CoPtSynt_stPwt_Coupe 1U
#endif /* CoPtSynt_stPwt_Coupe */

#ifndef CoPtSynt_stPwt_Coupure_en_cours
#define CoPtSynt_stPwt_Coupure_en_cours 3U
#endif /* CoPtSynt_stPwt_Coupure_en_cours */

#ifndef CoPtSynt_stPwt_Demarrage
#define CoPtSynt_stPwt_Demarrage 5U
#endif /* CoPtSynt_stPwt_Demarrage */

#ifndef CoPtSynt_stPwt_Mobilite_active
#define CoPtSynt_stPwt_Mobilite_active 7U
#endif /* CoPtSynt_stPwt_Mobilite_active */

#ifndef CoPtSynt_stPwt_Tournant
#define CoPtSynt_stPwt_Tournant 9U
#endif /* CoPtSynt_stPwt_Tournant */

#ifndef CoPtSynt_stPwt_Arret_en_cours
#define CoPtSynt_stPwt_Arret_en_cours 11U
#endif /* CoPtSynt_stPwt_Arret_en_cours */

#ifndef CoPtSynt_stPwt_Arret
#define CoPtSynt_stPwt_Arret 13U
#endif /* CoPtSynt_stPwt_Arret */

#ifndef CoPtSynt_stPwt_Redemarrage
#define CoPtSynt_stPwt_Redemarrage 15U
#endif /* CoPtSynt_stPwt_Redemarrage */

#ifndef CoPtSynt_stPwt_Calage_en_cours
#define CoPtSynt_stPwt_Calage_en_cours 21U
#endif /* CoPtSynt_stPwt_Calage_en_cours */

#ifndef CoPtSynt_stPwt_Cale
#define CoPtSynt_stPwt_Cale 23U
#endif /* CoPtSynt_stPwt_Cale */

#ifndef CoPtSynt_stPwt_Sortie_calage
#define CoPtSynt_stPwt_Sortie_calage 25U
#endif /* CoPtSynt_stPwt_Sortie_calage */

#ifndef CoPtUH_stTypSTTNotAvl_Reserve
#define CoPtUH_stTypSTTNotAvl_Reserve 0U
#endif /* CoPtUH_stTypSTTNotAvl_Reserve */

#ifndef CoPtUH_stTypSTTNotAvl_indisponibilite_indeterminee
#define CoPtUH_stTypSTTNotAvl_indisponibilite_indeterminee 1U
#endif /* CoPtUH_stTypSTTNotAvl_indisponibilite_indeterminee */

#ifndef CoPtUH_stTypSTTNotAvl_indisponibilie_moyenne
#define CoPtUH_stTypSTTNotAvl_indisponibilie_moyenne 2U
#endif /* CoPtUH_stTypSTTNotAvl_indisponibilie_moyenne */

#ifndef CoPtUH_stTypSTTNotAvl_indisponibilite_longue
#define CoPtUH_stTypSTTNotAvl_indisponibilite_longue 3U
#endif /* CoPtUH_stTypSTTNotAvl_indisponibilite_longue */

#ifndef CoStrtRStrt_stAcvReq_Pas_de_dmd
#define CoStrtRStrt_stAcvReq_Pas_de_dmd 0U
#endif /* CoStrtRStrt_stAcvReq_Pas_de_dmd */

#ifndef CoStrtRStrt_stAcvReq_Dmd_de_Demarrage
#define CoStrtRStrt_stAcvReq_Dmd_de_Demarrage 1U
#endif /* CoStrtRStrt_stAcvReq_Dmd_de_Demarrage */

#ifndef CoStrtRStrt_stAcvReq_Dmd_de_Redemarrage
#define CoStrtRStrt_stAcvReq_Dmd_de_Redemarrage 2U
#endif /* CoStrtRStrt_stAcvReq_Dmd_de_Redemarrage */

#ifndef ElecMgt_stPrioVoltMax_gravite_2
#define ElecMgt_stPrioVoltMax_gravite_2 2U
#endif /* ElecMgt_stPrioVoltMax_gravite_2 */

#ifndef ElecMgt_stPrioVoltMax_gravite_3
#define ElecMgt_stPrioVoltMax_gravite_3 3U
#endif /* ElecMgt_stPrioVoltMax_gravite_3 */

#ifndef ElecMgt_stPrioVoltMax_gravite_4
#define ElecMgt_stPrioVoltMax_gravite_4 4U
#endif /* ElecMgt_stPrioVoltMax_gravite_4 */

#ifndef ElecMgt_stPrioVoltMin_gravite_2
#define ElecMgt_stPrioVoltMin_gravite_2 2U
#endif /* ElecMgt_stPrioVoltMin_gravite_2 */

#ifndef ElecMgt_stPrioVoltMin_gravite_3
#define ElecMgt_stPrioVoltMin_gravite_3 3U
#endif /* ElecMgt_stPrioVoltMin_gravite_3 */

#ifndef ElecMgt_stPrioVoltMin_gravite_4
#define ElecMgt_stPrioVoltMin_gravite_4 4U
#endif /* ElecMgt_stPrioVoltMin_gravite_4 */

#ifndef ElProdMgt_bAcvCoefFilDftAlt_Pas_d_activation
#define ElProdMgt_bAcvCoefFilDftAlt_Pas_d_activation 0U
#endif /* ElProdMgt_bAcvCoefFilDftAlt_Pas_d_activation */

#ifndef ElProdMgt_bAcvCoefFilDftAlt_Activation
#define ElProdMgt_bAcvCoefFilDftAlt_Activation 1U
#endif /* ElProdMgt_bAcvCoefFilDftAlt_Activation */

#ifndef Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Feux_de_croisement_seuls
#define Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Feux_de_croisement_seuls 1U
#endif /* Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Feux_de_croisement_seuls */

#ifndef Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Feux_route
#define Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Feux_route 2U
#endif /* Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Feux_route */

#ifndef Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Pulseur_air_habitacle
#define Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Pulseur_air_habitacle 4U
#endif /* Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Pulseur_air_habitacle */

#ifndef Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_FSE
#define Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_FSE 8U
#endif /* Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_FSE */

#ifndef Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Essuyage_pare_brise
#define Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Essuyage_pare_brise 16U
#endif /* Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Essuyage_pare_brise */

#ifndef Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Lavage_pare_brise
#define Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Lavage_pare_brise 32U
#endif /* Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Lavage_pare_brise */

#ifndef Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_GMV_pour_besoin_Clim
#define Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_GMV_pour_besoin_Clim 64U
#endif /* Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_GMV_pour_besoin_Clim */

#ifndef Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Durabilite_organes_EE
#define Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Durabilite_organes_EE 128U
#endif /* Ext_bfAcvConstElMgt1_Besoin_QRDB_GEI_Durabilite_organes_EE */

#ifndef Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_City_Park
#define Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_City_Park 1U
#endif /* Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_City_Park */

#ifndef Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_Besoin_Usine_Terminale
#define Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_Besoin_Usine_Terminale 2U
#endif /* Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_Besoin_Usine_Terminale */

#ifndef Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_Besoin_securite_LAS
#define Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_Besoin_securite_LAS 4U
#endif /* Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_Besoin_securite_LAS */

#ifndef Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_1
#define Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_1 8U
#endif /* Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_1 */

#ifndef Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_2
#define Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_2 16U
#endif /* Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_2 */

#ifndef Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_3
#define Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_3 32U
#endif /* Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_3 */

#ifndef Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_4
#define Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_4 64U
#endif /* Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_4 */

#ifndef Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_5
#define Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_5 128U
#endif /* Ext_bfAcvConstElMgt2_Besoin_QRDB_GEI_5 */

#ifndef Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_6
#define Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_6 1U
#endif /* Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_6 */

#ifndef Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_7
#define Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_7 2U
#endif /* Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_7 */

#ifndef Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_8
#define Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_8 4U
#endif /* Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_8 */

#ifndef Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_9
#define Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_9 8U
#endif /* Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_9 */

#ifndef Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_10
#define Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_10 16U
#endif /* Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_10 */

#ifndef Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_11
#define Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_11 32U
#endif /* Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_11 */

#ifndef Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_12
#define Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_12 64U
#endif /* Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_12 */

#ifndef Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_13
#define Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_13 128U
#endif /* Ext_bfAcvConstElMgt3_Besoin_QRDB_GEI_13 */

#ifndef Ext_bfAcvConstEng1_Besoin_QRDB_MTH_MJP
#define Ext_bfAcvConstEng1_Besoin_QRDB_MTH_MJP 1U
#endif /* Ext_bfAcvConstEng1_Besoin_QRDB_MTH_MJP */

#ifndef Ext_bfAcvConstEng1_Besoin_QRDB_MTH_Bougies
#define Ext_bfAcvConstEng1_Besoin_QRDB_MTH_Bougies 2U
#endif /* Ext_bfAcvConstEng1_Besoin_QRDB_MTH_Bougies */

#ifndef Ext_bfAcvConstEng1_Besoin_QRDB_MTH_Sural
#define Ext_bfAcvConstEng1_Besoin_QRDB_MTH_Sural 4U
#endif /* Ext_bfAcvConstEng1_Besoin_QRDB_MTH_Sural */

#ifndef Ext_bfAcvConstEng1_Besoin_QRDB_MTH_GMV
#define Ext_bfAcvConstEng1_Besoin_QRDB_MTH_GMV 8U
#endif /* Ext_bfAcvConstEng1_Besoin_QRDB_MTH_GMV */

#ifndef Ext_bfAcvConstEng1_Besoin_QRDB_MTH_SCR_injection_uree
#define Ext_bfAcvConstEng1_Besoin_QRDB_MTH_SCR_injection_uree 16U
#endif /* Ext_bfAcvConstEng1_Besoin_QRDB_MTH_SCR_injection_uree */

#ifndef Ext_bfAcvConstEng1_Besoin_QRDB_MTH_RG_FAP
#define Ext_bfAcvConstEng1_Besoin_QRDB_MTH_RG_FAP 32U
#endif /* Ext_bfAcvConstEng1_Besoin_QRDB_MTH_RG_FAP */

#ifndef Ext_bfAcvConstEng1_Besoin_QRDB_MTH_chauffe_electrique_SCR
#define Ext_bfAcvConstEng1_Besoin_QRDB_MTH_chauffe_electrique_SCR 64U
#endif /* Ext_bfAcvConstEng1_Besoin_QRDB_MTH_chauffe_electrique_SCR */

#ifndef Ext_bfAcvConstEng1_Besoin_QRDB_MTH_mise_en_thermique_SCR
#define Ext_bfAcvConstEng1_Besoin_QRDB_MTH_mise_en_thermique_SCR 128U
#endif /* Ext_bfAcvConstEng1_Besoin_QRDB_MTH_mise_en_thermique_SCR */

#ifndef Ext_stAltClasCf_Classe_6
#define Ext_stAltClasCf_Classe_6 0U
#endif /* Ext_stAltClasCf_Classe_6 */

#ifndef Ext_stAltClasCf_Classe_7
#define Ext_stAltClasCf_Classe_7 1U
#endif /* Ext_stAltClasCf_Classe_7 */

#ifndef Ext_stAltClasCf_Classe_8
#define Ext_stAltClasCf_Classe_8 2U
#endif /* Ext_stAltClasCf_Classe_8 */

#ifndef Ext_stAltClasCf_Classe_9
#define Ext_stAltClasCf_Classe_9 3U
#endif /* Ext_stAltClasCf_Classe_9 */

#ifndef Ext_stAltClasCf_Classe_12
#define Ext_stAltClasCf_Classe_12 4U
#endif /* Ext_stAltClasCf_Classe_12 */

#ifndef Ext_stAltClasCf_Classe_15
#define Ext_stAltClasCf_Classe_15 5U
#endif /* Ext_stAltClasCf_Classe_15 */

#ifndef Ext_stAltClasCf_Classe_18
#define Ext_stAltClasCf_Classe_18 6U
#endif /* Ext_stAltClasCf_Classe_18 */

#ifndef Ext_stAltClasCf_Reserve
#define Ext_stAltClasCf_Reserve 7U
#endif /* Ext_stAltClasCf_Reserve */

#ifndef Ext_stVSSCf_Pas_de_DMT
#define Ext_stVSSCf_Pas_de_DMT 0U
#endif /* Ext_stVSSCf_Pas_de_DMT */

#ifndef Ext_stVSSCf_DMTC
#define Ext_stVSSCf_DMTC 1U
#endif /* Ext_stVSSCf_DMTC */

#ifndef Ext_stVSSCf_DMTR
#define Ext_stVSSCf_DMTR 2U
#endif /* Ext_stVSSCf_DMTR */

#ifndef Ext_stVSSCf_reserve_3
#define Ext_stVSSCf_reserve_3 3U
#endif /* Ext_stVSSCf_reserve_3 */

#ifndef StopStrtEng_stCdnNxtCkg_Nominal
#define StopStrtEng_stCdnNxtCkg_Nominal 0U
#endif /* StopStrtEng_stCdnNxtCkg_Nominal */

#ifndef StopStrtEng_stCdnNxtCkg_Favorable
#define StopStrtEng_stCdnNxtCkg_Favorable 1U
#endif /* StopStrtEng_stCdnNxtCkg_Favorable */

#ifndef StopStrtEng_stCdnNxtCkg_Defavorable
#define StopStrtEng_stCdnNxtCkg_Defavorable 2U
#endif /* StopStrtEng_stCdnNxtCkg_Defavorable */

#ifndef TqDem_bTqGrdLim_Pas_de_demande
#define TqDem_bTqGrdLim_Pas_de_demande 0U
#endif /* TqDem_bTqGrdLim_Pas_de_demande */

#ifndef TqDem_bTqGrdLim_Demande
#define TqDem_bTqGrdLim_Demande 1U
#endif /* TqDem_bTqGrdLim_Demande */

#ifndef Afts_bLrnRstReq_rOfsSoC_Pas_de_demande
#define Afts_bLrnRstReq_rOfsSoC_Pas_de_demande 0U
#endif /* Afts_bLrnRstReq_rOfsSoC_Pas_de_demande */

#ifndef Afts_bLrnRstReq_rOfsSoC_Demande
#define Afts_bLrnRstReq_rOfsSoC_Demande 1U
#endif /* Afts_bLrnRstReq_rOfsSoC_Demande */

#ifndef Afts_bRstReq_stSoHBatt_Pas_de_demande
#define Afts_bRstReq_stSoHBatt_Pas_de_demande 0U
#endif /* Afts_bRstReq_stSoHBatt_Pas_de_demande */

#ifndef Afts_bRstReq_stSoHBatt_Demande
#define Afts_bRstReq_stSoHBatt_Demande 1U
#endif /* Afts_bRstReq_stSoHBatt_Demande */

#ifndef Afts_bRstReqStcBatt_Pas_de_demande
#define Afts_bRstReqStcBatt_Pas_de_demande 0U
#endif /* Afts_bRstReqStcBatt_Pas_de_demande */

#ifndef Afts_bRstReqStcBatt_Demande
#define Afts_bRstReqStcBatt_Demande 1U
#endif /* Afts_bRstReqStcBatt_Demande */

#ifndef CoOptmEl_stOptmElCf_VC4
#define CoOptmEl_stOptmElCf_VC4 0U
#endif /* CoOptmEl_stOptmElCf_VC4 */

#ifndef CoOptmEl_stOptmElCf_VC3
#define CoOptmEl_stOptmElCf_VC3 1U
#endif /* CoOptmEl_stOptmElCf_VC3 */

#ifndef CoOptmEl_stOptmElCf_Specifique_1
#define CoOptmEl_stOptmElCf_Specifique_1 2U
#endif /* CoOptmEl_stOptmElCf_Specifique_1 */

#ifndef CoOptmEl_stOptmElCf_Specifique_2
#define CoOptmEl_stOptmElCf_Specifique_2 3U
#endif /* CoOptmEl_stOptmElCf_Specifique_2 */

#ifndef CoOptmEl_stStraVoltBatt_Strategie_optimale
#define CoOptmEl_stStraVoltBatt_Strategie_optimale 0U
#endif /* CoOptmEl_stStraVoltBatt_Strategie_optimale */

#ifndef CoOptmEl_stStraVoltBatt_Strategie_Tbatt_seule
#define CoOptmEl_stStraVoltBatt_Strategie_Tbatt_seule 1U
#endif /* CoOptmEl_stStraVoltBatt_Strategie_Tbatt_seule */

#ifndef CoOptmEl_stStraVoltBatt_Compensation_thermique
#define CoOptmEl_stStraVoltBatt_Compensation_thermique 2U
#endif /* CoOptmEl_stStraVoltBatt_Compensation_thermique */

#ifndef CoOptmEl_stStraVoltBatt_Tension_par_defaut
#define CoOptmEl_stStraVoltBatt_Tension_par_defaut 3U
#endif /* CoOptmEl_stStraVoltBatt_Tension_par_defaut */

#ifndef Ext_bNotAvl_rBattSoCLoResl_Disponible
#define Ext_bNotAvl_rBattSoCLoResl_Disponible 0U
#endif /* Ext_bNotAvl_rBattSoCLoResl_Disponible */

#ifndef Ext_bNotAvl_rBattSoCLoResl_Indisponible
#define Ext_bNotAvl_rBattSoCLoResl_Indisponible 1U
#endif /* Ext_bNotAvl_rBattSoCLoResl_Indisponible */

#ifndef Ext_bNotAvl_uBattStrt_Flux_disponible
#define Ext_bNotAvl_uBattStrt_Flux_disponible 0U
#endif /* Ext_bNotAvl_uBattStrt_Flux_disponible */

#ifndef Ext_bNotAvl_uBattStrt_Flux_indisponible
#define Ext_bNotAvl_uBattStrt_Flux_indisponible 1U
#endif /* Ext_bNotAvl_uBattStrt_Flux_indisponible */

#ifndef CoOptmEl_stPrevElProdReq_Pas_de_demande_de_production
#define CoOptmEl_stPrevElProdReq_Pas_de_demande_de_production 0U
#endif /* CoOptmEl_stPrevElProdReq_Pas_de_demande_de_production */

#ifndef CoOptmEl_stPrevElProdReq_Demande_de_production_apres_Coupe_Cale
#define CoOptmEl_stPrevElProdReq_Demande_de_production_apres_Coupe_Cale 1U
#endif /* CoOptmEl_stPrevElProdReq_Demande_de_production_apres_Coupe_Cale */

#ifndef CoOptmEl_stPrevElProdReq_Demande_de_production_apres_Stop
#define CoOptmEl_stPrevElProdReq_Demande_de_production_apres_Stop 2U
#endif /* CoOptmEl_stPrevElProdReq_Demande_de_production_apres_Stop */

#ifndef CoPtUH_bTestPrvtBltAcv_inactif
#define CoPtUH_bTestPrvtBltAcv_inactif 0U
#endif /* CoPtUH_bTestPrvtBltAcv_inactif */

#ifndef CoPtUH_bTestPrvtBltAcv_actif
#define CoPtUH_bTestPrvtBltAcv_actif 1U
#endif /* CoPtUH_bTestPrvtBltAcv_actif */

#ifndef CoStrtRStrt_stEngStrtReq_Pas_de_demande
#define CoStrtRStrt_stEngStrtReq_Pas_de_demande 0U
#endif /* CoStrtRStrt_stEngStrtReq_Pas_de_demande */

#ifndef CoStrtRStrt_stEngStrtReq_Demande_de_demarrage
#define CoStrtRStrt_stEngStrtReq_Demande_de_demarrage 1U
#endif /* CoStrtRStrt_stEngStrtReq_Demande_de_demarrage */

#ifndef CoStrtRStrt_stEngStrtReq_Demande_de_redemarrage
#define CoStrtRStrt_stEngStrtReq_Demande_de_redemarrage 2U
#endif /* CoStrtRStrt_stEngStrtReq_Demande_de_redemarrage */

#ifndef CoStrtRStrt_stEngStrtReq_Sortie_calage_type_demarrage
#define CoStrtRStrt_stEngStrtReq_Sortie_calage_type_demarrage 3U
#endif /* CoStrtRStrt_stEngStrtReq_Sortie_calage_type_demarrage */

#ifndef CoStrtRStrt_stEngStrtReq_Sortie_calage_type_redemarrage
#define CoStrtRStrt_stEngStrtReq_Sortie_calage_type_redemarrage 4U
#endif /* CoStrtRStrt_stEngStrtReq_Sortie_calage_type_redemarrage */

#ifndef CoStrtRStrt_stEngStrtReq_reserve_5
#define CoStrtRStrt_stEngStrtReq_reserve_5 5U
#endif /* CoStrtRStrt_stEngStrtReq_reserve_5 */

#ifndef CoStrtRStrt_stEngStrtReq_reserve_6
#define CoStrtRStrt_stEngStrtReq_reserve_6 6U
#endif /* CoStrtRStrt_stEngStrtReq_reserve_6 */

#ifndef CoStrtRStrt_stEngStrtReq_reserve_7
#define CoStrtRStrt_stEngStrtReq_reserve_7 7U
#endif /* CoStrtRStrt_stEngStrtReq_reserve_7 */

#ifndef RvAltMgt_stRvAltModReq_Neutre
#define RvAltMgt_stRvAltModReq_Neutre 0U
#endif /* RvAltMgt_stRvAltModReq_Neutre */

#ifndef RvAltMgt_stRvAltModReq_Alternateur
#define RvAltMgt_stRvAltModReq_Alternateur 1U
#endif /* RvAltMgt_stRvAltModReq_Alternateur */

#ifndef RvAltMgt_stRvAltModReq_Re_demarrage_type_1
#define RvAltMgt_stRvAltModReq_Re_demarrage_type_1 2U
#endif /* RvAltMgt_stRvAltModReq_Re_demarrage_type_1 */

#ifndef RvAltMgt_stRvAltModReq_Re_demarrage_type_2
#define RvAltMgt_stRvAltModReq_Re_demarrage_type_2 3U
#endif /* RvAltMgt_stRvAltModReq_Re_demarrage_type_2 */

#ifndef RvAltMgt_stRvAltModReq_Re_demarrage_type_3
#define RvAltMgt_stRvAltModReq_Re_demarrage_type_3 4U
#endif /* RvAltMgt_stRvAltModReq_Re_demarrage_type_3 */

#ifndef RvAltMgt_stRvAltModReq_Re_demarrage_type_4
#define RvAltMgt_stRvAltModReq_Re_demarrage_type_4 5U
#endif /* RvAltMgt_stRvAltModReq_Re_demarrage_type_4 */

#ifndef RvAltMgt_stRvAltModReq_Prefluxage
#define RvAltMgt_stRvAltModReq_Prefluxage 6U
#endif /* RvAltMgt_stRvAltModReq_Prefluxage */

#ifndef RvAltMgt_stRvAltModReq_Aide_au_calage
#define RvAltMgt_stRvAltModReq_Aide_au_calage 7U
#endif /* RvAltMgt_stRvAltModReq_Aide_au_calage */

#ifndef CoOptmEl_stOptmElStra_FEEGO
#define CoOptmEl_stOptmElStra_FEEGO 0U
#endif /* CoOptmEl_stOptmElStra_FEEGO */

#ifndef CoOptmEl_stOptmElStra_FEEGO_Inactif
#define CoOptmEl_stOptmElStra_FEEGO_Inactif 1U
#endif /* CoOptmEl_stOptmElStra_FEEGO_Inactif */

#ifndef CoOptmEl_stOptmElStra_FEEGOR
#define CoOptmEl_stOptmElStra_FEEGOR 2U
#endif /* CoOptmEl_stOptmElStra_FEEGOR */

#ifndef CoOptmEl_stOptmElStra_WarmUp
#define CoOptmEl_stOptmElStra_WarmUp 3U
#endif /* CoOptmEl_stOptmElStra_WarmUp */

#ifndef Ext_idxCtlAltProvIdf_BOSCH
#define Ext_idxCtlAltProvIdf_BOSCH 0U
#endif /* Ext_idxCtlAltProvIdf_BOSCH */

#ifndef Ext_idxCtlAltProvIdf_VALEO
#define Ext_idxCtlAltProvIdf_VALEO 1U
#endif /* Ext_idxCtlAltProvIdf_VALEO */

#ifndef Ext_idxCtlAltProvIdf_DELPHI
#define Ext_idxCtlAltProvIdf_DELPHI 2U
#endif /* Ext_idxCtlAltProvIdf_DELPHI */

#ifndef Ext_idxCtlAltProvIdf_HITACHI
#define Ext_idxCtlAltProvIdf_HITACHI 3U
#endif /* Ext_idxCtlAltProvIdf_HITACHI */

#ifndef Ext_idxCtlAltProvIdf_DENSO
#define Ext_idxCtlAltProvIdf_DENSO 4U
#endif /* Ext_idxCtlAltProvIdf_DENSO */

#ifndef Ext_idxCtlAltProvIdf_MELCO
#define Ext_idxCtlAltProvIdf_MELCO 5U
#endif /* Ext_idxCtlAltProvIdf_MELCO */

#ifndef Ext_idxCtlAltProvIdf_VISTEON
#define Ext_idxCtlAltProvIdf_VISTEON 6U
#endif /* Ext_idxCtlAltProvIdf_VISTEON */

#ifndef Ext_idxCtlAltProvIdf_Autre
#define Ext_idxCtlAltProvIdf_Autre 7U
#endif /* Ext_idxCtlAltProvIdf_Autre */

#ifndef RvAltMgt_bIdcVldCurGenMod_Invalide
#define RvAltMgt_bIdcVldCurGenMod_Invalide 0U
#endif /* RvAltMgt_bIdcVldCurGenMod_Invalide */

#ifndef RvAltMgt_bIdcVldCurGenMod_Valide
#define RvAltMgt_bIdcVldCurGenMod_Valide 1U
#endif /* RvAltMgt_bIdcVldCurGenMod_Valide */

#ifndef VSSCtzMgt_bAcvElCnsReq_Pas_de_demande
#define VSSCtzMgt_bAcvElCnsReq_Pas_de_demande 0U
#endif /* VSSCtzMgt_bAcvElCnsReq_Pas_de_demande */

#ifndef VSSCtzMgt_bAcvElCnsReq_Demande
#define VSSCtzMgt_bAcvElCnsReq_Demande 1U
#endif /* VSSCtzMgt_bAcvElCnsReq_Demande */

#ifndef CoOptmEl_stPrgChReq_Pas_de_CP
#define CoOptmEl_stPrgChReq_Pas_de_CP 0U
#endif /* CoOptmEl_stPrgChReq_Pas_de_CP */

#ifndef CoOptmEl_stPrgChReq__0_25s
#define CoOptmEl_stPrgChReq__0_25s 1U
#endif /* CoOptmEl_stPrgChReq__0_25s */

#ifndef CoOptmEl_stPrgChReq__0_5s
#define CoOptmEl_stPrgChReq__0_5s 2U
#endif /* CoOptmEl_stPrgChReq__0_5s */

#ifndef CoOptmEl_stPrgChReq__0_75s
#define CoOptmEl_stPrgChReq__0_75s 3U
#endif /* CoOptmEl_stPrgChReq__0_75s */

#ifndef CoOptmEl_stPrgChReq__1s
#define CoOptmEl_stPrgChReq__1s 4U
#endif /* CoOptmEl_stPrgChReq__1s */

#ifndef CoOptmEl_stPrgChReq__2s
#define CoOptmEl_stPrgChReq__2s 5U
#endif /* CoOptmEl_stPrgChReq__2s */

#ifndef CoOptmEl_stPrgChReq__3s
#define CoOptmEl_stPrgChReq__3s 6U
#endif /* CoOptmEl_stPrgChReq__3s */

#ifndef CoOptmEl_stPrgChReq__4s
#define CoOptmEl_stPrgChReq__4s 7U
#endif /* CoOptmEl_stPrgChReq__4s */

#ifndef CoOptmEl_stPrgChReq__5s
#define CoOptmEl_stPrgChReq__5s 8U
#endif /* CoOptmEl_stPrgChReq__5s */

#ifndef CoOptmEl_stPrgChReq__6s
#define CoOptmEl_stPrgChReq__6s 9U
#endif /* CoOptmEl_stPrgChReq__6s */

#ifndef CoOptmEl_stPrgChReq__7s
#define CoOptmEl_stPrgChReq__7s 10U
#endif /* CoOptmEl_stPrgChReq__7s */

#ifndef CoOptmEl_stPrgChReq__8s
#define CoOptmEl_stPrgChReq__8s 11U
#endif /* CoOptmEl_stPrgChReq__8s */

#ifndef CoOptmEl_stPrgChReq__9s
#define CoOptmEl_stPrgChReq__9s 12U
#endif /* CoOptmEl_stPrgChReq__9s */

#ifndef CoOptmEl_stPrgChReq__10s
#define CoOptmEl_stPrgChReq__10s 13U
#endif /* CoOptmEl_stPrgChReq__10s */

#ifndef CoOptmEl_stPrgChReq__12s
#define CoOptmEl_stPrgChReq__12s 14U
#endif /* CoOptmEl_stPrgChReq__12s */

#ifndef CoOptmEl_stPrgChReq__15s
#define CoOptmEl_stPrgChReq__15s 15U
#endif /* CoOptmEl_stPrgChReq__15s */

#ifndef CoOptmEl_bWupAcv_Pas_d_activation
#define CoOptmEl_bWupAcv_Pas_d_activation 0U
#endif /* CoOptmEl_bWupAcv_Pas_d_activation */

#ifndef CoOptmEl_bWupAcv_Activation
#define CoOptmEl_bWupAcv_Activation 1U
#endif /* CoOptmEl_bWupAcv_Activation */

#ifndef CoOptmEl_stElLvlProd_BAS
#define CoOptmEl_stElLvlProd_BAS 0U
#endif /* CoOptmEl_stElLvlProd_BAS */

#ifndef CoOptmEl_stElLvlProd_MODERE
#define CoOptmEl_stElLvlProd_MODERE 1U
#endif /* CoOptmEl_stElLvlProd_MODERE */

#ifndef CoOptmEl_stElLvlProd_HAUT
#define CoOptmEl_stElLvlProd_HAUT 2U
#endif /* CoOptmEl_stElLvlProd_HAUT */

#ifndef CoOptmEl_stElLvlProd_PLEINE_CHARGE
#define CoOptmEl_stElLvlProd_PLEINE_CHARGE 3U
#endif /* CoOptmEl_stElLvlProd_PLEINE_CHARGE */

#ifndef CoOptmEl_stElLvlProd_NON_UTILISE_4
#define CoOptmEl_stElLvlProd_NON_UTILISE_4 4U
#endif /* CoOptmEl_stElLvlProd_NON_UTILISE_4 */

#ifndef CoOptmEl_stElLvlProd_NON_UTILISE_5
#define CoOptmEl_stElLvlProd_NON_UTILISE_5 5U
#endif /* CoOptmEl_stElLvlProd_NON_UTILISE_5 */

#ifndef CoOptmEl_stElLvlProd_INDISPONIBLE
#define CoOptmEl_stElLvlProd_INDISPONIBLE 6U
#endif /* CoOptmEl_stElLvlProd_INDISPONIBLE */

#ifndef CoOptmEl_stElLvlProd_INVALIDE
#define CoOptmEl_stElLvlProd_INVALIDE 7U
#endif /* CoOptmEl_stElLvlProd_INVALIDE */

#ifndef CoOptmEl_stElProd_Pas_de_contrainte_particuliere
#define CoOptmEl_stElProd_Pas_de_contrainte_particuliere 0U
#endif /* CoOptmEl_stElProd_Pas_de_contrainte_particuliere */

#ifndef CoOptmEl_stElProd_Lestage
#define CoOptmEl_stElProd_Lestage 1U
#endif /* CoOptmEl_stElProd_Lestage */

#ifndef CoOptmEl_stElProd_Delestage
#define CoOptmEl_stElProd_Delestage 2U
#endif /* CoOptmEl_stElProd_Delestage */

#ifndef CoOptmEl_stElProd_Reserve
#define CoOptmEl_stElProd_Reserve 3U
#endif /* CoOptmEl_stElProd_Reserve */

#ifndef BatMgt_stBattSt_intermediaire
#define BatMgt_stBattSt_intermediaire 0U
#endif /* BatMgt_stBattSt_intermediaire */

#ifndef BatMgt_stBattSt_charge
#define BatMgt_stBattSt_charge 1U
#endif /* BatMgt_stBattSt_charge */

#ifndef BatMgt_stBattSt_decharge
#define BatMgt_stBattSt_decharge 2U
#endif /* BatMgt_stBattSt_decharge */

#ifndef BatMgt_stBattSt_indisponible
#define BatMgt_stBattSt_indisponible 3U
#endif /* BatMgt_stBattSt_indisponible */

#ifndef BatMgt_stBattSt_invalide
#define BatMgt_stBattSt_invalide 4U
#endif /* BatMgt_stBattSt_invalide */

#ifndef BatMgt_stBattSt_reserve_5
#define BatMgt_stBattSt_reserve_5 5U
#endif /* BatMgt_stBattSt_reserve_5 */

#ifndef BatMgt_stBattSt_reserve_6
#define BatMgt_stBattSt_reserve_6 6U
#endif /* BatMgt_stBattSt_reserve_6 */

#ifndef BatMgt_stBattSt_reserve_7
#define BatMgt_stBattSt_reserve_7 7U
#endif /* BatMgt_stBattSt_reserve_7 */

#ifndef ElProdMgt_stProdPrgCh_Pas_de_CP
#define ElProdMgt_stProdPrgCh_Pas_de_CP 0U
#endif /* ElProdMgt_stProdPrgCh_Pas_de_CP */

#ifndef ElProdMgt_stProdPrgCh__0_25s
#define ElProdMgt_stProdPrgCh__0_25s 1U
#endif /* ElProdMgt_stProdPrgCh__0_25s */

#ifndef ElProdMgt_stProdPrgCh__0_5s
#define ElProdMgt_stProdPrgCh__0_5s 2U
#endif /* ElProdMgt_stProdPrgCh__0_5s */

#ifndef ElProdMgt_stProdPrgCh__0_75s
#define ElProdMgt_stProdPrgCh__0_75s 3U
#endif /* ElProdMgt_stProdPrgCh__0_75s */

#ifndef ElProdMgt_stProdPrgCh__1s
#define ElProdMgt_stProdPrgCh__1s 4U
#endif /* ElProdMgt_stProdPrgCh__1s */

#ifndef ElProdMgt_stProdPrgCh__2s
#define ElProdMgt_stProdPrgCh__2s 5U
#endif /* ElProdMgt_stProdPrgCh__2s */

#ifndef ElProdMgt_stProdPrgCh__3s
#define ElProdMgt_stProdPrgCh__3s 6U
#endif /* ElProdMgt_stProdPrgCh__3s */

#ifndef ElProdMgt_stProdPrgCh__4s
#define ElProdMgt_stProdPrgCh__4s 7U
#endif /* ElProdMgt_stProdPrgCh__4s */

#ifndef ElProdMgt_stProdPrgCh__5s
#define ElProdMgt_stProdPrgCh__5s 8U
#endif /* ElProdMgt_stProdPrgCh__5s */

#ifndef ElProdMgt_stProdPrgCh__6s
#define ElProdMgt_stProdPrgCh__6s 9U
#endif /* ElProdMgt_stProdPrgCh__6s */

#ifndef ElProdMgt_stProdPrgCh__7s
#define ElProdMgt_stProdPrgCh__7s 10U
#endif /* ElProdMgt_stProdPrgCh__7s */

#ifndef ElProdMgt_stProdPrgCh__8s
#define ElProdMgt_stProdPrgCh__8s 11U
#endif /* ElProdMgt_stProdPrgCh__8s */

#ifndef ElProdMgt_stProdPrgCh__9s
#define ElProdMgt_stProdPrgCh__9s 12U
#endif /* ElProdMgt_stProdPrgCh__9s */

#ifndef ElProdMgt_stProdPrgCh__10s
#define ElProdMgt_stProdPrgCh__10s 13U
#endif /* ElProdMgt_stProdPrgCh__10s */

#ifndef ElProdMgt_stProdPrgCh__12s
#define ElProdMgt_stProdPrgCh__12s 14U
#endif /* ElProdMgt_stProdPrgCh__12s */

#ifndef ElProdMgt_stProdPrgCh__15s
#define ElProdMgt_stProdPrgCh__15s 15U
#endif /* ElProdMgt_stProdPrgCh__15s */

#ifndef ElProdMgt_stProdPrgChDi_nEng__2400
#define ElProdMgt_stProdPrgChDi_nEng__2400 0U
#endif /* ElProdMgt_stProdPrgChDi_nEng__2400 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__2530
#define ElProdMgt_stProdPrgChDi_nEng__2530 1U
#endif /* ElProdMgt_stProdPrgChDi_nEng__2530 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__2670
#define ElProdMgt_stProdPrgChDi_nEng__2670 2U
#endif /* ElProdMgt_stProdPrgChDi_nEng__2670 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__2830
#define ElProdMgt_stProdPrgChDi_nEng__2830 3U
#endif /* ElProdMgt_stProdPrgChDi_nEng__2830 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__3000
#define ElProdMgt_stProdPrgChDi_nEng__3000 4U
#endif /* ElProdMgt_stProdPrgChDi_nEng__3000 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__3200
#define ElProdMgt_stProdPrgChDi_nEng__3200 5U
#endif /* ElProdMgt_stProdPrgChDi_nEng__3200 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__3430
#define ElProdMgt_stProdPrgChDi_nEng__3430 6U
#endif /* ElProdMgt_stProdPrgChDi_nEng__3430 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__3690
#define ElProdMgt_stProdPrgChDi_nEng__3690 7U
#endif /* ElProdMgt_stProdPrgChDi_nEng__3690 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__4000
#define ElProdMgt_stProdPrgChDi_nEng__4000 8U
#endif /* ElProdMgt_stProdPrgChDi_nEng__4000 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__4360
#define ElProdMgt_stProdPrgChDi_nEng__4360 9U
#endif /* ElProdMgt_stProdPrgChDi_nEng__4360 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__4790
#define ElProdMgt_stProdPrgChDi_nEng__4790 10U
#endif /* ElProdMgt_stProdPrgChDi_nEng__4790 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__5320
#define ElProdMgt_stProdPrgChDi_nEng__5320 11U
#endif /* ElProdMgt_stProdPrgChDi_nEng__5320 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__5990
#define ElProdMgt_stProdPrgChDi_nEng__5990 12U
#endif /* ElProdMgt_stProdPrgChDi_nEng__5990 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__6860
#define ElProdMgt_stProdPrgChDi_nEng__6860 13U
#endif /* ElProdMgt_stProdPrgChDi_nEng__6860 */

#ifndef ElProdMgt_stProdPrgChDi_nEng__8010
#define ElProdMgt_stProdPrgChDi_nEng__8010 14U
#endif /* ElProdMgt_stProdPrgChDi_nEng__8010 */

#ifndef ElProdMgt_stProdPrgChDi_nEng_toujours_active
#define ElProdMgt_stProdPrgChDi_nEng_toujours_active 15U
#endif /* ElProdMgt_stProdPrgChDi_nEng_toujours_active */

#ifndef CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_protection_batterie
#define CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_protection_batterie 1U
#endif /* CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_protection_batterie */

#ifndef CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_anti_sulfatation_batterie
#define CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_anti_sulfatation_batterie 2U
#endif /* CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_anti_sulfatation_batterie */

#ifndef CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_preparation_de_la_batterie_pour_le_STOP
#define CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_preparation_de_la_batterie_pour_le_STOP 4U
#endif /* CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_preparation_de_la_batterie_pour_le_STOP */

#ifndef CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_de_protection_lestage_div_delestage_trop_important_de_la_batterie_12V
#define CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_de_protection_lestage_div_delestage_trop_important_de_la_batterie_12V 8U
#endif /* CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_de_protection_lestage_div_delestage_trop_important_de_la_batterie_12V */

#ifndef CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_de_protection_au_SOC_bas_de_la_batterie_12V
#define CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_de_protection_au_SOC_bas_de_la_batterie_12V 16U
#endif /* CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_de_protection_au_SOC_bas_de_la_batterie_12V */

#ifndef CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_glissement_courroie
#define CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_glissement_courroie 32U
#endif /* CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_glissement_courroie */

#ifndef CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_1
#define CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_1 64U
#endif /* CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_1 */

#ifndef CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_2
#define CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_2 128U
#endif /* CoOptmEl_bfAcvConstEm1_Besoin_QRDB_SEEM_2 */

#ifndef CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_delestage_Anti_calage
#define CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_delestage_Anti_calage 1U
#endif /* CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_delestage_Anti_calage */

#ifndef CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_delestage_BRIO_batterie
#define CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_delestage_BRIO_batterie 2U
#endif /* CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_delestage_BRIO_batterie */

#ifndef CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_delestage_Opti_Vide
#define CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_delestage_Opti_Vide 4U
#endif /* CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_delestage_Opti_Vide */

#ifndef CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_lestage_Haut
#define CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_lestage_Haut 8U
#endif /* CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_lestage_Haut */

#ifndef CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_lestage_Moyen
#define CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_lestage_Moyen 16U
#endif /* CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_lestage_Moyen */

#ifndef CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_figeage
#define CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_figeage 32U
#endif /* CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_figeage */

#ifndef CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_3
#define CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_3 64U
#endif /* CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_3 */

#ifndef CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_4
#define CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_4 128U
#endif /* CoOptmEl_bfAcvConstEm2_Besoin_QRDB_SEEM_4 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_1
#define CoOptmEl_stDetConstNegSlop_Besoin_1 0U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_1 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_2
#define CoOptmEl_stDetConstNegSlop_Besoin_2 1U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_2 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_3
#define CoOptmEl_stDetConstNegSlop_Besoin_3 2U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_3 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_4
#define CoOptmEl_stDetConstNegSlop_Besoin_4 3U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_4 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_5
#define CoOptmEl_stDetConstNegSlop_Besoin_5 4U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_5 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_6
#define CoOptmEl_stDetConstNegSlop_Besoin_6 5U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_6 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_7
#define CoOptmEl_stDetConstNegSlop_Besoin_7 6U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_7 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_8
#define CoOptmEl_stDetConstNegSlop_Besoin_8 7U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_8 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_9
#define CoOptmEl_stDetConstNegSlop_Besoin_9 8U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_9 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_10
#define CoOptmEl_stDetConstNegSlop_Besoin_10 9U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_10 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_11
#define CoOptmEl_stDetConstNegSlop_Besoin_11 10U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_11 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_12
#define CoOptmEl_stDetConstNegSlop_Besoin_12 11U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_12 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_13
#define CoOptmEl_stDetConstNegSlop_Besoin_13 12U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_13 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_14
#define CoOptmEl_stDetConstNegSlop_Besoin_14 13U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_14 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_15
#define CoOptmEl_stDetConstNegSlop_Besoin_15 14U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_15 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_16
#define CoOptmEl_stDetConstNegSlop_Besoin_16 15U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_16 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_17
#define CoOptmEl_stDetConstNegSlop_Besoin_17 16U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_17 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_18
#define CoOptmEl_stDetConstNegSlop_Besoin_18 17U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_18 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_19
#define CoOptmEl_stDetConstNegSlop_Besoin_19 18U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_19 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_20
#define CoOptmEl_stDetConstNegSlop_Besoin_20 19U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_20 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_21
#define CoOptmEl_stDetConstNegSlop_Besoin_21 20U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_21 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_22
#define CoOptmEl_stDetConstNegSlop_Besoin_22 21U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_22 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_23
#define CoOptmEl_stDetConstNegSlop_Besoin_23 22U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_23 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_24
#define CoOptmEl_stDetConstNegSlop_Besoin_24 23U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_24 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_25
#define CoOptmEl_stDetConstNegSlop_Besoin_25 24U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_25 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_26
#define CoOptmEl_stDetConstNegSlop_Besoin_26 25U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_26 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_27
#define CoOptmEl_stDetConstNegSlop_Besoin_27 26U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_27 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_28
#define CoOptmEl_stDetConstNegSlop_Besoin_28 27U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_28 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_29
#define CoOptmEl_stDetConstNegSlop_Besoin_29 28U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_29 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_30
#define CoOptmEl_stDetConstNegSlop_Besoin_30 29U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_30 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_31
#define CoOptmEl_stDetConstNegSlop_Besoin_31 30U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_31 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_32
#define CoOptmEl_stDetConstNegSlop_Besoin_32 31U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_32 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_33
#define CoOptmEl_stDetConstNegSlop_Besoin_33 32U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_33 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_34
#define CoOptmEl_stDetConstNegSlop_Besoin_34 33U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_34 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_35
#define CoOptmEl_stDetConstNegSlop_Besoin_35 34U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_35 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_36
#define CoOptmEl_stDetConstNegSlop_Besoin_36 35U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_36 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_37
#define CoOptmEl_stDetConstNegSlop_Besoin_37 36U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_37 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_38
#define CoOptmEl_stDetConstNegSlop_Besoin_38 37U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_38 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_39
#define CoOptmEl_stDetConstNegSlop_Besoin_39 38U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_39 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_40
#define CoOptmEl_stDetConstNegSlop_Besoin_40 39U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_40 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_41
#define CoOptmEl_stDetConstNegSlop_Besoin_41 40U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_41 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_42
#define CoOptmEl_stDetConstNegSlop_Besoin_42 41U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_42 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_43
#define CoOptmEl_stDetConstNegSlop_Besoin_43 42U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_43 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_44
#define CoOptmEl_stDetConstNegSlop_Besoin_44 43U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_44 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_45
#define CoOptmEl_stDetConstNegSlop_Besoin_45 44U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_45 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_46
#define CoOptmEl_stDetConstNegSlop_Besoin_46 45U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_46 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_47
#define CoOptmEl_stDetConstNegSlop_Besoin_47 46U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_47 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_48
#define CoOptmEl_stDetConstNegSlop_Besoin_48 47U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_48 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_49
#define CoOptmEl_stDetConstNegSlop_Besoin_49 48U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_49 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_50
#define CoOptmEl_stDetConstNegSlop_Besoin_50 49U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_50 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_51
#define CoOptmEl_stDetConstNegSlop_Besoin_51 50U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_51 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_52
#define CoOptmEl_stDetConstNegSlop_Besoin_52 51U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_52 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_53
#define CoOptmEl_stDetConstNegSlop_Besoin_53 52U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_53 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_54
#define CoOptmEl_stDetConstNegSlop_Besoin_54 53U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_54 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_55
#define CoOptmEl_stDetConstNegSlop_Besoin_55 54U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_55 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_56
#define CoOptmEl_stDetConstNegSlop_Besoin_56 55U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_56 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_57
#define CoOptmEl_stDetConstNegSlop_Besoin_57 56U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_57 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_58
#define CoOptmEl_stDetConstNegSlop_Besoin_58 57U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_58 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_59
#define CoOptmEl_stDetConstNegSlop_Besoin_59 58U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_59 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_60
#define CoOptmEl_stDetConstNegSlop_Besoin_60 59U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_60 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_61
#define CoOptmEl_stDetConstNegSlop_Besoin_61 60U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_61 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_62
#define CoOptmEl_stDetConstNegSlop_Besoin_62 61U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_62 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_63
#define CoOptmEl_stDetConstNegSlop_Besoin_63 62U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_63 */

#ifndef CoOptmEl_stDetConstNegSlop_Besoin_64
#define CoOptmEl_stDetConstNegSlop_Besoin_64 63U
#endif /* CoOptmEl_stDetConstNegSlop_Besoin_64 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_1
#define CoOptmEl_stDetConstPosSlop_Besoin_1 0U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_1 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_2
#define CoOptmEl_stDetConstPosSlop_Besoin_2 1U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_2 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_3
#define CoOptmEl_stDetConstPosSlop_Besoin_3 2U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_3 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_4
#define CoOptmEl_stDetConstPosSlop_Besoin_4 3U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_4 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_5
#define CoOptmEl_stDetConstPosSlop_Besoin_5 4U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_5 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_6
#define CoOptmEl_stDetConstPosSlop_Besoin_6 5U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_6 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_7
#define CoOptmEl_stDetConstPosSlop_Besoin_7 6U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_7 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_8
#define CoOptmEl_stDetConstPosSlop_Besoin_8 7U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_8 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_9
#define CoOptmEl_stDetConstPosSlop_Besoin_9 8U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_9 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_10
#define CoOptmEl_stDetConstPosSlop_Besoin_10 9U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_10 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_11
#define CoOptmEl_stDetConstPosSlop_Besoin_11 10U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_11 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_12
#define CoOptmEl_stDetConstPosSlop_Besoin_12 11U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_12 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_13
#define CoOptmEl_stDetConstPosSlop_Besoin_13 12U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_13 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_14
#define CoOptmEl_stDetConstPosSlop_Besoin_14 13U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_14 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_15
#define CoOptmEl_stDetConstPosSlop_Besoin_15 14U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_15 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_16
#define CoOptmEl_stDetConstPosSlop_Besoin_16 15U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_16 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_17
#define CoOptmEl_stDetConstPosSlop_Besoin_17 16U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_17 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_18
#define CoOptmEl_stDetConstPosSlop_Besoin_18 17U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_18 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_19
#define CoOptmEl_stDetConstPosSlop_Besoin_19 18U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_19 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_20
#define CoOptmEl_stDetConstPosSlop_Besoin_20 19U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_20 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_21
#define CoOptmEl_stDetConstPosSlop_Besoin_21 20U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_21 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_22
#define CoOptmEl_stDetConstPosSlop_Besoin_22 21U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_22 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_23
#define CoOptmEl_stDetConstPosSlop_Besoin_23 22U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_23 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_24
#define CoOptmEl_stDetConstPosSlop_Besoin_24 23U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_24 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_25
#define CoOptmEl_stDetConstPosSlop_Besoin_25 24U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_25 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_26
#define CoOptmEl_stDetConstPosSlop_Besoin_26 25U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_26 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_27
#define CoOptmEl_stDetConstPosSlop_Besoin_27 26U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_27 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_28
#define CoOptmEl_stDetConstPosSlop_Besoin_28 27U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_28 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_29
#define CoOptmEl_stDetConstPosSlop_Besoin_29 28U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_29 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_30
#define CoOptmEl_stDetConstPosSlop_Besoin_30 29U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_30 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_31
#define CoOptmEl_stDetConstPosSlop_Besoin_31 30U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_31 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_32
#define CoOptmEl_stDetConstPosSlop_Besoin_32 31U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_32 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_33
#define CoOptmEl_stDetConstPosSlop_Besoin_33 32U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_33 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_34
#define CoOptmEl_stDetConstPosSlop_Besoin_34 33U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_34 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_35
#define CoOptmEl_stDetConstPosSlop_Besoin_35 34U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_35 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_36
#define CoOptmEl_stDetConstPosSlop_Besoin_36 35U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_36 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_37
#define CoOptmEl_stDetConstPosSlop_Besoin_37 36U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_37 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_38
#define CoOptmEl_stDetConstPosSlop_Besoin_38 37U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_38 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_39
#define CoOptmEl_stDetConstPosSlop_Besoin_39 38U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_39 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_40
#define CoOptmEl_stDetConstPosSlop_Besoin_40 39U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_40 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_41
#define CoOptmEl_stDetConstPosSlop_Besoin_41 40U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_41 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_42
#define CoOptmEl_stDetConstPosSlop_Besoin_42 41U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_42 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_43
#define CoOptmEl_stDetConstPosSlop_Besoin_43 42U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_43 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_44
#define CoOptmEl_stDetConstPosSlop_Besoin_44 43U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_44 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_45
#define CoOptmEl_stDetConstPosSlop_Besoin_45 44U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_45 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_46
#define CoOptmEl_stDetConstPosSlop_Besoin_46 45U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_46 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_47
#define CoOptmEl_stDetConstPosSlop_Besoin_47 46U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_47 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_48
#define CoOptmEl_stDetConstPosSlop_Besoin_48 47U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_48 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_49
#define CoOptmEl_stDetConstPosSlop_Besoin_49 48U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_49 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_50
#define CoOptmEl_stDetConstPosSlop_Besoin_50 49U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_50 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_51
#define CoOptmEl_stDetConstPosSlop_Besoin_51 50U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_51 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_52
#define CoOptmEl_stDetConstPosSlop_Besoin_52 51U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_52 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_53
#define CoOptmEl_stDetConstPosSlop_Besoin_53 52U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_53 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_54
#define CoOptmEl_stDetConstPosSlop_Besoin_54 53U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_54 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_55
#define CoOptmEl_stDetConstPosSlop_Besoin_55 54U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_55 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_56
#define CoOptmEl_stDetConstPosSlop_Besoin_56 55U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_56 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_57
#define CoOptmEl_stDetConstPosSlop_Besoin_57 56U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_57 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_58
#define CoOptmEl_stDetConstPosSlop_Besoin_58 57U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_58 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_59
#define CoOptmEl_stDetConstPosSlop_Besoin_59 58U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_59 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_60
#define CoOptmEl_stDetConstPosSlop_Besoin_60 59U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_60 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_61
#define CoOptmEl_stDetConstPosSlop_Besoin_61 60U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_61 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_62
#define CoOptmEl_stDetConstPosSlop_Besoin_62 61U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_62 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_63
#define CoOptmEl_stDetConstPosSlop_Besoin_63 62U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_63 */

#ifndef CoOptmEl_stDetConstPosSlop_Besoin_64
#define CoOptmEl_stDetConstPosSlop_Besoin_64 63U
#endif /* CoOptmEl_stDetConstPosSlop_Besoin_64 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_1
#define CoOptmEl_stDetConstVoltMax_Besoin_1 0U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_1 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_2
#define CoOptmEl_stDetConstVoltMax_Besoin_2 1U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_2 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_3
#define CoOptmEl_stDetConstVoltMax_Besoin_3 2U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_3 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_4
#define CoOptmEl_stDetConstVoltMax_Besoin_4 3U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_4 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_5
#define CoOptmEl_stDetConstVoltMax_Besoin_5 4U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_5 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_6
#define CoOptmEl_stDetConstVoltMax_Besoin_6 5U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_6 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_7
#define CoOptmEl_stDetConstVoltMax_Besoin_7 6U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_7 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_8
#define CoOptmEl_stDetConstVoltMax_Besoin_8 7U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_8 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_9
#define CoOptmEl_stDetConstVoltMax_Besoin_9 8U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_9 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_10
#define CoOptmEl_stDetConstVoltMax_Besoin_10 9U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_10 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_11
#define CoOptmEl_stDetConstVoltMax_Besoin_11 10U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_11 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_12
#define CoOptmEl_stDetConstVoltMax_Besoin_12 11U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_12 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_13
#define CoOptmEl_stDetConstVoltMax_Besoin_13 12U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_13 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_14
#define CoOptmEl_stDetConstVoltMax_Besoin_14 13U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_14 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_15
#define CoOptmEl_stDetConstVoltMax_Besoin_15 14U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_15 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_16
#define CoOptmEl_stDetConstVoltMax_Besoin_16 15U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_16 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_17
#define CoOptmEl_stDetConstVoltMax_Besoin_17 16U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_17 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_18
#define CoOptmEl_stDetConstVoltMax_Besoin_18 17U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_18 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_19
#define CoOptmEl_stDetConstVoltMax_Besoin_19 18U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_19 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_20
#define CoOptmEl_stDetConstVoltMax_Besoin_20 19U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_20 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_21
#define CoOptmEl_stDetConstVoltMax_Besoin_21 20U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_21 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_22
#define CoOptmEl_stDetConstVoltMax_Besoin_22 21U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_22 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_23
#define CoOptmEl_stDetConstVoltMax_Besoin_23 22U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_23 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_24
#define CoOptmEl_stDetConstVoltMax_Besoin_24 23U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_24 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_25
#define CoOptmEl_stDetConstVoltMax_Besoin_25 24U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_25 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_26
#define CoOptmEl_stDetConstVoltMax_Besoin_26 25U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_26 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_27
#define CoOptmEl_stDetConstVoltMax_Besoin_27 26U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_27 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_28
#define CoOptmEl_stDetConstVoltMax_Besoin_28 27U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_28 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_29
#define CoOptmEl_stDetConstVoltMax_Besoin_29 28U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_29 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_30
#define CoOptmEl_stDetConstVoltMax_Besoin_30 29U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_30 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_31
#define CoOptmEl_stDetConstVoltMax_Besoin_31 30U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_31 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_32
#define CoOptmEl_stDetConstVoltMax_Besoin_32 31U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_32 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_33
#define CoOptmEl_stDetConstVoltMax_Besoin_33 32U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_33 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_34
#define CoOptmEl_stDetConstVoltMax_Besoin_34 33U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_34 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_35
#define CoOptmEl_stDetConstVoltMax_Besoin_35 34U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_35 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_36
#define CoOptmEl_stDetConstVoltMax_Besoin_36 35U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_36 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_37
#define CoOptmEl_stDetConstVoltMax_Besoin_37 36U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_37 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_38
#define CoOptmEl_stDetConstVoltMax_Besoin_38 37U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_38 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_39
#define CoOptmEl_stDetConstVoltMax_Besoin_39 38U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_39 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_40
#define CoOptmEl_stDetConstVoltMax_Besoin_40 39U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_40 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_41
#define CoOptmEl_stDetConstVoltMax_Besoin_41 40U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_41 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_42
#define CoOptmEl_stDetConstVoltMax_Besoin_42 41U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_42 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_43
#define CoOptmEl_stDetConstVoltMax_Besoin_43 42U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_43 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_44
#define CoOptmEl_stDetConstVoltMax_Besoin_44 43U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_44 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_45
#define CoOptmEl_stDetConstVoltMax_Besoin_45 44U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_45 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_46
#define CoOptmEl_stDetConstVoltMax_Besoin_46 45U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_46 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_47
#define CoOptmEl_stDetConstVoltMax_Besoin_47 46U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_47 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_48
#define CoOptmEl_stDetConstVoltMax_Besoin_48 47U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_48 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_49
#define CoOptmEl_stDetConstVoltMax_Besoin_49 48U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_49 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_50
#define CoOptmEl_stDetConstVoltMax_Besoin_50 49U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_50 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_51
#define CoOptmEl_stDetConstVoltMax_Besoin_51 50U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_51 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_52
#define CoOptmEl_stDetConstVoltMax_Besoin_52 51U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_52 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_53
#define CoOptmEl_stDetConstVoltMax_Besoin_53 52U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_53 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_54
#define CoOptmEl_stDetConstVoltMax_Besoin_54 53U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_54 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_55
#define CoOptmEl_stDetConstVoltMax_Besoin_55 54U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_55 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_56
#define CoOptmEl_stDetConstVoltMax_Besoin_56 55U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_56 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_57
#define CoOptmEl_stDetConstVoltMax_Besoin_57 56U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_57 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_58
#define CoOptmEl_stDetConstVoltMax_Besoin_58 57U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_58 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_59
#define CoOptmEl_stDetConstVoltMax_Besoin_59 58U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_59 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_60
#define CoOptmEl_stDetConstVoltMax_Besoin_60 59U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_60 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_61
#define CoOptmEl_stDetConstVoltMax_Besoin_61 60U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_61 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_62
#define CoOptmEl_stDetConstVoltMax_Besoin_62 61U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_62 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_63
#define CoOptmEl_stDetConstVoltMax_Besoin_63 62U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_63 */

#ifndef CoOptmEl_stDetConstVoltMax_Besoin_64
#define CoOptmEl_stDetConstVoltMax_Besoin_64 63U
#endif /* CoOptmEl_stDetConstVoltMax_Besoin_64 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_1
#define CoOptmEl_stDetConstVoltMin_Besoin_1 0U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_1 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_2
#define CoOptmEl_stDetConstVoltMin_Besoin_2 1U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_2 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_3
#define CoOptmEl_stDetConstVoltMin_Besoin_3 2U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_3 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_4
#define CoOptmEl_stDetConstVoltMin_Besoin_4 3U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_4 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_5
#define CoOptmEl_stDetConstVoltMin_Besoin_5 4U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_5 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_6
#define CoOptmEl_stDetConstVoltMin_Besoin_6 5U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_6 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_7
#define CoOptmEl_stDetConstVoltMin_Besoin_7 6U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_7 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_8
#define CoOptmEl_stDetConstVoltMin_Besoin_8 7U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_8 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_9
#define CoOptmEl_stDetConstVoltMin_Besoin_9 8U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_9 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_10
#define CoOptmEl_stDetConstVoltMin_Besoin_10 9U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_10 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_11
#define CoOptmEl_stDetConstVoltMin_Besoin_11 10U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_11 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_12
#define CoOptmEl_stDetConstVoltMin_Besoin_12 11U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_12 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_13
#define CoOptmEl_stDetConstVoltMin_Besoin_13 12U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_13 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_14
#define CoOptmEl_stDetConstVoltMin_Besoin_14 13U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_14 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_15
#define CoOptmEl_stDetConstVoltMin_Besoin_15 14U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_15 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_16
#define CoOptmEl_stDetConstVoltMin_Besoin_16 15U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_16 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_17
#define CoOptmEl_stDetConstVoltMin_Besoin_17 16U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_17 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_18
#define CoOptmEl_stDetConstVoltMin_Besoin_18 17U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_18 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_19
#define CoOptmEl_stDetConstVoltMin_Besoin_19 18U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_19 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_20
#define CoOptmEl_stDetConstVoltMin_Besoin_20 19U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_20 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_21
#define CoOptmEl_stDetConstVoltMin_Besoin_21 20U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_21 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_22
#define CoOptmEl_stDetConstVoltMin_Besoin_22 21U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_22 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_23
#define CoOptmEl_stDetConstVoltMin_Besoin_23 22U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_23 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_24
#define CoOptmEl_stDetConstVoltMin_Besoin_24 23U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_24 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_25
#define CoOptmEl_stDetConstVoltMin_Besoin_25 24U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_25 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_26
#define CoOptmEl_stDetConstVoltMin_Besoin_26 25U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_26 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_27
#define CoOptmEl_stDetConstVoltMin_Besoin_27 26U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_27 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_28
#define CoOptmEl_stDetConstVoltMin_Besoin_28 27U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_28 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_29
#define CoOptmEl_stDetConstVoltMin_Besoin_29 28U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_29 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_30
#define CoOptmEl_stDetConstVoltMin_Besoin_30 29U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_30 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_31
#define CoOptmEl_stDetConstVoltMin_Besoin_31 30U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_31 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_32
#define CoOptmEl_stDetConstVoltMin_Besoin_32 31U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_32 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_33
#define CoOptmEl_stDetConstVoltMin_Besoin_33 32U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_33 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_34
#define CoOptmEl_stDetConstVoltMin_Besoin_34 33U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_34 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_35
#define CoOptmEl_stDetConstVoltMin_Besoin_35 34U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_35 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_36
#define CoOptmEl_stDetConstVoltMin_Besoin_36 35U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_36 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_37
#define CoOptmEl_stDetConstVoltMin_Besoin_37 36U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_37 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_38
#define CoOptmEl_stDetConstVoltMin_Besoin_38 37U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_38 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_39
#define CoOptmEl_stDetConstVoltMin_Besoin_39 38U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_39 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_40
#define CoOptmEl_stDetConstVoltMin_Besoin_40 39U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_40 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_41
#define CoOptmEl_stDetConstVoltMin_Besoin_41 40U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_41 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_42
#define CoOptmEl_stDetConstVoltMin_Besoin_42 41U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_42 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_43
#define CoOptmEl_stDetConstVoltMin_Besoin_43 42U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_43 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_44
#define CoOptmEl_stDetConstVoltMin_Besoin_44 43U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_44 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_45
#define CoOptmEl_stDetConstVoltMin_Besoin_45 44U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_45 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_46
#define CoOptmEl_stDetConstVoltMin_Besoin_46 45U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_46 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_47
#define CoOptmEl_stDetConstVoltMin_Besoin_47 46U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_47 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_48
#define CoOptmEl_stDetConstVoltMin_Besoin_48 47U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_48 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_49
#define CoOptmEl_stDetConstVoltMin_Besoin_49 48U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_49 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_50
#define CoOptmEl_stDetConstVoltMin_Besoin_50 49U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_50 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_51
#define CoOptmEl_stDetConstVoltMin_Besoin_51 50U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_51 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_52
#define CoOptmEl_stDetConstVoltMin_Besoin_52 51U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_52 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_53
#define CoOptmEl_stDetConstVoltMin_Besoin_53 52U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_53 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_54
#define CoOptmEl_stDetConstVoltMin_Besoin_54 53U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_54 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_55
#define CoOptmEl_stDetConstVoltMin_Besoin_55 54U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_55 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_56
#define CoOptmEl_stDetConstVoltMin_Besoin_56 55U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_56 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_57
#define CoOptmEl_stDetConstVoltMin_Besoin_57 56U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_57 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_58
#define CoOptmEl_stDetConstVoltMin_Besoin_58 57U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_58 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_59
#define CoOptmEl_stDetConstVoltMin_Besoin_59 58U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_59 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_60
#define CoOptmEl_stDetConstVoltMin_Besoin_60 59U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_60 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_61
#define CoOptmEl_stDetConstVoltMin_Besoin_61 60U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_61 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_62
#define CoOptmEl_stDetConstVoltMin_Besoin_62 61U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_62 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_63
#define CoOptmEl_stDetConstVoltMin_Besoin_63 62U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_63 */

#ifndef CoOptmEl_stDetConstVoltMin_Besoin_64
#define CoOptmEl_stDetConstVoltMin_Besoin_64 63U
#endif /* CoOptmEl_stDetConstVoltMin_Besoin_64 */

#ifndef CoOptmEl_stElEProv__1_1_stockeur_div_stockeur
#define CoOptmEl_stElEProv__1_1_stockeur_div_stockeur 0U
#endif /* CoOptmEl_stElEProv__1_1_stockeur_div_stockeur */

#ifndef CoOptmEl_stElEProv__1_2_stockeur_div_stockeur_plus_MEL_sans_maintien
#define CoOptmEl_stElEProv__1_2_stockeur_div_stockeur_plus_MEL_sans_maintien 1U
#endif /* CoOptmEl_stElEProv__1_2_stockeur_div_stockeur_plus_MEL_sans_maintien */

#ifndef CoOptmEl_stElEProv__1_3c_stockeur_div_stockeur_avec_MEL_avec_maintien_complet
#define CoOptmEl_stElEProv__1_3c_stockeur_div_stockeur_avec_MEL_avec_maintien_complet 2U
#endif /* CoOptmEl_stElEProv__1_3c_stockeur_div_stockeur_avec_MEL_avec_maintien_complet */

#ifndef CoOptmEl_stElEProv__1_3r_stockeur_div_stockeur_avec_MEL_avec_maintien_restreint
#define CoOptmEl_stElEProv__1_3r_stockeur_div_stockeur_avec_MEL_avec_maintien_restreint 3U
#endif /* CoOptmEl_stElEProv__1_3r_stockeur_div_stockeur_avec_MEL_avec_maintien_restreint */

#ifndef CoOptmEl_stElEProv__2_1_stockeur_avec_MEL_sans_maintien_div_stockeur
#define CoOptmEl_stElEProv__2_1_stockeur_avec_MEL_sans_maintien_div_stockeur 4U
#endif /* CoOptmEl_stElEProv__2_1_stockeur_avec_MEL_sans_maintien_div_stockeur */

#ifndef CoOptmEl_stElEProv__3c_1_stockeur_avec_MEL_avec_maintien_complet_div_stockeur
#define CoOptmEl_stElEProv__3c_1_stockeur_avec_MEL_avec_maintien_complet_div_stockeur 5U
#endif /* CoOptmEl_stElEProv__3c_1_stockeur_avec_MEL_avec_maintien_complet_div_stockeur */

#ifndef CoOptmEl_stElEProv__3r_x_1_stockeur_avec_MEL_avec_maintien_restreint_div_stockeur
#define CoOptmEl_stElEProv__3r_x_1_stockeur_avec_MEL_avec_maintien_restreint_div_stockeur 6U
#endif /* CoOptmEl_stElEProv__3r_x_1_stockeur_avec_MEL_avec_maintien_restreint_div_stockeur */

#ifndef CoOptmEl_stElEProv__4_1_producteur_actif_avec_stockeur_div_stockeur
#define CoOptmEl_stElEProv__4_1_producteur_actif_avec_stockeur_div_stockeur 7U
#endif /* CoOptmEl_stElEProv__4_1_producteur_actif_avec_stockeur_div_stockeur */

#ifndef CoOptmEl_stElEProv__5_5_producteur_actif_sans_stockeur_div_producteur_actif_sans_stockeur
#define CoOptmEl_stElEProv__5_5_producteur_actif_sans_stockeur_div_producteur_actif_sans_stockeur 8U
#endif /* CoOptmEl_stElEProv__5_5_producteur_actif_sans_stockeur_div_producteur_actif_sans_stockeur */

#ifndef CoOptmEl_stSoCRefTyp_Referentiel_B0
#define CoOptmEl_stSoCRefTyp_Referentiel_B0 0U
#endif /* CoOptmEl_stSoCRefTyp_Referentiel_B0 */

#ifndef CoOptmEl_stSoCRefTyp_Referentiel_B1
#define CoOptmEl_stSoCRefTyp_Referentiel_B1 1U
#endif /* CoOptmEl_stSoCRefTyp_Referentiel_B1 */

#ifndef CoOptmEl_stSoCRefTyp_Referentiel_B2
#define CoOptmEl_stSoCRefTyp_Referentiel_B2 2U
#endif /* CoOptmEl_stSoCRefTyp_Referentiel_B2 */

#ifndef BatMgt_bAntiAgiStraEfcChIdc_Charge_non_effective
#define BatMgt_bAntiAgiStraEfcChIdc_Charge_non_effective 0U
#endif /* BatMgt_bAntiAgiStraEfcChIdc_Charge_non_effective */

#ifndef BatMgt_bAntiAgiStraEfcChIdc_Charge_effective
#define BatMgt_bAntiAgiStraEfcChIdc_Charge_effective 1U
#endif /* BatMgt_bAntiAgiStraEfcChIdc_Charge_effective */

#ifndef BatMgt_bAntiAgiStraEndIdc_Strategie_non_terminee
#define BatMgt_bAntiAgiStraEndIdc_Strategie_non_terminee 0U
#endif /* BatMgt_bAntiAgiStraEndIdc_Strategie_non_terminee */

#ifndef BatMgt_bAntiAgiStraEndIdc_Strategie_terminee
#define BatMgt_bAntiAgiStraEndIdc_Strategie_terminee 1U
#endif /* BatMgt_bAntiAgiStraEndIdc_Strategie_terminee */

#ifndef CoOptmEl_bAcvElCnsReq_Pas_de_demande
#define CoOptmEl_bAcvElCnsReq_Pas_de_demande 0U
#endif /* CoOptmEl_bAcvElCnsReq_Pas_de_demande */

#ifndef CoOptmEl_bAcvElCnsReq_Demande
#define CoOptmEl_bAcvElCnsReq_Demande 1U
#endif /* CoOptmEl_bAcvElCnsReq_Demande */

#ifndef DEM_EVENT_STATUS_FAILED
#define DEM_EVENT_STATUS_FAILED 1U
#endif /* DEM_EVENT_STATUS_FAILED */

#ifndef DEM_EVENT_STATUS_INIT
#define DEM_EVENT_STATUS_INIT 32U
#endif /* DEM_EVENT_STATUS_INIT */

#ifndef DEM_EVENT_STATUS_PASSED
#define DEM_EVENT_STATUS_PASSED 0U
#endif /* DEM_EVENT_STATUS_PASSED */

#ifndef DEM_EVENT_STATUS_PREFAILED
#define DEM_EVENT_STATUS_PREFAILED 3U
#endif /* DEM_EVENT_STATUS_PREFAILED */

#ifndef DEM_EVENT_STATUS_PREPASSED
#define DEM_EVENT_STATUS_PREPASSED 2U
#endif /* DEM_EVENT_STATUS_PREPASSED */

#endif /* (!defined RTE_CORE) */

/*------------------[range definitions]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif /* (!defined RTE_CORE) */

/*------------------[mode declarations]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#ifndef RTE_TRANSITION_RCD_stWkuMainRelSt
#define RTE_TRANSITION_RCD_stWkuMainRelSt 4U
#endif

#ifndef RTE_MODE_RCD_stWkuMainRelSt_Invalid
#define RTE_MODE_RCD_stWkuMainRelSt_Invalid 0U
#endif

#ifndef RTE_MODE_RCD_stWkuMainRelSt_MainWakeUp
#define RTE_MODE_RCD_stWkuMainRelSt_MainWakeUp 1U
#endif

#ifndef RTE_MODE_RCD_stWkuMainRelSt_PostMainWakeUp
#define RTE_MODE_RCD_stWkuMainRelSt_PostMainWakeUp 2U
#endif

#ifndef RTE_MODE_RCD_stWkuMainRelSt_PreMainWakeUp
#define RTE_MODE_RCD_stWkuMainRelSt_PreMainWakeUp 3U
#endif

#ifndef RTE_TRANSITION_EcuM_Mode
#define RTE_TRANSITION_EcuM_Mode 6U
#endif

#ifndef RTE_MODE_EcuM_Mode_POST_RUN
#define RTE_MODE_EcuM_Mode_POST_RUN 0U
#endif

#ifndef RTE_MODE_EcuM_Mode_RUN
#define RTE_MODE_EcuM_Mode_RUN 1U
#endif

#ifndef RTE_MODE_EcuM_Mode_SHUTDOWN
#define RTE_MODE_EcuM_Mode_SHUTDOWN 2U
#endif

#ifndef RTE_MODE_EcuM_Mode_SLEEP
#define RTE_MODE_EcuM_Mode_SLEEP 3U
#endif

#ifndef RTE_MODE_EcuM_Mode_STARTUP
#define RTE_MODE_EcuM_Mode_STARTUP 4U
#endif

#ifndef RTE_MODE_EcuM_Mode_WAKE_SLEEP
#define RTE_MODE_EcuM_Mode_WAKE_SLEEP 5U
#endif

#endif /* (!defined RTE_CORE) */

/*==================[type definitions]=======================================*/

/*------------------[mode declaration group types]---------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#ifndef RTE_MODETYPE_RCD_stWkuMainRelSt
#define RTE_MODETYPE_RCD_stWkuMainRelSt
typedef UInt8 Rte_ModeType_RCD_stWkuMainRelSt;
#endif

#ifndef RTE_MODETYPE_EcuM_Mode
#define RTE_MODETYPE_EcuM_Mode
typedef UInt8 Rte_ModeType_EcuM_Mode;
#endif

#endif /* (!defined RTE_CORE) */

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(RTE_PRODELEM_TYPE_H) */
/*==================[end of file]============================================*/

