#if !defined(RTE_VSINFO_TYPE_H)
#define RTE_VSINFO_TYPE_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains the application-specific types for component type VSINFO
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.57
  * on Mon Nov 03 12:24:32 CET 2014. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <Rte_Type.h>         /* RTE types header file */

/*==================[macros]=================================================*/

/*------------------[enumeration constants]----------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#ifndef VSCtl_bAvlTqWhlPT_no1_Non_disponible
#define VSCtl_bAvlTqWhlPT_no1_Non_disponible 0U
#endif /* VSCtl_bAvlTqWhlPT_no1_Non_disponible */

#ifndef VSCtl_bAvlTqWhlPT_no1_Disponible
#define VSCtl_bAvlTqWhlPT_no1_Disponible 1U
#endif /* VSCtl_bAvlTqWhlPT_no1_Disponible */

#ifndef VSCtl_bAvlTqWhlPT_no2_Non_disponible
#define VSCtl_bAvlTqWhlPT_no2_Non_disponible 0U
#endif /* VSCtl_bAvlTqWhlPT_no2_Non_disponible */

#ifndef VSCtl_bAvlTqWhlPT_no2_Disponible
#define VSCtl_bAvlTqWhlPT_no2_Disponible 1U
#endif /* VSCtl_bAvlTqWhlPT_no2_Disponible */

#ifndef VSCtl_bAvlTqWhlPT_no3_Non_disponible
#define VSCtl_bAvlTqWhlPT_no3_Non_disponible 0U
#endif /* VSCtl_bAvlTqWhlPT_no3_Non_disponible */

#ifndef VSCtl_bAvlTqWhlPT_no3_Disponible
#define VSCtl_bAvlTqWhlPT_no3_Disponible 1U
#endif /* VSCtl_bAvlTqWhlPT_no3_Disponible */

#ifndef VSCtl_bCtlaTqPT_Non_pilotable
#define VSCtl_bCtlaTqPT_Non_pilotable 0U
#endif /* VSCtl_bCtlaTqPT_Non_pilotable */

#ifndef VSCtl_bCtlaTqPT_Pilotable
#define VSCtl_bCtlaTqPT_Pilotable 1U
#endif /* VSCtl_bCtlaTqPT_Pilotable */

#ifndef VSCtl_bLgtCtlDyn_Transitoire
#define VSCtl_bLgtCtlDyn_Transitoire 0U
#endif /* VSCtl_bLgtCtlDyn_Transitoire */

#ifndef VSCtl_bLgtCtlDyn_Stabilise
#define VSCtl_bLgtCtlDyn_Stabilise 1U
#endif /* VSCtl_bLgtCtlDyn_Stabilise */

#ifndef VSCtl_bNbGearEgdChg_Pas_de_changement
#define VSCtl_bNbGearEgdChg_Pas_de_changement 0U
#endif /* VSCtl_bNbGearEgdChg_Pas_de_changement */

#ifndef VSCtl_bNbGearEgdChg_Changement_en_cours
#define VSCtl_bNbGearEgdChg_Changement_en_cours 1U
#endif /* VSCtl_bNbGearEgdChg_Changement_en_cours */

#ifndef VSCtl_stVSCtlInfo_Arret_div_ARRET
#define VSCtl_stVSCtlInfo_Arret_div_ARRET 0U
#endif /* VSCtl_stVSCtlInfo_Arret_div_ARRET */

#ifndef VSCtl_stVSCtlInfo_Verification_div_VERIF_20
#define VSCtl_stVSCtlInfo_Verification_div_VERIF_20 1U
#endif /* VSCtl_stVSCtlInfo_Verification_div_VERIF_20 */

#ifndef VSCtl_stVSCtlInfo_Initialisation_div_INIT_20
#define VSCtl_stVSCtlInfo_Initialisation_div_INIT_20 2U
#endif /* VSCtl_stVSCtlInfo_Initialisation_div_INIT_20 */

#ifndef VSCtl_stVSCtlInfo_Nominal_div_NOMINAL_20
#define VSCtl_stVSCtlInfo_Nominal_div_NOMINAL_20 3U
#endif /* VSCtl_stVSCtlInfo_Nominal_div_NOMINAL_20 */

#ifndef VSCtl_stVSCtlInfo_Defaut_div_DEFAUT_20
#define VSCtl_stVSCtlInfo_Defaut_div_DEFAUT_20 4U
#endif /* VSCtl_stVSCtlInfo_Defaut_div_DEFAUT_20 */

#ifndef Brk_bBrkAuto_Pas_en_cours
#define Brk_bBrkAuto_Pas_en_cours 0U
#endif /* Brk_bBrkAuto_Pas_en_cours */

#ifndef Brk_bBrkAuto_En_cours
#define Brk_bBrkAuto_En_cours 1U
#endif /* Brk_bBrkAuto_En_cours */

#ifndef Brk_bBrkDyn_Pas_en_cours
#define Brk_bBrkDyn_Pas_en_cours 0U
#endif /* Brk_bBrkDyn_Pas_en_cours */

#ifndef Brk_bBrkDyn_En_cours
#define Brk_bBrkDyn_En_cours 1U
#endif /* Brk_bBrkDyn_En_cours */

#ifndef CoPTSt_stEng_Coupe_Cale
#define CoPTSt_stEng_Coupe_Cale 1U
#endif /* CoPTSt_stEng_Coupe_Cale */

#ifndef CoPTSt_stEng_Preparation
#define CoPTSt_stEng_Preparation 2U
#endif /* CoPTSt_stEng_Preparation */

#ifndef CoPTSt_stEng_Driven_Start
#define CoPTSt_stEng_Driven_Start 3U
#endif /* CoPTSt_stEng_Driven_Start */

#ifndef CoPTSt_stEng_Autonomous_Start
#define CoPTSt_stEng_Autonomous_Start 4U
#endif /* CoPTSt_stEng_Autonomous_Start */

#ifndef CoPTSt_stEng_Engine_Running
#define CoPTSt_stEng_Engine_Running 5U
#endif /* CoPTSt_stEng_Engine_Running */

#ifndef CoPTSt_stEng_Stop
#define CoPTSt_stEng_Stop 6U
#endif /* CoPTSt_stEng_Stop */

#ifndef CoPTSt_stEng_Driven_Restart
#define CoPTSt_stEng_Driven_Restart 7U
#endif /* CoPTSt_stEng_Driven_Restart */

#ifndef CoPTSt_stEng_Autonomous_Restart
#define CoPTSt_stEng_Autonomous_Restart 8U
#endif /* CoPTSt_stEng_Autonomous_Restart */

#ifndef CoPTSt_stEng_reserve_9
#define CoPTSt_stEng_reserve_9 9U
#endif /* CoPTSt_stEng_reserve_9 */

#ifndef CoPTSt_stEng_reserve_10
#define CoPTSt_stEng_reserve_10 10U
#endif /* CoPTSt_stEng_reserve_10 */

#ifndef CoPTSt_stEng_reserve_11
#define CoPTSt_stEng_reserve_11 11U
#endif /* CoPTSt_stEng_reserve_11 */

#ifndef CoPTSt_stEng_reserve_12
#define CoPTSt_stEng_reserve_12 12U
#endif /* CoPTSt_stEng_reserve_12 */

#ifndef CoPTSt_stEng_reserve_13
#define CoPTSt_stEng_reserve_13 13U
#endif /* CoPTSt_stEng_reserve_13 */

#ifndef CoPTSt_stEng_reserve_14
#define CoPTSt_stEng_reserve_14 14U
#endif /* CoPTSt_stEng_reserve_14 */

#ifndef CoPTSt_stEng_reserve_15
#define CoPTSt_stEng_reserve_15 15U
#endif /* CoPTSt_stEng_reserve_15 */

#ifndef CoPt_bSIPCord_Pas_de_changement_de_rapport_en_cours
#define CoPt_bSIPCord_Pas_de_changement_de_rapport_en_cours 0U
#endif /* CoPt_bSIPCord_Pas_de_changement_de_rapport_en_cours */

#ifndef CoPt_bSIPCord_Changement_de_rapport_en_cours
#define CoPt_bSIPCord_Changement_de_rapport_en_cours 1U
#endif /* CoPt_bSIPCord_Changement_de_rapport_en_cours */

#ifndef CoPt_noEgdGearCordIt_rapport_de_marche_arriere
#define CoPt_noEgdGearCordIt_rapport_de_marche_arriere -1
#endif /* CoPt_noEgdGearCordIt_rapport_de_marche_arriere */

#ifndef CoPt_noEgdGearCordIt_rapport_0
#define CoPt_noEgdGearCordIt_rapport_0 0U
#endif /* CoPt_noEgdGearCordIt_rapport_0 */

#ifndef CoPt_noEgdGearCordIt_rapport_1
#define CoPt_noEgdGearCordIt_rapport_1 1U
#endif /* CoPt_noEgdGearCordIt_rapport_1 */

#ifndef CoPt_noEgdGearCordIt_rapport_2
#define CoPt_noEgdGearCordIt_rapport_2 2U
#endif /* CoPt_noEgdGearCordIt_rapport_2 */

#ifndef CoPt_noEgdGearCordIt_rapport_3
#define CoPt_noEgdGearCordIt_rapport_3 3U
#endif /* CoPt_noEgdGearCordIt_rapport_3 */

#ifndef CoPt_noEgdGearCordIt_rapport_4
#define CoPt_noEgdGearCordIt_rapport_4 4U
#endif /* CoPt_noEgdGearCordIt_rapport_4 */

#ifndef CoPt_noEgdGearCordIt_rapport_5
#define CoPt_noEgdGearCordIt_rapport_5 5U
#endif /* CoPt_noEgdGearCordIt_rapport_5 */

#ifndef CoPt_noEgdGearCordIt_rapport_6
#define CoPt_noEgdGearCordIt_rapport_6 6U
#endif /* CoPt_noEgdGearCordIt_rapport_6 */

#ifndef CoPt_noEgdGearCordIt_rapport_7
#define CoPt_noEgdGearCordIt_rapport_7 7U
#endif /* CoPt_noEgdGearCordIt_rapport_7 */

#ifndef CoPt_noEgdGearCordIt_rapport_8
#define CoPt_noEgdGearCordIt_rapport_8 8U
#endif /* CoPt_noEgdGearCordIt_rapport_8 */

#ifndef CoPt_posnLev_P
#define CoPt_posnLev_P 0U
#endif /* CoPt_posnLev_P */

#ifndef CoPt_posnLev_R
#define CoPt_posnLev_R 1U
#endif /* CoPt_posnLev_R */

#ifndef CoPt_posnLev_N
#define CoPt_posnLev_N 2U
#endif /* CoPt_posnLev_N */

#ifndef CoPt_posnLev_Drive
#define CoPt_posnLev_Drive 3U
#endif /* CoPt_posnLev_Drive */

#ifndef CoPt_posnLev_Intermediaire_P_div_R_ou_N_div_R
#define CoPt_posnLev_Intermediaire_P_div_R_ou_N_div_R 4U
#endif /* CoPt_posnLev_Intermediaire_P_div_R_ou_N_div_R */

#ifndef CoPt_posnLev_Intermediaire_N_div_D
#define CoPt_posnLev_Intermediaire_N_div_D 5U
#endif /* CoPt_posnLev_Intermediaire_N_div_D */

#ifndef CoPt_posnLev_Mode_Manuel
#define CoPt_posnLev_Mode_Manuel 6U
#endif /* CoPt_posnLev_Mode_Manuel */

#ifndef CoPt_posnLev_Indisponible
#define CoPt_posnLev_Indisponible 7U
#endif /* CoPt_posnLev_Indisponible */

#ifndef CoPt_stClu_Ouvert
#define CoPt_stClu_Ouvert 0U
#endif /* CoPt_stClu_Ouvert */

#ifndef CoPt_stClu_Glissant
#define CoPt_stClu_Glissant 1U
#endif /* CoPt_stClu_Glissant */

#ifndef CoPt_stClu_Synchronise
#define CoPt_stClu_Synchronise 2U
#endif /* CoPt_stClu_Synchronise */

#ifndef CoPt_stClu_Ferme
#define CoPt_stClu_Ferme 3U
#endif /* CoPt_stClu_Ferme */

#ifndef ECU_bAuthVSCtlIni_Non_autorise
#define ECU_bAuthVSCtlIni_Non_autorise 0U
#endif /* ECU_bAuthVSCtlIni_Non_autorise */

#ifndef ECU_bAuthVSCtlIni_Autorise
#define ECU_bAuthVSCtlIni_Autorise 1U
#endif /* ECU_bAuthVSCtlIni_Autorise */

#ifndef Ext_bAvlTqWhlPT_no1_Non_disponible
#define Ext_bAvlTqWhlPT_no1_Non_disponible 0U
#endif /* Ext_bAvlTqWhlPT_no1_Non_disponible */

#ifndef Ext_bAvlTqWhlPT_no1_Disponible
#define Ext_bAvlTqWhlPT_no1_Disponible 1U
#endif /* Ext_bAvlTqWhlPT_no1_Disponible */

#ifndef Ext_bAvlTqWhlPT_no2_Non_disponible
#define Ext_bAvlTqWhlPT_no2_Non_disponible 0U
#endif /* Ext_bAvlTqWhlPT_no2_Non_disponible */

#ifndef Ext_bAvlTqWhlPT_no2_Disponible
#define Ext_bAvlTqWhlPT_no2_Disponible 1U
#endif /* Ext_bAvlTqWhlPT_no2_Disponible */

#ifndef Ext_bAvlTqWhlPT_no3_Non_disponible
#define Ext_bAvlTqWhlPT_no3_Non_disponible 0U
#endif /* Ext_bAvlTqWhlPT_no3_Non_disponible */

#ifndef Ext_bAvlTqWhlPT_no3_Disponible
#define Ext_bAvlTqWhlPT_no3_Disponible 1U
#endif /* Ext_bAvlTqWhlPT_no3_Disponible */

#ifndef Ext_bBrkAutoCf_Absent
#define Ext_bBrkAutoCf_Absent 0U
#endif /* Ext_bBrkAutoCf_Absent */

#ifndef Ext_bBrkAutoCf_Present
#define Ext_bBrkAutoCf_Present 1U
#endif /* Ext_bBrkAutoCf_Present */

#ifndef Ext_bBrkDynCf_Absent
#define Ext_bBrkDynCf_Absent 0U
#endif /* Ext_bBrkDynCf_Absent */

#ifndef Ext_bBrkDynCf_Present
#define Ext_bBrkDynCf_Present 1U
#endif /* Ext_bBrkDynCf_Present */

#ifndef Ext_bBrkPedPrss_Pedale_de_frein_relachee
#define Ext_bBrkPedPrss_Pedale_de_frein_relachee 0U
#endif /* Ext_bBrkPedPrss_Pedale_de_frein_relachee */

#ifndef Ext_bBrkPedPrss_Pedale_de_frein_enfoncee
#define Ext_bBrkPedPrss_Pedale_de_frein_enfoncee 1U
#endif /* Ext_bBrkPedPrss_Pedale_de_frein_enfoncee */

#ifndef Ext_bCluPedPrss_Pedale_d_embrayage_relachee
#define Ext_bCluPedPrss_Pedale_d_embrayage_relachee 0U
#endif /* Ext_bCluPedPrss_Pedale_d_embrayage_relachee */

#ifndef Ext_bCluPedPrss_Appui_sur_pedale_d_embrayage
#define Ext_bCluPedPrss_Appui_sur_pedale_d_embrayage 1U
#endif /* Ext_bCluPedPrss_Appui_sur_pedale_d_embrayage */

#ifndef Ext_bDetLoWhlGrip_Non_degradee
#define Ext_bDetLoWhlGrip_Non_degradee 0U
#endif /* Ext_bDetLoWhlGrip_Non_degradee */

#ifndef Ext_bDetLoWhlGrip_Degradee
#define Ext_bDetLoWhlGrip_Degradee 1U
#endif /* Ext_bDetLoWhlGrip_Degradee */

#ifndef Ext_bDetLoWhlGripCf_Absent
#define Ext_bDetLoWhlGripCf_Absent 0U
#endif /* Ext_bDetLoWhlGripCf_Absent */

#ifndef Ext_bDetLoWhlGripCf_Present
#define Ext_bDetLoWhlGripCf_Present 1U
#endif /* Ext_bDetLoWhlGripCf_Present */

#ifndef Ext_bPosnGBxCf_Absent
#define Ext_bPosnGBxCf_Absent 0U
#endif /* Ext_bPosnGBxCf_Absent */

#ifndef Ext_bPosnGBxCf_Present
#define Ext_bPosnGBxCf_Present 1U
#endif /* Ext_bPosnGBxCf_Present */

#ifndef Ext_bPrkBrk_Pas_de_serrage
#define Ext_bPrkBrk_Pas_de_serrage 0U
#endif /* Ext_bPrkBrk_Pas_de_serrage */

#ifndef Ext_bPrkBrk_Serrage
#define Ext_bPrkBrk_Serrage 1U
#endif /* Ext_bPrkBrk_Serrage */

#ifndef Ext_bRatConvTraCf_Absent
#define Ext_bRatConvTraCf_Absent 0U
#endif /* Ext_bRatConvTraCf_Absent */

#ifndef Ext_bRatConvTraCf_Present
#define Ext_bRatConvTraCf_Present 1U
#endif /* Ext_bRatConvTraCf_Present */

#ifndef Ext_bRotSpdFrntWhlCf_Absent
#define Ext_bRotSpdFrntWhlCf_Absent 0U
#endif /* Ext_bRotSpdFrntWhlCf_Absent */

#ifndef Ext_bRotSpdFrntWhlCf_Present
#define Ext_bRotSpdFrntWhlCf_Present 1U
#endif /* Ext_bRotSpdFrntWhlCf_Present */

#ifndef Ext_bSpdFrntWhlCf_Absent
#define Ext_bSpdFrntWhlCf_Absent 0U
#endif /* Ext_bSpdFrntWhlCf_Absent */

#ifndef Ext_bSpdFrntWhlCf_Present
#define Ext_bSpdFrntWhlCf_Present 1U
#endif /* Ext_bSpdFrntWhlCf_Present */

#ifndef Ext_bSpdReWhlCf_Absent
#define Ext_bSpdReWhlCf_Absent 0U
#endif /* Ext_bSpdReWhlCf_Absent */

#ifndef Ext_bSpdReWhlCf_Present
#define Ext_bSpdReWhlCf_Present 1U
#endif /* Ext_bSpdReWhlCf_Present */

#ifndef Ext_bTqWhlBrkCf_Absent
#define Ext_bTqWhlBrkCf_Absent 0U
#endif /* Ext_bTqWhlBrkCf_Absent */

#ifndef Ext_bTqWhlBrkCf_Present
#define Ext_bTqWhlBrkCf_Present 1U
#endif /* Ext_bTqWhlBrkCf_Present */

#ifndef Ext_bVSLimCf_LVV_non_active
#define Ext_bVSLimCf_LVV_non_active 0U
#endif /* Ext_bVSLimCf_LVV_non_active */

#ifndef Ext_bVSLimCf_LVV_active
#define Ext_bVSLimCf_LVV_active 1U
#endif /* Ext_bVSLimCf_LVV_active */

#ifndef Ext_bVSMaxfCf_Absent
#define Ext_bVSMaxfCf_Absent 0U
#endif /* Ext_bVSMaxfCf_Absent */

#ifndef Ext_bVSMaxfCf_Present
#define Ext_bVSMaxfCf_Present 1U
#endif /* Ext_bVSMaxfCf_Present */

#ifndef Ext_bVSMaxpCf_Absent
#define Ext_bVSMaxpCf_Absent 0U
#endif /* Ext_bVSMaxpCf_Absent */

#ifndef Ext_bVSMaxpCf_Present
#define Ext_bVSMaxpCf_Present 1U
#endif /* Ext_bVSMaxpCf_Present */

#ifndef Ext_bVSMaxsCf_Absent
#define Ext_bVSMaxsCf_Absent 0U
#endif /* Ext_bVSMaxsCf_Absent */

#ifndef Ext_bVSMaxsCf_Present
#define Ext_bVSMaxsCf_Present 1U
#endif /* Ext_bVSMaxsCf_Present */

#ifndef Ext_stDVSRegCf_Absente
#define Ext_stDVSRegCf_Absente 0U
#endif /* Ext_stDVSRegCf_Absente */

#ifndef Ext_stDVSRegCf_RVV_presente
#define Ext_stDVSRegCf_RVV_presente 1U
#endif /* Ext_stDVSRegCf_RVV_presente */

#ifndef Ext_stDVSRegCf_ACC_presente
#define Ext_stDVSRegCf_ACC_presente 2U
#endif /* Ext_stDVSRegCf_ACC_presente */

#ifndef Ext_stGBxCf_BVM
#define Ext_stGBxCf_BVM 0U
#endif /* Ext_stGBxCf_BVM */

#ifndef Ext_stGBxCf_BVA
#define Ext_stGBxCf_BVA 1U
#endif /* Ext_stGBxCf_BVA */

#ifndef Ext_stGBxCf_BVMP
#define Ext_stGBxCf_BVMP 2U
#endif /* Ext_stGBxCf_BVMP */

#ifndef Ext_stPTCf_Traction
#define Ext_stPTCf_Traction 0U
#endif /* Ext_stPTCf_Traction */

#ifndef Ext_stPTCf_Propulsion
#define Ext_stPTCf_Propulsion 1U
#endif /* Ext_stPTCf_Propulsion */

#ifndef Ext_stPTCf_Integrale
#define Ext_stPTCf_Integrale 2U
#endif /* Ext_stPTCf_Integrale */

#ifndef InjSys_bFuCutOff_injection_not_cut_off
#define InjSys_bFuCutOff_injection_not_cut_off 0U
#endif /* InjSys_bFuCutOff_injection_not_cut_off */

#ifndef InjSys_bFuCutOff_injection_cut_off
#define InjSys_bFuCutOff_injection_cut_off 1U
#endif /* InjSys_bFuCutOff_injection_cut_off */

#ifndef DEM_EVENT_STATUS_FAILED
#define DEM_EVENT_STATUS_FAILED 1U
#endif /* DEM_EVENT_STATUS_FAILED */

#ifndef DEM_EVENT_STATUS_INIT
#define DEM_EVENT_STATUS_INIT 32U
#endif /* DEM_EVENT_STATUS_INIT */

#ifndef DEM_EVENT_STATUS_PASSED
#define DEM_EVENT_STATUS_PASSED 0U
#endif /* DEM_EVENT_STATUS_PASSED */

#ifndef DEM_EVENT_STATUS_PREFAILED
#define DEM_EVENT_STATUS_PREFAILED 3U
#endif /* DEM_EVENT_STATUS_PREFAILED */

#ifndef DEM_EVENT_STATUS_PREPASSED
#define DEM_EVENT_STATUS_PREPASSED 2U
#endif /* DEM_EVENT_STATUS_PREPASSED */

#ifndef VSCtl_bCtlEfc_tqCkEfcMax_Couple_non_effectif
#define VSCtl_bCtlEfc_tqCkEfcMax_Couple_non_effectif 0U
#endif /* VSCtl_bCtlEfc_tqCkEfcMax_Couple_non_effectif */

#ifndef VSCtl_bCtlEfc_tqCkEfcMax_Couple_effectif
#define VSCtl_bCtlEfc_tqCkEfcMax_Couple_effectif 1U
#endif /* VSCtl_bCtlEfc_tqCkEfcMax_Couple_effectif */

#ifndef VSCtl_bCtlEfc_tqWhlPTMax_Couple_non_effectif
#define VSCtl_bCtlEfc_tqWhlPTMax_Couple_non_effectif 0U
#endif /* VSCtl_bCtlEfc_tqWhlPTMax_Couple_non_effectif */

#ifndef VSCtl_bCtlEfc_tqWhlPTMax_Couple_effectif
#define VSCtl_bCtlEfc_tqWhlPTMax_Couple_effectif 1U
#endif /* VSCtl_bCtlEfc_tqWhlPTMax_Couple_effectif */

#ifndef VehEst_bCtlTqWhlPT_Zone_basse
#define VehEst_bCtlTqWhlPT_Zone_basse 0U
#endif /* VehEst_bCtlTqWhlPT_Zone_basse */

#ifndef VehEst_bCtlTqWhlPT_Zone_haute
#define VehEst_bCtlTqWhlPT_Zone_haute 1U
#endif /* VehEst_bCtlTqWhlPT_Zone_haute */

#endif /* (!defined RTE_CORE) */

/*------------------[range definitions]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif /* (!defined RTE_CORE) */

/*------------------[mode declarations]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#ifndef RTE_TRANSITION_EcuM_Mode
#define RTE_TRANSITION_EcuM_Mode 6U
#endif

#ifndef RTE_MODE_EcuM_Mode_POST_RUN
#define RTE_MODE_EcuM_Mode_POST_RUN 0U
#endif

#ifndef RTE_MODE_EcuM_Mode_RUN
#define RTE_MODE_EcuM_Mode_RUN 1U
#endif

#ifndef RTE_MODE_EcuM_Mode_SHUTDOWN
#define RTE_MODE_EcuM_Mode_SHUTDOWN 2U
#endif

#ifndef RTE_MODE_EcuM_Mode_SLEEP
#define RTE_MODE_EcuM_Mode_SLEEP 3U
#endif

#ifndef RTE_MODE_EcuM_Mode_STARTUP
#define RTE_MODE_EcuM_Mode_STARTUP 4U
#endif

#ifndef RTE_MODE_EcuM_Mode_WAKE_SLEEP
#define RTE_MODE_EcuM_Mode_WAKE_SLEEP 5U
#endif

#ifndef RTE_TRANSITION_RCD_stWkuMainRelSt
#define RTE_TRANSITION_RCD_stWkuMainRelSt 4U
#endif

#ifndef RTE_MODE_RCD_stWkuMainRelSt_Invalid
#define RTE_MODE_RCD_stWkuMainRelSt_Invalid 0U
#endif

#ifndef RTE_MODE_RCD_stWkuMainRelSt_MainWakeUp
#define RTE_MODE_RCD_stWkuMainRelSt_MainWakeUp 1U
#endif

#ifndef RTE_MODE_RCD_stWkuMainRelSt_PostMainWakeUp
#define RTE_MODE_RCD_stWkuMainRelSt_PostMainWakeUp 2U
#endif

#ifndef RTE_MODE_RCD_stWkuMainRelSt_PreMainWakeUp
#define RTE_MODE_RCD_stWkuMainRelSt_PreMainWakeUp 3U
#endif

#endif /* (!defined RTE_CORE) */

/*==================[type definitions]=======================================*/

/*------------------[mode declaration group types]---------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#ifndef RTE_MODETYPE_EcuM_Mode
#define RTE_MODETYPE_EcuM_Mode
typedef UInt8 Rte_ModeType_EcuM_Mode;
#endif

#ifndef RTE_MODETYPE_RCD_stWkuMainRelSt
#define RTE_MODETYPE_RCD_stWkuMainRelSt
typedef UInt8 Rte_ModeType_RCD_stWkuMainRelSt;
#endif

#endif /* (!defined RTE_CORE) */

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(RTE_VSINFO_TYPE_H) */
/*==================[end of file]============================================*/

