#if !defined(RTE_VSSP_H)
#define RTE_VSSP_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains Rte component declarations for component type VSSP
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.57
  * on Mon Nov 03 12:24:32 CET 2014. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <Rte_Intern_Application_Core1.h>
#include <Rte_Main.h>         /* RTE main header file */
#include <Rte_VSSP_Type.h> /* RTE application types header file */
#include <Rte_Hook.h> /* RTE VFB trace hooks header file */

/*==================[macros]=================================================*/

#if (!defined RTE_CORE) /* if included by software component */

#if (!defined RTE_APPLICATION_HEADER_FILE_H) /* prevent double inclusion */
#define RTE_APPLICATION_HEADER_FILE_H
#else
#error Multiple application header files included.
#endif /* if !defined( RTE_APPLICATION_HEADER_FILE_H ) */

#endif

/*------------------[API mapping]--------------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
#if !defined(RTE_RUNNABLEAPI_RE_VSSp_003_TEV) || !defined(RTE_RUNNABLEAPI_RE_VSSp_004_MSE) || !defined(RTE_RUNNABLEAPI_RE_VSSp_001_MSE)
#define Rte_IrvWrite_RE_VSSp_002_TEV_VSCtl_bCtlEfc_tqWhlPT_pt1(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_bCtlEfc_tqWhlPT_pt1 = (data))

#define Rte_IrvWrite_RE_VSSp_002_TEV_VSCtl_bCtlEfc_tqWhlPT_pt2(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_bCtlEfc_tqWhlPT_pt2 = (data))

#define Rte_IrvWrite_RE_VSSp_002_TEV_VSCtl_stTqPTMinCtl_pt1(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMinCtl_pt1 = (data))

#define Rte_IrvWrite_RE_VSSp_002_TEV_VSCtl_stTqPTMinCtl_pt2(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMinCtl_pt2 = (data))

#define Rte_IrvWrite_RE_VSSp_002_TEV_VSCtl_stTqPTMaxCtl_pt1(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMaxCtl_pt1 = (data))

#define Rte_IrvWrite_RE_VSSp_002_TEV_VSCtl_stTqPTMaxCtl_pt2(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMaxCtl_pt2 = (data))

#define Rte_Read_R_VSCtl_tqWhlPTMin_VSCtl_tqWhlPTMin(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTMin_VSCtl_tqWhlPTMin(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTMin_VSCtl_tqWhlPTMin() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4474.isUpdated)

#define Rte_Read_R_VSCtl_tqCkEfcMin_VSCtl_tqCkEfcMin(data) Rte_Read_VSSP_R_VSCtl_tqCkEfcMin_VSCtl_tqCkEfcMin(data)

#define Rte_IsUpdated_R_VSCtl_tqCkEfcMin_VSCtl_tqCkEfcMin() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4461.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPTPotRawMax_VSCtl_tqWhlPTPotRawMax(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTPotRawMax_VSCtl_tqWhlPTPotRawMax(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTPotRawMax_VSCtl_tqWhlPTPotRawMax() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4476.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPTPreCoVSCMaxReq_VSCtl_tqWhlPTPreCoVSCMaxReq(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTPreCoVSCMaxReq_VSCtl_tqWhlPTPreCoVSCMaxReq(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTPreCoVSCMaxReq_VSCtl_tqWhlPTPreCoVSCMaxReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4478.isUpdated)

#define Rte_Read_R_VSCtl_bCtlaTqPT_VSCtl_bCtlaTqPT(data) Rte_Read_VSSP_R_VSCtl_bCtlaTqPT_VSCtl_bCtlaTqPT(data)

#define Rte_IsUpdated_R_VSCtl_bCtlaTqPT_VSCtl_bCtlaTqPT() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4433.isUpdated)

#define Rte_Read_R_VSCtl_spdVehErrVSMax_VSCtl_spdVehErrVSMax(data) Rte_Read_VSSP_R_VSCtl_spdVehErrVSMax_VSCtl_spdVehErrVSMax(data)

#define Rte_IsUpdated_R_VSCtl_spdVehErrVSMax_VSCtl_spdVehErrVSMax() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4442.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPTDrvMinReqRaw_VSCtl_tqWhlPTDrvMinReqRaw(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTDrvMinReqRaw_VSCtl_tqWhlPTDrvMinReqRaw(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTDrvMinReqRaw_VSCtl_tqWhlPTDrvMinReqRaw() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4471.isUpdated)

#define Rte_Read_R_VSCtl_rConvTra_VSCtl_rConvTra(data) Rte_Read_VSSP_R_VSCtl_rConvTra_VSCtl_rConvTra(data)

#define Rte_IsUpdated_R_VSCtl_rConvTra_VSCtl_rConvTra() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4439.isUpdated)

#define Rte_Read_R_VSCtl_aVehDVSRegReq_VSCtl_aVehDVSRegReq(data) Rte_Read_VSSP_R_VSCtl_aVehDVSRegReq_VSCtl_aVehDVSRegReq(data)

#define Rte_IsUpdated_R_VSCtl_aVehDVSRegReq_VSCtl_aVehDVSRegReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4429.isUpdated)

#define Rte_Read_R_VSCtl_tqCkEfcMax_VSCtl_tqCkEfcMax(data) Rte_Read_VSSP_R_VSCtl_tqCkEfcMax_VSCtl_tqCkEfcMax(data)

#define Rte_IsUpdated_R_VSCtl_tqCkEfcMax_VSCtl_tqCkEfcMax() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4459.isUpdated)

#define Rte_Read_R_VSCtl_stCtl_tqWhlMin_VSCtl_stCtl_tqWhlMin(data) Rte_Read_VSSP_R_VSCtl_stCtl_tqWhlMin_VSCtl_stCtl_tqWhlMin(data)

#define Rte_IsUpdated_R_VSCtl_stCtl_tqWhlMin_VSCtl_stCtl_tqWhlMin() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4449.isUpdated)

#define Rte_Read_R_AccP_rAccP_AccP_rAccP(data) Rte_Read_VSSP_R_AccP_rAccP_AccP_rAccP(data)

#define Rte_IsUpdated_R_AccP_rAccP_AccP_rAccP() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4422.isUpdated)

#define Rte_Read_R_VSCtl_tqCkEfcDrvMaxReq_VSCtl_tqCkEfcDrvMaxReq(data) Rte_Read_VSSP_R_VSCtl_tqCkEfcDrvMaxReq_VSCtl_tqCkEfcDrvMaxReq(data)

#define Rte_IsUpdated_R_VSCtl_tqCkEfcDrvMaxReq_VSCtl_tqCkEfcDrvMaxReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4457.isUpdated)

#define Rte_Read_R_Ext_nFrntWhl_Ext_nFrntWhl(data) Rte_Read_VSSP_R_Ext_nFrntWhl_Ext_nFrntWhl(data)

#define Rte_IsUpdated_R_Ext_nFrntWhl_Ext_nFrntWhl() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4425.isUpdated)

#define Rte_Read_R_CoPt_nPrimShaftTar_CoPt_nPrimShaftTar(data) Rte_Read_VSSP_R_CoPt_nPrimShaftTar_CoPt_nPrimShaftTar(data)

#define Rte_IsUpdated_R_CoPt_nPrimShaftTar_CoPt_nPrimShaftTar() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4423.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlMaxReq_VSCtl_tqWhlMaxReq(data) Rte_Read_VSSP_R_VSCtl_tqWhlMaxReq_VSCtl_tqWhlMaxReq(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlMaxReq_VSCtl_tqWhlMaxReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4466.isUpdated)

#define Rte_Read_R_VSCtl_tqCkEfcPreCoVSCtlReq_VSCtl_tqCkEfcPreCoVSCtlReq(data) Rte_Read_VSSP_R_VSCtl_tqCkEfcPreCoVSCtlReq_VSCtl_tqCkEfcPreCoVSCtlReq(data)

#define Rte_IsUpdated_R_VSCtl_tqCkEfcPreCoVSCtlReq_VSCtl_tqCkEfcPreCoVSCtlReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4464.isUpdated)

#define Rte_Read_R_Ext_stCtlCmdPTTqPotCf_Ext_stCtlCmdPTTqPotCf(data) Rte_Read_VSSP_R_Ext_stCtlCmdPTTqPotCf_Ext_stCtlCmdPTTqPotCf(data)

#define Rte_IsUpdated_R_Ext_stCtlCmdPTTqPotCf_Ext_stCtlCmdPTTqPotCf() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4426.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlMinReq_VSCtl_tqWhlMinReq(data) Rte_Read_VSSP_R_VSCtl_tqWhlMinReq_VSCtl_tqWhlMinReq(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlMinReq_VSCtl_tqWhlMinReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4467.isUpdated)

#define Rte_Read_R_Ext_stTraTypCf_Ext_stTraTypCf(data) Rte_Read_VSSP_R_Ext_stTraTypCf_Ext_stTraTypCf(data)

#define Rte_IsUpdated_R_Ext_stTraTypCf_Ext_stTraTypCf() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4427.isUpdated)

#define Rte_Read_R_VSCtl_tqCkEfcDrvMinReq_VSCtl_tqCkEfcDrvMinReq(data) Rte_Read_VSSP_R_VSCtl_tqCkEfcDrvMinReq_VSCtl_tqCkEfcDrvMinReq(data)

#define Rte_IsUpdated_R_VSCtl_tqCkEfcDrvMinReq_VSCtl_tqCkEfcDrvMinReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4458.isUpdated)

#define Rte_Read_R_VSCtl_tqCkEfcMinNotCtla_VSCtl_tqCkEfcMinNotCtla(data) Rte_Read_VSSP_R_VSCtl_tqCkEfcMinNotCtla_VSCtl_tqCkEfcMinNotCtla(data)

#define Rte_IsUpdated_R_VSCtl_tqCkEfcMinNotCtla_VSCtl_tqCkEfcMinNotCtla() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4462.isUpdated)

#define Rte_Read_R_VSCtl_bLgtCtlDyn_VSCtl_bLgtCtlDyn(data) Rte_Read_VSSP_R_VSCtl_bLgtCtlDyn_VSCtl_bLgtCtlDyn(data)

#define Rte_IsUpdated_R_VSCtl_bLgtCtlDyn_VSCtl_bLgtCtlDyn() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4435.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPTPreCoVSCMinReq_VSCtl_tqWhlPTPreCoVSCMinReq(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTPreCoVSCMinReq_VSCtl_tqWhlPTPreCoVSCMinReq(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTPreCoVSCMinReq_VSCtl_tqWhlPTPreCoVSCMinReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4479.isUpdated)

#define Rte_Read_R_VSCtl_nFrntWhlFil_VSCtl_nFrntWhlFil(data) Rte_Read_VSSP_R_VSCtl_nFrntWhlFil_VSCtl_nFrntWhlFil(data)

#define Rte_IsUpdated_R_VSCtl_nFrntWhlFil_VSCtl_nFrntWhlFil() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4438.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPTPreCoVSCtlReq_VSCtl_tqWhlPTPreCoVSCtlReq(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTPreCoVSCtlReq_VSCtl_tqWhlPTPreCoVSCtlReq(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTPreCoVSCtlReq_VSCtl_tqWhlPTPreCoVSCtlReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4480.isUpdated)

#define Rte_Read_R_VSCtl_bAuthAntTqWhlMin_VSCtl_bAuthAntTqWhlMin(data) Rte_Read_VSSP_R_VSCtl_bAuthAntTqWhlMin_VSCtl_bAuthAntTqWhlMin(data)

#define Rte_IsUpdated_R_VSCtl_bAuthAntTqWhlMin_VSCtl_bAuthAntTqWhlMin() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4431.isUpdated)

#define Rte_Read_R_VSCtl_spdVeh_VSCtl_spdVeh(data) Rte_Read_VSSP_R_VSCtl_spdVeh_VSCtl_spdVeh(data)

#define Rte_IsUpdated_R_VSCtl_spdVeh_VSCtl_spdVeh() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4440.isUpdated)

#define Rte_Read_R_VSCtl_tqCkEfcPreCoVSCMinReq_VSCtl_tqCkEfcPreCoVSCMinReq(data) Rte_Read_VSSP_R_VSCtl_tqCkEfcPreCoVSCMinReq_VSCtl_tqCkEfcPreCoVSCMinReq(data)

#define Rte_IsUpdated_R_VSCtl_tqCkEfcPreCoVSCMinReq_VSCtl_tqCkEfcPreCoVSCMinReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4463.isUpdated)

#define Rte_Read_R_VSCtl_tiCfmSdwnTqMinReq_VSCtl_tiCfmSdwnTqMinReq(data) Rte_Read_VSSP_R_VSCtl_tiCfmSdwnTqMinReq_VSCtl_tiCfmSdwnTqMinReq(data)

#define Rte_IsUpdated_R_VSCtl_tiCfmSdwnTqMinReq_VSCtl_tiCfmSdwnTqMinReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4454.isUpdated)

#define Rte_Read_R_VSCtl_bFastDeacVSLimReq_VSCtl_bFastDeacVSLimReq(data) Rte_Read_VSSP_R_VSCtl_bFastDeacVSLimReq_VSCtl_bFastDeacVSLimReq(data)

#define Rte_IsUpdated_R_VSCtl_bFastDeacVSLimReq_VSCtl_bFastDeacVSLimReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4434.isUpdated)

#define Rte_Read_R_VSCtl_bAuthAntTqWhlMax_VSCtl_bAuthAntTqWhlMax(data) Rte_Read_VSSP_R_VSCtl_bAuthAntTqWhlMax_VSCtl_bAuthAntTqWhlMax(data)

#define Rte_IsUpdated_R_VSCtl_bAuthAntTqWhlMax_VSCtl_bAuthAntTqWhlMax() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4430.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPTPotRawMin_VSCtl_tqWhlPTPotRawMin(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTPotRawMin_VSCtl_tqWhlPTPotRawMin(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTPotRawMin_VSCtl_tqWhlPTPotRawMin() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4477.isUpdated)

#define Rte_Read_R_VSCtl_stCtl_aVehVSReg_VSCtl_stCtl_aVehVSReg(data) Rte_Read_VSSP_R_VSCtl_stCtl_aVehVSReg_VSCtl_stCtl_aVehVSReg(data)

#define Rte_IsUpdated_R_VSCtl_stCtl_aVehVSReg_VSCtl_stCtl_aVehVSReg() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4447.isUpdated)

#define Rte_Read_R_VSCtl_stCtl_tqWhlPotMax_VSCtl_stCtl_tqWhlPotMax(data) Rte_Read_VSSP_R_VSCtl_stCtl_tqWhlPotMax_VSCtl_stCtl_tqWhlPotMax(data)

#define Rte_IsUpdated_R_VSCtl_stCtl_tqWhlPotMax_VSCtl_stCtl_tqWhlPotMax() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4451.isUpdated)

#define Rte_Read_R_VSCtl_nEngFil_VSCtl_nEngFil(data) Rte_Read_VSSP_R_VSCtl_nEngFil_VSCtl_nEngFil(data)

#define Rte_IsUpdated_R_VSCtl_nEngFil_VSCtl_nEngFil() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4437.isUpdated)

#define Rte_Read_R_Tra_stGearCtl_Tra_stGearCtl(data) Rte_Read_VSSP_R_Tra_stGearCtl_Tra_stGearCtl(data)

#define Rte_IsUpdated_R_Tra_stGearCtl_Tra_stGearCtl() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4428.isUpdated)

#define Rte_Read_R_VSCtl_tiCfmSdwnTqMaxReq_VSCtl_tiCfmSdwnTqMaxReq(data) Rte_Read_VSSP_R_VSCtl_tiCfmSdwnTqMaxReq_VSCtl_tiCfmSdwnTqMaxReq(data)

#define Rte_IsUpdated_R_VSCtl_tiCfmSdwnTqMaxReq_VSCtl_tiCfmSdwnTqMaxReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4453.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPTMinNotCtla_VSCtl_tqWhlPTMinNotCtla(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTMinNotCtla_VSCtl_tqWhlPTMinNotCtla(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTMinNotCtla_VSCtl_tqWhlPTMinNotCtla() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4475.isUpdated)

#define Rte_Read_R_VSCtl_stCtl_aVehVSLim_VSCtl_stCtl_aVehVSLim(data) Rte_Read_VSSP_R_VSCtl_stCtl_aVehVSLim_VSCtl_stCtl_aVehVSLim(data)

#define Rte_IsUpdated_R_VSCtl_stCtl_aVehVSLim_VSCtl_stCtl_aVehVSLim() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4445.isUpdated)

#define Rte_Read_R_VSCtl_bTqWhlMinSat_VSCtl_bTqWhlMinSat(data) Rte_Read_VSSP_R_VSCtl_bTqWhlMinSat_VSCtl_bTqWhlMinSat(data)

#define Rte_IsUpdated_R_VSCtl_bTqWhlMinSat_VSCtl_bTqWhlMinSat() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4436.isUpdated)

#define Rte_Read_R_VSCtl_tiCfmSupTqMinReq_VSCtl_tiCfmSupTqMinReq(data) Rte_Read_VSSP_R_VSCtl_tiCfmSupTqMinReq_VSCtl_tiCfmSupTqMinReq(data)

#define Rte_IsUpdated_R_VSCtl_tiCfmSupTqMinReq_VSCtl_tiCfmSupTqMinReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4456.isUpdated)

#define Rte_Read_R_VSCtl_stCtl_tqWhlMax_VSCtl_stCtl_tqWhlMax(data) Rte_Read_VSSP_R_VSCtl_stCtl_tqWhlMax_VSCtl_stCtl_tqWhlMax(data)

#define Rte_IsUpdated_R_VSCtl_stCtl_tqWhlMax_VSCtl_stCtl_tqWhlMax() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4448.isUpdated)

#define Rte_Read_R_VSCtl_tqLossTra_VSCtl_tqLossTra(data) Rte_Read_VSSP_R_VSCtl_tqLossTra_VSCtl_tqLossTra(data)

#define Rte_IsUpdated_R_VSCtl_tqLossTra_VSCtl_tqLossTra() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4465.isUpdated)

#define Rte_Read_R_VSCtl_spdVehErrVSLim_VSCtl_spdVehErrVSLim(data) Rte_Read_VSSP_R_VSCtl_spdVehErrVSLim_VSCtl_spdVehErrVSLim(data)

#define Rte_IsUpdated_R_VSCtl_spdVehErrVSLim_VSCtl_spdVehErrVSLim() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4441.isUpdated)

#define Rte_Read_R_VSCtl_stCtl_aVehDVSReg_VSCtl_stCtl_aVehDVSReg(data) Rte_Read_VSSP_R_VSCtl_stCtl_aVehDVSReg_VSCtl_stCtl_aVehDVSReg(data)

#define Rte_IsUpdated_R_VSCtl_stCtl_aVehDVSReg_VSCtl_stCtl_aVehDVSReg() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4444.isUpdated)

#define Rte_Read_R_VSCtl_bAvlTqWhlPT_no3_VSCtl_bAvlTqWhlPT_no3(data) Rte_Read_VSSP_R_VSCtl_bAvlTqWhlPT_no3_VSCtl_bAvlTqWhlPT_no3(data)

#define Rte_IsUpdated_R_VSCtl_bAvlTqWhlPT_no3_VSCtl_bAvlTqWhlPT_no3() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4432.isUpdated)

#define Rte_Read_R_VSCtl_stCtl_tqWhlPot_VSCtl_stCtl_tqWhlPot(data) Rte_Read_VSSP_R_VSCtl_stCtl_tqWhlPot_VSCtl_stCtl_tqWhlPot(data)

#define Rte_IsUpdated_R_VSCtl_stCtl_tqWhlPot_VSCtl_stCtl_tqWhlPot() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4450.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPotMaxReq_VSCtl_tqWhlPotMaxReq(data) Rte_Read_VSSP_R_VSCtl_tqWhlPotMaxReq_VSCtl_tqWhlPotMaxReq(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPotMaxReq_VSCtl_tqWhlPotMaxReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4481.isUpdated)

#define Rte_Read_R_CoPt_noTarGearCordIt_CoPt_noTarGearCordIt(data) Rte_Read_VSSP_R_CoPt_noTarGearCordIt_CoPt_noTarGearCordIt(data)

#define Rte_IsUpdated_R_CoPt_noTarGearCordIt_CoPt_noTarGearCordIt() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4424.isUpdated)

#define Rte_Read_R_VSCtl_tiCfmSupTqMaxReq_VSCtl_tiCfmSupTqMaxReq(data) Rte_Read_VSSP_R_VSCtl_tiCfmSupTqMaxReq_VSCtl_tiCfmSupTqMaxReq(data)

#define Rte_IsUpdated_R_VSCtl_tiCfmSupTqMaxReq_VSCtl_tiCfmSupTqMaxReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4455.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPotReq_VSCtl_tqWhlPotReq(data) Rte_Read_VSSP_R_VSCtl_tqWhlPotReq_VSCtl_tqWhlPotReq(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPotReq_VSCtl_tqWhlPotReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4483.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPTDrvMinReq_VSCtl_tqWhlPTDrvMinReq(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTDrvMinReq_VSCtl_tqWhlPTDrvMinReq(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTDrvMinReq_VSCtl_tqWhlPTDrvMinReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4470.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPTMaxNotCtla_VSCtl_tqWhlPTMaxNotCtla(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTMaxNotCtla_VSCtl_tqWhlPTMaxNotCtla(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTMaxNotCtla_VSCtl_tqWhlPTMaxNotCtla() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4473.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPTDrvMaxReq_VSCtl_tqWhlPTDrvMaxReq(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTDrvMaxReq_VSCtl_tqWhlPTDrvMaxReq(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTDrvMaxReq_VSCtl_tqWhlPTDrvMaxReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4469.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPTMax_VSCtl_tqWhlPTMax(data) Rte_Read_VSSP_R_VSCtl_tqWhlPTMax_VSCtl_tqWhlPTMax(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPTMax_VSCtl_tqWhlPTMax() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4472.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlPotMinReq_VSCtl_tqWhlPotMinReq(data) Rte_Read_VSSP_R_VSCtl_tqWhlPotMinReq_VSCtl_tqWhlPotMinReq(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlPotMinReq_VSCtl_tqWhlPotMinReq() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4482.isUpdated)

#define Rte_Read_R_VSCtl_spdVehErrVSReg_VSCtl_spdVehErrVSReg(data) Rte_Read_VSSP_R_VSCtl_spdVehErrVSReg_VSCtl_spdVehErrVSReg(data)

#define Rte_IsUpdated_R_VSCtl_spdVehErrVSReg_VSCtl_spdVehErrVSReg() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4443.isUpdated)

#define Rte_Read_R_VSCtl_stCtl_aVehVSMax_VSCtl_stCtl_aVehVSMax(data) Rte_Read_VSSP_R_VSCtl_stCtl_aVehVSMax_VSCtl_stCtl_aVehVSMax(data)

#define Rte_IsUpdated_R_VSCtl_stCtl_aVehVSMax_VSCtl_stCtl_aVehVSMax() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4446.isUpdated)

#define Rte_Read_R_VSCtl_tqCkEfcMaxNotCtla_VSCtl_tqCkEfcMaxNotCtla(data) Rte_Read_VSSP_R_VSCtl_tqCkEfcMaxNotCtla_VSCtl_tqCkEfcMaxNotCtla(data)

#define Rte_IsUpdated_R_VSCtl_tqCkEfcMaxNotCtla_VSCtl_tqCkEfcMaxNotCtla() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4460.isUpdated)

#define Rte_Read_R_VSCtl_stCtl_tqWhlPotMin_VSCtl_stCtl_tqWhlPotMin(data) Rte_Read_VSSP_R_VSCtl_stCtl_tqWhlPotMin_VSCtl_stCtl_tqWhlPotMin(data)

#define Rte_IsUpdated_R_VSCtl_stCtl_tqWhlPotMin_VSCtl_stCtl_tqWhlPotMin() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4452.isUpdated)

#define Rte_Read_R_VSCtl_tqWhlMinSat_VSCtl_tqWhlMinSat(data) Rte_Read_VSSP_R_VSCtl_tqWhlMinSat_VSCtl_tqWhlMinSat(data)

#define Rte_IsUpdated_R_VSCtl_tqWhlMinSat_VSCtl_tqWhlMinSat() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4468.isUpdated)

#define Rte_Call_R_FRM_bDeacVSCtlGearCtl_GetFunctionPermission(Permission) (RE_FRM_bDeacVSCtlGearCtl_GetFunctionPermission(Permission), RTE_E_OK)

#endif
#if !defined(RTE_RUNNABLEAPI_RE_VSSp_003_TEV)
#define Rte_Write_P_VSCtl_noGearReqMax_VSCtl_noGearReqMax(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_944.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_bCtlEfc_tqCkEfcMin_VSCtl_bCtlEfc_tqCkEfcMin(data) Rte_Write_VSSP_P_VSCtl_bCtlEfc_tqCkEfcMin_VSCtl_bCtlEfc_tqCkEfcMin(data)

#define Rte_Write_P_VSCtl_bAcvTqWhlPTMinSat_VSCtl_bAcvTqWhlPTMinSat(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_372.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_stGearCtlReq_VSCtl_stGearCtlReq(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_897.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_tqWhlPTMinReq_VSCtl_tqWhlPTMinReq(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_237.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_rAccPEngMax_VSCtl_rAccPEngMax(data) Rte_Write_VSSP_P_VSCtl_rAccPEngMax_VSCtl_rAccPEngMax(data)

#define Rte_Write_P_VSCtl_tqEfcTarMin_VSCtl_tqEfcTarMin(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_605.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_stTqWhlPTCutOffReq_VSCtl_stTqWhlPTCutOffReq(data) Rte_Write_VSSP_P_VSCtl_stTqWhlPTCutOffReq_VSCtl_stTqWhlPTCutOffReq(data)

#define Rte_Write_P_VSCtl_bCtlEfc_tqWhlPTMax_VSCtl_bCtlEfc_tqWhlPTMax(data) Rte_Write_VSSP_P_VSCtl_bCtlEfc_tqWhlPTMax_VSCtl_bCtlEfc_tqWhlPTMax(data)

#define Rte_Write_P_VSCtl_tqCkEfcMinReq_VSCtl_tqCkEfcMinReq(data) Rte_Write_VSSP_P_VSCtl_tqCkEfcMinReq_VSCtl_tqCkEfcMinReq(data)

#define Rte_Write_P_VSCtl_tqWhlPTPotMinReq_VSCtl_tqWhlPTPotMinReq(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1047.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_tqWhlPTMaxReq_VSCtl_tqWhlPTMaxReq(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1003.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_bCtlEfc_tqCkEfcMax_VSCtl_bCtlEfc_tqCkEfcMax(data) Rte_Write_VSSP_P_VSCtl_bCtlEfc_tqCkEfcMax_VSCtl_bCtlEfc_tqCkEfcMax(data)

#define Rte_Write_P_VSCtl_tiCfmSupReq_VSCtl_tiCfmSupReq(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1363.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_rAccPPTMin_VSCtl_rAccPPTMin(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1298.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_bCtlEfc_tqWhlPTMin_VSCtl_bCtlEfc_tqWhlPTMin(data) Rte_Write_VSSP_P_VSCtl_bCtlEfc_tqWhlPTMin_VSCtl_bCtlEfc_tqWhlPTMin(data)

#define Rte_Write_P_VSCtl_noGearReqMin_VSCtl_noGearReqMin(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1683.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_rAccPEngMin_VSCtl_rAccPEngMin(data) Rte_Write_VSSP_P_VSCtl_rAccPEngMin_VSCtl_rAccPEngMin(data)

#define Rte_Write_P_VSCtl_tqCkEfcMaxReq_VSCtl_tqCkEfcMaxReq(data) Rte_Write_VSSP_P_VSCtl_tqCkEfcMaxReq_VSCtl_tqCkEfcMaxReq(data)

#define Rte_Write_P_VSCtl_tqEfcTarMax_VSCtl_tqEfcTarMax(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_271.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_tqWhlPTPotReq_VSCtl_tqWhlPTPotReq(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1248.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_stCtl_noGear_VSCtl_stCtl_noGear(data) Rte_Write_VSSP_P_VSCtl_stCtl_noGear_VSCtl_stCtl_noGear(data)

#define Rte_Write_P_VSCtl_rAccPPTMax_VSCtl_rAccPPTMax(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1175.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_rAccPTraMin_VSCtl_rAccPTraMin(data) Rte_Write_VSSP_P_VSCtl_rAccPTraMin_VSCtl_rAccPTraMin(data)

#define Rte_Write_P_VSCtl_tqWhlPTPotMaxReq_VSCtl_tqWhlPTPotMaxReq(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_207.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_bInhRecup_VSCtl_bInhRecup(data) Rte_Write_VSSP_P_VSCtl_bInhRecup_VSCtl_bInhRecup(data)

#define Rte_Write_P_VSCtl_tiCfmSdwnReq_VSCtl_tiCfmSdwnReq(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1639.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_tqWhlPTMinSat_VSCtl_tqWhlPTMinSat(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1634.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_stTqWhlPTPotCtlReq_VSCtl_stTqWhlPTPotCtlReq(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_1406.value = (data), RTE_E_OK)

#define Rte_Write_P_VSCtl_rAccPTraMax_VSCtl_rAccPTraMax(data) Rte_Write_VSSP_P_VSCtl_rAccPTraMax_VSCtl_rAccPTraMax(data)

#endif
#if !defined(RTE_RUNNABLEAPI_RE_VSSp_004_MSE) || !defined(RTE_RUNNABLEAPI_RE_VSSp_001_MSE)
#define Rte_Read_R_Ext_bCtlCmdPTTqCf_Ext_bCtlCmdPTTqCf(data) Rte_Read_VSSP_R_Ext_bCtlCmdPTTqCf_Ext_bCtlCmdPTTqCf(data)

#define Rte_IsUpdated_R_Ext_bCtlCmdPTTqCf_Ext_bCtlCmdPTTqCf() (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_4484.isUpdated)

#endif
#define Rte_Call_R_VSSp_GetTimer_1ms_U32_GetTimer_1ms_U32 FRunTime_GetTimer_1ms_U32

#if !defined(RTE_RUNNABLEAPI_RE_VSSp_002_TEV) || !defined(RTE_RUNNABLEAPI_RE_VSSp_004_MSE) || !defined(RTE_RUNNABLEAPI_RE_VSSp_001_MSE)
#define Rte_IrvRead_RE_VSSp_003_TEV_VSCtl_stTqPTMaxCtl_pt1() (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMaxCtl_pt1)

#define Rte_IrvRead_RE_VSSp_003_TEV_VSCtl_bCtlEfc_tqWhlPT_pt2() (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_bCtlEfc_tqWhlPT_pt2)

#define Rte_IrvRead_RE_VSSp_003_TEV_VSCtl_bCtlEfc_tqWhlPT_pt1() (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_bCtlEfc_tqWhlPT_pt1)

#define Rte_IrvRead_RE_VSSp_003_TEV_VSCtl_stTqPTMinCtl_pt1() (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMinCtl_pt1)

#define Rte_IrvRead_RE_VSSp_003_TEV_VSCtl_stTqPTMinCtl_pt2() (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMinCtl_pt2)

#define Rte_IrvRead_RE_VSSp_003_TEV_VSCtl_stTqPTMaxCtl_pt2() (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMaxCtl_pt2)

#endif
#if !defined(RTE_RUNNABLEAPI_RE_VSSp_002_TEV)
#define Rte_Write_P_VSCtl_stTqPTMaxCtl_VSCtl_stTqPTMaxCtl(data) Rte_Write_VSSP_P_VSCtl_stTqPTMaxCtl_VSCtl_stTqPTMaxCtl(data)

#define Rte_Write_P_VSCtl_stTqPTMinCtl_VSCtl_stTqPTMinCtl(data) Rte_Write_VSSP_P_VSCtl_stTqPTMinCtl_VSCtl_stTqPTMinCtl(data)

#define Rte_Write_P_VSCtl_bCtlEfc_tqWhlPt_VSCtl_bCtlEfc_tqWhlPt(data) (Rte_SwcBDS_Application_Core1.Rte_ReceiveBuffer_89.value = (data), RTE_E_OK)

#endif
#if !defined(RTE_RUNNABLEAPI_RE_VSSp_002_TEV) || !defined(RTE_RUNNABLEAPI_RE_VSSp_003_TEV) || !defined(RTE_RUNNABLEAPI_RE_VSSp_001_MSE)
#define Rte_IrvWrite_RE_VSSp_004_MSE_VSCtl_bCtlEfc_tqWhlPT_pt1(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_bCtlEfc_tqWhlPT_pt1 = (data))

#define Rte_IrvWrite_RE_VSSp_004_MSE_VSCtl_stTqPTMaxCtl_pt2(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMaxCtl_pt2 = (data))

#define Rte_IrvWrite_RE_VSSp_004_MSE_VSCtl_stTqPTMinCtl_pt1(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMinCtl_pt1 = (data))

#define Rte_IrvWrite_RE_VSSp_004_MSE_VSCtl_bCtlEfc_tqWhlPT_pt2(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_bCtlEfc_tqWhlPT_pt2 = (data))

#define Rte_IrvWrite_RE_VSSp_004_MSE_VSCtl_stTqPTMaxCtl_pt1(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMaxCtl_pt1 = (data))

#define Rte_IrvWrite_RE_VSSp_004_MSE_VSCtl_stTqPTMinCtl_pt2(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMinCtl_pt2 = (data))

#endif
#if !defined(RTE_RUNNABLEAPI_RE_VSSp_002_TEV) || !defined(RTE_RUNNABLEAPI_RE_VSSp_003_TEV) || !defined(RTE_RUNNABLEAPI_RE_VSSp_004_MSE)
#define Rte_IrvWrite_RE_VSSp_001_MSE_VSCtl_bCtlEfc_tqWhlPT_pt1(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_bCtlEfc_tqWhlPT_pt1 = (data))

#define Rte_IrvWrite_RE_VSSp_001_MSE_VSCtl_stTqPTMaxCtl_pt1(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMaxCtl_pt1 = (data))

#define Rte_IrvWrite_RE_VSSp_001_MSE_VSCtl_stTqPTMaxCtl_pt2(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMaxCtl_pt2 = (data))

#define Rte_IrvWrite_RE_VSSp_001_MSE_VSCtl_bCtlEfc_tqWhlPT_pt2(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_bCtlEfc_tqWhlPT_pt2 = (data))

#define Rte_IrvWrite_RE_VSSp_001_MSE_VSCtl_stTqPTMinCtl_pt1(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMinCtl_pt1 = (data))

#define Rte_IrvWrite_RE_VSSp_001_MSE_VSCtl_stTqPTMinCtl_pt2(data) (Rte_SwcBDS_Application_Core1.Rte_Irv_inst_TopLevelComposition_VSSP_VSCtl_stTqPTMinCtl_pt2 = (data))

#endif

#endif

/*------------------[port handle API mapping]--------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*------------------[application errors]-------------------------------------*/

#define RTE_E_IF_CS_FRunTime_1MS_U32_E_NOT_OK 1U

/*------------------[init values]--------------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#define Rte_InitValue_P_VSCtl_bAcvTqWhlPTMinSat_VSCtl_bAcvTqWhlPTMinSat 0U
#define Rte_InitValue_P_VSCtl_bCtlEfc_tqCkEfcMax_VSCtl_bCtlEfc_tqCkEfcMax 0U
#define Rte_InitValue_P_VSCtl_bCtlEfc_tqCkEfcMin_VSCtl_bCtlEfc_tqCkEfcMin 0U
#define Rte_InitValue_P_VSCtl_bCtlEfc_tqWhlPTMax_VSCtl_bCtlEfc_tqWhlPTMax 0U
#define Rte_InitValue_P_VSCtl_bCtlEfc_tqWhlPTMin_VSCtl_bCtlEfc_tqWhlPTMin 0U
#define Rte_InitValue_P_VSCtl_bCtlEfc_tqWhlPt_VSCtl_bCtlEfc_tqWhlPt 0U
#define Rte_InitValue_P_VSCtl_bInhRecup_VSCtl_bInhRecup 0U
#define Rte_InitValue_P_VSCtl_noGearReqMax_VSCtl_noGearReqMax 15U
#define Rte_InitValue_P_VSCtl_noGearReqMin_VSCtl_noGearReqMin 0U
#define Rte_InitValue_P_VSCtl_rAccPEngMax_VSCtl_rAccPEngMax 12800U
#define Rte_InitValue_P_VSCtl_rAccPEngMin_VSCtl_rAccPEngMin 0U
#define Rte_InitValue_P_VSCtl_rAccPPTMax_VSCtl_rAccPPTMax 12800U
#define Rte_InitValue_P_VSCtl_rAccPPTMin_VSCtl_rAccPPTMin 0U
#define Rte_InitValue_P_VSCtl_rAccPTraMax_VSCtl_rAccPTraMax 0U
#define Rte_InitValue_P_VSCtl_rAccPTraMin_VSCtl_rAccPTraMin 0U
#define Rte_InitValue_P_VSCtl_stCtl_noGear_VSCtl_stCtl_noGear 0U
#define Rte_InitValue_P_VSCtl_stGearCtlReq_VSCtl_stGearCtlReq 0U
#define Rte_InitValue_P_VSCtl_stTqPTMaxCtl_VSCtl_stTqPTMaxCtl 0U
#define Rte_InitValue_P_VSCtl_stTqPTMinCtl_VSCtl_stTqPTMinCtl 0U
#define Rte_InitValue_P_VSCtl_stTqWhlPTCutOffReq_VSCtl_stTqWhlPTCutOffReq 0U
#define Rte_InitValue_P_VSCtl_stTqWhlPTPotCtlReq_VSCtl_stTqWhlPTPotCtlReq 0U
#define Rte_InitValue_P_VSCtl_tiCfmSdwnReq_VSCtl_tiCfmSdwnReq 0U
#define Rte_InitValue_P_VSCtl_tiCfmSupReq_VSCtl_tiCfmSupReq 0U
#define Rte_InitValue_P_VSCtl_tqCkEfcMaxReq_VSCtl_tqCkEfcMaxReq 32000
#define Rte_InitValue_P_VSCtl_tqCkEfcMinReq_VSCtl_tqCkEfcMinReq -32000
#define Rte_InitValue_P_VSCtl_tqEfcTarMax_VSCtl_tqEfcTarMax 32000
#define Rte_InitValue_P_VSCtl_tqEfcTarMin_VSCtl_tqEfcTarMin -32000
#define Rte_InitValue_P_VSCtl_tqWhlPTMaxReq_VSCtl_tqWhlPTMaxReq 22000
#define Rte_InitValue_P_VSCtl_tqWhlPTMinReq_VSCtl_tqWhlPTMinReq -8000
#define Rte_InitValue_P_VSCtl_tqWhlPTMinSat_VSCtl_tqWhlPTMinSat -8000
#define Rte_InitValue_P_VSCtl_tqWhlPTPotMaxReq_VSCtl_tqWhlPTPotMaxReq 22000
#define Rte_InitValue_P_VSCtl_tqWhlPTPotMinReq_VSCtl_tqWhlPTPotMinReq -8000
#define Rte_InitValue_P_VSCtl_tqWhlPTPotReq_VSCtl_tqWhlPTPotReq -8000
#define Rte_InitValue_R_AccP_rAccP_AccP_rAccP 0U
#define Rte_InitValue_R_CoPt_nPrimShaftTar_CoPt_nPrimShaftTar 0U
#define Rte_InitValue_R_CoPt_noTarGearCordIt_CoPt_noTarGearCordIt 0
#define Rte_InitValue_R_Ext_nFrntWhl_Ext_nFrntWhl 0U
#define Rte_InitValue_R_Ext_stCtlCmdPTTqPotCf_Ext_stCtlCmdPTTqPotCf 0U
#define Rte_InitValue_R_Ext_stTraTypCf_Ext_stTraTypCf 0U
#define Rte_InitValue_R_Tra_stGearCtl_Tra_stGearCtl 0U
#define Rte_InitValue_R_VSCtl_aVehDVSRegReq_VSCtl_aVehDVSRegReq -10240
#define Rte_InitValue_R_VSCtl_bAuthAntTqWhlMax_VSCtl_bAuthAntTqWhlMax 0U
#define Rte_InitValue_R_VSCtl_bAuthAntTqWhlMin_VSCtl_bAuthAntTqWhlMin 0U
#define Rte_InitValue_R_VSCtl_bAvlTqWhlPT_no3_VSCtl_bAvlTqWhlPT_no3 0U
#define Rte_InitValue_R_VSCtl_bCtlaTqPT_VSCtl_bCtlaTqPT 0U
#define Rte_InitValue_R_VSCtl_bFastDeacVSLimReq_VSCtl_bFastDeacVSLimReq 0U
#define Rte_InitValue_R_VSCtl_bLgtCtlDyn_VSCtl_bLgtCtlDyn 0U
#define Rte_InitValue_R_VSCtl_bTqWhlMinSat_VSCtl_bTqWhlMinSat 0U
#define Rte_InitValue_R_VSCtl_nEngFil_VSCtl_nEngFil 0U
#define Rte_InitValue_R_VSCtl_nFrntWhlFil_VSCtl_nFrntWhlFil 0U
#define Rte_InitValue_R_VSCtl_rConvTra_VSCtl_rConvTra 2560U
#define Rte_InitValue_R_VSCtl_spdVeh_VSCtl_spdVeh 0U
#define Rte_InitValue_R_VSCtl_spdVehErrVSLim_VSCtl_spdVehErrVSLim 0
#define Rte_InitValue_R_VSCtl_spdVehErrVSMax_VSCtl_spdVehErrVSMax 0
#define Rte_InitValue_R_VSCtl_spdVehErrVSReg_VSCtl_spdVehErrVSReg 0
#define Rte_InitValue_R_VSCtl_stCtl_aVehDVSReg_VSCtl_stCtl_aVehDVSReg 0U
#define Rte_InitValue_R_VSCtl_stCtl_aVehVSLim_VSCtl_stCtl_aVehVSLim 0U
#define Rte_InitValue_R_VSCtl_stCtl_aVehVSMax_VSCtl_stCtl_aVehVSMax 0U
#define Rte_InitValue_R_VSCtl_stCtl_aVehVSReg_VSCtl_stCtl_aVehVSReg 0U
#define Rte_InitValue_R_VSCtl_stCtl_tqWhlMax_VSCtl_stCtl_tqWhlMax 0U
#define Rte_InitValue_R_VSCtl_stCtl_tqWhlMin_VSCtl_stCtl_tqWhlMin 0U
#define Rte_InitValue_R_VSCtl_stCtl_tqWhlPot_VSCtl_stCtl_tqWhlPot 0U
#define Rte_InitValue_R_VSCtl_stCtl_tqWhlPotMax_VSCtl_stCtl_tqWhlPotMax 0U
#define Rte_InitValue_R_VSCtl_stCtl_tqWhlPotMin_VSCtl_stCtl_tqWhlPotMin 0U
#define Rte_InitValue_R_VSCtl_tiCfmSdwnTqMaxReq_VSCtl_tiCfmSdwnTqMaxReq 0U
#define Rte_InitValue_R_VSCtl_tiCfmSdwnTqMinReq_VSCtl_tiCfmSdwnTqMinReq 0U
#define Rte_InitValue_R_VSCtl_tiCfmSupTqMaxReq_VSCtl_tiCfmSupTqMaxReq 0U
#define Rte_InitValue_R_VSCtl_tiCfmSupTqMinReq_VSCtl_tiCfmSupTqMinReq 0U
#define Rte_InitValue_R_VSCtl_tqCkEfcDrvMaxReq_VSCtl_tqCkEfcDrvMaxReq 32000
#define Rte_InitValue_R_VSCtl_tqCkEfcDrvMinReq_VSCtl_tqCkEfcDrvMinReq -32000
#define Rte_InitValue_R_VSCtl_tqCkEfcMax_VSCtl_tqCkEfcMax 32000
#define Rte_InitValue_R_VSCtl_tqCkEfcMaxNotCtla_VSCtl_tqCkEfcMaxNotCtla 0
#define Rte_InitValue_R_VSCtl_tqCkEfcMin_VSCtl_tqCkEfcMin -32000
#define Rte_InitValue_R_VSCtl_tqCkEfcMinNotCtla_VSCtl_tqCkEfcMinNotCtla 0
#define Rte_InitValue_R_VSCtl_tqCkEfcPreCoVSCMinReq_VSCtl_tqCkEfcPreCoVSCMinReq -32000
#define Rte_InitValue_R_VSCtl_tqCkEfcPreCoVSCtlReq_VSCtl_tqCkEfcPreCoVSCtlReq 4000
#define Rte_InitValue_R_VSCtl_tqLossTra_VSCtl_tqLossTra 0
#define Rte_InitValue_R_VSCtl_tqWhlMaxReq_VSCtl_tqWhlMaxReq 32000
#define Rte_InitValue_R_VSCtl_tqWhlMinReq_VSCtl_tqWhlMinReq -32000
#define Rte_InitValue_R_VSCtl_tqWhlMinSat_VSCtl_tqWhlMinSat -32000
#define Rte_InitValue_R_VSCtl_tqWhlPTDrvMaxReq_VSCtl_tqWhlPTDrvMaxReq 32000
#define Rte_InitValue_R_VSCtl_tqWhlPTDrvMinReq_VSCtl_tqWhlPTDrvMinReq 0
#define Rte_InitValue_R_VSCtl_tqWhlPTDrvMinReqRaw_VSCtl_tqWhlPTDrvMinReqRaw 0
#define Rte_InitValue_R_VSCtl_tqWhlPTMax_VSCtl_tqWhlPTMax 0
#define Rte_InitValue_R_VSCtl_tqWhlPTMaxNotCtla_VSCtl_tqWhlPTMaxNotCtla 0
#define Rte_InitValue_R_VSCtl_tqWhlPTMin_VSCtl_tqWhlPTMin 0
#define Rte_InitValue_R_VSCtl_tqWhlPTMinNotCtla_VSCtl_tqWhlPTMinNotCtla 0
#define Rte_InitValue_R_VSCtl_tqWhlPTPotRawMax_VSCtl_tqWhlPTPotRawMax -32000
#define Rte_InitValue_R_VSCtl_tqWhlPTPotRawMin_VSCtl_tqWhlPTPotRawMin -32000
#define Rte_InitValue_R_VSCtl_tqWhlPTPreCoVSCMaxReq_VSCtl_tqWhlPTPreCoVSCMaxReq -32000
#define Rte_InitValue_R_VSCtl_tqWhlPTPreCoVSCMinReq_VSCtl_tqWhlPTPreCoVSCMinReq -32000
#define Rte_InitValue_R_VSCtl_tqWhlPTPreCoVSCtlReq_VSCtl_tqWhlPTPreCoVSCtlReq 0
#define Rte_InitValue_R_VSCtl_tqWhlPotMaxReq_VSCtl_tqWhlPotMaxReq 32000
#define Rte_InitValue_R_VSCtl_tqWhlPotMinReq_VSCtl_tqWhlPotMinReq -32000
#define Rte_InitValue_R_VSCtl_tqWhlPotReq_VSCtl_tqWhlPotReq -32000
#define Rte_InitValue_R_Ext_bCtlCmdPTTqCf_Ext_bCtlCmdPTTqCf 0U

#endif

/*==================[type definitions]=======================================*/

/*------------------[instance handle type]-----------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
typedef CONSTP2CONST(Rte_CDS_VSSP, RTE_CONST, RTE_CONST) Rte_Instance;
#endif

/*------------------[port handle types]--------------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */
#endif

/*------------------[per instance memory types]------------------------------*/

#if (!defined RTE_CORE) /* if included by software component */

#endif

/*==================[external function declarations]=========================*/

/*------------------[declaration of runnable entities]-----------------------*/

#define RTE_START_SEC_APPLICATION_CORE1_APPL_CODE
#include "MemMap.h"

extern FUNC(void, RTE_APPL_CODE) RE_VSSp_002_TEV(void);

extern FUNC(void, RTE_APPL_CODE) RE_VSSp_003_TEV(void);

extern FUNC(void, RTE_APPL_CODE) RE_VSSp_004_MSE(void);

extern FUNC(void, RTE_APPL_CODE) RE_VSSp_001_MSE(void);

#define RTE_STOP_SEC_APPLICATION_CORE1_APPL_CODE
#include "MemMap.h"

/*--------------[declaration of API functions provided by Rte]--------------*/

#define RTE_START_SEC_APPLICATION_CORE1_CODE
#include "MemMap.h"
#if (!defined(RTE_RUNNABLEAPI_RE_VSSp_003_TEV))  || (!defined(RTE_RUNNABLEAPI_RE_VSSp_004_MSE)) || (!defined(RTE_RUNNABLEAPI_RE_VSSp_001_MSE))
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTMin_VSCtl_tqWhlPTMin (P2VAR(DT_VSCtl_tqWhlPTMin, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqCkEfcMin_VSCtl_tqCkEfcMin (P2VAR(DT_VSCtl_tqCkEfcMin, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTPotRawMax_VSCtl_tqWhlPTPotRawMax (P2VAR(DT_VSCtl_tqWhlPTPotRawMax, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTPreCoVSCMaxReq_VSCtl_tqWhlPTPreCoVSCMaxReq (P2VAR(DT_VSCtl_tqWhlPTPreCoVSCMaxReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_bCtlaTqPT_VSCtl_bCtlaTqPT (P2VAR(DT_VSCtl_bCtlaTqPT, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_spdVehErrVSMax_VSCtl_spdVehErrVSMax (P2VAR(DT_VSCtl_spdVehErrVSMax, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTDrvMinReqRaw_VSCtl_tqWhlPTDrvMinReqRaw (P2VAR(DT_VSCtl_tqWhlPTDrvMinReqRaw, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_rConvTra_VSCtl_rConvTra (P2VAR(DT_VSCtl_rConvTra, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_aVehDVSRegReq_VSCtl_aVehDVSRegReq (P2VAR(DT_VSCtl_aVehDVSRegReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqCkEfcMax_VSCtl_tqCkEfcMax (P2VAR(DT_VSCtl_tqCkEfcMax, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_stCtl_tqWhlMin_VSCtl_stCtl_tqWhlMin (P2VAR(DT_VSCtl_stCtl_tqWhlMin, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_AccP_rAccP_AccP_rAccP (P2VAR(DT_AccP_rAccP, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqCkEfcDrvMaxReq_VSCtl_tqCkEfcDrvMaxReq (P2VAR(DT_VSCtl_tqCkEfcDrvMaxReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_Ext_nFrntWhl_Ext_nFrntWhl (P2VAR(DT_Ext_nFrntWhl, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_CoPt_nPrimShaftTar_CoPt_nPrimShaftTar (P2VAR(DT_CoPt_nPrimShaftTar, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlMaxReq_VSCtl_tqWhlMaxReq (P2VAR(DT_VSCtl_tqWhlMaxReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqCkEfcPreCoVSCtlReq_VSCtl_tqCkEfcPreCoVSCtlReq (P2VAR(DT_VSCtl_tqCkEfcPreCoVSCtlReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_Ext_stCtlCmdPTTqPotCf_Ext_stCtlCmdPTTqPotCf (P2VAR(DT_Ext_stCtlCmdPTTqPotCf, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlMinReq_VSCtl_tqWhlMinReq (P2VAR(DT_VSCtl_tqWhlMinReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_Ext_stTraTypCf_Ext_stTraTypCf (P2VAR(DT_Ext_stTraTypCf, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqCkEfcDrvMinReq_VSCtl_tqCkEfcDrvMinReq (P2VAR(DT_VSCtl_tqCkEfcDrvMinReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqCkEfcMinNotCtla_VSCtl_tqCkEfcMinNotCtla (P2VAR(DT_VSCtl_tqCkEfcMinNotCtla, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_bLgtCtlDyn_VSCtl_bLgtCtlDyn (P2VAR(DT_VSCtl_bLgtCtlDyn, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTPreCoVSCMinReq_VSCtl_tqWhlPTPreCoVSCMinReq (P2VAR(DT_VSCtl_tqWhlPTPreCoVSCMinReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_nFrntWhlFil_VSCtl_nFrntWhlFil (P2VAR(DT_VSCtl_nFrntWhlFil, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTPreCoVSCtlReq_VSCtl_tqWhlPTPreCoVSCtlReq (P2VAR(DT_VSCtl_tqWhlPTPreCoVSCtlReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_bAuthAntTqWhlMin_VSCtl_bAuthAntTqWhlMin (P2VAR(DT_VSCtl_bAuthAntTqWhlMin, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_spdVeh_VSCtl_spdVeh (P2VAR(DT_VSCtl_spdVeh, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqCkEfcPreCoVSCMinReq_VSCtl_tqCkEfcPreCoVSCMinReq (P2VAR(DT_VSCtl_tqCkEfcPreCoVSCMinReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tiCfmSdwnTqMinReq_VSCtl_tiCfmSdwnTqMinReq (P2VAR(DT_VSCtl_tiCfmSdwnTqMinReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_bFastDeacVSLimReq_VSCtl_bFastDeacVSLimReq (P2VAR(DT_VSCtl_bFastDeacVSLimReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_bAuthAntTqWhlMax_VSCtl_bAuthAntTqWhlMax (P2VAR(DT_VSCtl_bAuthAntTqWhlMax, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTPotRawMin_VSCtl_tqWhlPTPotRawMin (P2VAR(DT_VSCtl_tqWhlPTPotRawMin, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_stCtl_aVehVSReg_VSCtl_stCtl_aVehVSReg (P2VAR(DT_VSCtl_stCtl_aVehVSReg, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_stCtl_tqWhlPotMax_VSCtl_stCtl_tqWhlPotMax (P2VAR(DT_VSCtl_stCtl_tqWhlPotMax, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_nEngFil_VSCtl_nEngFil (P2VAR(DT_VSCtl_nEngFil, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_Tra_stGearCtl_Tra_stGearCtl (P2VAR(DT_Tra_stGearCtl, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tiCfmSdwnTqMaxReq_VSCtl_tiCfmSdwnTqMaxReq (P2VAR(DT_VSCtl_tiCfmSdwnTqMaxReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTMinNotCtla_VSCtl_tqWhlPTMinNotCtla (P2VAR(DT_VSCtl_tqWhlPTMinNotCtla, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_stCtl_aVehVSLim_VSCtl_stCtl_aVehVSLim (P2VAR(DT_VSCtl_stCtl_aVehVSLim, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_bTqWhlMinSat_VSCtl_bTqWhlMinSat (P2VAR(DT_VSCtl_bTqWhlMinSat, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tiCfmSupTqMinReq_VSCtl_tiCfmSupTqMinReq (P2VAR(DT_VSCtl_tiCfmSupTqMinReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_stCtl_tqWhlMax_VSCtl_stCtl_tqWhlMax (P2VAR(DT_VSCtl_stCtl_tqWhlMax, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqLossTra_VSCtl_tqLossTra (P2VAR(DT_VSCtl_tqLossTra, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_spdVehErrVSLim_VSCtl_spdVehErrVSLim (P2VAR(DT_VSCtl_spdVehErrVSLim, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_stCtl_aVehDVSReg_VSCtl_stCtl_aVehDVSReg (P2VAR(DT_VSCtl_stCtl_aVehDVSReg, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_bAvlTqWhlPT_no3_VSCtl_bAvlTqWhlPT_no3 (P2VAR(DT_VSCtl_bAvlTqWhlPT_no3, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_stCtl_tqWhlPot_VSCtl_stCtl_tqWhlPot (P2VAR(DT_VSCtl_stCtl_tqWhlPot, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPotMaxReq_VSCtl_tqWhlPotMaxReq (P2VAR(DT_VSCtl_tqWhlPotMaxReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_CoPt_noTarGearCordIt_CoPt_noTarGearCordIt (P2VAR(DT_CoPt_noTarGearCordIt, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tiCfmSupTqMaxReq_VSCtl_tiCfmSupTqMaxReq (P2VAR(DT_VSCtl_tiCfmSupTqMaxReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPotReq_VSCtl_tqWhlPotReq (P2VAR(DT_VSCtl_tqWhlPotReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTDrvMinReq_VSCtl_tqWhlPTDrvMinReq (P2VAR(DT_VSCtl_tqWhlPTDrvMinReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTMaxNotCtla_VSCtl_tqWhlPTMaxNotCtla (P2VAR(DT_VSCtl_tqWhlPTMaxNotCtla, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTDrvMaxReq_VSCtl_tqWhlPTDrvMaxReq (P2VAR(DT_VSCtl_tqWhlPTDrvMaxReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPTMax_VSCtl_tqWhlPTMax (P2VAR(DT_VSCtl_tqWhlPTMax, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlPotMinReq_VSCtl_tqWhlPotMinReq (P2VAR(DT_VSCtl_tqWhlPotMinReq, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_spdVehErrVSReg_VSCtl_spdVehErrVSReg (P2VAR(DT_VSCtl_spdVehErrVSReg, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_stCtl_aVehVSMax_VSCtl_stCtl_aVehVSMax (P2VAR(DT_VSCtl_stCtl_aVehVSMax, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqCkEfcMaxNotCtla_VSCtl_tqCkEfcMaxNotCtla (P2VAR(DT_VSCtl_tqCkEfcMaxNotCtla, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_stCtl_tqWhlPotMin_VSCtl_stCtl_tqWhlPotMin (P2VAR(DT_VSCtl_stCtl_tqWhlPotMin, AUTOMATIC, RTE_APPL_DATA) data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_VSCtl_tqWhlMinSat_VSCtl_tqWhlMinSat (P2VAR(DT_VSCtl_tqWhlMinSat, AUTOMATIC, RTE_APPL_DATA) data);

#endif
#if (!defined(RTE_RUNNABLEAPI_RE_VSSp_003_TEV))
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_bCtlEfc_tqCkEfcMin_VSCtl_bCtlEfc_tqCkEfcMin (DT_VSCtl_bCtlEfc_tqCkEfcMin data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_rAccPEngMax_VSCtl_rAccPEngMax (DT_VSCtl_rAccPEngMax data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_stTqWhlPTCutOffReq_VSCtl_stTqWhlPTCutOffReq (DT_VSCtl_stTqWhlPTCutOffReq data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_bCtlEfc_tqWhlPTMax_VSCtl_bCtlEfc_tqWhlPTMax (DT_VSCtl_bCtlEfc_tqWhlPTMax data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_tqCkEfcMinReq_VSCtl_tqCkEfcMinReq (DT_VSCtl_tqCkEfcMinReq data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_bCtlEfc_tqCkEfcMax_VSCtl_bCtlEfc_tqCkEfcMax (DT_VSCtl_bCtlEfc_tqCkEfcMax data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_bCtlEfc_tqWhlPTMin_VSCtl_bCtlEfc_tqWhlPTMin (DT_VSCtl_bCtlEfc_tqWhlPTMin data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_rAccPEngMin_VSCtl_rAccPEngMin (DT_VSCtl_rAccPEngMin data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_tqCkEfcMaxReq_VSCtl_tqCkEfcMaxReq (DT_VSCtl_tqCkEfcMaxReq data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_stCtl_noGear_VSCtl_stCtl_noGear (DT_VSCtl_stCtl_noGear data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_rAccPTraMin_VSCtl_rAccPTraMin (DT_VSCtl_rAccPTraMin data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_bInhRecup_VSCtl_bInhRecup (DT_VSCtl_bInhRecup data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_rAccPTraMax_VSCtl_rAccPTraMax (DT_VSCtl_rAccPTraMax data);

#endif
#if (!defined(RTE_RUNNABLEAPI_RE_VSSp_004_MSE))  || (!defined(RTE_RUNNABLEAPI_RE_VSSp_001_MSE))
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Read_VSSP_R_Ext_bCtlCmdPTTqCf_Ext_bCtlCmdPTTqCf (P2VAR(DT_Ext_bCtlCmdPTTqCf, AUTOMATIC, RTE_APPL_DATA) data);

#endif
#if (!defined(RTE_RUNNABLEAPI_RE_VSSp_002_TEV))  || (!defined(RTE_RUNNABLEAPI_RE_VSSp_004_MSE)) || (!defined(RTE_RUNNABLEAPI_RE_VSSp_001_MSE))
#endif
#if (!defined(RTE_RUNNABLEAPI_RE_VSSp_002_TEV))
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_stTqPTMaxCtl_VSCtl_stTqPTMaxCtl (DT_VSCtl_stTqPTMaxCtl data);

extern FUNC(Std_ReturnType, RTE_CODE) Rte_Write_VSSP_P_VSCtl_stTqPTMinCtl_VSCtl_stTqPTMinCtl (DT_VSCtl_stTqPTMinCtl data);

#endif
#if (!defined(RTE_RUNNABLEAPI_RE_VSSp_002_TEV))  || (!defined(RTE_RUNNABLEAPI_RE_VSSp_003_TEV)) || (!defined(RTE_RUNNABLEAPI_RE_VSSp_001_MSE))
#endif
#if (!defined(RTE_RUNNABLEAPI_RE_VSSp_002_TEV))  || (!defined(RTE_RUNNABLEAPI_RE_VSSp_003_TEV)) || (!defined(RTE_RUNNABLEAPI_RE_VSSp_004_MSE))
#endif

#define RTE_STOP_SEC_APPLICATION_CORE1_CODE
#include "MemMap.h"

/*--------------[declaration of API functions provided by other Appl]--------*/

#define RTE_START_SEC_APPLICATION_CORE1_APPL_CODE
#include "MemMap.h"

#if (!defined RTE_CORE) /* if included by software component */

extern FUNC(void, RTE_APPL_CODE) RE_FRM_bDeacVSCtlGearCtl_GetFunctionPermission (P2VAR(DT_Permission, AUTOMATIC, RTE_APPL_DATA) Permission);
extern FUNC(Std_ReturnType, RTE_APPL_CODE) FRunTime_GetTimer_1ms_U32 (P2VAR(UInt32, AUTOMATIC, RTE_APPL_DATA) CurrentTime1msPtr);

#endif /* (!defined RTE_CORE) */

#define RTE_STOP_SEC_APPLICATION_CORE1_APPL_CODE
#include "MemMap.h"

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*------------------[instance handle declaration]----------------------------*/
#define RTE_START_SEC_APPLICATION_CORE1_CONST_UNSPECIFIED
#include "MemMap.h"

extern CONSTP2CONST(Rte_CDS_VSSP, RTE_CONST, RTE_CONST) Rte_Inst_VSSP;

#define RTE_STOP_SEC_APPLICATION_CORE1_CONST_UNSPECIFIED
#include "MemMap.h"

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(RTE_VSSP_H) */
/*==================[end of file]============================================*/

