/**************************************************************************************************\
 *** 
 ***                            P. C. A.
 *** 
 ***                     Peugeot Citroen Automobile
 *** 
 ***         This file is the property of PCA. All rights are reserved
 ***         by PCA and this file must not be copied or disclosed
 ***        (in whole or in part) without prior written consent of PCA.
 *** 
 *** *******************************************************************************
 *** 
 ***  %name: TraBVx_016_lut.h %
 *** 
 ***  %version: 13.0 %
 *** 
 ***  %date_modified: Wed Jan  4 15:29:41 2012 %
 *** 
 *** 
 ***  %derived_by: e360852 %
 ***  %release: TqStruct/13.0 %
 ***  %full_filespec: TraBVx_016_lut.h-13.0:incl:1 %
 *** 
 *** *******************************************************************************
 *** 
 *** Simulink model       : RE_016
 *** TargetLink subsystem : RE_016/F00_Regulation_Regime_BV
 *** Codefile             : trabvx_016_lut.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2012-01-04 15:27:20
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : disabled
 *** Share fcns between TL subsystems    : enabled
 *** Generate 64bit functions            : enabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : enabled
 *** Style definition file               : C:\dSPACE\Matlab\Tl\config\codegen\cconfig.xml
 *** Root style sheet                    : C:\dSPACE\Matlab\Tl\XML\CodeGen\Stylesheets\TL_CSourceCod
 ***                                       eSS.xsl
 *** Enable Multirate codegeneration     : disabled
 *** Add model checksum                  : disabled
 ***
 *** TargetLink version      : 3.0.1 from 26-May-2009
 *** Code generator version  : Build Id 3.0.1.7 from 2009-May-06 15:28:18
 *** Copyright (c) 2006 dSPACE GmbH
\**************************************************************************************************/

#ifndef _TRABVX_016_LUT_H_
#define _TRABVX_016_LUT_H_

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "tl_basetypes.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   UserGlobalLookup1D_016: Derived TL_CG default function class.
\******************************************************************************/
extern UInt16 TraBVx_016_Tab2DIntp2I1T4097(const UInt16 * z_table, UInt8 N, UInt8 irx, UInt8
    fractionX, UInt16 iry, UInt8 fractionY);
extern SInt16 TraBVx_016_Tab2DIntp2I1T4100(const SInt16 * z_table, UInt8 N, UInt8 irx, UInt8
    fractionX, UInt16 iry, UInt8 fractionY);
extern SInt16 TraBVx_016_Tab2DIntp2I1T4164(const SInt16 * z_table, UInt8 N, UInt16 irx, UInt8
    fractionX, UInt16 iry, UInt8 fractionY);

/******************************************************************************\
   UserGlobalLookup1D_016: Derived TL_CG default function class.
\******************************************************************************/
extern Void TraBVx_016_TabIdxS50T3(const SInt8 * x_table, UInt8 N, SInt8 x, UInt8 * irx, UInt8 *
    fraction);
extern Void TraBVx_016_TabIdxS50T73(const UInt16 * x_table, UInt16 N, UInt16 x, UInt16 * irx, UInt8
    * fraction);
extern Void TraBVx_016_TabIdxS50T76(const SInt16 * x_table, UInt16 N, SInt16 x, UInt16 * irx, UInt8
    * fraction);


#endif/*_TRABVX_016_LUT_H_ */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
