/******************************************************************************/
/* !Layer           : MCAL                                                    */
/* !Component       : ISR                                                     */
/* !Description     : ISR Management                                          */
/*                                                                            */
/* !File            : Isr_Cfg.h                                               */
/* !Description     : ISR declaration                                         */
/*                                                                            */
/* !Reference       :                                                         */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT VALEO all rights reserved                                        */
/******************************************************************************/
/* Dimension Informations
 * %PCMS_HEADER_SUBSTITUTION_START:%
 * The PID has this format: <Product ID>:<Item ID>.<Variant>-<Item Type>;<Revision>
 * %PID: P2017_BSW:0A192596.A-SRC;2 %
 * %PCMS_HEADER_SUBSTITUTION_END:%
 ******************************************************************************/

#ifndef ISR_CFG_H
#define ISR_CFG_H

#include "Std_Types.h"
#include "IfxSrc.h"
#include "IfxInt_regDef.h"
#include "IsrMapping.h"


#define GEN_BSW_START_SEC_CODE
#include "GEN_BSW_MemMap.h"

void DMADRV_vidInit(void);
void DMADRV_vidDeInit(void);

#define GEN_BSW_STOP_SEC_CODE
#include "GEN_BSW_MemMap.h"



/******************************************************************************/
/* !FuncName    : INT                                                         */
/* !Description : Macro to define an ISR                                      */
/*                                                                            */
/* !LastAuthor  : TBOU                                                        */
/******************************************************************************/
#define INT(itFunc) \
   m_INT(itFunc)

   /* internal macros */
   #define m_INT(itFunc) \
      m__INT(itFunc,ISR_CATEGORY_##itFunc)

   #define m__INT(itFunc,isrCategory) \
      m___INT(itFunc,isrCategory)

   #define m___INT(itFunc,isrCategory) \
      m_ISR##isrCategory(itFunc)
  
/* ISR1 */
   #define m_ISR1(itFunc) \
      m__ISR1(Isr##itFunc, ISR_UNDEF_##itFunc)

   #define m__ISR1(userIsr, isr) \
      static void userIsr(void); \
      isr \
      { \
         userIsr(); \
         OsDrvIsrEndHook(); \
      } \
      static void userIsr(void)
      

/* ISR2 */
   #define m_ISR2(itFunc) \
      ISR(Os##itFunc)


      
/******************************************************************************/
/* !FuncName    : OsDrvIsrEndHook                                             */
/* !Description : Macro called at the end of all isr to enable fast interrupts*/
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define OsDrvIsrEndHook()  __asm__("rslcx;nop;nop;nop;rfe;nop":::"memory")







#define DMA_ISR_QSPI0RX_USED  SRC_DMA_DMA0_CH0_USED
#define DMA_ISR_QSPI0TX_USED  SRC_DMA_DMA0_CH1_USED
#define DMA_ISR_QSPI2RX_USED  SRC_DMA_DMA0_CH4_USED
#define DMA_ISR_QSPI2TX_USED  SRC_DMA_DMA0_CH5_USED
#define DMA_ISR_QSPI4RX_USED  SRC_DMA_DMA0_CH8_USED
#define DMA_ISR_QSPI4TX_USED  SRC_DMA_DMA0_CH9_USED
#define DMA_ISR_MSC0RX_USED   SRC_DMA_DMA0_CH10_USED


#define INTBSL_u8KRN_SCHEDULER_MANAGE_IT_SRC_REG       SRC_STM_STM0_SR0

#define INTBSL_u8TSKSRV_ACTIVATION_MANAGER_IT_SRC_REG  SRC_GPSR_GPSR1_SR0


/* SRN registers */
#define INTBSL_u8SRC_AGBT_AGBT0_REG             SRC_AGBT_AGBT0_SR
#define INTBSL_u8SRC_ASCLIN_ASCLIN0_ERR_REG     SRC_ASCLIN_ASCLIN0_ERR
#define INTBSL_u8SRC_ASCLIN_ASCLIN0_RX_REG      SRC_ASCLIN_ASCLIN0_RX
#define INTBSL_u8SRC_ASCLIN_ASCLIN0_TX_REG      SRC_ASCLIN_ASCLIN0_TX
#define INTBSL_u8SRC_ASCLIN_ASCLIN1_ERR_REG     SRC_ASCLIN_ASCLIN1_ERR
#define INTBSL_u8SRC_ASCLIN_ASCLIN1_RX_REG      SRC_ASCLIN_ASCLIN1_RX
#define INTBSL_u8SRC_ASCLIN_ASCLIN1_TX_REG      SRC_ASCLIN_ASCLIN1_TX
#define INTBSL_u8SRC_ASCLIN_ASCLIN2_ERR_REG     SRC_ASCLIN_ASCLIN2_ERR
#define INTBSL_u8SRC_ASCLIN_ASCLIN2_RX_REG      SRC_ASCLIN_ASCLIN2_RX
#define INTBSL_u8SRC_ASCLIN_ASCLIN2_TX_REG      SRC_ASCLIN_ASCLIN2_TX
#define INTBSL_u8SRC_ASCLIN_ASCLIN3_ERR_REG     SRC_ASCLIN_ASCLIN3_ERR
#define INTBSL_u8SRC_ASCLIN_ASCLIN3_RX_REG      SRC_ASCLIN_ASCLIN3_RX
#define INTBSL_u8SRC_ASCLIN_ASCLIN3_TX_REG      SRC_ASCLIN_ASCLIN3_TX
#define INTBSL_u8SRC_BCU_SPB_SBSRC_REG          SRC_BCU_SPB_SBSRC
#define INTBSL_u8SRC_CAN_CAN0_INT0_REG          SRC_CAN_CAN0_INT0
#define INTBSL_u8SRC_CAN_CAN0_INT1_REG          SRC_CAN_CAN0_INT1
#define INTBSL_u8SRC_CAN_CAN0_INT10_REG         SRC_CAN_CAN0_INT10
#define INTBSL_u8SRC_CAN_CAN0_INT11_REG         SRC_CAN_CAN0_INT11
#define INTBSL_u8SRC_CAN_CAN0_INT12_REG         SRC_CAN_CAN0_INT12
#define INTBSL_u8SRC_CAN_CAN0_INT13_REG         SRC_CAN_CAN0_INT13
#define INTBSL_u8SRC_CAN_CAN0_INT14_REG         SRC_CAN_CAN0_INT14
#define INTBSL_u8SRC_CAN_CAN0_INT15_REG         SRC_CAN_CAN0_INT15
#define INTBSL_u8SRC_CAN_CAN0_INT2_REG          SRC_CAN_CAN0_INT2
#define INTBSL_u8SRC_CAN_CAN0_INT3_REG          SRC_CAN_CAN0_INT3
#define INTBSL_u8SRC_CAN_CAN0_INT4_REG          SRC_CAN_CAN0_INT4
#define INTBSL_u8SRC_CAN_CAN0_INT5_REG          SRC_CAN_CAN0_INT5
#define INTBSL_u8SRC_CAN_CAN0_INT6_REG          SRC_CAN_CAN0_INT6
#define INTBSL_u8SRC_CAN_CAN0_INT7_REG          SRC_CAN_CAN0_INT7
#define INTBSL_u8SRC_CAN_CAN0_INT8_REG          SRC_CAN_CAN0_INT8
#define INTBSL_u8SRC_CAN_CAN0_INT9_REG          SRC_CAN_CAN0_INT9
#define INTBSL_u8SRC_CANR_CANR0_RINT1_REG       SRC_CANR_CANR0_RINT0
#define INTBSL_u8SRC_CANR_CANR1_RINT1_REG       SRC_CANR_CANR0_RINT1
#define INTBSL_u8SRC_CANR_CANR2_RINT1_REG       SRC_CANR_CANR0_RINT2
#define INTBSL_u8SRC_CANR_CANR3_RINT1_REG       SRC_CANR_CANR0_RINT3
#define INTBSL_u8SRC_CANR_CANR4_RINT1_REG       SRC_CANR_CANR0_RINT4
#define INTBSL_u8SRC_CANR_CANR5_RINT1_REG       SRC_CANR_CANR0_RINT5
#define INTBSL_u8SRC_CANR_CANR6_RINT1_REG       SRC_CANR_CANR0_RINT6
#define INTBSL_u8SRC_CANR_CANR7_RINT1_REG       SRC_CANR_CANR0_RINT7
#define INTBSL_u8SRC_CCU6_CCU60_SR0_REG         SRC_CCU6_CCU60_SR0
#define INTBSL_u8SRC_CCU6_CCU60_SR1_REG         SRC_CCU6_CCU60_SR1
#define INTBSL_u8SRC_CCU6_CCU60_SR2_REG         SRC_CCU6_CCU60_SR2
#define INTBSL_u8SRC_CCU6_CCU60_SR3_REG         SRC_CCU6_CCU60_SR3
#define INTBSL_u8SRC_CCU6_CCU61_SR0_REG         SRC_CCU6_CCU61_SR0
#define INTBSL_u8SRC_CCU6_CCU61_SR1_REG         SRC_CCU6_CCU61_SR1
#define INTBSL_u8SRC_CCU6_CCU61_SR2_REG         SRC_CCU6_CCU61_SR2
#define INTBSL_u8SRC_CCU6_CCU61_SR3_REG         SRC_CCU6_CCU61_SR3
#define INTBSL_u8SRC_CERBERUS_CERBERUS_SR0_REG  SRC_CERBERUS_CERBERUS_SR0
#define INTBSL_u8SRC_CERBERUS_CERBERUS_SR1_REG  SRC_CERBERUS_CERBERUS_SR1
#define INTBSL_u8SRC_CIF_CIF0_ISP_REG           SRC_CIF_CIF0_ISP
#define INTBSL_u8SRC_CIF_CIF0_MI_REG            SRC_CIF_CIF0_MI
#define INTBSL_u8SRC_CIF_CIF0_MIEP_REG          SRC_CIF_CIF0_MIEP
#define INTBSL_u8SRC_CIF_CIF0_MJPEG_REG         SRC_CIF_CIF0_MJPEG
#define INTBSL_u8SRC_CPU_CPU0_SBSRC_REG         SRC_CPU_CPU0_SBSRC
#define INTBSL_u8SRC_CPU_CPU1_SBSRC_REG         SRC_CPU_CPU1_SBSRC
#define INTBSL_u8SRC_CPU_CPU2_SBSRC_REG         SRC_CPU_CPU2_SBSRC
#define INTBSL_u8SRC_DAM_DAM0_SR0_REG           SRC_DAM_DAM0_SR0
#define INTBSL_u8SRC_DAM_DAM0_SR1_REG           SRC_DAM_DAM0_SR1
#define INTBSL_u8SRC_DAM_DAM0_SR2_REG           SRC_DAM_DAM0_SR2
#define INTBSL_u8SRC_DAM_DAM0_SR3_REG           SRC_DAM_DAM0_SR3
#define INTBSL_u8SRC_DAM_DAM0_SR4_REG           SRC_DAM_DAM0_SR4
#define INTBSL_u8SRC_DAM_DAM0_SR5_REG           SRC_DAM_DAM0_SR5
#define INTBSL_u8SRC_DMA_DMA0_CH0_REG           SRC_DMA_DMA0_CH0
#define INTBSL_u8SRC_DMA_DMA0_CH1_REG           SRC_DMA_DMA0_CH1
#define INTBSL_u8SRC_DMA_DMA0_CH2_REG           SRC_DMA_DMA0_CH2
#define INTBSL_u8SRC_DMA_DMA0_CH3_REG           SRC_DMA_DMA0_CH3
#define INTBSL_u8SRC_DMA_DMA0_CH4_REG           SRC_DMA_DMA0_CH4
#define INTBSL_u8SRC_DMA_DMA0_CH5_REG           SRC_DMA_DMA0_CH5
#define INTBSL_u8SRC_DMA_DMA0_CH6_REG           SRC_DMA_DMA0_CH6
#define INTBSL_u8SRC_DMA_DMA0_CH7_REG           SRC_DMA_DMA0_CH7
#define INTBSL_u8SRC_DMA_DMA0_CH8_REG           SRC_DMA_DMA0_CH8
#define INTBSL_u8SRC_DMA_DMA0_CH9_REG           SRC_DMA_DMA0_CH9
#define INTBSL_u8SRC_DMA_DMA0_CH10_REG          SRC_DMA_DMA0_CH10
#define INTBSL_u8SRC_DMA_DMA0_CH11_REG          SRC_DMA_DMA0_CH11
#define INTBSL_u8SRC_DMA_DMA0_CH12_REG          SRC_DMA_DMA0_CH12
#define INTBSL_u8SRC_DMA_DMA0_CH13_REG          SRC_DMA_DMA0_CH13
#define INTBSL_u8SRC_DMA_DMA0_CH14_REG          SRC_DMA_DMA0_CH14
#define INTBSL_u8SRC_DMA_DMA0_CH15_REG          SRC_DMA_DMA0_CH15
#define INTBSL_u8SRC_DMA_DMA0_CH16_REG          SRC_DMA_DMA0_CH16
#define INTBSL_u8SRC_DMA_DMA0_CH17_REG          SRC_DMA_DMA0_CH17
#define INTBSL_u8SRC_DMA_DMA0_CH18_REG          SRC_DMA_DMA0_CH18
#define INTBSL_u8SRC_DMA_DMA0_CH19_REG          SRC_DMA_DMA0_CH19
#define INTBSL_u8SRC_DMA_DMA0_CH20_REG          SRC_DMA_DMA0_CH20
#define INTBSL_u8SRC_DMA_DMA0_CH21_REG          SRC_DMA_DMA0_CH21
#define INTBSL_u8SRC_DMA_DMA0_CH22_REG          SRC_DMA_DMA0_CH22
#define INTBSL_u8SRC_DMA_DMA0_CH23_REG          SRC_DMA_DMA0_CH23
#define INTBSL_u8SRC_DMA_DMA0_CH24_REG          SRC_DMA_DMA0_CH24
#define INTBSL_u8SRC_DMA_DMA0_CH25_REG          SRC_DMA_DMA0_CH25
#define INTBSL_u8SRC_DMA_DMA0_CH26_REG          SRC_DMA_DMA0_CH26
#define INTBSL_u8SRC_DMA_DMA0_CH27_REG          SRC_DMA_DMA0_CH27
#define INTBSL_u8SRC_DMA_DMA0_CH28_REG          SRC_DMA_DMA0_CH28
#define INTBSL_u8SRC_DMA_DMA0_CH29_REG          SRC_DMA_DMA0_CH29
#define INTBSL_u8SRC_DMA_DMA0_CH30_REG          SRC_DMA_DMA0_CH30
#define INTBSL_u8SRC_DMA_DMA0_CH31_REG          SRC_DMA_DMA0_CH31
#define INTBSL_u8SRC_DMA_DMA0_CH32_REG          SRC_DMA_DMA0_CH32
#define INTBSL_u8SRC_DMA_DMA0_CH33_REG          SRC_DMA_DMA0_CH33
#define INTBSL_u8SRC_DMA_DMA0_CH34_REG          SRC_DMA_DMA0_CH34
#define INTBSL_u8SRC_DMA_DMA0_CH35_REG          SRC_DMA_DMA0_CH35
#define INTBSL_u8SRC_DMA_DMA0_CH36_REG          SRC_DMA_DMA0_CH36
#define INTBSL_u8SRC_DMA_DMA0_CH37_REG          SRC_DMA_DMA0_CH37
#define INTBSL_u8SRC_DMA_DMA0_CH38_REG          SRC_DMA_DMA0_CH38
#define INTBSL_u8SRC_DMA_DMA0_CH39_REG          SRC_DMA_DMA0_CH39
#define INTBSL_u8SRC_DMA_DMA0_CH40_REG          SRC_DMA_DMA0_CH40
#define INTBSL_u8SRC_DMA_DMA0_CH41_REG          SRC_DMA_DMA0_CH41
#define INTBSL_u8SRC_DMA_DMA0_CH42_REG          SRC_DMA_DMA0_CH42
#define INTBSL_u8SRC_DMA_DMA0_CH43_REG          SRC_DMA_DMA0_CH43
#define INTBSL_u8SRC_DMA_DMA0_CH44_REG          SRC_DMA_DMA0_CH44
#define INTBSL_u8SRC_DMA_DMA0_CH45_REG          SRC_DMA_DMA0_CH45
#define INTBSL_u8SRC_DMA_DMA0_CH46_REG          SRC_DMA_DMA0_CH46
#define INTBSL_u8SRC_DMA_DMA0_CH47_REG          SRC_DMA_DMA0_CH47
#define INTBSL_u8SRC_DMA_DMA0_CH48_REG          SRC_DMA_DMA0_CH48
#define INTBSL_u8SRC_DMA_DMA0_CH49_REG          SRC_DMA_DMA0_CH49
#define INTBSL_u8SRC_DMA_DMA0_CH50_REG          SRC_DMA_DMA0_CH50
#define INTBSL_u8SRC_DMA_DMA0_CH51_REG          SRC_DMA_DMA0_CH51
#define INTBSL_u8SRC_DMA_DMA0_CH52_REG          SRC_DMA_DMA0_CH52
#define INTBSL_u8SRC_DMA_DMA0_CH53_REG          SRC_DMA_DMA0_CH53
#define INTBSL_u8SRC_DMA_DMA0_CH54_REG          SRC_DMA_DMA0_CH54
#define INTBSL_u8SRC_DMA_DMA0_CH55_REG          SRC_DMA_DMA0_CH55
#define INTBSL_u8SRC_DMA_DMA0_CH56_REG          SRC_DMA_DMA0_CH56
#define INTBSL_u8SRC_DMA_DMA0_CH57_REG          SRC_DMA_DMA0_CH57
#define INTBSL_u8SRC_DMA_DMA0_CH58_REG          SRC_DMA_DMA0_CH58
#define INTBSL_u8SRC_DMA_DMA0_CH59_REG          SRC_DMA_DMA0_CH59
#define INTBSL_u8SRC_DMA_DMA0_CH60_REG          SRC_DMA_DMA0_CH60
#define INTBSL_u8SRC_DMA_DMA0_CH61_REG          SRC_DMA_DMA0_CH61
#define INTBSL_u8SRC_DMA_DMA0_CH62_REG          SRC_DMA_DMA0_CH62
#define INTBSL_u8SRC_DMA_DMA0_CH63_REG          SRC_DMA_DMA0_CH63
#define INTBSL_u8SRC_DMA_DMA0_CH64_REG          SRC_DMA_DMA0_CH64
#define INTBSL_u8SRC_DMA_DMA0_CH65_REG          SRC_DMA_DMA0_CH65
#define INTBSL_u8SRC_DMA_DMA0_CH66_REG          SRC_DMA_DMA0_CH66
#define INTBSL_u8SRC_DMA_DMA0_CH67_REG          SRC_DMA_DMA0_CH67
#define INTBSL_u8SRC_DMA_DMA0_CH68_REG          SRC_DMA_DMA0_CH68
#define INTBSL_u8SRC_DMA_DMA0_CH69_REG          SRC_DMA_DMA0_CH69
#define INTBSL_u8SRC_DMA_DMA0_CH70_REG          SRC_DMA_DMA0_CH70
#define INTBSL_u8SRC_DMA_DMA0_CH71_REG          SRC_DMA_DMA0_CH71
#define INTBSL_u8SRC_DMA_DMA0_CH72_REG          SRC_DMA_DMA0_CH72
#define INTBSL_u8SRC_DMA_DMA0_CH73_REG          SRC_DMA_DMA0_CH73
#define INTBSL_u8SRC_DMA_DMA0_CH74_REG          SRC_DMA_DMA0_CH74
#define INTBSL_u8SRC_DMA_DMA0_CH75_REG          SRC_DMA_DMA0_CH75
#define INTBSL_u8SRC_DMA_DMA0_CH76_REG          SRC_DMA_DMA0_CH76
#define INTBSL_u8SRC_DMA_DMA0_CH77_REG          SRC_DMA_DMA0_CH77
#define INTBSL_u8SRC_DMA_DMA0_CH78_REG          SRC_DMA_DMA0_CH78
#define INTBSL_u8SRC_DMA_DMA0_CH79_REG          SRC_DMA_DMA0_CH79
#define INTBSL_u8SRC_DMA_DMA0_CH80_REG          SRC_DMA_DMA0_CH80
#define INTBSL_u8SRC_DMA_DMA0_CH81_REG          SRC_DMA_DMA0_CH81
#define INTBSL_u8SRC_DMA_DMA0_CH82_REG          SRC_DMA_DMA0_CH82
#define INTBSL_u8SRC_DMA_DMA0_CH83_REG          SRC_DMA_DMA0_CH83
#define INTBSL_u8SRC_DMA_DMA0_CH84_REG          SRC_DMA_DMA0_CH84
#define INTBSL_u8SRC_DMA_DMA0_CH85_REG          SRC_DMA_DMA0_CH85
#define INTBSL_u8SRC_DMA_DMA0_CH86_REG          SRC_DMA_DMA0_CH86
#define INTBSL_u8SRC_DMA_DMA0_CH87_REG          SRC_DMA_DMA0_CH87
#define INTBSL_u8SRC_DMA_DMA0_CH88_REG          SRC_DMA_DMA0_CH88
#define INTBSL_u8SRC_DMA_DMA0_CH89_REG          SRC_DMA_DMA0_CH89
#define INTBSL_u8SRC_DMA_DMA0_CH90_REG          SRC_DMA_DMA0_CH90
#define INTBSL_u8SRC_DMA_DMA0_CH91_REG          SRC_DMA_DMA0_CH91
#define INTBSL_u8SRC_DMA_DMA0_CH92_REG          SRC_DMA_DMA0_CH92
#define INTBSL_u8SRC_DMA_DMA0_CH93_REG          SRC_DMA_DMA0_CH93
#define INTBSL_u8SRC_DMA_DMA0_CH94_REG          SRC_DMA_DMA0_CH94
#define INTBSL_u8SRC_DMA_DMA0_CH95_REG          SRC_DMA_DMA0_CH95
#define INTBSL_u8SRC_DMA_DMA0_CH96_REG          SRC_DMA_DMA0_CH96
#define INTBSL_u8SRC_DMA_DMA0_CH97_REG          SRC_DMA_DMA0_CH97
#define INTBSL_u8SRC_DMA_DMA0_CH98_REG          SRC_DMA_DMA0_CH98
#define INTBSL_u8SRC_DMA_DMA0_CH99_REG          SRC_DMA_DMA0_CH99
#define INTBSL_u8SRC_DMA_DMA0_CH100_REG         SRC_DMA_DMA0_CH100
#define INTBSL_u8SRC_DMA_DMA0_CH101_REG         SRC_DMA_DMA0_CH101
#define INTBSL_u8SRC_DMA_DMA0_CH102_REG         SRC_DMA_DMA0_CH102
#define INTBSL_u8SRC_DMA_DMA0_CH103_REG         SRC_DMA_DMA0_CH103
#define INTBSL_u8SRC_DMA_DMA0_CH104_REG         SRC_DMA_DMA0_CH104
#define INTBSL_u8SRC_DMA_DMA0_CH105_REG         SRC_DMA_DMA0_CH105
#define INTBSL_u8SRC_DMA_DMA0_CH106_REG         SRC_DMA_DMA0_CH106
#define INTBSL_u8SRC_DMA_DMA0_CH107_REG         SRC_DMA_DMA0_CH107
#define INTBSL_u8SRC_DMA_DMA0_CH108_REG         SRC_DMA_DMA0_CH108
#define INTBSL_u8SRC_DMA_DMA0_CH109_REG         SRC_DMA_DMA0_CH109
#define INTBSL_u8SRC_DMA_DMA0_CH110_REG         SRC_DMA_DMA0_CH110
#define INTBSL_u8SRC_DMA_DMA0_CH111_REG         SRC_DMA_DMA0_CH111
#define INTBSL_u8SRC_DMA_DMA0_CH112_REG         SRC_DMA_DMA0_CH112
#define INTBSL_u8SRC_DMA_DMA0_CH113_REG         SRC_DMA_DMA0_CH113
#define INTBSL_u8SRC_DMA_DMA0_CH114_REG         SRC_DMA_DMA0_CH114
#define INTBSL_u8SRC_DMA_DMA0_CH115_REG         SRC_DMA_DMA0_CH115
#define INTBSL_u8SRC_DMA_DMA0_CH116_REG         SRC_DMA_DMA0_CH116
#define INTBSL_u8SRC_DMA_DMA0_CH117_REG         SRC_DMA_DMA0_CH117
#define INTBSL_u8SRC_DMA_DMA0_CH118_REG         SRC_DMA_DMA0_CH118
#define INTBSL_u8SRC_DMA_DMA0_CH119_REG         SRC_DMA_DMA0_CH119
#define INTBSL_u8SRC_DMA_DMA0_CH120_REG         SRC_DMA_DMA0_CH120
#define INTBSL_u8SRC_DMA_DMA0_CH121_REG         SRC_DMA_DMA0_CH121
#define INTBSL_u8SRC_DMA_DMA0_CH122_REG         SRC_DMA_DMA0_CH122
#define INTBSL_u8SRC_DMA_DMA0_CH123_REG         SRC_DMA_DMA0_CH123
#define INTBSL_u8SRC_DMA_DMA0_CH124_REG         SRC_DMA_DMA0_CH124
#define INTBSL_u8SRC_DMA_DMA0_CH125_REG         SRC_DMA_DMA0_CH125
#define INTBSL_u8SRC_DMA_DMA0_CH126_REG         SRC_DMA_DMA0_CH126
#define INTBSL_u8SRC_DMA_DMA0_CH127_REG         SRC_DMA_DMA0_CH127
#define INTBSL_u8SRC_DMA_DMA0_ERR_REG           SRC_DMA_DMA0_ERR
#define INTBSL_u8SRC_DSADC_DSADC0_SRA_REG       SRC_DSADC_DSADC0_SRA
#define INTBSL_u8SRC_DSADC_DSADC0_SRM_REG       SRC_DSADC_DSADC0_SRM
#define INTBSL_u8SRC_DSADC_DSADC1_SRA_REG       SRC_DSADC_DSADC1_SRA
#define INTBSL_u8SRC_DSADC_DSADC1_SRM_REG       SRC_DSADC_DSADC1_SRM
#define INTBSL_u8SRC_DSADC_DSADC2_SRA_REG       SRC_DSADC_DSADC2_SRA
#define INTBSL_u8SRC_DSADC_DSADC2_SRM_REG       SRC_DSADC_DSADC2_SRM
#define INTBSL_u8SRC_DSADC_DSADC3_SRA_REG       SRC_DSADC_DSADC3_SRA
#define INTBSL_u8SRC_DSADC_DSADC3_SRM_REG       SRC_DSADC_DSADC3_SRM
#define INTBSL_u8SRC_DSADC_DSADC4_SRA_REG       SRC_DSADC_DSADC4_SRA
#define INTBSL_u8SRC_DSADC_DSADC4_SRM_REG       SRC_DSADC_DSADC4_SRM
#define INTBSL_u8SRC_DSADC_DSADC5_SRA_REG       SRC_DSADC_DSADC5_SRA
#define INTBSL_u8SRC_DSADC_DSADC5_SRM_REG       SRC_DSADC_DSADC5_SRM
#define INTBSL_u8SRC_DSADC_DSADC6_SRA_REG       SRC_DSADC_DSADC6_SRA
#define INTBSL_u8SRC_DSADC_DSADC6_SRM_REG       SRC_DSADC_DSADC6_SRM
#define INTBSL_u8SRC_DSADC_DSADC7_SRA_REG       SRC_DSADC_DSADC7_SRA
#define INTBSL_u8SRC_DSADC_DSADC7_SRM_REG       SRC_DSADC_DSADC7_SRM
#define INTBSL_u8SRC_DSADC_DSADC8_SRA_REG       SRC_DSADC_DSADC8_SRA
#define INTBSL_u8SRC_DSADC_DSADC8_SRM_REG       SRC_DSADC_DSADC8_SRM
#define INTBSL_u8SRC_DSADC_DSADC9_SRA_REG       SRC_DSADC_DSADC9_SRA
#define INTBSL_u8SRC_DSADC_DSADC9_SRM_REG       SRC_DSADC_DSADC9_SRM
#define INTBSL_u8SRC_EMEM_EMEM0_SR_REG          SRC_EMEM_EMEM0_SR
#define INTBSL_u8SRC_ERAY_ERAY0_IBUSY_REG       SRC_ERAY_ERAY0_IBUSY
#define INTBSL_u8SRC_ERAY_ERAY0_INT0_REG        SRC_ERAY_ERAY0_INT0
#define INTBSL_u8SRC_ERAY_ERAY0_INT1_REG        SRC_ERAY_ERAY0_INT1
#define INTBSL_u8SRC_ERAY_ERAY0_MBSC0_REG       SRC_ERAY_ERAY0_MBSC0
#define INTBSL_u8SRC_ERAY_ERAY0_MBSC1_REG       SRC_ERAY_ERAY0_MBSC1
#define INTBSL_u8SRC_ERAY_ERAY0_NDAT0_REG       SRC_ERAY_ERAY0_NDAT0
#define INTBSL_u8SRC_ERAY_ERAY0_NDAT1_REG       SRC_ERAY_ERAY0_NDAT1
#define INTBSL_u8SRC_ERAY_ERAY0_OBUSY_REG       SRC_ERAY_ERAY0_OBUSY
#define INTBSL_u8SRC_ERAY_ERAY0_TINT0_REG       SRC_ERAY_ERAY0_TINT0
#define INTBSL_u8SRC_ERAY_ERAY0_TINT1_REG       SRC_ERAY_ERAY0_TINT1
#define INTBSL_u8SRC_ERAY_ERAY1_IBUSY_REG       SRC_ERAY_ERAY1_IBUSY
#define INTBSL_u8SRC_ERAY_ERAY1_INT0_REG        SRC_ERAY_ERAY1_INT0
#define INTBSL_u8SRC_ERAY_ERAY1_INT1_REG        SRC_ERAY_ERAY1_INT1
#define INTBSL_u8SRC_ERAY_ERAY1_MBSC0_REG       SRC_ERAY_ERAY1_MBSC0
#define INTBSL_u8SRC_ERAY_ERAY1_MBSC1_REG       SRC_ERAY_ERAY1_MBSC1
#define INTBSL_u8SRC_ERAY_ERAY1_NDAT0_REG       SRC_ERAY_ERAY1_NDAT0
#define INTBSL_u8SRC_ERAY_ERAY1_NDAT1_REG       SRC_ERAY_ERAY1_NDAT1
#define INTBSL_u8SRC_ERAY_ERAY1_OBUSY_REG       SRC_ERAY_ERAY1_OBUSY
#define INTBSL_u8SRC_ERAY_ERAY1_TINT0_REG       SRC_ERAY_ERAY1_TINT0
#define INTBSL_u8SRC_ERAY_ERAY1_TINT1_REG       SRC_ERAY_ERAY1_TINT1
#define INTBSL_u8SRC_ETH_ETH0_SR_REG            SRC_ETH_ETH0_SR
#define INTBSL_u8SRC_FCE_FCE0_SR_REG            SRC_FCE_FCE0_SR
#define INTBSL_u8SRC_FFT_FFT0_DONE_REG          SRC_FFT_FFT0_DONE
#define INTBSL_u8SRC_FFT_FFT0_ERR_REG           SRC_FFT_FFT0_ERR
#define INTBSL_u8SRC_FFT_FFT0_RFS_REG           SRC_FFT_FFT0_RFS
#define INTBSL_u8SRC_GPSR_GPSR0_SR0_REG         SRC_GPSR_GPSR0_SR0
#define INTBSL_u8SRC_GPSR_GPSR0_SR1_REG         SRC_GPSR_GPSR0_SR1
#define INTBSL_u8SRC_GPSR_GPSR0_SR2_REG         SRC_GPSR_GPSR0_SR2
#define INTBSL_u8SRC_GPSR_GPSR0_SR3_REG         SRC_GPSR_GPSR0_SR3
#define INTBSL_u8SRC_GPSR_GPSR1_SR0_REG         SRC_GPSR_GPSR1_SR0
#define INTBSL_u8SRC_GPSR_GPSR1_SR1_REG         SRC_GPSR_GPSR1_SR1
#define INTBSL_u8SRC_GPSR_GPSR1_SR2_REG         SRC_GPSR_GPSR1_SR2
#define INTBSL_u8SRC_GPSR_GPSR1_SR3_REG         SRC_GPSR_GPSR1_SR3
#define INTBSL_u8SRC_GPSR_GPSR2_SR0_REG         SRC_GPSR_GPSR2_SR0
#define INTBSL_u8SRC_GPSR_GPSR2_SR1_REG         SRC_GPSR_GPSR2_SR1
#define INTBSL_u8SRC_GPSR_GPSR2_SR2_REG         SRC_GPSR_GPSR2_SR2
#define INTBSL_u8SRC_GPSR_GPSR2_SR3_REG         SRC_GPSR_GPSR2_SR3
#define INTBSL_u8SRC_GPT12_GPT120_CIRQ_REG      SRC_GPT12_GPT120_CIRQ
#define INTBSL_u8SRC_GPT12_GPT120_T2_REG        SRC_GPT12_GPT120_T2
#define INTBSL_u8SRC_GPT12_GPT120_T3_REG        SRC_GPT12_GPT120_T3
#define INTBSL_u8SRC_GPT12_GPT120_T4_REG        SRC_GPT12_GPT120_T4
#define INTBSL_u8SRC_GPT12_GPT120_T5_REG        SRC_GPT12_GPT120_T5
#define INTBSL_u8SRC_GPT12_GPT120_T6_REG        SRC_GPT12_GPT120_T6
#define INTBSL_u8SRC_GTM_GTM0_AEIIRQ_REG        SRC_GTM_GTM0_AEIIRQ
#define INTBSL_u8SRC_GTM_GTM0_ARUIRQ0_REG       SRC_GTM_GTM0_ARUIRQ0
#define INTBSL_u8SRC_GTM_GTM0_ARUIRQ1_REG       SRC_GTM_GTM0_ARUIRQ1
#define INTBSL_u8SRC_GTM_GTM0_ARUIRQ2_REG       SRC_GTM_GTM0_ARUIRQ2
#define INTBSL_u8SRC_GTM_GTM0_ATOM0_0_REG       SRC_GTM_GTM0_ATOM0_0
#define INTBSL_u8SRC_GTM_GTM0_ATOM0_1_REG       SRC_GTM_GTM0_ATOM0_1
#define INTBSL_u8SRC_GTM_GTM0_ATOM0_2_REG       SRC_GTM_GTM0_ATOM0_2
#define INTBSL_u8SRC_GTM_GTM0_ATOM0_3_REG       SRC_GTM_GTM0_ATOM0_3
#define INTBSL_u8SRC_GTM_GTM0_ATOM1_0_REG       SRC_GTM_GTM0_ATOM1_0
#define INTBSL_u8SRC_GTM_GTM0_ATOM1_1_REG       SRC_GTM_GTM0_ATOM1_1
#define INTBSL_u8SRC_GTM_GTM0_ATOM1_2_REG       SRC_GTM_GTM0_ATOM1_2
#define INTBSL_u8SRC_GTM_GTM0_ATOM1_3_REG       SRC_GTM_GTM0_ATOM1_3
#define INTBSL_u8SRC_GTM_GTM0_ATOM2_0_REG       SRC_GTM_GTM0_ATOM2_0
#define INTBSL_u8SRC_GTM_GTM0_ATOM2_1_REG       SRC_GTM_GTM0_ATOM2_1
#define INTBSL_u8SRC_GTM_GTM0_ATOM2_2_REG       SRC_GTM_GTM0_ATOM2_2
#define INTBSL_u8SRC_GTM_GTM0_ATOM2_3_REG       SRC_GTM_GTM0_ATOM2_3
#define INTBSL_u8SRC_GTM_GTM0_ATOM3_0_REG       SRC_GTM_GTM0_ATOM3_0
#define INTBSL_u8SRC_GTM_GTM0_ATOM3_1_REG       SRC_GTM_GTM0_ATOM3_1
#define INTBSL_u8SRC_GTM_GTM0_ATOM3_2_REG       SRC_GTM_GTM0_ATOM3_2
#define INTBSL_u8SRC_GTM_GTM0_ATOM3_3_REG       SRC_GTM_GTM0_ATOM3_3
#define INTBSL_u8SRC_GTM_GTM0_ATOM4_0_REG       SRC_GTM_GTM0_ATOM4_0
#define INTBSL_u8SRC_GTM_GTM0_ATOM4_1_REG       SRC_GTM_GTM0_ATOM4_1
#define INTBSL_u8SRC_GTM_GTM0_ATOM4_2_REG       SRC_GTM_GTM0_ATOM4_2
#define INTBSL_u8SRC_GTM_GTM0_ATOM4_3_REG       SRC_GTM_GTM0_ATOM4_3
#define INTBSL_u8SRC_GTM_GTM0_ATOM5_0_REG       SRC_GTM_GTM0_ATOM5_0
#define INTBSL_u8SRC_GTM_GTM0_ATOM5_1_REG       SRC_GTM_GTM0_ATOM5_1
#define INTBSL_u8SRC_GTM_GTM0_ATOM5_2_REG       SRC_GTM_GTM0_ATOM5_2
#define INTBSL_u8SRC_GTM_GTM0_ATOM5_3_REG       SRC_GTM_GTM0_ATOM5_3
#define INTBSL_u8SRC_GTM_GTM0_ATOM6_0_REG       SRC_GTM_GTM0_ATOM6_0
#define INTBSL_u8SRC_GTM_GTM0_ATOM6_1_REG       SRC_GTM_GTM0_ATOM6_1
#define INTBSL_u8SRC_GTM_GTM0_ATOM6_2_REG       SRC_GTM_GTM0_ATOM6_2
#define INTBSL_u8SRC_GTM_GTM0_ATOM6_3_REG       SRC_GTM_GTM0_ATOM6_3
#define INTBSL_u8SRC_GTM_GTM0_ATOM7_0_REG       SRC_GTM_GTM0_ATOM7_0
#define INTBSL_u8SRC_GTM_GTM0_ATOM7_1_REG       SRC_GTM_GTM0_ATOM7_1
#define INTBSL_u8SRC_GTM_GTM0_ATOM7_2_REG       SRC_GTM_GTM0_ATOM7_2
#define INTBSL_u8SRC_GTM_GTM0_ATOM7_3_REG       SRC_GTM_GTM0_ATOM7_3
#define INTBSL_u8SRC_GTM_GTM0_ATOM8_0_REG       SRC_GTM_GTM0_ATOM8_0
#define INTBSL_u8SRC_GTM_GTM0_ATOM8_1_REG       SRC_GTM_GTM0_ATOM8_1
#define INTBSL_u8SRC_GTM_GTM0_ATOM8_2_REG       SRC_GTM_GTM0_ATOM8_2
#define INTBSL_u8SRC_GTM_GTM0_ATOM8_3_REG       SRC_GTM_GTM0_ATOM8_3
#define INTBSL_u8SRC_GTM_GTM0_BRCIRQ_REG        SRC_GTM_GTM0_BRCIRQ
#define INTBSL_u8SRC_GTM_GTM0_CMPIRQ_REG        SRC_GTM_GTM0_CMPIRQ
#define INTBSL_u8SRC_GTM_GTM0_DPLL0_REG         SRC_GTM_GTM0_DPLL0
#define INTBSL_u8SRC_GTM_GTM0_DPLL1_REG         SRC_GTM_GTM0_DPLL1
#define INTBSL_u8SRC_GTM_GTM0_DPLL10_REG        SRC_GTM_GTM0_DPLL10
#define INTBSL_u8SRC_GTM_GTM0_DPLL11_REG        SRC_GTM_GTM0_DPLL11
#define INTBSL_u8SRC_GTM_GTM0_DPLL12_REG        SRC_GTM_GTM0_DPLL12
#define INTBSL_u8SRC_GTM_GTM0_DPLL13_REG        SRC_GTM_GTM0_DPLL13
#define INTBSL_u8SRC_GTM_GTM0_DPLL14_REG        SRC_GTM_GTM0_DPLL14
#define INTBSL_u8SRC_GTM_GTM0_DPLL15_REG        SRC_GTM_GTM0_DPLL15
#define INTBSL_u8SRC_GTM_GTM0_DPLL16_REG        SRC_GTM_GTM0_DPLL16
#define INTBSL_u8SRC_GTM_GTM0_DPLL17_REG        SRC_GTM_GTM0_DPLL17
#define INTBSL_u8SRC_GTM_GTM0_DPLL18_REG        SRC_GTM_GTM0_DPLL18
#define INTBSL_u8SRC_GTM_GTM0_DPLL19_REG        SRC_GTM_GTM0_DPLL19
#define INTBSL_u8SRC_GTM_GTM0_DPLL2_REG         SRC_GTM_GTM0_DPLL2
#define INTBSL_u8SRC_GTM_GTM0_DPLL20_REG        SRC_GTM_GTM0_DPLL20
#define INTBSL_u8SRC_GTM_GTM0_DPLL21_REG        SRC_GTM_GTM0_DPLL21
#define INTBSL_u8SRC_GTM_GTM0_DPLL22_REG        SRC_GTM_GTM0_DPLL22
#define INTBSL_u8SRC_GTM_GTM0_DPLL23_REG        SRC_GTM_GTM0_DPLL23
#define INTBSL_u8SRC_GTM_GTM0_DPLL24_REG        SRC_GTM_GTM0_DPLL24
#define INTBSL_u8SRC_GTM_GTM0_DPLL25_REG        SRC_GTM_GTM0_DPLL25
#define INTBSL_u8SRC_GTM_GTM0_DPLL26_REG        SRC_GTM_GTM0_DPLL26
#define INTBSL_u8SRC_GTM_GTM0_DPLL3_REG         SRC_GTM_GTM0_DPLL3
#define INTBSL_u8SRC_GTM_GTM0_DPLL4_REG         SRC_GTM_GTM0_DPLL4
#define INTBSL_u8SRC_GTM_GTM0_DPLL5_REG         SRC_GTM_GTM0_DPLL5
#define INTBSL_u8SRC_GTM_GTM0_DPLL6_REG         SRC_GTM_GTM0_DPLL6
#define INTBSL_u8SRC_GTM_GTM0_DPLL7_REG         SRC_GTM_GTM0_DPLL7
#define INTBSL_u8SRC_GTM_GTM0_DPLL8_REG         SRC_GTM_GTM0_DPLL8
#define INTBSL_u8SRC_GTM_GTM0_DPLL9_REG         SRC_GTM_GTM0_DPLL9
#define INTBSL_u8SRC_GTM_GTM0_ERR_REG           SRC_GTM_GTM0_ERR
#define INTBSL_u8SRC_GTM_GTM0_MCS0_0_REG        SRC_GTM_GTM0_MCS0_0
#define INTBSL_u8SRC_GTM_GTM0_MCS0_1_REG        SRC_GTM_GTM0_MCS0_1
#define INTBSL_u8SRC_GTM_GTM0_MCS0_2_REG        SRC_GTM_GTM0_MCS0_2
#define INTBSL_u8SRC_GTM_GTM0_MCS0_3_REG        SRC_GTM_GTM0_MCS0_3
#define INTBSL_u8SRC_GTM_GTM0_MCS0_4_REG        SRC_GTM_GTM0_MCS0_4
#define INTBSL_u8SRC_GTM_GTM0_MCS0_5_REG        SRC_GTM_GTM0_MCS0_5
#define INTBSL_u8SRC_GTM_GTM0_MCS0_6_REG        SRC_GTM_GTM0_MCS0_6
#define INTBSL_u8SRC_GTM_GTM0_MCS0_7_REG        SRC_GTM_GTM0_MCS0_7
#define INTBSL_u8SRC_GTM_GTM0_MCS1_0_REG        SRC_GTM_GTM0_MCS1_0
#define INTBSL_u8SRC_GTM_GTM0_MCS1_1_REG        SRC_GTM_GTM0_MCS1_1
#define INTBSL_u8SRC_GTM_GTM0_MCS1_2_REG        SRC_GTM_GTM0_MCS1_2
#define INTBSL_u8SRC_GTM_GTM0_MCS1_3_REG        SRC_GTM_GTM0_MCS1_3
#define INTBSL_u8SRC_GTM_GTM0_MCS1_4_REG        SRC_GTM_GTM0_MCS1_4
#define INTBSL_u8SRC_GTM_GTM0_MCS1_5_REG        SRC_GTM_GTM0_MCS1_5
#define INTBSL_u8SRC_GTM_GTM0_MCS1_6_REG        SRC_GTM_GTM0_MCS1_6
#define INTBSL_u8SRC_GTM_GTM0_MCS1_7_REG        SRC_GTM_GTM0_MCS1_7
#define INTBSL_u8SRC_GTM_GTM0_MCS2_0_REG        SRC_GTM_GTM0_MCS2_0
#define INTBSL_u8SRC_GTM_GTM0_MCS2_1_REG        SRC_GTM_GTM0_MCS2_1
#define INTBSL_u8SRC_GTM_GTM0_MCS2_2_REG        SRC_GTM_GTM0_MCS2_2
#define INTBSL_u8SRC_GTM_GTM0_MCS2_3_REG        SRC_GTM_GTM0_MCS2_3
#define INTBSL_u8SRC_GTM_GTM0_MCS2_4_REG        SRC_GTM_GTM0_MCS2_4
#define INTBSL_u8SRC_GTM_GTM0_MCS2_5_REG        SRC_GTM_GTM0_MCS2_5
#define INTBSL_u8SRC_GTM_GTM0_MCS2_6_REG        SRC_GTM_GTM0_MCS2_6
#define INTBSL_u8SRC_GTM_GTM0_MCS2_7_REG        SRC_GTM_GTM0_MCS2_7
#define INTBSL_u8SRC_GTM_GTM0_MCS3_0_REG        SRC_GTM_GTM0_MCS3_0
#define INTBSL_u8SRC_GTM_GTM0_MCS3_1_REG        SRC_GTM_GTM0_MCS3_1
#define INTBSL_u8SRC_GTM_GTM0_MCS3_2_REG        SRC_GTM_GTM0_MCS3_2
#define INTBSL_u8SRC_GTM_GTM0_MCS3_3_REG        SRC_GTM_GTM0_MCS3_3
#define INTBSL_u8SRC_GTM_GTM0_MCS3_4_REG        SRC_GTM_GTM0_MCS3_4
#define INTBSL_u8SRC_GTM_GTM0_MCS3_5_REG        SRC_GTM_GTM0_MCS3_5
#define INTBSL_u8SRC_GTM_GTM0_MCS3_6_REG        SRC_GTM_GTM0_MCS3_6
#define INTBSL_u8SRC_GTM_GTM0_MCS3_7_REG        SRC_GTM_GTM0_MCS3_7
#define INTBSL_u8SRC_GTM_GTM0_MCS4_0_REG        SRC_GTM_GTM0_MCS4_0
#define INTBSL_u8SRC_GTM_GTM0_MCS4_1_REG        SRC_GTM_GTM0_MCS4_1
#define INTBSL_u8SRC_GTM_GTM0_MCS4_2_REG        SRC_GTM_GTM0_MCS4_2
#define INTBSL_u8SRC_GTM_GTM0_MCS4_3_REG        SRC_GTM_GTM0_MCS4_3
#define INTBSL_u8SRC_GTM_GTM0_MCS4_4_REG        SRC_GTM_GTM0_MCS4_4
#define INTBSL_u8SRC_GTM_GTM0_MCS4_5_REG        SRC_GTM_GTM0_MCS4_5
#define INTBSL_u8SRC_GTM_GTM0_MCS4_6_REG        SRC_GTM_GTM0_MCS4_6
#define INTBSL_u8SRC_GTM_GTM0_MCS4_7_REG        SRC_GTM_GTM0_MCS4_7
#define INTBSL_u8SRC_GTM_GTM0_MCS5_0_REG        SRC_GTM_GTM0_MCS5_0
#define INTBSL_u8SRC_GTM_GTM0_MCS5_1_REG        SRC_GTM_GTM0_MCS5_1
#define INTBSL_u8SRC_GTM_GTM0_MCS5_2_REG        SRC_GTM_GTM0_MCS5_2
#define INTBSL_u8SRC_GTM_GTM0_MCS5_3_REG        SRC_GTM_GTM0_MCS5_3
#define INTBSL_u8SRC_GTM_GTM0_MCS5_4_REG        SRC_GTM_GTM0_MCS5_4
#define INTBSL_u8SRC_GTM_GTM0_MCS5_5_REG        SRC_GTM_GTM0_MCS5_5
#define INTBSL_u8SRC_GTM_GTM0_MCS5_6_REG        SRC_GTM_GTM0_MCS5_6
#define INTBSL_u8SRC_GTM_GTM0_MCS5_7_REG        SRC_GTM_GTM0_MCS5_7
#define INTBSL_u8SRC_GTM_GTM0_PSM00_REG         SRC_GTM_GTM0_PSM0_0
#define INTBSL_u8SRC_GTM_GTM0_PSM01_REG         SRC_GTM_GTM0_PSM0_1
#define INTBSL_u8SRC_GTM_GTM0_PSM02_REG         SRC_GTM_GTM0_PSM0_2
#define INTBSL_u8SRC_GTM_GTM0_PSM03_REG         SRC_GTM_GTM0_PSM0_3
#define INTBSL_u8SRC_GTM_GTM0_PSM04_REG         SRC_GTM_GTM0_PSM0_4
#define INTBSL_u8SRC_GTM_GTM0_PSM05_REG         SRC_GTM_GTM0_PSM0_5
#define INTBSL_u8SRC_GTM_GTM0_PSM06_REG         SRC_GTM_GTM0_PSM0_6
#define INTBSL_u8SRC_GTM_GTM0_PSM07_REG         SRC_GTM_GTM0_PSM0_7
#define INTBSL_u8SRC_GTM_GTM0_PSM10_REG         SRC_GTM_GTM0_PSM1_0
#define INTBSL_u8SRC_GTM_GTM0_PSM11_REG         SRC_GTM_GTM0_PSM1_1
#define INTBSL_u8SRC_GTM_GTM0_PSM12_REG         SRC_GTM_GTM0_PSM1_2
#define INTBSL_u8SRC_GTM_GTM0_PSM13_REG         SRC_GTM_GTM0_PSM1_3
#define INTBSL_u8SRC_GTM_GTM0_PSM14_REG         SRC_GTM_GTM0_PSM1_4
#define INTBSL_u8SRC_GTM_GTM0_PSM15_REG         SRC_GTM_GTM0_PSM1_5
#define INTBSL_u8SRC_GTM_GTM0_PSM16_REG         SRC_GTM_GTM0_PSM1_6
#define INTBSL_u8SRC_GTM_GTM0_PSM17_REG         SRC_GTM_GTM0_PSM1_7
#define INTBSL_u8SRC_GTM_GTM0_SPE0IRQ_REG       SRC_GTM_GTM0_SPEIRQ0
#define INTBSL_u8SRC_GTM_GTM0_SPE1IRQ_REG       SRC_GTM_GTM0_SPEIRQ1
#define INTBSL_u8SRC_GTM_GTM0_SPE2IRQ_REG       SRC_GTM_GTM0_SPEIRQ2
#define INTBSL_u8SRC_GTM_GTM0_SPE3IRQ_REG       SRC_GTM_GTM0_SPEIRQ3
#define INTBSL_u8SRC_GTM_GTM0_TIM0_0_REG        SRC_GTM_GTM0_TIM0_0
#define INTBSL_u8SRC_GTM_GTM0_TIM0_1_REG        SRC_GTM_GTM0_TIM0_1
#define INTBSL_u8SRC_GTM_GTM0_TIM0_2_REG        SRC_GTM_GTM0_TIM0_2
#define INTBSL_u8SRC_GTM_GTM0_TIM0_3_REG        SRC_GTM_GTM0_TIM0_3
#define INTBSL_u8SRC_GTM_GTM0_TIM0_4_REG        SRC_GTM_GTM0_TIM0_4
#define INTBSL_u8SRC_GTM_GTM0_TIM0_5_REG        SRC_GTM_GTM0_TIM0_5
#define INTBSL_u8SRC_GTM_GTM0_TIM0_6_REG        SRC_GTM_GTM0_TIM0_6
#define INTBSL_u8SRC_GTM_GTM0_TIM0_7_REG        SRC_GTM_GTM0_TIM0_7
#define INTBSL_u8SRC_GTM_GTM0_TIM1_0_REG        SRC_GTM_GTM0_TIM1_0
#define INTBSL_u8SRC_GTM_GTM0_TIM1_1_REG        SRC_GTM_GTM0_TIM1_1
#define INTBSL_u8SRC_GTM_GTM0_TIM1_2_REG        SRC_GTM_GTM0_TIM1_2
#define INTBSL_u8SRC_GTM_GTM0_TIM1_3_REG        SRC_GTM_GTM0_TIM1_3
#define INTBSL_u8SRC_GTM_GTM0_TIM1_4_REG        SRC_GTM_GTM0_TIM1_4
#define INTBSL_u8SRC_GTM_GTM0_TIM1_5_REG        SRC_GTM_GTM0_TIM1_5
#define INTBSL_u8SRC_GTM_GTM0_TIM1_6_REG        SRC_GTM_GTM0_TIM1_6
#define INTBSL_u8SRC_GTM_GTM0_TIM1_7_REG        SRC_GTM_GTM0_TIM1_7
#define INTBSL_u8SRC_GTM_GTM0_TIM2_0_REG        SRC_GTM_GTM0_TIM2_0
#define INTBSL_u8SRC_GTM_GTM0_TIM2_1_REG        SRC_GTM_GTM0_TIM2_1
#define INTBSL_u8SRC_GTM_GTM0_TIM2_2_REG        SRC_GTM_GTM0_TIM2_2
#define INTBSL_u8SRC_GTM_GTM0_TIM2_3_REG        SRC_GTM_GTM0_TIM2_3
#define INTBSL_u8SRC_GTM_GTM0_TIM2_4_REG        SRC_GTM_GTM0_TIM2_4
#define INTBSL_u8SRC_GTM_GTM0_TIM2_5_REG        SRC_GTM_GTM0_TIM2_5
#define INTBSL_u8SRC_GTM_GTM0_TIM2_6_REG        SRC_GTM_GTM0_TIM2_6
#define INTBSL_u8SRC_GTM_GTM0_TIM2_7_REG        SRC_GTM_GTM0_TIM2_7
#define INTBSL_u8SRC_GTM_GTM0_TIM3_0_REG        SRC_GTM_GTM0_TIM3_0
#define INTBSL_u8SRC_GTM_GTM0_TIM3_1_REG        SRC_GTM_GTM0_TIM3_1
#define INTBSL_u8SRC_GTM_GTM0_TIM3_2_REG        SRC_GTM_GTM0_TIM3_2
#define INTBSL_u8SRC_GTM_GTM0_TIM3_3_REG        SRC_GTM_GTM0_TIM3_3
#define INTBSL_u8SRC_GTM_GTM0_TIM3_4_REG        SRC_GTM_GTM0_TIM3_4
#define INTBSL_u8SRC_GTM_GTM0_TIM3_5_REG        SRC_GTM_GTM0_TIM3_5
#define INTBSL_u8SRC_GTM_GTM0_TIM3_6_REG        SRC_GTM_GTM0_TIM3_6
#define INTBSL_u8SRC_GTM_GTM0_TIM3_7_REG        SRC_GTM_GTM0_TIM3_7
#define INTBSL_u8SRC_GTM_GTM0_TIM4_0_REG        SRC_GTM_GTM0_TIM4_0
#define INTBSL_u8SRC_GTM_GTM0_TIM4_1_REG        SRC_GTM_GTM0_TIM4_1
#define INTBSL_u8SRC_GTM_GTM0_TIM4_2_REG        SRC_GTM_GTM0_TIM4_2
#define INTBSL_u8SRC_GTM_GTM0_TIM4_3_REG        SRC_GTM_GTM0_TIM4_3
#define INTBSL_u8SRC_GTM_GTM0_TIM4_4_REG        SRC_GTM_GTM0_TIM4_4
#define INTBSL_u8SRC_GTM_GTM0_TIM4_5_REG        SRC_GTM_GTM0_TIM4_5
#define INTBSL_u8SRC_GTM_GTM0_TIM4_6_REG        SRC_GTM_GTM0_TIM4_6
#define INTBSL_u8SRC_GTM_GTM0_TIM4_7_REG        SRC_GTM_GTM0_TIM4_7
#define INTBSL_u8SRC_GTM_GTM0_TIM5_0_REG        SRC_GTM_GTM0_TIM5_0
#define INTBSL_u8SRC_GTM_GTM0_TIM5_1_REG        SRC_GTM_GTM0_TIM5_1
#define INTBSL_u8SRC_GTM_GTM0_TIM5_2_REG        SRC_GTM_GTM0_TIM5_2
#define INTBSL_u8SRC_GTM_GTM0_TIM5_3_REG        SRC_GTM_GTM0_TIM5_3
#define INTBSL_u8SRC_GTM_GTM0_TIM5_4_REG        SRC_GTM_GTM0_TIM5_4
#define INTBSL_u8SRC_GTM_GTM0_TIM5_5_REG        SRC_GTM_GTM0_TIM5_5
#define INTBSL_u8SRC_GTM_GTM0_TIM5_6_REG        SRC_GTM_GTM0_TIM5_6
#define INTBSL_u8SRC_GTM_GTM0_TIM5_7_REG        SRC_GTM_GTM0_TIM5_7
#define INTBSL_u8SRC_GTM_GTM0_TOM0_0_REG        SRC_GTM_GTM0_TOM0_0
#define INTBSL_u8SRC_GTM_GTM0_TOM0_1_REG        SRC_GTM_GTM0_TOM0_1
#define INTBSL_u8SRC_GTM_GTM0_TOM0_2_REG        SRC_GTM_GTM0_TOM0_2
#define INTBSL_u8SRC_GTM_GTM0_TOM0_3_REG        SRC_GTM_GTM0_TOM0_3
#define INTBSL_u8SRC_GTM_GTM0_TOM0_4_REG        SRC_GTM_GTM0_TOM0_4
#define INTBSL_u8SRC_GTM_GTM0_TOM0_5_REG        SRC_GTM_GTM0_TOM0_5
#define INTBSL_u8SRC_GTM_GTM0_TOM0_6_REG        SRC_GTM_GTM0_TOM0_6
#define INTBSL_u8SRC_GTM_GTM0_TOM0_7_REG        SRC_GTM_GTM0_TOM0_7
#define INTBSL_u8SRC_GTM_GTM0_TOM1_0_REG        SRC_GTM_GTM0_TOM1_0
#define INTBSL_u8SRC_GTM_GTM0_TOM1_1_REG        SRC_GTM_GTM0_TOM1_1
#define INTBSL_u8SRC_GTM_GTM0_TOM1_2_REG        SRC_GTM_GTM0_TOM1_2
#define INTBSL_u8SRC_GTM_GTM0_TOM1_3_REG        SRC_GTM_GTM0_TOM1_3
#define INTBSL_u8SRC_GTM_GTM0_TOM1_4_REG        SRC_GTM_GTM0_TOM1_4
#define INTBSL_u8SRC_GTM_GTM0_TOM1_5_REG        SRC_GTM_GTM0_TOM1_5
#define INTBSL_u8SRC_GTM_GTM0_TOM1_6_REG        SRC_GTM_GTM0_TOM1_6
#define INTBSL_u8SRC_GTM_GTM0_TOM1_7_REG        SRC_GTM_GTM0_TOM1_7
#define INTBSL_u8SRC_GTM_GTM0_TOM2_0_REG        SRC_GTM_GTM0_TOM2_0
#define INTBSL_u8SRC_GTM_GTM0_TOM2_1_REG        SRC_GTM_GTM0_TOM2_1
#define INTBSL_u8SRC_GTM_GTM0_TOM2_2_REG        SRC_GTM_GTM0_TOM2_2
#define INTBSL_u8SRC_GTM_GTM0_TOM2_3_REG        SRC_GTM_GTM0_TOM2_3
#define INTBSL_u8SRC_GTM_GTM0_TOM2_4_REG        SRC_GTM_GTM0_TOM2_4
#define INTBSL_u8SRC_GTM_GTM0_TOM2_5_REG        SRC_GTM_GTM0_TOM2_5
#define INTBSL_u8SRC_GTM_GTM0_TOM2_6_REG        SRC_GTM_GTM0_TOM2_6
#define INTBSL_u8SRC_GTM_GTM0_TOM2_7_REG        SRC_GTM_GTM0_TOM2_7
#define INTBSL_u8SRC_GTM_GTM0_TOM3_0_REG        SRC_GTM_GTM3_TOM1_0
#define INTBSL_u8SRC_GTM_GTM0_TOM3_1_REG        SRC_GTM_GTM3_TOM1_1
#define INTBSL_u8SRC_GTM_GTM0_TOM3_2_REG        SRC_GTM_GTM3_TOM1_2
#define INTBSL_u8SRC_GTM_GTM0_TOM3_3_REG        SRC_GTM_GTM3_TOM1_3
#define INTBSL_u8SRC_GTM_GTM0_TOM3_4_REG        SRC_GTM_GTM3_TOM1_4
#define INTBSL_u8SRC_GTM_GTM0_TOM3_5_REG        SRC_GTM_GTM3_TOM1_5
#define INTBSL_u8SRC_GTM_GTM0_TOM3_6_REG        SRC_GTM_GTM3_TOM1_6
#define INTBSL_u8SRC_GTM_GTM0_TOM3_7_REG        SRC_GTM_GTM3_TOM1_7
#define INTBSL_u8SRC_GTM_GTM0_TOM4_0_REG        SRC_GTM_GTM4_TOM2_0
#define INTBSL_u8SRC_GTM_GTM0_TOM4_1_REG        SRC_GTM_GTM4_TOM2_1
#define INTBSL_u8SRC_GTM_GTM0_TOM4_2_REG        SRC_GTM_GTM4_TOM2_2
#define INTBSL_u8SRC_GTM_GTM0_TOM4_3_REG        SRC_GTM_GTM4_TOM2_3
#define INTBSL_u8SRC_GTM_GTM0_TOM4_4_REG        SRC_GTM_GTM4_TOM2_4
#define INTBSL_u8SRC_GTM_GTM0_TOM4_5_REG        SRC_GTM_GTM4_TOM2_5
#define INTBSL_u8SRC_GTM_GTM0_TOM4_6_REG        SRC_GTM_GTM4_TOM2_6
#define INTBSL_u8SRC_GTM_GTM0_TOM4_7_REG        SRC_GTM_GTM4_TOM2_7
#define INTBSL_u8SRC_HSCT_HSCT0_SR_REG          SRC_HSCT_HSCT0_SR
#define INTBSL_u8SRC_HSM_HSM0_HSM0_REG          SRC_HSM_HSM0_HSM0
#define INTBSL_u8SRC_HSM_HSM0_HSM1_REG          SRC_HSM_HSM0_HSM1
#define INTBSL_u8SRC_HSSL_EXI_REG               SRC_HSSL_EXI
#define INTBSL_u8SRC_HSSL_HSSL0_COK_REG         SRC_HSSL_HSSL0_COK
#define INTBSL_u8SRC_HSSL_HSSL0_ERR_REG         SRC_HSSL_HSSL0_ERR
#define INTBSL_u8SRC_HSSL_HSSL0_RDI_REG         SRC_HSSL_HSSL0_RDI
#define INTBSL_u8SRC_HSSL_HSSL0_TRG_REG         SRC_HSSL_HSSL0_TRG
#define INTBSL_u8SRC_HSSL_HSSL1_COK_REG         SRC_HSSL_HSSL1_COK
#define INTBSL_u8SRC_HSSL_HSSL1_ERR_REG         SRC_HSSL_HSSL1_ERR
#define INTBSL_u8SRC_HSSL_HSSL1_RDI_REG         SRC_HSSL_HSSL1_RDI
#define INTBSL_u8SRC_HSSL_HSSL1_TRG_REG         SRC_HSSL_HSSL1_TRG
#define INTBSL_u8SRC_HSSL_HSSL2_COK_REG         SRC_HSSL_HSSL2_COK
#define INTBSL_u8SRC_HSSL_HSSL2_ERR_REG         SRC_HSSL_HSSL2_ERR
#define INTBSL_u8SRC_HSSL_HSSL2_RDI_REG         SRC_HSSL_HSSL2_RDI
#define INTBSL_u8SRC_HSSL_HSSL2_TRG_REG         SRC_HSSL_HSSL2_TRG
#define INTBSL_u8SRC_HSSL_HSSL3_COK_REG         SRC_HSSL_HSSL3_COK
#define INTBSL_u8SRC_HSSL_HSSL3_ERR_REG         SRC_HSSL_HSSL3_ERR
#define INTBSL_u8SRC_HSSL_HSSL3_RDI_REG         SRC_HSSL_HSSL3_RDI
#define INTBSL_u8SRC_HSSL_HSSL3_TRG_REG         SRC_HSSL_HSSL3_TRG
#define INTBSL_u8SRC_I2C_I2C0_BREQ_REG          SRC_I2C_I2C0_BREQ
#define INTBSL_u8SRC_I2C_I2C0_ERR_REG           SRC_I2C_I2C0_ERR
#define INTBSL_u8SRC_I2C_I2C0_LBREQ_REG         SRC_I2C_I2C0_LBREQ
#define INTBSL_u8SRC_I2C_I2C0_LSREQ_REG         SRC_I2C_I2C0_LSREQ
#define INTBSL_u8SRC_I2C_I2C0_P_REG             SRC_I2C_I2C0_P
#define INTBSL_u8SRC_I2C_I2C0_SREQ_REG          SRC_I2C_I2C0_SREQ
#define INTBSL_u8SRC_I2C_I2C1_BREQ_REG          SRC_I2C_I2C1_BREQ
#define INTBSL_u8SRC_I2C_I2C1_ERR_REG           SRC_I2C_I2C1_ERR
#define INTBSL_u8SRC_I2C_I2C1_LBREQ_REG         SRC_I2C_I2C1_LBREQ
#define INTBSL_u8SRC_I2C_I2C1_LSREQ_REG         SRC_I2C_I2C1_LSREQ
#define INTBSL_u8SRC_I2C_I2C1_P_REG             SRC_I2C_I2C1_P
#define INTBSL_u8SRC_I2C_I2C1_SREQ_REG          SRC_I2C_I2C1_SREQ
#define INTBSL_u8SRC_LMU_LMU0_SR_REG            SRC_LMU_LMU0_SR
#define INTBSL_u8SRC_MSC_MSC0_SR0_REG           SRC_MSC_MSC0_SR0
#define INTBSL_u8SRC_MSC_MSC0_SR1_REG           SRC_MSC_MSC0_SR1
#define INTBSL_u8SRC_MSC_MSC0_SR2_REG           SRC_MSC_MSC0_SR2
#define INTBSL_u8SRC_MSC_MSC0_SR3_REG           SRC_MSC_MSC0_SR3
#define INTBSL_u8SRC_MSC_MSC0_SR4_REG           SRC_MSC_MSC0_SR4
#define INTBSL_u8SRC_MSC_MSC1_SR0_REG           SRC_MSC_MSC1_SR0
#define INTBSL_u8SRC_MSC_MSC1_SR1_REG           SRC_MSC_MSC1_SR1
#define INTBSL_u8SRC_MSC_MSC1_SR2_REG           SRC_MSC_MSC1_SR2
#define INTBSL_u8SRC_MSC_MSC1_SR3_REG           SRC_MSC_MSC1_SR3
#define INTBSL_u8SRC_MSC_MSC1_SR4_REG           SRC_MSC_MSC1_SR4
#define INTBSL_u8SRC_MSC_MSC2_SR0_REG           SRC_MSC_MSC2_SR0
#define INTBSL_u8SRC_MSC_MSC2_SR1_REG           SRC_MSC_MSC2_SR1
#define INTBSL_u8SRC_MSC_MSC2_SR2_REG           SRC_MSC_MSC2_SR2
#define INTBSL_u8SRC_MSC_MSC2_SR3_REG           SRC_MSC_MSC2_SR3
#define INTBSL_u8SRC_MSC_MSC2_SR4_REG           SRC_MSC_MSC2_SR4
#define INTBSL_u8SRC_PMU00_REG                  SRC_PMU00
#define INTBSL_u8SRC_PMU01_REG                  SRC_PMU01
#define INTBSL_u8SRC_PSI5_PSI50_SR0_REG         SRC_PSI5_PSI50_SR0
#define INTBSL_u8SRC_PSI5_PSI50_SR1_REG         SRC_PSI5_PSI50_SR1
#define INTBSL_u8SRC_PSI5_PSI50_SR2_REG         SRC_PSI5_PSI50_SR2
#define INTBSL_u8SRC_PSI5_PSI50_SR3_REG         SRC_PSI5_PSI50_SR3
#define INTBSL_u8SRC_PSI5_PSI50_SR4_REG         SRC_PSI5_PSI50_SR4
#define INTBSL_u8SRC_PSI5_PSI50_SR5_REG         SRC_PSI5_PSI50_SR5
#define INTBSL_u8SRC_PSI5_PSI50_SR6_REG         SRC_PSI5_PSI50_SR6
#define INTBSL_u8SRC_PSI5_PSI50_SR7_REG         SRC_PSI5_PSI50_SR7
#define INTBSL_u8SRC_PSI5S_PSI5S0_SR0_REG       SRC_PSI5S_PSI5S0_SR0
#define INTBSL_u8SRC_PSI5S_PSI5S0_SR1_REG       SRC_PSI5S_PSI5S0_SR1
#define INTBSL_u8SRC_PSI5S_PSI5S0_SR2_REG       SRC_PSI5S_PSI5S0_SR2
#define INTBSL_u8SRC_PSI5S_PSI5S0_SR3_REG       SRC_PSI5S_PSI5S0_SR3
#define INTBSL_u8SRC_PSI5S_PSI5S0_SR4_REG       SRC_PSI5S_PSI5S0_SR4
#define INTBSL_u8SRC_PSI5S_PSI5S0_SR5_REG       SRC_PSI5S_PSI5S0_SR5
#define INTBSL_u8SRC_PSI5S_PSI5S0_SR6_REG       SRC_PSI5S_PSI5S0_SR6
#define INTBSL_u8SRC_PSI5S_PSI5S0_SR7_REG       SRC_PSI5S_PSI5S0_SR7
#define INTBSL_u8SRC_QSPI_QSPI0_ERR_REG         SRC_QSPI_QSPI0_ERR
#define INTBSL_u8SRC_QSPI_QSPI0_HC_REG          SRC_QSPI_QSPI0_HC
#define INTBSL_u8SRC_QSPI_QSPI0_PT_REG          SRC_QSPI_QSPI0_PT
#define INTBSL_u8SRC_QSPI_QSPI0_RX_REG          SRC_QSPI_QSPI0_RX
#define INTBSL_u8SRC_QSPI_QSPI0_TX_REG          SRC_QSPI_QSPI0_TX
#define INTBSL_u8SRC_QSPI_QSPI0_U_REG           SRC_QSPI_QSPI0_U
#define INTBSL_u8SRC_QSPI_QSPI1_ERR_REG         SRC_QSPI_QSPI1_ERR
#define INTBSL_u8SRC_QSPI_QSPI1_HC_REG          SRC_QSPI_QSPI1_HC
#define INTBSL_u8SRC_QSPI_QSPI1_PT_REG          SRC_QSPI_QSPI1_PT
#define INTBSL_u8SRC_QSPI_QSPI1_RX_REG          SRC_QSPI_QSPI1_RX
#define INTBSL_u8SRC_QSPI_QSPI1_TX_REG          SRC_QSPI_QSPI1_TX
#define INTBSL_u8SRC_QSPI_QSPI1_U_REG           SRC_QSPI_QSPI1_U
#define INTBSL_u8SRC_QSPI_QSPI2_ERR_REG         SRC_QSPI_QSPI2_ERR
#define INTBSL_u8SRC_QSPI_QSPI2_HC_REG          SRC_QSPI_QSPI2_HC
#define INTBSL_u8SRC_QSPI_QSPI2_PT_REG          SRC_QSPI_QSPI2_PT
#define INTBSL_u8SRC_QSPI_QSPI2_RX_REG          SRC_QSPI_QSPI2_RX
#define INTBSL_u8SRC_QSPI_QSPI2_TX_REG          SRC_QSPI_QSPI2_TX
#define INTBSL_u8SRC_QSPI_QSPI2_U_REG           SRC_QSPI_QSPI2_U
#define INTBSL_u8SRC_QSPI_QSPI3_ERR_REG         SRC_QSPI_QSPI3_ERR
#define INTBSL_u8SRC_QSPI_QSPI3_HC_REG          SRC_QSPI_QSPI3_HC
#define INTBSL_u8SRC_QSPI_QSPI3_PT_REG          SRC_QSPI_QSPI3_PT
#define INTBSL_u8SRC_QSPI_QSPI3_RX_REG          SRC_QSPI_QSPI3_RX
#define INTBSL_u8SRC_QSPI_QSPI3_TX_REG          SRC_QSPI_QSPI3_TX
#define INTBSL_u8SRC_QSPI_QSPI3_U_REG           SRC_QSPI_QSPI3_U
#define INTBSL_u8SRC_QSPI_QSPI4_ERR_REG         SRC_QSPI_QSPI4_ERR
#define INTBSL_u8SRC_QSPI_QSPI4_HC_REG          SRC_QSPI_QSPI4_HC
#define INTBSL_u8SRC_QSPI_QSPI4_PT_REG          SRC_QSPI_QSPI4_PT
#define INTBSL_u8SRC_QSPI_QSPI4_RX_REG          SRC_QSPI_QSPI4_RX
#define INTBSL_u8SRC_QSPI_QSPI4_TX_REG          SRC_QSPI_QSPI4_TX
#define INTBSL_u8SRC_QSPI_QSPI4_U_REG           SRC_QSPI_QSPI4_U
#define INTBSL_u8SRC_QSPI_QSPI5_ERR_REG         SRC_QSPI_QSPI5_ERR
#define INTBSL_u8SRC_QSPI_QSPI5_HC_REG          SRC_QSPI_QSPI5_HC
#define INTBSL_u8SRC_QSPI_QSPI5_PT_REG          SRC_QSPI_QSPI5_PT
#define INTBSL_u8SRC_QSPI_QSPI5_RX_REG          SRC_QSPI_QSPI5_RX
#define INTBSL_u8SRC_QSPI_QSPI5_TX_REG          SRC_QSPI_QSPI5_TX
#define INTBSL_u8SRC_QSPI_QSPI5_U_REG           SRC_QSPI_QSPI5_U
#define INTBSL_u8SRC_SCU_SCU_DTS_REG            SRC_SCU_SCU_DTS
#define INTBSL_u8SRC_SCU_SCU_ERU0_REG           SRC_SCU_SCU_ERU0
#define INTBSL_u8SRC_SCU_SCU_ERU1_REG           SRC_SCU_SCU_ERU1
#define INTBSL_u8SRC_SCU_SCU_ERU2_REG           SRC_SCU_SCU_ERU2
#define INTBSL_u8SRC_SCU_SCU_ERU3_REG           SRC_SCU_SCU_ERU3
#define INTBSL_u8SRC_SENT_SENT0_SR0_REG         SRC_SENT_SENT0_SR0
#define INTBSL_u8SRC_SENT_SENT0_SR1_REG         SRC_SENT_SENT0_SR1
#define INTBSL_u8SRC_SENT_SENT0_SR2_REG         SRC_SENT_SENT0_SR2
#define INTBSL_u8SRC_SENT_SENT0_SR3_REG         SRC_SENT_SENT0_SR3
#define INTBSL_u8SRC_SENT_SENT0_SR4_REG         SRC_SENT_SENT0_SR4
#define INTBSL_u8SRC_SENT_SENT0_SR5_REG         SRC_SENT_SENT0_SR5
#define INTBSL_u8SRC_SENT_SENT0_SR6_REG         SRC_SENT_SENT0_SR6
#define INTBSL_u8SRC_SENT_SENT0_SR7_REG         SRC_SENT_SENT0_SR7
#define INTBSL_u8SRC_SENT_SENT0_SR8_REG         SRC_SENT_SENT0_SR8
#define INTBSL_u8SRC_SENT_SENT0_SR9_REG         SRC_SENT_SENT0_SR9
#define INTBSL_u8SRC_SENT_SENT0_SR10_REG        SRC_SENT_SENT0_SR10
#define INTBSL_u8SRC_SENT_SENT0_SR11_REG        SRC_SENT_SENT0_SR11
#define INTBSL_u8SRC_SENT_SENT0_SR12_REG        SRC_SENT_SENT0_SR12
#define INTBSL_u8SRC_SENT_SENT0_SR13_REG        SRC_SENT_SENT0_SR13
#define INTBSL_u8SRC_SENT_SENT0_SR14_REG        SRC_SENT_SENT0_SR14
#define INTBSL_u8SRC_SMU_SMU0_SR0_REG           SRC_SMU_SMU0_SR0
#define INTBSL_u8SRC_SMU_SMU0_SR1_REG           SRC_SMU_SMU0_SR1
#define INTBSL_u8SRC_SMU_SMU0_SR2_REG           SRC_SMU_SMU0_SR2
#define INTBSL_u8SRC_STM_STM0_SR0_REG           SRC_STM_STM0_SR0
#define INTBSL_u8SRC_STM_STM0_SR1_REG           SRC_STM_STM0_SR1
#define INTBSL_u8SRC_STM_STM1_SR0_REG           SRC_STM_STM1_SR0
#define INTBSL_u8SRC_STM_STM1_SR1_REG           SRC_STM_STM1_SR1
#define INTBSL_u8SRC_STM_STM2_SR0_REG           SRC_STM_STM2_SR0
#define INTBSL_u8SRC_STM_STM2_SR1_REG           SRC_STM_STM2_SR1
#define INTBSL_u8SRC_VADC_CG0_SR0_REG           SRC_VADC_CG0_SR0
#define INTBSL_u8SRC_VADC_CG0_SR1_REG           SRC_VADC_CG0_SR1
#define INTBSL_u8SRC_VADC_CG0_SR2_REG           SRC_VADC_CG0_SR2
#define INTBSL_u8SRC_VADC_CG0_SR3_REG           SRC_VADC_CG0_SR3
#define INTBSL_u8SRC_VADC_CG1_SR0_REG           SRC_VADC_CG1_SR0
#define INTBSL_u8SRC_VADC_CG1_SR1_REG           SRC_VADC_CG1_SR1
#define INTBSL_u8SRC_VADC_CG1_SR2_REG           SRC_VADC_CG1_SR2
#define INTBSL_u8SRC_VADC_CG1_SR3_REG           SRC_VADC_CG1_SR3
#define INTBSL_u8SRC_VADC_G0_SR0_REG            SRC_VADC_G0_SR0
#define INTBSL_u8SRC_VADC_G0_SR1_REG            SRC_VADC_G0_SR1
#define INTBSL_u8SRC_VADC_G0_SR2_REG            SRC_VADC_G0_SR2
#define INTBSL_u8SRC_VADC_G0_SR3_REG            SRC_VADC_G0_SR3
#define INTBSL_u8SRC_VADC_G1_SR0_REG            SRC_VADC_G1_SR0
#define INTBSL_u8SRC_VADC_G1_SR1_REG            SRC_VADC_G1_SR1
#define INTBSL_u8SRC_VADC_G1_SR2_REG            SRC_VADC_G1_SR2
#define INTBSL_u8SRC_VADC_G1_SR3_REG            SRC_VADC_G1_SR3
#define INTBSL_u8SRC_VADC_G2_SR0_REG            SRC_VADC_G2_SR0
#define INTBSL_u8SRC_VADC_G2_SR1_REG            SRC_VADC_G2_SR1
#define INTBSL_u8SRC_VADC_G2_SR2_REG            SRC_VADC_G2_SR2
#define INTBSL_u8SRC_VADC_G2_SR3_REG            SRC_VADC_G2_SR3
#define INTBSL_u8SRC_VADC_G3_SR0_REG            SRC_VADC_G3_SR0
#define INTBSL_u8SRC_VADC_G3_SR1_REG            SRC_VADC_G3_SR1
#define INTBSL_u8SRC_VADC_G3_SR2_REG            SRC_VADC_G3_SR2
#define INTBSL_u8SRC_VADC_G3_SR3_REG            SRC_VADC_G3_SR3
#define INTBSL_u8SRC_VADC_G4_SR0_REG            SRC_VADC_G4_SR0
#define INTBSL_u8SRC_VADC_G4_SR1_REG            SRC_VADC_G4_SR1
#define INTBSL_u8SRC_VADC_G4_SR2_REG            SRC_VADC_G4_SR2
#define INTBSL_u8SRC_VADC_G4_SR3_REG            SRC_VADC_G4_SR3
#define INTBSL_u8SRC_VADC_G5_SR0_REG            SRC_VADC_G5_SR0
#define INTBSL_u8SRC_VADC_G5_SR1_REG            SRC_VADC_G5_SR1
#define INTBSL_u8SRC_VADC_G5_SR2_REG            SRC_VADC_G5_SR2
#define INTBSL_u8SRC_VADC_G5_SR3_REG            SRC_VADC_G5_SR3
#define INTBSL_u8SRC_VADC_G6_SR0_REG            SRC_VADC_G6_SR0
#define INTBSL_u8SRC_VADC_G6_SR1_REG            SRC_VADC_G6_SR1
#define INTBSL_u8SRC_VADC_G6_SR2_REG            SRC_VADC_G6_SR2
#define INTBSL_u8SRC_VADC_G6_SR3_REG            SRC_VADC_G6_SR3
#define INTBSL_u8SRC_VADC_G7_SR0_REG            SRC_VADC_G7_SR0
#define INTBSL_u8SRC_VADC_G7_SR1_REG            SRC_VADC_G7_SR1
#define INTBSL_u8SRC_VADC_G7_SR2_REG            SRC_VADC_G7_SR2
#define INTBSL_u8SRC_VADC_G7_SR3_REG            SRC_VADC_G7_SR3
#define INTBSL_u8SRC_VADC_G8_SR0_REG            SRC_VADC_G8_SR0
#define INTBSL_u8SRC_VADC_G8_SR1_REG            SRC_VADC_G8_SR1
#define INTBSL_u8SRC_VADC_G8_SR2_REG            SRC_VADC_G8_SR2
#define INTBSL_u8SRC_VADC_G8_SR3_REG            SRC_VADC_G8_SR3
#define INTBSL_u8SRC_VADC_G9_SR0_REG            SRC_VADC_G9_SR0
#define INTBSL_u8SRC_VADC_G9_SR1_REG            SRC_VADC_G9_SR1
#define INTBSL_u8SRC_VADC_G9_SR2_REG            SRC_VADC_G9_SR2
#define INTBSL_u8SRC_VADC_G9_SR3_REG            SRC_VADC_G9_SR3
#define INTBSL_u8SRC_VADC_G10_SR0_REG           SRC_VADC_G10_SR0
#define INTBSL_u8SRC_VADC_G10_SR1_REG           SRC_VADC_G10_SR1
#define INTBSL_u8SRC_VADC_G10_SR2_REG           SRC_VADC_G10_SR2
#define INTBSL_u8SRC_VADC_G10_SR3_REG           SRC_VADC_G10_SR3
#define INTBSL_u8SRC_XBARSRC_REG                SRC_XBARSRC


#define INTBSL_u8LWSR0_REG                      INT_CH0_LWSR
#define INTBSL_u8LWSR1_REG                      INT_CH1_LWSR
#define INTBSL_u8LWSR2_REG                      INT_CH2_LWSR
#define INTBSL_u8LWSR3_REG                      INT_CH3_LWSR


/*************************************************/

/* macro INTBSL */

/******************************************************************************/
/* !FuncName    : INTBSL_vidSTART_SW_IT                                       */
/* !Description : Interrupt Trig by software                                  */
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define INTBSL_vidSTART_SW_IT( \
\
   snItChannel /* !Comment : Identifier of the it channel */ \
) \
   INTBSL_vidSTART_SW_IT_I(snItChannel)
   
/******************************************************************************/
/* !FuncName    : INTBSL_vidSTART_SW_IT_I                                     */
/* !Description : Start software interrupt                                    */
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define INTBSL_vidSTART_SW_IT_I(snItChannel) \
   M1_INTBSL_vidSTART_SW_IT_I(INTBSL_u8GET_CFG_SRC_REG(snItChannel))

   /* internal macros */
   #define M1_INTBSL_vidSTART_SW_IT_I(snSrcReg) \
      do \
      { \
         (&snSrcReg)->B.SETR = 1; \
      } \
      while (0)
      
/******************************************************************************/
/* !FuncName    : INTBSL_snGET_CFG_SRC_REG                                    */
/* !Description : Get the SRC reg managing the configurated IT channel        */
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define INTBSL_u8GET_CFG_SRC_REG(snItChannel) \
   INTBSL_u8##snItChannel##_SRC_REG
   
/******************************************************************************/
/* !FuncName    : INTBSL_vidCONFIG_SRC                                        */
/* !Description : SRC Initialization                                          */
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define INTBSL_vidCONFIG_SRC( \
\
   snSrcChannel /* !Comment : Identifier of the SRC channel */ \
) \
   INTBSL_vidCONFIG_SRC_I(snSrcChannel)
   
/******************************************************************************/
/* !FuncName    : INTBSL_vidCONFIG_SRC_I                                      */
/* !Description : Initialize SRC                                              */
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define INTBSL_vidCONFIG_SRC_I(snSrcChannel) \
   M1_INTBSL_vidCONFIG_SRC_I(INTBSL_snGET_SRC_REG(snSrcChannel), \
                             INTBSL_u8GET_IT_SRV_PROVIDER(snSrcChannel), \
                             INTBSL_u16GET_PRIO(snSrcChannel), \
                             INTBSL_bGET_ENA_BIT(snSrcChannel))

   /* internal macros */
   #define M1_INTBSL_vidCONFIG_SRC_I(snSrcReg, \
                                     u8Tos, \
                                     u16SrcPriority, \
                                     bEnaBit) \
      do \
      { \
         (&snSrcReg)->U = ( ((u16SrcPriority) << 0) \
                          | ((bEnaBit) << 10) \
                          | ((u8Tos) << 11)); \
      } \
      while (0)
      
/******************************************************************************/
/* !FuncName    : INTBSL_vidRESET_SRC                                         */
/* !Description : SRC Reset                                                   */
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define INTBSL_vidRESET_SRC( \
\
   snSrcChannel /* !Comment : Identifier of the SRC channel */ \
) \
   INTBSL_vidRESET_SRC_I(snSrcChannel)

/******************************************************************************/
/* !FuncName    : INTBSL_vidRESET_SRC_I                                       */
/* !Description : Reset SRC                                                   */
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define INTBSL_vidRESET_SRC_I(snSrcChannel) \
   M1_INTBSL_vidRESET_SRC_I(INTBSL_snGET_SRC_REG(snSrcChannel))

   /* internal macros */
   #define M1_INTBSL_vidRESET_SRC_I(snSrcReg) \
      M2_INTBSL_vidRESET_SRC_I(snSrcReg)

   #define M2_INTBSL_vidRESET_SRC_I(snSrcReg) \
      do \
      { \
         (&snSrcReg)->B.SRE = 0u; \
      } \
      while (0)

/******************************************************************************/
/* !FuncName    : INTBSL_snGET_SRC_REG                                        */
/* !Description : Get the SRN register managing the IT                        */
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define INTBSL_snGET_SRC_REG(snSrcChannel) \
   INTBSL_snSRC_##snSrcChannel##_REG
   
/******************************************************************************/
/* !FuncName    : INTBSL_u8GET_IT_SRV_PROVIDER                                */
/* !Description : Get the cpu number managing the IT                          */
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define INTBSL_u8GET_IT_SRV_PROVIDER(snSrcChannel) \
   INTBSL_u8SRC_##snSrcChannel##_TOS
      
/******************************************************************************/
/* !FuncName    : INTBSL_u16GET_PRIO                                          */
/* !Description : Get the cpu number managing the IT                          */
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define INTBSL_u16GET_PRIO(snSrcChannel) \
   INTBSL_u16SRC_##snSrcChannel##_PRIO
      
/******************************************************************************/
/* !FuncName    : INTBSL_bGET_ENA_BIT                                         */
/* !Description : Get the enable bit of SRC managing the IT                   */
/*                                                                            */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define INTBSL_bGET_ENA_BIT(snSrcChannel) \
   INTBSL_bSRC_##snSrcChannel##_ENA_BIT
   
/* Defines related to DMA */

/* SPI0 uses DMA Ch0 for RX */
#define INTBSL_u8SRC_QSPI_QSPI0_RX_TOS        3u /* TOS = DMA */
#define INTBSL_u16SRC_QSPI_QSPI0_RX_PRIO      0u /* DMA Ch0 */
#define INTBSL_bSRC_QSPI_QSPI0_RX_ENA_BIT     0u
#define INTBSL_snSRC_QSPI_QSPI0_RX_REG        SRC_QSPI_QSPI0_RX

/* SPI0 uses DMA Ch1 for TX */
#define INTBSL_u8SRC_QSPI_QSPI0_TX_TOS        3u /* TOS = DMA */
#define INTBSL_u16SRC_QSPI_QSPI0_TX_PRIO      1u /* DMA Ch1 */
#define INTBSL_bSRC_QSPI_QSPI0_TX_ENA_BIT     0u
#define INTBSL_snSRC_QSPI_QSPI0_TX_REG        SRC_QSPI_QSPI0_TX

/* SPI2 uses DMA Ch4 for RX */
#define INTBSL_u8SRC_QSPI_QSPI2_RX_TOS        3u /* TOS = DMA */
#define INTBSL_u16SRC_QSPI_QSPI2_RX_PRIO      4u /* DMA Ch4 */
#define INTBSL_bSRC_QSPI_QSPI2_RX_ENA_BIT     0u
#define INTBSL_snSRC_QSPI_QSPI2_RX_REG        SRC_QSPI_QSPI2_RX

/* SPI2 uses DMA Ch5 for TX */
#define INTBSL_u8SRC_QSPI_QSPI2_TX_TOS        3u /* TOS = DMA */
#define INTBSL_u16SRC_QSPI_QSPI2_TX_PRIO      5u /* DMA Ch5 */
#define INTBSL_bSRC_QSPI_QSPI2_TX_ENA_BIT     0u
#define INTBSL_snSRC_QSPI_QSPI2_TX_REG        SRC_QSPI_QSPI2_TX

/* SPI4 uses DMA Ch8 for RX */
#define INTBSL_u8SRC_QSPI_QSPI4_RX_TOS        3u /* TOS = DMA */
#define INTBSL_u16SRC_QSPI_QSPI4_RX_PRIO      8u /* DMA Ch8 */
#define INTBSL_bSRC_QSPI_QSPI4_RX_ENA_BIT     0u
#define INTBSL_snSRC_QSPI_QSPI4_RX_REG        SRC_QSPI_QSPI4_RX

/* SPI4 uses DMA Ch9 for TX */
#define INTBSL_u8SRC_QSPI_QSPI4_TX_TOS        3u /* TOS = DMA */
#define INTBSL_u16SRC_QSPI_QSPI4_TX_PRIO      9u /* DMA Ch9 */
#define INTBSL_bSRC_QSPI_QSPI4_TX_ENA_BIT     0u
#define INTBSL_snSRC_QSPI_QSPI4_TX_REG        SRC_QSPI_QSPI4_TX

/* MSC0 uses DMA Ch10 for RX */
#define INTBSL_u8SRC_MSC_MSC0_SR1_TOS         3u /* TOS = DMA */
#define INTBSL_u16SRC_MSC_MSC0_SR1_PRIO       10u /* DMA Ch10 */
#define INTBSL_bSRC_MSC_MSC0_SR1_ENA_BIT      1u /* SRC Enabled at Init */
#define INTBSL_snSRC_MSC_MSC0_SR1_REG         SRC_MSC_MSC0_SR1

/* DSADC3 uses DMA Ch5 for save acquisitions */
#define INTBSL_u8SRC_DSADC_DSADC3_SRM_TOS     3u /* TOS = DMA */
#define INTBSL_u16SRC_DSADC_DSADC3_SRM_PRIO   5u /* DMA Ch5 */
#define INTBSL_bSRC_DSADC_DSADC3_SRM_ENA_BIT  0u
#define INTBSL_snSRC_DSADC_DSADC3_SRM_REG     SRC_DSADC_DSADC3_SRM

#endif /* ISR_CFG_H */

/*-------------------------------- end of file -------------------------------*/
