/**************************************************************************************************\
 ***
 *** Simulink model       : CSMT_CGMT07_2040_v3_0
 *** TargetLink subsystem : CSMT_CGMT07_2040_v3_0/F00_CordCluP
 *** Codefile             : tqsys_sdl10ms_clupcord_fct.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2010-08-25 14:00:18
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : disabled
 *** Share fcns between TL subsystems    : enabled
 *** Generate 64bit functions            : enabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : disabled
 *** Style definition file               : C:\dSPACE\Matlab\Tl\config\codegen\cconfig.xml
 *** Root style sheet                    : C:\dSPACE\Matlab\Tl\XML\CodeGen\Stylesheets\TL_CSourceCod
 ***                                       eSS.xsl
 *** Enable Multirate codegeneration     : disabled
 *** Add model checksum                  : disabled
 ***
 *** TargetLink version      : 3.0.1_RC3 from 13-May-2009
 *** Code generator version  : Build Id 3.0.1.7 from 2009-May-06 15:28:18
 *** Copyright (c) 2006 dSPACE GmbH
\**************************************************************************************************/

#ifndef _TQSYS_SDL10MS_CLUPCORD_FCT_H_
#define _TQSYS_SDL10MS_CLUPCORD_FCT_H_

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "tl_defines.h"
#include "tl_basetypes.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

#define COGBX_START_SEC_GLOBAL_16BIT
#include "CoGBx_MemMap.h"
/******************************************************************************\
   AR_IF_GLOBAL_16BIT: Global 16 bits for AUTOSAR modules | Width: 16
\******************************************************************************/
extern AR_IF_GLOBAL_16BIT UInt16 CoGBx_2040_Ext_rCluPHiFreq_in /*
   Unit       : %
   Description: Position de la commande d'embrayage
   LSB: 2^-4 OFF:  0 MIN/MAX:  0 .. 100 */;

#define COGBX_STOP_SEC_GLOBAL_16BIT
#include "CoGBx_MemMap.h"

#define COGBX_START_SEC_GLOBAL_BOOLEAN
#include "CoGBx_MemMap.h"

/******************************************************************************\
   AR_IF_GLOBAL_BOOLEAN: Global boolean for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_IF_GLOBAL_BOOLEAN Boolean Clu_bCluPedEng_out /*
   Description: Etat du capteur d'embrayage pour la structure couple
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_IF_GLOBAL_BOOLEAN Boolean Clu_bCluPedxVV_out /*
   Description: Etat du capteur d'embrayage pour la xVV
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_IF_GLOBAL_BOOLEAN Boolean Clu_bDrvTra_out /*
   Description: Etat de la chaine de traction
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_IF_GLOBAL_BOOLEAN Boolean CoGBx_2040_FRM_bAcvDrvTraInvld_in /*
   Description: Flag de reconfiguration dans le cas  dysfonctionnel
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

#define COGBX_STOP_SEC_GLOBAL_BOOLEAN
#include "CoGBx_MemMap.h"

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/******************************************************************************\
   AR_GLOBAL_FCN: Function class
\******************************************************************************/
extern Void TqSys_Sdl10ms_CluPCord_fct(Void);
extern Void TqSys_Sdl10ms_CluPCord_ini(Void);

/******************************************************************************\
   UserGlobalRestart: static function(s) (invisible for other modules)
\******************************************************************************/
extern Void CoGBx_2040_FctVarInit(Void);


#endif/*_TQSYS_SDL10MS_CLUPCORD_FCT_H_ */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
