
#ifndef _EOMGSL_004_CALIBRATIONS_H_
#define _EOMGSL_004_CALIBRATIONS_H_
#include "tl_defines.h"
#include "tl_basetypes.h"
#define EOMGSL_START_SEC_CALIB_16BIT
#include "EOMGsl_MemMap.h"
extern AR_MERGEABLE_CALIB_16BIT UInt16 EOM_tiTranMax_C;
#define EOMGSL_STOP_SEC_CALIB_16BIT
#include "EOMGsl_MemMap.h"
#define EOMGSL_START_SEC_CARTO_16BIT
#include "EOMGsl_MemMap.h"
extern AR_MERGEABLE_CARTO_16BIT UInt16 EOM_stCmdModCur_stTranTypX_A[21];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_stCmdModTar_stTranTypY_A[21];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiIgSysTranDly_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiInjPFuTranDly_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiInjTranDly_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiRmpIgSys_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiRmpInjSys_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiRmpPFu_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiRmpRateMixt_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiRmpTEx_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiRmpTarIdl_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiRmpTqRes_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiRmpVlvSys_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiTExTranDly_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiTRateMixtTranDly_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiTarIdlTranDly_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiTqResTranDly_T[12];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 EOM_tiVlvTranDly_T[12];
#define EOMGSL_STOP_SEC_CARTO_16BIT
#include "EOMGsl_MemMap.h"
#define EOMGSL_START_SEC_CARTO_8BIT
#include "EOMGsl_MemMap.h"
extern AR_MERGEABLE_CARTO_8BIT UInt8 EOM_stTranTyp_M[21][21];
#define EOMGSL_STOP_SEC_CARTO_8BIT
#include "EOMGsl_MemMap.h"
#define EOMGSL_START_SEC_INTERNAL_VAR_16BIT
#include "EOMGsl_MemMap.h"
extern AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiIgSysRmp;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiInjRmp;extern AR_INTERNAL_VAR_DISP_16BIT
 UInt16 EOM_tiPFuRmp;extern AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiRateMixtRmp;
extern AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiRmpIgSys;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiRmpInjSys;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiRmpPFu;extern AR_INTERNAL_VAR_DISP_16BIT
 UInt16 EOM_tiRmpRateMixt;extern AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiRmpTEx;
extern AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiRmpTarIdl;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiRmpTqRes;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiRmpVlvSys;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiTExRmp;extern AR_INTERNAL_VAR_DISP_16BIT
 UInt16 EOM_tiTarIdlRmp;extern AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiTqResRmp;
extern AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiTran;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 EOM_tiVlvRmp;
#define EOMGSL_STOP_SEC_INTERNAL_VAR_16BIT
#include "EOMGsl_MemMap.h"
#define EOMGSL_START_SEC_INTERNAL_VAR_8BIT
#include "EOMGsl_MemMap.h"
extern AR_INTERNAL_VAR_DISP_8BIT UInt8 EOM_stTranTyp;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_01_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_02_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_03_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_04_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_05_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_06_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_07_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_08_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_09_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_10_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_11_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_12_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_13_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_14_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_15_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_prm_facTranModNotSync_16_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_stCmbModCur_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_stCmbModReq_in;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 RE004_EOM_stCmbModTar_out;
#define EOMGSL_STOP_SEC_INTERNAL_VAR_8BIT
#include "EOMGsl_MemMap.h"
#define EOMGSL_START_SEC_INTERNAL_VAR_BOOLEAN
#include "EOMGsl_MemMap.h"
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EOM_bEnaCmbModChgNotDly;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EOM_bRmpTranEnd;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EOM_bRmpTranEndDly;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean RE004_EOM_bDiTran_in;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean RE004_EOM_bEnaCmbModChg_out;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean RE004_EOM_bFdoutModReq_in;
#define EOMGSL_STOP_SEC_INTERNAL_VAR_BOOLEAN
#include "EOMGsl_MemMap.h"
#endif

