/******************************************************************************/
/*                                                                            */
/* !Layer           : APPLI                                                   */
/*                                                                            */
/* !Component       : DCM_MANU                                                */
/* !Description     : DCM_MANU Component.                                     */
/*                                                                            */
/* !Module          : DCM_MANU                                                */
/* !Description     : interface du module  DCM_MANU                           */
/*                                                                            */
/* !File            : DCM_MANU_IM.H                                           */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : 32BIT                                                   */
/*                                                                            */
/* !Vendor          : Valeo VEMS                                              */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2008 VALEO                                                       */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* PVCS Information                                                           */
/* $Archive::   I:/PROJETS/EBX6_2/LOG/ASW/REF/MODULES/DCM_CONFIG/DCM_MANU_Im.$*/
/* $Revision::   1.0 $$Author::   pbakabad       $$Date::   22 May 2$  */
/* $Author::   pbakabad                          $$Date::   22 May 2$  */
/******************************************************************************/
#ifndef DCM_MANU_IM_H
#define DCM_MANU_IM_H

#include "DCM_CONFIG_im.h"

#endif /*DCM_MANU_IM_H */
/*-------------------------------- end of file -------------------------------*/
