/**************************************************************************************************\
 *** 
 *** Simulink model       : ProdElEng_07_2659_TL
 *** TargetLink subsystem : ProdElEng_07_2659_TL/ProdElEng_012
 *** Codefile             : prodeleng_012_calibrations.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2011-05-23 10:13:01
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : disabled
 *** Share fcns between TL subsystems    : enabled
 *** Generate 64bit functions            : enabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : enabled
 *** Style definition file               : C:\dSPACE30\Matlab\Tl\config\codegen\cconfig.xml
 *** Root style sheet                    : C:\dSPACE30\Matlab\Tl\XML\CodeGen\Stylesheets\TL_CSourceC
 ***                                       odeSS.xsl
 *** Enable Multirate codegeneration     : disabled
 *** Add model checksum                  : disabled
 ***
 *** TargetLink version      : 3.0.1 from 26-May-2009
 *** Code generator version  : Build Id 3.0.1.7 from 2009-May-06 15:28:18
 *** Copyright (c) 2006 dSPACE GmbH
\**************************************************************************************************/

#ifndef _PRODELENG_012_CALIBRATIONS_H_
#define _PRODELENG_012_CALIBRATIONS_H_

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "tl_defines.h"
#include "tl_basetypes.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

#define PRODELENG_START_SEC_CALIB_16BIT
#include "ProdElEng_MemMap.h"
/******************************************************************************\
   AR_MERGEABLE_CALIB_16BIT: Mergeable Calib 16 bits for AUTOSAR modules | Width: 16
\******************************************************************************/
extern AR_MERGEABLE_CALIB_16BIT UInt16 TqLimUH_grdVoltCtlDynMax_C /* 
   Unit       : (tr/min.N.m)/s
   Description: Saturation max de la variable de limitation dynamique max
   LSB: 250 OFF:  0 MIN/MAX:  1000 .. 125000 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 TqLimUH_grdVoltCtlDynMin_C /* 
   Unit       : (tr/min.N.m)/s
   Description: Saturation min de la variable de limitation dynamique max
   LSB: 2^7 OFF:  0 MIN/MAX:  1000 .. 125000 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 TqLimUH_tiDlyConstFrntTra1_C /* 
   Unit       : s
   Description: Temporisation de confirmation de la demande de boost pour la boite
   LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 10 */;
extern AR_MERGEABLE_CALIB_16BIT SInt16 TqLimUH_tqEngRealThdOfsBls_C /* 
   Unit       : N.m
   Description: Offset de seuil de couple CME pour sortie lestage
   LSB: 2^1 OFF:  0 MIN/MAX:  -100 .. 400 */;

#define PRODELENG_STOP_SEC_CALIB_16BIT
#include "ProdElEng_MemMap.h"

#define PRODELENG_START_SEC_CALIB_8BIT
#include "ProdElEng_MemMap.h"

/******************************************************************************\
   AR_MERGEABLE_CALIB_8BIT: Mergeable Calib 8 bits for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_MERGEABLE_CALIB_8BIT UInt8 TqLimUH_grdTqVoltCtlProt_C /* 
   Unit       : (tr/min.N.m)/s
   Description: Gradient de protection du Volt Control
   LSB: 2^0 OFF:  1 MIN/MAX:  1 .. 256 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 TqLimUH_rAccPThdOfsBls_C /* 
   Unit       : %
   Description: Offset de seuil de position pédale pour sortie lestage
   LSB: 2^-1 OFF:  0 MIN/MAX:  0 .. 100 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 TqLimUH_stEngRunVoltCtl_C /* 
   Unit       : -
   Description: Constante état moteur tournant
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 15 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 TqLimUH_stPwtRecup_C /* 
   Unit       : -
   Description: Constante état GMP UH à récupération
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 15 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 TqLimUH_stVoltCtlRecup_C /* 
   Unit       : -
   Description: Constante état Volt Control à récupération
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 7 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 TqLimUH_tiDlyAuthUnBls_C /* 
   Unit       : s
   Description: Temporisation de maintien du délastage après démarrage
   LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 25 */;

#define PRODELENG_STOP_SEC_CALIB_8BIT
#include "ProdElEng_MemMap.h"

#define PRODELENG_START_SEC_CALIB_BOOLEAN
#include "ProdElEng_MemMap.h"

/******************************************************************************\
   AR_MERGEABLE_CALIB_BOOLEAN: Mergeable Calib 1 bit for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_MERGEABLE_CALIB_BOOLEAN Boolean TqLimUH_bAcvGBxBlsInh_C /* 
   Description: Constante de configuration pour prise en compte de l'inhibition récupération BVA/BVM
   P
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

#define PRODELENG_STOP_SEC_CALIB_BOOLEAN
#include "ProdElEng_MemMap.h"

#define PRODELENG_START_SEC_CARTO_16BIT
#include "ProdElEng_MemMap.h"

/******************************************************************************\
   AR_MERGEABLE_CARTO_16BIT: Mergeable Carto 16 bits for AUTOSAR modules | Width: 16
\******************************************************************************/
extern AR_MERGEABLE_CARTO_16BIT SInt16 TqLimUH_nEngThdBlslX_A[6] /* 
   Unit       : tr/min
   Description: Points d'appuis en delta régime par rapport à la consigne ralenti des seuils de péda
   le et de couple
   LSB: 2^-2 OFF:  0 MIN/MAX:  -1000 .. 7000 */;
extern AR_MERGEABLE_CARTO_16BIT UInt16 TqLimUH_rAccPThdBls_T[6] /* 
   Unit       : %
   Description: Table des seuils de position pédale en-dessous duquel le lestage est autorisé
   LSB: 2^-9 OFF:  0 MIN/MAX:  0 .. 100 */;
extern AR_MERGEABLE_CARTO_16BIT SInt16 TqLimUH_tqEngRealThdBls_T[6] /* 
   Unit       : N.m
   Description: Table des seuils de couple CME en-dessous duquel le lestage est autorisé
   LSB: 2^1 OFF:  0 MIN/MAX:  -100 .. 400 */;

#define PRODELENG_STOP_SEC_CARTO_16BIT
#include "ProdElEng_MemMap.h"

#define PRODELENG_START_SEC_CARTO_8BIT
#include "ProdElEng_MemMap.h"

/******************************************************************************\
   AR_MERGEABLE_CARTO_8BIT: Mergeable Carto 8 bits for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_MERGEABLE_CARTO_8BIT UInt8 TqLimUH_bAcvCpl_A[4] /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CARTO_8BIT UInt8 TqLimUH_bAcvCpl_T[4] /* 
   Unit       : -
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_MERGEABLE_CARTO_8BIT UInt8 TqLimUH_noLdVoltCtlReqMax_M[2][7] /* 
   Description: Map de récupération Maximum Volt Control
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CARTO_8BIT UInt8 TqLimUH_noLdVoltCtlReq_M[2][7] /* 
   Unit       : -
   Description: Map des types de récupération Volt Control
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;

#define PRODELENG_STOP_SEC_CARTO_8BIT
#include "ProdElEng_MemMap.h"

#define PRODELENG_START_SEC_INTERNAL_VAR_16BIT
#include "ProdElEng_MemMap.h"

/******************************************************************************\
   AR_INTERNAL_VAR_DISP_16BIT: Display 16 bits for AUTOSAR modules | Width: 16
\******************************************************************************/
extern AR_INTERNAL_VAR_DISP_16BIT UInt16 TqLimUH_rAccPThdBls_MP /* 
   Unit       : %
   Description: seuils de position pédale en-dessous duquel le lestage est autorisé
   LSB: 2^-9 OFF:  0 MIN/MAX:  0 .. 100 */;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 TqLimUH_tqEngRealThdBls_MP /* 
   Unit       : N.m
   Description: seuils de couple CME en-dessous duquel le lestage est autorisé
   LSB: 2^1 OFF:  0 MIN/MAX:  -100 .. 400 */;

#define PRODELENG_STOP_SEC_INTERNAL_VAR_16BIT
#include "ProdElEng_MemMap.h"

#define PRODELENG_START_SEC_INTERNAL_VAR_32BIT

#include "ProdElEng_MemMap.h"

/******************************************************************************\
   AR_INTERNAL_VAR_DISP_32BIT: Display 32 bits for AUTOSAR modules | Width: 32
\******************************************************************************/
extern AR_INTERNAL_VAR_DISP_32BIT UInt32 TqLimUH_grdTqVoltCtlDyn_MP /* 
   Unit       : (RPM.N.m)/s
   Description: gradient de couple AR Volt Control adaptée
   LSB: 2^-11 OFF:  0 MIN/MAX:  0 .. 2097151.99951172 */;

#define PRODELENG_STOP_SEC_INTERNAL_VAR_32BIT

#include "ProdElEng_MemMap.h"

#define PRODELENG_START_SEC_INTERNAL_VAR_BOOLEAN
#include "ProdElEng_MemMap.h"

/******************************************************************************\
   AR_INTERNAL_VAR_DISP_BOOLEAN: Display Boolean for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TqLimUH_bAuthEngAcvRecup_MP /*
   Description: autorisation et activation de la récupération sous condition moteur et pédale d'accé
   lération */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TqLimUH_bEngBlsAuth /* 
   Unit       : -
   Description: Flag d'autorisation moteur de récupération Volt Control
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TqLimUH_bInhEngAcvRecup_MP /*
   Description: inhibition et activation de la récupération sous condition moteur et pédale d'accéle
   ration */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TqLimUH_bLdVoltCtlReq_MP /*
   Description: demande de contrôle de charge */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TqLimUH_bRecupUHAcv /* 
   Unit       : -
   Description: Flag indiquant récupération UH active 
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

#define PRODELENG_STOP_SEC_INTERNAL_VAR_BOOLEAN
#include "ProdElEng_MemMap.h"

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

#endif/*_PRODELENG_012_CALIBRATIONS_H_ */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
