/*******************************************************************************
*                           P. C. A.
*
*                    Peugeot Citroen Automobile
*
*        This file is the property of PCA. All rights are reserved
*        by PCA and this file must not be copied or disclosed
*       (in whole or in part) without prior written consent of PCA.
*
********************************************************************************
*
* %name: TPM_calibrations.h %
*
* %version: 3.0 %
*
* %date_modified: Mon Dec  3 09:47:28 2012 %
*
*
* %derived_by: u260001 %
* %release: EPflex/Vf %
* %full_filespec: TPM_calibrations.h-3.0:incl:2 %
*
*******************************************************************************/


#ifndef _TPM_CALIBRATIONS_H_
#define _TPM_CALIBRATIONS_H_
#include "tl_defines.h"
#include "tl_basetypes.h"
#define TPM_START_SEC_CALIB_16BIT
#include "TPM_MemMap.h"
extern AR_MERGEABLE_CALIB_16BIT UInt16 PhyMSI_cppExMnf_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 PhyMSI_cppTrbCase_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 PhyMSI_pwrCylHdEstimIni_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 PhyMSI_rCppExMnf_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 PhyMSI_rCppTrbCase_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 PhyMSI_tiExMnfThd_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 PhyMSI_tiTrbCaseThd_C;extern 
AR_MERGEABLE_CALIB_16BIT SInt16 TPM_agIgMinThermoOfs_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_facCorTWCSt_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_facEOxdEmiGsl_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_facFilFacCorProtComp_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_facFilTExBasReq_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_facFildeltaTExoScvMax_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_facStoichGsl_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_mfAirScvLimMaxHcLdTWC_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_mfAirScvMax_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_mfAirScvUnLim_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_mfSelAirScvLimMaxCor_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_mfSelMfAirScvLimMax_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_rAirLdMax_C;extern AR_MERGEABLE_CALIB_16BIT 
UInt16 TPM_rMixtMaxInhOvb_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_rMixtProtOxdTWCMin_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_rMixtTWCStMax_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 TPM_rMixtTWCStMin_C;
extern AR_MERGEABLE_CALIB_16BIT UInt16 TPM_rMixtThdTWCHcFull_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_rMixtThdTWCO2Full_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_rSelRatMixtMaxAflScv_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tBypReg_C;extern AR_MERGEABLE_CALIB_16BIT 
UInt16 TPM_tDeltaLamDev1_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tDeltaLamDev2_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tDeltaLamDev3_C;
extern AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tDeltaLamDev4_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tDeltaLamTWC1_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tDeltaLamTWC2_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tDeltaLamTWC3_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tDeltaTDevMaxLihTEx_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tEcpHeatProtDelta_C;extern 
AR_MERGEABLE_CALIB_16BIT SInt16 TPM_tEgOplOfsReqAirLdDev1_C;extern 
AR_MERGEABLE_CALIB_16BIT SInt16 TPM_tEgOplOfsReqAirLdDev2_C;extern 
AR_MERGEABLE_CALIB_16BIT SInt16 TPM_tEgOplOfsReqAirLdDev3_C;extern 
AR_MERGEABLE_CALIB_16BIT SInt16 TPM_tEgOplOfsReqAirLdDev4_C;extern 
AR_MERGEABLE_CALIB_16BIT SInt16 TPM_tEgOplOfsReqRlamDev1_C;extern 
AR_MERGEABLE_CALIB_16BIT SInt16 TPM_tEgOplOfsReqRlamDev2_C;extern 
AR_MERGEABLE_CALIB_16BIT SInt16 TPM_tEgOplOfsReqRlamDev3_C;extern 
AR_MERGEABLE_CALIB_16BIT SInt16 TPM_tEgOplOfsReqRlamDev4_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tExNotReq_C;extern AR_MERGEABLE_CALIB_16BIT 
UInt16 TPM_tHysRbl_C;extern AR_MERGEABLE_CALIB_16BIT SInt16 
TPM_tIniIntRegThermoProt_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tMaxDeltaHysAirLdLim_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tMaxDeltaHys_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxDev1Delta_C;
extern AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxDev2Delta_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxDev3Delta_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxDev4Delta_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxOxdTWCScvMax_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxRichCutOffTWC_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxStoichTWC1Delta_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxStoichTWC2Delta_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxStoichTWC3Delta_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxStoichTWC_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxTWC1Delta_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxTWC2Delta_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tMaxTWC3Delta_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tOxdTWCSelCutOff_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tRefTWC_C;extern AR_MERGEABLE_CALIB_16BIT 
SInt16 TPM_tSatMaxInt_C;extern AR_MERGEABLE_CALIB_16BIT SInt16 TPM_tSatMinInt_C;
extern AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tSelTCurThermoProtDev_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tSelTRefTWCScvMax_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tSelTTWC_C;extern AR_MERGEABLE_CALIB_16BIT 
UInt16 TPM_tSelTTarThermoProtDev_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tThdTWCSt_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tiLimScvTmp_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tiRichScvTmp_C;extern 
AR_MERGEABLE_CALIB_16BIT UInt16 TPM_tiScvTmp_C;extern AR_MERGEABLE_CALIB_16BIT 
UInt16 TPM_tiSdlTPM_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev1ThermoProt_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev1TmpAirLd_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev1Tmp_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev2ThermoProt_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev2TmpAirLd_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev2Tmp_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev3ThermoProt_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev3TmpAirLd_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev3Tmp_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev4ThermoProt_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev4TmpAirLd_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxDev4Tmp_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxStoichTWC1Tmp_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxStoichTWC2Tmp_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxStoichTWC3Tmp_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxTWC1ThermoProt_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxTWC1TmpAirLd_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxTWC1Tmp_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxTWC2ThermoProt_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxTWC2TmpAirLd_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxTWC2Tmp_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxTWC3ThermoProt_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxTWC3TmpAirLd_C;extern AR_MERGEABLE_CALIB_16BIT UInt16 
TPM_tiTMaxTWC3Tmp_C;
#define TPM_STOP_SEC_CALIB_16BIT
#include "TPM_MemMap.h"
#define TPM_START_SEC_CALIB_32BIT
#include "TPM_MemMap.h"
extern AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampDecDev1_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampDecDev2_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampDecDev3_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampDecDev4_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampDecTWC1_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampDecTWC2_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampDecTWC3_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampDec_C;extern AR_MERGEABLE_CALIB_32BIT
 UInt32 TPM_facRampIncDev1_C;extern AR_MERGEABLE_CALIB_32BIT UInt32 
TPM_facRampIncDev2_C;extern AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampIncDev3_C
;extern AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampIncDev4_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampIncTWC1_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampIncTWC2_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampIncTWC3_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_facRampInc_C;extern AR_MERGEABLE_CALIB_32BIT
 UInt32 TPM_lamThdCutOff_C;extern AR_MERGEABLE_CALIB_32BIT UInt32 
TPM_lamThdSelCutOff_C;extern AR_MERGEABLE_CALIB_32BIT UInt32 TPM_mfAirScvOfs_C;
extern AR_MERGEABLE_CALIB_32BIT UInt32 TPM_mfAirScvThdSelCutOff_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_tMaxDev1_C;extern AR_MERGEABLE_CALIB_32BIT 
UInt32 TPM_tMaxDev2Step2_C;extern AR_MERGEABLE_CALIB_32BIT UInt32 
TPM_tMaxDev2Step3_C;extern AR_MERGEABLE_CALIB_32BIT UInt32 TPM_tMaxDev2_C;extern
 AR_MERGEABLE_CALIB_32BIT UInt32 TPM_tMaxDev3Step2_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_tMaxDev3Step3_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_tMaxDev3_C;extern AR_MERGEABLE_CALIB_32BIT 
UInt32 TPM_tMaxDev4_C;extern AR_MERGEABLE_CALIB_32BIT UInt32 
TPM_tMaxStoichTWC1_C;extern AR_MERGEABLE_CALIB_32BIT UInt32 TPM_tMaxStoichTWC2_C
;extern AR_MERGEABLE_CALIB_32BIT UInt32 TPM_tMaxStoichTWC3_C;extern 
AR_MERGEABLE_CALIB_32BIT UInt32 TPM_tMaxTWC1_C;extern AR_MERGEABLE_CALIB_32BIT 
UInt32 TPM_tMaxTWC2_C;extern AR_MERGEABLE_CALIB_32BIT UInt32 TPM_tMaxTWC3_C;
#define TPM_STOP_SEC_CALIB_32BIT
#include "TPM_MemMap.h"
#define TPM_START_SEC_CALIB_8BIT
#include "TPM_MemMap.h"
extern AR_MERGEABLE_CALIB_8BIT UInt8 PhyMSI_rAirRatExMnf_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 PhyMSI_rAirRatTrbCase_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 PhyMSI_rCoRatExMnf_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 PhyMSI_rCoRatTrbCase_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_concO2Air_C;extern AR_MERGEABLE_CALIB_8BIT 
UInt8 TPM_idxSelTEgDev1_C;extern AR_MERGEABLE_CALIB_8BIT UInt8 
TPM_idxSelTEgDev2_C;extern AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTEgDev3_C;
extern AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTEgDev4_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTEgTWC1_C;extern AR_MERGEABLE_CALIB_8BIT
 UInt8 TPM_idxSelTEgTWC2_C;extern AR_MERGEABLE_CALIB_8BIT UInt8 
TPM_idxSelTEgTWC3_C;extern AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTEgTWCInp_C;
extern AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTEgTWCScvMax_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTWallDev1_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTWallDev2_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTWallDev3_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTWallDev4_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTWallTWC1_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTWallTWC2_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTWallTWC3_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_idxSelTWallTWCScvMax_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_mAirMol_C;extern AR_MERGEABLE_CALIB_8BIT UInt8
 TPM_noSelAcvThermoProtDev_C;extern AR_MERGEABLE_CALIB_8BIT UInt8 
TPM_rSelRatAirLdReqRbl_C;extern AR_MERGEABLE_CALIB_8BIT UInt8 
TPM_rSelRatAirLdReq_C;extern AR_MERGEABLE_CALIB_8BIT UInt8 
TPM_rSelRatLdProtExThermo_C;extern AR_MERGEABLE_CALIB_8BIT UInt8 
TPM_stSelStO2HcStgTWC_C;extern AR_MERGEABLE_CALIB_8BIT UInt8 TPM_stTWCRbl2_C;
extern AR_MERGEABLE_CALIB_8BIT UInt8 TPM_stTWCRbl3_C;extern 
AR_MERGEABLE_CALIB_8BIT UInt8 TPM_stTWCRbl_C;extern AR_MERGEABLE_CALIB_8BIT 
UInt8 TPM_uLsDsMesThdTWCHcFull_C;extern AR_MERGEABLE_CALIB_8BIT UInt8 
TPM_uLsDsMesThdTWCO2Full_C;
#define TPM_STOP_SEC_CALIB_8BIT
#include "TPM_MemMap.h"
#define TPM_START_SEC_CALIB_BOOLEAN
#include "TPM_MemMap.h"
extern AR_MERGEABLE_CALIB_BOOLEAN Boolean PhyMSI_bAcvPCylMax_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean PhyMSI_bAcvPwrCylHd_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean PhyMSI_bAcvTExMnf_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean PhyMSI_bAcvTTrbCase_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvAirLdDev1Tmp_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvAirLdDev2Tmp_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvAirLdDev3Tmp_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvAirLdDev4Tmp_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvAirLdTWC1Tmp_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvAirLdTWC2Tmp_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvAirLdTWC3Tmp_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvBypReg_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvDev1EcpHeatProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvDev2EcpHeatProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvDev3EcpHeatProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvDev4EcpHeatProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvGas_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvHisTWCCutOff_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvNotAgIgMin_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvProtLimScv_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvR1234Mg_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvRichLimScv_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvRichScvThermoInvld_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvSelAcvProtExScv_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvSelAirLdLimTExMgr_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvSelExThermoProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvSelRichLimScv_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvSelRichProtOxdTWC_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvSelRichThermoProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvStTWCCutOff_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvStTWCSelCutOff_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvTPReqNotAuth_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvTWC1EcpHeatProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvTWC2EcpHeatProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvTWC2_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvTWC3EcpHeatProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bAcvTWC3_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bEnaHldIntReg_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bEnaIniAirLdChgDev_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bEnaIniAirLdFall_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bEnaIniInt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bEnaIniRichChgDev_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bInhIniRichRise_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bInhIniWiPropAct_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bInhSelInhInjCutOff_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bInhSelInhInjSelCutOff_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bInhSelInhOvbReq_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bInhStTWCRbl_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelAcvProtExScv_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelAcvRichProtOxdTWC_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelAcvRichThermoProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelAirLdLimTExMgr_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelAirScvLimMaxCor_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelExThermoProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelInhInjCutOff_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelInhInjSelCutOff_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelInhOvbReq_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelMfAirScvLimMax_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelNbAcvThermoProtDev_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelRatAirLdReqRbl_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelRatAirLdReq_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelRatLdProtExThermo_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelRatMixtMaxAflScv_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelRichLimScv_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelStO2HcStgTWC_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTCurThermoProtDev_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTRefTWCScvMax_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTTWC_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTTarThermoProtDev_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTWallCritDev2_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTWallCritDev3_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTWallDev1_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTWallDev2_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTWallDev3_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTWallDev4_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTWallTWC1_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTWallTWC2_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTWallTWC3_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bSelTWallTWCScvMax_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bTWC1StoichEcpHeatProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bTWC2StoichEcpHeatProt_C;extern 
AR_MERGEABLE_CALIB_BOOLEAN Boolean TPM_bTWC3StoichEcpHeatProt_C;
#define TPM_STOP_SEC_CALIB_BOOLEAN
#include "TPM_MemMap.h"
#define TPM_START_SEC_CARTO_16BIT
#include "TPM_MemMap.h"
extern AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_facEgExMnfHeatExg_T[8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_facEgTrbCaseHeatExg_T[8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_facExtExMnfHeatExg_M[8][10];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_facExtTrbCaseHeatExg_M[8][10];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_nEng_pCylMaxY_A[20];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_nEng_pwrCylHdY_A[20];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_pwrCylHdEstim_M[16][20];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_rMixtCylPwrHd_A[8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_spdVeh_facExtExMnfY_A[10];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_spdVeh_facExtTrbCaseY_A[10];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_tAir_tExMnfIniY_A[10];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_tAir_tTrbCaseIniY_A[10];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_tDeltaExMnfIni_M[8][10];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 PhyMSI_tDeltaTrbCaseIni_M[8][10];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_cppEg_T[8];extern AR_MERGEABLE_CARTO_16BIT 
UInt16 TPM_facIgCorGsl_M[6][9];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facIntCoefAirLdDev1_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facIntCoefAirLdDev2_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facIntCoefAirLdDev3_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facIntCoefAirLdDev4_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facIntCoefRlamDev1_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facIntCoefRlamDev2_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facIntCoefRlamDev3_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facIntCoefRlamDev4_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facPropCoefAirLdDev1_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facPropCoefAirLdDev2_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facPropCoefAirLdDev3_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facPropCoefAirLdDev4_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facPropCoefRlamDev1_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facPropCoefRlamDev2_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facPropCoefRlamDev3_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_facPropCoefRlamDev4_M[6][8];extern AR_MERGEABLE_CARTO_16BIT UInt16 
TPM_mfTotExCorY_A[9];extern AR_MERGEABLE_CARTO_16BIT UInt16 TPM_nEng18X_A[18];
extern AR_MERGEABLE_CARTO_16BIT UInt16 TPM_nEngRblX_A[16];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_nEngTEgOpl_A[6];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_nEngconcO2EgCmb_A[8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_rAirLdCorTEgOpl_A[8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_rAirLdCorconcO2EgCmb_A[8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_rAirLdLimRbl_T[16];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_rAirLdMaxRbl_T[16];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_rAirLdReqFlex_M[18][16];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_rAirLdReqMid_M[18][16];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_rMixtCyl_mEgCmbMol_A[8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_rMixtIniThermoProt_A[11];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_rMixtconcO2EgCmb_A[8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_rMixtconcO2EgTotLimMax_A[8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_rStatIgSpEfcX_A[6];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_tEgOplReqAirLdDev1_T[6];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_tEgOplReqAirLdDev2_T[6];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_tEgOplReqAirLdDev3_T[6];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_tEgOplReqAirLdDev4_T[6];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_tEgOplReqRlamDev1_M[6][8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_tEgOplReqRlamDev2_M[6][8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_tEgOplReqRlamDev3_M[6][8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_tEgOplReqRlamDev4_M[6][8];extern 
AR_MERGEABLE_CARTO_16BIT UInt16 TPM_tEg_A[8];extern AR_MERGEABLE_CARTO_16BIT 
UInt16 TPM_tTWCconcO2EgTotLimMax_A[8];
#define TPM_STOP_SEC_CARTO_16BIT
#include "TPM_MemMap.h"
#define TPM_START_SEC_CARTO_32BIT
#include "TPM_MemMap.h"
extern AR_MERGEABLE_CARTO_32BIT UInt32 PhyMSI_facPwrCylHdCor_T[8];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 PhyMSI_mfEg_facEgExMnf_A[8];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 PhyMSI_mfEg_facEgTrbCase_A[8];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 PhyMSI_pCylMaxEstim_M[16][20];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 PhyMSI_rAirLd_pCylMaxX_A[16];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 PhyMSI_rAirLd_pwrCylHdX_A[16];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 PhyMSI_tiEngStop_tExMnfIniX_A[8];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 PhyMSI_tiEngStop_tTrbCaseIniX_A[8];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 TPM_facEgEstimRlamIni_M[11][9];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 TPM_facPresAltiCorX_A[16];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 TPM_facPresAltiCor_T[16];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 TPM_facSqrtAirMfScvLimMax_A[29];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 TPM_facSqrtAirMfScvLimMax_T[29];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 TPM_mfEgTotAirEstim_A[9];extern 
AR_MERGEABLE_CARTO_32BIT UInt32 TPM_tExBasReqY_A[16];
#define TPM_STOP_SEC_CARTO_32BIT
#include "TPM_MemMap.h"
#define TPM_START_SEC_CARTO_8BIT
#include "TPM_MemMap.h"
extern AR_MERGEABLE_CARTO_8BIT UInt8 PhyMSI_rSpdFan_facExtExMnfX_A[8];extern 
AR_MERGEABLE_CARTO_8BIT UInt8 PhyMSI_rSpdFan_facExtTrbCaseX_A[8];extern 
AR_MERGEABLE_CARTO_8BIT UInt8 TPM_concO2EgCmb_M[8][8];extern 
AR_MERGEABLE_CARTO_8BIT UInt8 TPM_concO2EgTotLimMax_M[8][8];extern 
AR_MERGEABLE_CARTO_8BIT UInt8 TPM_facconcO2EgCmbCor_T[8];extern 
AR_MERGEABLE_CARTO_8BIT UInt8 TPM_idxGrpDevCll_T[7];extern 
AR_MERGEABLE_CARTO_8BIT UInt8 TPM_idxGrpDevOpl_T[7];extern 
AR_MERGEABLE_CARTO_8BIT UInt8 TPM_mEgCmbMol_T[8];extern AR_MERGEABLE_CARTO_8BIT 
UInt8 TPM_noDevCll_A[7];extern AR_MERGEABLE_CARTO_8BIT UInt8 TPM_noDevOpl_A[7];
#define TPM_STOP_SEC_CARTO_8BIT
#include "TPM_MemMap.h"
#define TPM_START_SEC_INTERNAL_VAR_16BIT
#include "TPM_MemMap.h"
extern AR_INTERNAL_VAR_DISP_16BIT UInt16 PhyMSI_tExMnfEstimPrev;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 PhyMSI_tTrbCaseEstimPrev;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 RE002_TPM_mfAirScvLimMax_out;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 RE002_TPM_tRefTWCScvMax_out;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 RE003_TPM_tExCurAcvThermoProtDev_out;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 RE003_TPM_tTWC_out;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 RE004_TPM_rAirLdReqRbl_out;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 RE007_TPM_rAirLdReq_out;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_concO2EgCmb;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_fac1AirMfScvLimMax_MP;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_facIntCoefAirLdSel;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_facIntCoefRlamSel;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_facIntCoefRun;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_facPropCoefAirLdSel;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_facPropCoefRlamSel;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_facPropCoefRun;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_mfAirScvLimMaxConcO2lim;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_mfAirScvLimMaxHcLd;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_mfAirScvLimMaxIvsMdlTWC;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_prm_agIgKnkSatMax_MP[6];extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_rAirLdReqFlex;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_rAirLdReqMid;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_rMixtTWCSt;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tAddCmdCll;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tAddCmdOpl;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tDeltaLamDev1Tar;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tDeltaLamDev2Tar;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tDeltaLamDev3Tar;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tDeltaLamDev4Tar;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tDeltaLamTWC1Tar;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tDeltaLamTWC2Tar;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tDeltaLamTWC3Tar;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tDeltaTExoScvTWCAuth_MP;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tDev1;extern AR_INTERNAL_VAR_DISP_16BIT 
UInt16 TPM_tDev2;extern AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tDev3;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tDev4;extern AR_INTERNAL_VAR_DISP_16BIT 
SInt16 TPM_tDifMin_MP;extern AR_INTERNAL_VAR_DISP_16BIT UInt16 
TPM_tEgOplReqAirLdSel;extern AR_INTERNAL_VAR_DISP_16BIT UInt16 
TPM_tEgOplReqRlamSel;extern AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tEgTWCInp;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tExDev1Delta;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tExDev1Delta_MP;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tExDev2Delta;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tExDev2Delta_MP;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tExDev3Delta;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tExDev3Delta_MP;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tExDev4Delta;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tExDev4Delta_MP;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tExReqPrev;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tExTWC1Delta;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tExTWC2Delta;extern 
AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tExTWC3Delta;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tIniAirLdIntReg;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tIniRichIntReg;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tTWC1;extern AR_INTERNAL_VAR_DISP_16BIT 
SInt16 TPM_tTWC1Delta_MP;extern AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tTWC2;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 TPM_tTWC2Delta_MP;extern 
AR_INTERNAL_VAR_DISP_16BIT UInt16 TPM_tTWC3;extern AR_INTERNAL_VAR_DISP_16BIT 
SInt16 TPM_tTWC3Delta_MP;
#define TPM_STOP_SEC_INTERNAL_VAR_16BIT
#include "TPM_MemMap.h"
#define TPM_START_SEC_INTERNAL_VAR_32BIT
#include "TPM_MemMap.h"
extern AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_fac2AirMfScvLimMax_MP;extern 
AR_INTERNAL_VAR_DISP_32BIT SInt32 TPM_fac3AirMfScvLimMax_MP;extern 
AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_mfAirScvLimMaxAfrScv_MP;extern 
AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_rAirLdGslFlex_MP;extern 
AR_INTERNAL_VAR_DISP_32BIT SInt32 TPM_tActIntCmd;extern 
AR_INTERNAL_VAR_DISP_32BIT SInt32 TPM_tActPropCmd;extern 
AR_INTERNAL_VAR_DISP_32BIT SInt32 TPM_tAddIntRun_MP;extern 
AR_INTERNAL_VAR_DISP_32BIT SInt32 TPM_tCurIntRun_MP;extern 
AR_INTERNAL_VAR_DISP_32BIT SInt32 TPM_tErrCmdReg;extern 
AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tExBasReq;extern 
AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tExBasReqStep1_MP;extern 
AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tExDev1;extern AR_INTERNAL_VAR_DISP_32BIT 
UInt32 TPM_tExDev2;extern AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tExDev3;extern 
AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tExDev4;extern AR_INTERNAL_VAR_DISP_32BIT 
UInt32 TPM_tExTWC1;extern AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tExTWC2;extern 
AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tExTWC3;extern AR_INTERNAL_VAR_DISP_32BIT 
SInt32 TPM_tIniIntRegThermoProt;extern AR_INTERNAL_VAR_DISP_32BIT UInt32 
TPM_tMaxDev1;extern AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tMaxDev2;extern 
AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tMaxDev3;extern AR_INTERNAL_VAR_DISP_32BIT
 UInt32 TPM_tMaxDev4;extern AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tMaxStoichTWC1
;extern AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tMaxStoichTWC2;extern 
AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tMaxStoichTWC3;extern 
AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tMaxTWC1;extern AR_INTERNAL_VAR_DISP_32BIT
 UInt32 TPM_tMaxTWC2;extern AR_INTERNAL_VAR_DISP_32BIT UInt32 TPM_tMaxTWC3;
#define TPM_STOP_SEC_INTERNAL_VAR_32BIT
#include "TPM_MemMap.h"
#define TPM_START_SEC_INTERNAL_VAR_8BIT
#include "TPM_MemMap.h"
extern AR_INTERNAL_VAR_DISP_8BIT UInt8 RE003_TPM_noAcvThermoProtDev_out;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 TPM_concO2EgTotLimMaxReq;extern 
AR_INTERNAL_VAR_DISP_8BIT UInt8 TPM_mEgCmbMol;extern AR_INTERNAL_VAR_DISP_8BIT 
UInt8 TPM_noAcvThermoProtDevSelCll;extern AR_INTERNAL_VAR_DISP_8BIT UInt8 
TPM_noAcvThermoProtDevSelOpl;
#define TPM_STOP_SEC_INTERNAL_VAR_8BIT
#include "TPM_MemMap.h"
#define TPM_START_SEC_INTERNAL_VAR_BOOLEAN
#include "TPM_MemMap.h"
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean RE004_TPM_bAcvProtExScv_out;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvCllRegClc;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvDsTmpTMaxRichDev1_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvDsTmpTMaxRichDev2_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvDsTmpTMaxRichDev3_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvDsTmpTMaxRichDev4_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvDsTmpTMaxRichTWC1_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvDsTmpTMaxRichTWC2_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvDsTmpTMaxRichTWC3_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvReg;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvRichProtOxdTWC1;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvRichProtOxdTWC1T_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvRichProtOxdTWC1_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvRichProtOxdTWC2;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvRichProtOxdTWC2T_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvRichProtOxdTWC2_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvRichProtOxdTWC3;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvRichProtOxdTWC3T_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvRichProtOxdTWC3_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvTMaxRichDev1_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvTMaxRichDev2_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvTMaxRichDev3_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvTMaxRichDev4_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvTMaxRichTWC1_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvTMaxRichTWC2_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAcvTMaxRichTWC3_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAfterTiScvTmp_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimDev1;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimDev1UsTmp_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimDev2;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimDev2UsTmp_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimDev3;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimDev3UsTmp_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimDev4;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimDev4UsTmp_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimTWC1;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimTWC1UsTmp_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimTWC2;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimTWC2UsTmp_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimTWC3;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bAirLdLimTWC3UsTmp_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bBfTiScvTmp_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bEnaSpcIniIntReg;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bExThermoProtDev1;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bExThermoProtDev2;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bExThermoProtDev3;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bExThermoProtDev4;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bExThermoProtTWC1;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bExThermoProtTWC2;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bExThermoProtTWC3;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bHldIntRegThermoProt;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bLimMaxInt;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bLimMinInt;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bMaxRichStO2HcLdTWCOk_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bMaxRichTWC_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bMaxStoichTWC_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bNotAgIgMin;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bRichDev1;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bRichDev2;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bRichDev3;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bRichDev4;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bRichLimScvCor;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bRichScvIn_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bRichScvThermoInvldCor;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bRichTWC1;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bRichTWC2;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bRichTWC3;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bSelTIniIntReg;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxDeltaHysRichDev1_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxDeltaHysRichDev2_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxDeltaHysRichDev3_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxDeltaHysRichDev4_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxDeltaHysRichTWC1_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxDeltaHysRichTWC2_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxDeltaHysRichTWC3_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxRAirLdLimDev1_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxRAirLdLimDev3_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxRAirLdLimDev4_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxRAirLdLimTWC1_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxRAirLdLimTWC2_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTMaxRAirLdLimTWC3_MP;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTWCHcFullSt;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bTWCO2FullSt;extern 
AR_INTERNAL_VAR_DISP_BOOLEAN Boolean TPM_bThermoProtReqNotAuth;
#define TPM_STOP_SEC_INTERNAL_VAR_BOOLEAN
#include "TPM_MemMap.h"
#endif

