/***************************** <AUTO_FILE_HEADER> *****************************/
/*                                                                            */
/* !Layer           : SWC Layer                                               */
/*                                                                            */
/* !Component       : FISA                                                 */
/* !Component       : FISASoftware Component                               */
/*                                                                            */
/* !Module          : FISA                                                 */
/*                                                                            */
/* !File            : FISA_nvm.c                                           */
/*                                                                            */
/* !Target          : All (optimized for "Generic->Custom")                   */
/*                                                                            */
/* !Vendor          : Valeo                                                   */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2008 VALEO                                                       */
/* all rights reserved                                                        */
/*                                                                            */
/**************************** </AUTO_FILE_HEADER> *****************************/
/* PVCS Information                                                           */
/* $Archive:   P:/ACT_EMS/LOG/REF/SWC_VEMS/PSA/SWC-TURBO/FISA/5-SOFT-LIV/FISA_nvm.c_v  $*/
/* $Revision:   1.0  $*/
 /*$Author:   adelvare  $*/
 /*****************************************************************************/
/*                   File generated by an automatic coding tool               */
/**************************** </AUTO_FILE_HEADER> *****************************/

/***************************** <NEEDED INCLUSION> *****************************/
#include "FISA_nvm.h"

/****************************** <DATA STRUCTURE> ******************************/
#define FISA_START_SEC_VAR_SAVED_ZONE1_CONST_8BIT
#include "FISA_MemMap.h"
VAR(FISA_stNV_Z1_CST_8BIT_1, AUTOMATIC) FISA_sNV_Z1_CST_8BIT_1;
#define FISA_STOP_SEC_VAR_SAVED_ZONE1_CONST_8BIT
#include "FISA_MemMap.h"

/************************* <RECOVERY DATA STRUCTURE> **************************/
#define FISA_START_SEC_VAR_SAVED_RECOVERY_ZONE1_CONST_8BIT
#include "FISA_MemMap.h"
CONST(FISA_stNV_Z1_CST_8BIT_1, AUTOMATIC) FISA_sNV_Z1_CST_8BIT_1_r = {
  /* Constants for variable: FISA_facAdp_NV */
  0
};
#define FISA_STOP_SEC_VAR_SAVED_RECOVERY_ZONE1_CONST_8BIT
#include "FISA_MemMap.h"

