/******************************************************************************/
/*                                                                            */
/* !Layer           : APPLI                                                   */
/*                                                                            */
/* !Component       : RND                                                   */
/* !Description     : RND Component.                                        */
/*                                                                            */
/* !Module          : RND                                                   */
/* !Description     : interface du module  RND                              */
/*                                                                            */
/* !File            : RND_IM.H                                              */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : 32BIT                                                   */
/*                                                                            */
/* !Vendor          : Valeo VEMS                                              */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2008 VALEO                                                       */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* PVCS Information                                                           */
/* $Archive::   P:/EBx6_2/LOG/ASW/Ref/Main/CONFIG/IMPORT_CONFIG/RND_IM.H_v $*/
/* $Revision::   1.0      $$Author::   fsanchez2     $$Date::   04 Mar 2014 1$*/
/* $Author::   fsanchez2                             $$Date::   04 Mar 2014 1$*/
/******************************************************************************/
#ifndef RND_IM_H
#define RND_IM_H
   #include "ADCHAL.H"
   #include "FRM.h"
   #include "GPT.H"
   #include "NOPROD.h"
   #include "NVMSRV.h"

   #include "vems.h"
#endif  /*RND_IM_H*/
/*-------------------------------- end of file -------------------------------*/
