/******************************************************************************/
/*                                                                            */
/* !Layer           : APPLI                                                   */
/*                                                                            */
/* !Component       : PWR                                                     */
/* !Description     : archi PWR Component.                                    */
/*                                                                            */
/* !Module          : PWR                                                     */
/* !Description     : interface du module PWR                                 */
/*                                                                            */
/* !File            : VSSNWDMTRACV_IM.H                                       */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : 32BIT                                                   */
/*                                                                            */
/* !Vendor          : Valeo VEMS                                              */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2008 VALEO                                                       */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* PVCS Information                                                           */
/* $Archive::   P:/EBx6_2/LOG/ASW/Ref/Main/CONFIG/IMPORT_CONFIG/VSSNWDMTRACV_IM.H_v $*/
/* $Revision::   1.0      $$Author::   croche2       $$Date::   11 Jun 2014 1$*/
/* $Author::   croche2                               $$Date::   11 Jun 2014 1$*/
/******************************************************************************/
#ifndef VSSNWDMTRACV_IM_H
#define VSSNWDMTRACV_IM_H

#include "NOPROD.H"

#include "CTRLCFG.H"
#include "CKMNGIF.H"

#include "FRM.H"
#include "GDGAR.H"      /* non inclut dans PWRSEN_ACQ */
#include "SWFAIL.H"     /* non inclut dans PWRSEN_ACQ */
#include "VEHST.h"

/* LDB */
#include "ADCHAL.H" /* nom inclut dans PWRSEN_ACQ */

#endif  /*VSSNWDMTRACV_IM_H*/
/*-------------------------------- end of file -------------------------------*/