/******************************************************************************/
/* !Layer           : HAL                                                     */
/* !Component       : CRKHAL                                                  */
/* !Description     : Crankshaft Driver                                       */
/*                                                                            */
/* !File            : CRKHAL_Cfg.h                                            */
/* !Description     : CRKHAL configuration                                    */
/*                                                                            */
/* !Reference       :                                                         */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT VALEO all rights reserved                                        */
/******************************************************************************/
/** 11/10/14, 10:16:14: generated by Genecode v2.6.0.0                        */
/******************************************************************************/

#ifndef CRKHAL_CFG_H
#define CRKHAL_CFG_H

#include "Std_Types.h"
#include "Std_Limits.h"

#include "CAMHAL.h"
#include "CRKHAL_Typ.h"
#include "CRKHAL_CFG_I.h"
#include "CRKHAL_I.h"
#include "CRKHAL.h"
#include "IfxGtm_Typ.h"
#include "KRN_BSW.h"

/******************************************************************************/
/* DEFINES                                                                    */
/******************************************************************************/
/* !MComment: Defines for CRKHAL port pin                                     */
#define CRKHAL_udtCRKHAL_CH (DioConf_DioChannel_M_ENG_CRK_SPD_ACTIVE_SGN) 

/* !MComment: Defines for all CRKHAL alarm channels                           */
#define CRKHAL_u8ALARM_ANGSCHED_1   0
#define CRKHAL_u8ALARM_ANGSCHED_2   1
#define CRKHAL_u8ALARM_COIL_A_CMD   2
#define CRKHAL_u8ALARM_COIL_B_CMD   3
#define CRKHAL_u8ALARM_COIL_C_CMD   4
#define CRKHAL_u8ALARM_IGN_REF_TEETH   5
#define CRKHAL_u8ALARM_INJ_1_ANGLE   6
#define CRKHAL_u8ALARM_INJ_2_ANGLE   7
#define CRKHAL_u8ALARM_INJ_3_ANGLE   8
#define CRKHAL_u8ALARM_KNW_SAMPLING_WIN   9
#define CRKHAL_u8ALARM_SPILL_EVENT_ANGLE   10
#define CRKHAL_u8ALARM_M_CMD_GDI_PMP_ANGLE   11
#define CRKHAL_u8ALARM_IT_1_4_TDC   12
#define CRKHAL_u8ALARM_PTMHAL   13
#define CRKHAL_u8ALARM_TDC   14
#define CRKHAL_u8ALARM_CAMHAL_INCAM_EDGE_MNG   15
#define CRKHAL_u8ALARM_CAMHAL_EXCAM_EDGE_MNG   16


/* !MComment: Defines for ATOM access ( ATOM CRKHAL alarm channels)          */
#define CRKHAL_u8AtomIndexANGSCHED_1   0
#define CRKHAL_u8AtomIndexANGSCHED_2   1
#define CRKHAL_u8AtomIndexCOIL_A_CMD   2
#define CRKHAL_u8AtomIndexCOIL_B_CMD   3
#define CRKHAL_u8AtomIndexCOIL_C_CMD   4
#define CRKHAL_u8AtomIndexIGN_REF_TEETH   5
#define CRKHAL_u8AtomIndexINJ_1_ANGLE   6
#define CRKHAL_u8AtomIndexINJ_2_ANGLE   7
#define CRKHAL_u8AtomIndexINJ_3_ANGLE   8
#define CRKHAL_u8AtomIndexKNW_SAMPLING_WIN   9
#define CRKHAL_u8AtomIndexSPILL_EVENT_ANGLE   10
#define CRKHAL_u8AtomIndexM_CMD_GDI_PMP_ANGLE   11
#define CRKHAL_u8AtomIndexIT_1_4_TDC   12
#define CRKHAL_u8AtomIndexPTMHAL   13
#define CRKHAL_u8AtomIndexTDC   14


/* !MComment: Defines for ATOM access ( TIM CRKHAL alarm channels)          */
#define CRKHAL_u8TimIndexCAMHAL_INCAM_EDGE_MNG   0
#define CRKHAL_u8TimIndexCAMHAL_EXCAM_EDGE_MNG   1


/* !MComment: Defines for CAMHAL channel                                      */
#define CRKHAL_udtCAMHAL_CH CAMHAL_udtCH_CM_81
/* Mapping of Alarm to respective Atoms */
#define CRKHAL_snANGSCHED_1_ATOM   IfxGtm_Atom_3
#define CRKHAL_snANGSCHED_2_ATOM   IfxGtm_Atom_3
#define CRKHAL_snCOIL_A_CMD_ATOM   IfxGtm_Atom_0
#define CRKHAL_snCOIL_B_CMD_ATOM   IfxGtm_Atom_0
#define CRKHAL_snCOIL_C_CMD_ATOM   IfxGtm_Atom_0
#define CRKHAL_snIGN_REF_TEETH_ATOM   IfxGtm_Atom_3
#define CRKHAL_snINJ_1_ANGLE_ATOM   IfxGtm_Atom_1
#define CRKHAL_snINJ_2_ANGLE_ATOM   IfxGtm_Atom_1
#define CRKHAL_snINJ_3_ANGLE_ATOM   IfxGtm_Atom_1
#define CRKHAL_snKNW_SAMPLING_WIN_ATOM   IfxGtm_Atom_2
#define CRKHAL_snSPILL_EVENT_ANGLE_ATOM   IfxGtm_Atom_3
#define CRKHAL_snM_CMD_GDI_PMP_ANGLE_ATOM   IfxGtm_Atom_1
#define CRKHAL_snIT_1_4_TDC_ATOM   IfxGtm_Atom_2
#define CRKHAL_snPTMHAL_ATOM   IfxGtm_Atom_3
#define CRKHAL_snTDC_ATOM   IfxGtm_Atom_2


/* Mapping of Alarm to respective Tims */
#define CRKHAL_snCAMHAL_INCAM_EDGE_MNG_TIM   IfxGtm_Tim_0
#define CRKHAL_snCAMHAL_EXCAM_EDGE_MNG_TIM   IfxGtm_Tim_0


/* Mapping of Alarm to respective AtomX Channel */
#define CRKHAL_snANGSCHED_1_CHANNEL   IfxGtm_AtomCh_2
#define CRKHAL_snANGSCHED_2_CHANNEL   IfxGtm_AtomCh_3
#define CRKHAL_snCOIL_A_CMD_CHANNEL   IfxGtm_AtomCh_7
#define CRKHAL_snCOIL_B_CMD_CHANNEL   IfxGtm_AtomCh_2
#define CRKHAL_snCOIL_C_CMD_CHANNEL   IfxGtm_AtomCh_5
#define CRKHAL_snIGN_REF_TEETH_CHANNEL   IfxGtm_AtomCh_0
#define CRKHAL_snINJ_1_ANGLE_CHANNEL   IfxGtm_AtomCh_3
#define CRKHAL_snINJ_2_ANGLE_CHANNEL   IfxGtm_AtomCh_4
#define CRKHAL_snINJ_3_ANGLE_CHANNEL   IfxGtm_AtomCh_5
#define CRKHAL_snKNW_SAMPLING_WIN_CHANNEL   IfxGtm_AtomCh_4
#define CRKHAL_snSPILL_EVENT_ANGLE_CHANNEL   IfxGtm_AtomCh_5
#define CRKHAL_snM_CMD_GDI_PMP_ANGLE_CHANNEL   IfxGtm_AtomCh_2
#define CRKHAL_snIT_1_4_TDC_CHANNEL   IfxGtm_AtomCh_7
#define CRKHAL_snPTMHAL_CHANNEL   IfxGtm_AtomCh_4
#define CRKHAL_snTDC_CHANNEL   IfxGtm_AtomCh_6


/* Mapping of Alarm to respective TimX Channels*/
#define CRKHAL_snCAMHAL_INCAM_EDGE_MNG_CHANNEL   IfxGtm_TimCh_4
#define CRKHAL_snCAMHAL_EXCAM_EDGE_MNG_CHANNEL   IfxGtm_TimCh_3


/******************************************************************************/
/* MACRO FUNCTIONS                                                            */
/******************************************************************************/

/******************************************************************************/
/* !FuncName    : CRKHAL_vidNormalModeEntry                                   */
/* !Description : Callback function to call when entering normal mode         */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define CRKHAL_vidNormalModeEntry() KRN_vidCRK_NORMAL_MODE_BSW_PRE()

/******************************************************************************/
/* !FuncName    : CRKHAL_vidDwnModeEntry                                      */
/* !Description : Callback function to call when entering downgraded mode     */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define CRKHAL_vidDwnModeEntry() KRN_vidCRK_DOWN_MODE_BSW_PRE()

/******************************************************************************/
/* !FuncName    : CRKHAL_vidSyncLossEntry                                     */
/* !Description : Callback function to call when loosing synchronisation      */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define CRKHAL_vidSyncLossEntry() KRN_vidS_TOLO_INTERRUPT_BSW()

/******************************************************************************/
/* !FuncName    : CRKHAL_vidSyncFoundEntry                                    */
/* !Description : Callback function to call when entering sync found          */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define CRKHAL_vidSyncFoundEntry()

/******************************************************************************/
/* !FuncName    : CRKHAL_vidINIT_INJ_OFFSETS                                  */
/* !Description : Macro to initialize Injection Alarm Offsets                 */
/* !LastAuthor  : L. Baglin                                                   */
/******************************************************************************/
#define CRKHAL_vidINIT_INJ_OFFSETS() \
do \
{ \
   CRKHAL_u16Offset_INJ_1_ANGLE = (uint16)UINT16_MIN; \
   CRKHAL_u16Offset_INJ_2_ANGLE = (uint16)UINT16_MIN; \
   CRKHAL_u16Offset_INJ_3_ANGLE = (uint16)UINT16_MIN; \
} \
while (0)


/******************************************************************************/
/* DATA DECLARATION                                                           */
/******************************************************************************/
#define CRKHAL_START_SEC_VAR_CLEARED_16BIT
#include "CRKHAL_MemMap.h"

extern uint16 CRKHAL_u16Offset_INJ_1_ANGLE;
extern uint16 CRKHAL_u16Offset_INJ_2_ANGLE;
extern uint16 CRKHAL_u16Offset_INJ_3_ANGLE;


#define CRKHAL_STOP_SEC_VAR_CLEARED_16BIT
#include "CRKHAL_MemMap.h"


/******************************************************************************/
/* EXTERNAL FUNCTIONS DECLARATION                                             */
/******************************************************************************/

#define CRKHAL_START_SEC_CODE
#include "CRKHAL_MemMap.h"

/* !Comment: ATOM Callback Functions Declaration                              */
extern void   CRKHAL_vidAtom3Ch2Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom3Ch3Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom0Ch7Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom0Ch2Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom0Ch5Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom3Ch0Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom1Ch3Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom1Ch4Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom1Ch5Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom2Ch4Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom3Ch5Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom1Ch2Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom2Ch7Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom3Ch4Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);
extern void   CRKHAL_vidAtom2Ch6Callback(uint8 ModuleType, uint8 ModuleNo, uint8 ChannelNo, uint16 IrqNotifVal);

/* !Comment: CRKHAL External Functions Declaration                            */
extern void   CRKHAL_vidEnableAlarmNotif(uint8 u8Channel);
extern void   CRKHAL_vidDisableAlarmNotif(uint8 u8Channel);
extern void   CRKHAL_vidActivateAlarmMode(uint8 u8Channel, uint8 u8Mode);
extern void   CRKHAL_vidDeactivateAlarmMode(uint8 u8Channel);
extern void   CRKHAL_vidSetAbsAlarm(uint8 u8Channel, uint16 u16AbsoluteAngle);
extern void   CRKHAL_vidSetRelAlarm(uint8 u8Channel, uint16 u16RelativeAngle);
extern uint16 CRKHAL_u16ReadAlarm(uint8 u8Channel);
extern uint16 CRKHAL_u16ReadCounter(uint8 u8Channel);

#define CRKHAL_STOP_SEC_CODE
#include "CRKHAL_MemMap.h"

#endif /* CRKHAL_CFG_H */

/*------------------------------ end of file ---------------------------------*/
