/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : ISFHCAN_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : Valeo                                                   */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 VALEO                                                       */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* PVCS Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 11/10/14, 10:16:21: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: ISFHCAN Section allocation */
#elif defined   ISFHCAN_START_SEC_CODE
   #undef  ISFHCAN_START_SEC_CODE
   #define START_SEC_CODE_SECTION
#elif defined   ISFHCAN_STOP_SEC_CODE
   #undef  ISFHCAN_STOP_SEC_CODE
   #define STOP_SEC_CODE_SECTION

#elif defined   ISFHCAN_START_SEC_INTERNAL_VAR_8BIT
   #undef  ISFHCAN_START_SEC_INTERNAL_VAR_8BIT
   #define START_SEC_INTERNAL_VAR_8BIT_SECTION
#elif defined   ISFHCAN_STOP_SEC_INTERNAL_VAR_8BIT
   #undef  ISFHCAN_STOP_SEC_INTERNAL_VAR_8BIT
   #define STOP_SEC_INTERNAL_VAR_8BIT_SECTION

#elif defined   ISFHCAN_START_SEC_INTERNAL_VAR_16BIT
   #undef  ISFHCAN_START_SEC_INTERNAL_VAR_16BIT
   #define START_SEC_INTERNAL_VAR_16BIT_SECTION
#elif defined   ISFHCAN_STOP_SEC_INTERNAL_VAR_16BIT
   #undef  ISFHCAN_STOP_SEC_INTERNAL_VAR_16BIT
   #define STOP_SEC_INTERNAL_VAR_16BIT_SECTION

#elif defined   ISFHCAN_START_SEC_INTERNAL_VAR_BOOLEAN
   #undef  ISFHCAN_START_SEC_INTERNAL_VAR_BOOLEAN
   #define START_SEC_INTERNAL_VAR_BOOLEAN_SECTION
#elif defined   ISFHCAN_STOP_SEC_INTERNAL_VAR_BOOLEAN
   #undef  ISFHCAN_STOP_SEC_INTERNAL_VAR_BOOLEAN
   #define STOP_SEC_INTERNAL_VAR_BOOLEAN_SECTION

#elif defined   ISFHCAN_START_SEC_CALIB_8BIT
   #undef  ISFHCAN_START_SEC_CALIB_8BIT
   #define START_SEC_CALIB_8BIT_SECTION
#elif defined   ISFHCAN_STOP_SEC_CALIB_8BIT
   #undef  ISFHCAN_STOP_SEC_CALIB_8BIT
   #define STOP_SEC_CALIB_8BIT_SECTION

#elif defined   ISFHCAN_START_SEC_CALIB_16BIT
   #undef  ISFHCAN_START_SEC_CALIB_16BIT
   #define START_SEC_CALIB_16BIT_SECTION
#elif defined   ISFHCAN_STOP_SEC_CALIB_16BIT
   #undef  ISFHCAN_STOP_SEC_CALIB_16BIT
   #define STOP_SEC_CALIB_16BIT_SECTION


#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Start Section treatment */
   #elif defined   START_SEC_CODE_SECTION
	  

      #pragma section ".text" ax

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_INTERNAL_VAR_8BIT Start Section treatment */
   #elif defined   START_SEC_INTERNAL_VAR_8BIT_SECTION
	  

      #pragma section ".bss_cpu1" aw

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_INTERNAL_VAR_16BIT Start Section treatment */
   #elif defined   START_SEC_INTERNAL_VAR_16BIT_SECTION
	  

      #pragma section ".bss_cpu1" aw

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_INTERNAL_VAR_BOOLEAN Start Section treatment */
   #elif defined   START_SEC_INTERNAL_VAR_BOOLEAN_SECTION
	  

      #pragma section ".bss_cpu1" aw

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_CALIB_8BIT Start Section treatment */
   #elif defined   START_SEC_CALIB_8BIT_SECTION
	  

      #pragma section ".calib" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_CALIB_16BIT Start Section treatment */
   #elif defined   START_SEC_CALIB_16BIT_SECTION
	  

      #pragma section ".calib" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE


   #endif

#else   /* if MEMMAP_START_DONE is not defined */

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Stop Section treatment */
   #elif defined   STOP_SEC_CODE_SECTION && defined  START_SEC_CODE_SECTION
	  

      #pragma section

      #undef START_SEC_CODE_SECTION
      #undef STOP_SEC_CODE_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_INTERNAL_VAR_8BIT Stop Section treatment */
   #elif defined   STOP_SEC_INTERNAL_VAR_8BIT_SECTION && defined  START_SEC_INTERNAL_VAR_8BIT_SECTION
	  

      #pragma section

      #undef START_SEC_INTERNAL_VAR_8BIT_SECTION
      #undef STOP_SEC_INTERNAL_VAR_8BIT_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_INTERNAL_VAR_16BIT Stop Section treatment */
   #elif defined   STOP_SEC_INTERNAL_VAR_16BIT_SECTION && defined  START_SEC_INTERNAL_VAR_16BIT_SECTION
	  

      #pragma section

      #undef START_SEC_INTERNAL_VAR_16BIT_SECTION
      #undef STOP_SEC_INTERNAL_VAR_16BIT_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_INTERNAL_VAR_BOOLEAN Stop Section treatment */
   #elif defined   STOP_SEC_INTERNAL_VAR_BOOLEAN_SECTION && defined  START_SEC_INTERNAL_VAR_BOOLEAN_SECTION
	  

      #pragma section

      #undef START_SEC_INTERNAL_VAR_BOOLEAN_SECTION
      #undef STOP_SEC_INTERNAL_VAR_BOOLEAN_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_CALIB_8BIT Stop Section treatment */
   #elif defined   STOP_SEC_CALIB_8BIT_SECTION && defined  START_SEC_CALIB_8BIT_SECTION
	  

      #pragma section

      #undef START_SEC_CALIB_8BIT_SECTION
      #undef STOP_SEC_CALIB_8BIT_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_CALIB_16BIT Stop Section treatment */
   #elif defined   STOP_SEC_CALIB_16BIT_SECTION && defined  START_SEC_CALIB_16BIT_SECTION
	  

      #pragma section

      #undef START_SEC_CALIB_16BIT_SECTION
      #undef STOP_SEC_CALIB_16BIT_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE


   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into ISFHCAN_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

