/**********************************************************************************************************************/
/* !Layer           : HAL                                                                                             */
/* !Component       : PWDHAL                                                                                          */
/* !Description     : Pulse width demodulation                                                                        */
/*                                                                                                                    */
/* !File            : PWDHAL_Scale_Cfg.c                                                                              */
/* !Description     : Configuration files for auto-scaling                                                            */
/*                                                                                                                    */
/* !Reference       : PTS_DOC_5611943                                                                                 */
/*                                                                                                                    */
/* Coding language  : C                                                                                               */
/*                                                                                                                    */
/* COPYRIGHT VALEO all rights reserved                                                                                */
/**********************************************************************************************************************/
/* Dimension Informations
 * %PCMS_HEADER_SUBSTITUTION_START:%
 * The PID has this format: <Product ID>:<Item ID>.<Variant>-<Item Type>;<Revision>
 * %PID: LIBEMB:A3583.A-SRC;2 %
 * %PCMS_HEADER_SUBSTITUTION_END:%
 **********************************************************************************************************************/
/** 11/10/14, 10:16:20: generated by Genecode v2.6.0.0                                                                */
/**********************************************************************************************************************/

#include "Std_Types.h"
#include "Std_Limits.h"
#include "AR_Mfx.h"
#include "PWDHAL.h"



/******************************************************************************/
/* CONSTANTS DEFINITION                                                       */
/******************************************************************************/

#define PWDHAL_START_SEC_CONST_UNSPECIFIED
#include "PWDHAL_MemMap.h"


#define PWDHAL_STOP_SEC_CONST_UNSPECIFIED
#include "PWDHAL_MemMap.h"



/******************************************************************************/
/* FUNCTIONS                                                                  */
/******************************************************************************/



/*---------------------------------------------------- end of file ---------------------------------------------------*/
