/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : RTMCLD2_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : Valeo                                                   */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 VALEO                                                       */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* PVCS Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 11/10/14, 10:16:22: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: RTMCLD2 Section allocation */
#elif defined   RTMCLD2_START_SEC_CODE
   #undef  RTMCLD2_START_SEC_CODE
   #define START_SEC_CODE_SECTION
#elif defined   RTMCLD2_STOP_SEC_CODE
   #undef  RTMCLD2_STOP_SEC_CODE
   #define STOP_SEC_CODE_SECTION

#elif defined   RTMCLD2_START_SEC_VAR_NOINIT_8BIT
   #undef  RTMCLD2_START_SEC_VAR_NOINIT_8BIT
   #define START_SEC_VAR_POWER_ON_INIT_8BIT_CPU1_SECTION
#elif defined   RTMCLD2_STOP_SEC_VAR_NOINIT_8BIT
   #undef  RTMCLD2_STOP_SEC_VAR_NOINIT_8BIT
   #define STOP_SEC_VAR_POWER_ON_INIT_8BIT_CPU1_SECTION

#elif defined   RTMCLD2_START_SEC_VAR_NOINIT_32BIT
   #undef  RTMCLD2_START_SEC_VAR_NOINIT_32BIT
   #define START_SEC_VAR_POWER_ON_INIT_32BIT_CPU1_SECTION
#elif defined   RTMCLD2_STOP_SEC_VAR_NOINIT_32BIT
   #undef  RTMCLD2_STOP_SEC_VAR_NOINIT_32BIT
   #define STOP_SEC_VAR_POWER_ON_INIT_32BIT_CPU1_SECTION

#elif defined   RTMCLD2_START_SEC_VAR_16BIT
   #undef  RTMCLD2_START_SEC_VAR_16BIT
   #define START_SEC_VAR_CLEARED_16BIT_CPU1_SECTION
#elif defined   RTMCLD2_STOP_SEC_VAR_16BIT
   #undef  RTMCLD2_STOP_SEC_VAR_16BIT
   #define STOP_SEC_VAR_CLEARED_16BIT_CPU1_SECTION

#elif defined   RTMCLD2_START_SEC_VAR_32BIT
   #undef  RTMCLD2_START_SEC_VAR_32BIT
   #define START_SEC_VAR_CLEARED_32BIT_CPU1_SECTION
#elif defined   RTMCLD2_STOP_SEC_VAR_32BIT
   #undef  RTMCLD2_STOP_SEC_VAR_32BIT
   #define STOP_SEC_VAR_CLEARED_32BIT_CPU1_SECTION

#elif defined   RTMCLD2_START_SEC_RTMCLD_ENDLESS_LOOP_CODE
   #undef  RTMCLD2_START_SEC_RTMCLD_ENDLESS_LOOP_CODE
   #define START_SEC_RTMCLD_ENDLESS_LOOP_CODE_CPU1_SECTION
#elif defined   RTMCLD2_STOP_SEC_RTMCLD_ENDLESS_LOOP_CODE
   #undef  RTMCLD2_STOP_SEC_RTMCLD_ENDLESS_LOOP_CODE
   #define STOP_SEC_RTMCLD_ENDLESS_LOOP_CODE_CPU1_SECTION


#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Start Section treatment */
   #elif defined   START_SEC_CODE_SECTION
	  

      #pragma section ".text" ax

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_NOINIT_8BIT Start Section treatment */
   #elif defined   START_SEC_VAR_POWER_ON_INIT_8BIT_CPU1_SECTION
	  

      #pragma section ".power_on_init_cpu1" aw

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_NOINIT_32BIT Start Section treatment */
   #elif defined   START_SEC_VAR_POWER_ON_INIT_32BIT_CPU1_SECTION
	  

      #pragma section ".power_on_init_cpu1" aw

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_16BIT Start Section treatment */
   #elif defined   START_SEC_VAR_CLEARED_16BIT_CPU1_SECTION
	  

      #pragma section ".bss_cpu1" aw

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_32BIT Start Section treatment */
   #elif defined   START_SEC_VAR_CLEARED_32BIT_CPU1_SECTION
	  

      #pragma section ".bss_cpu1" aw

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_RTMCLD_ENDLESS_LOOP_CODE Start Section treatment */
   #elif defined   START_SEC_RTMCLD_ENDLESS_LOOP_CODE_CPU1_SECTION
	  

      #pragma section ".rtmcld_endless_loop_cpu1" ax

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE


   #endif

#else   /* if MEMMAP_START_DONE is not defined */

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Stop Section treatment */
   #elif defined   STOP_SEC_CODE_SECTION && defined  START_SEC_CODE_SECTION
	  

      #pragma section

      #undef START_SEC_CODE_SECTION
      #undef STOP_SEC_CODE_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_NOINIT_8BIT Stop Section treatment */
   #elif defined   STOP_SEC_VAR_POWER_ON_INIT_8BIT_CPU1_SECTION && defined  START_SEC_VAR_POWER_ON_INIT_8BIT_CPU1_SECTION
	  

      #pragma section

      #undef START_SEC_VAR_POWER_ON_INIT_8BIT_CPU1_SECTION
      #undef STOP_SEC_VAR_POWER_ON_INIT_8BIT_CPU1_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_NOINIT_32BIT Stop Section treatment */
   #elif defined   STOP_SEC_VAR_POWER_ON_INIT_32BIT_CPU1_SECTION && defined  START_SEC_VAR_POWER_ON_INIT_32BIT_CPU1_SECTION
	  

      #pragma section

      #undef START_SEC_VAR_POWER_ON_INIT_32BIT_CPU1_SECTION
      #undef STOP_SEC_VAR_POWER_ON_INIT_32BIT_CPU1_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_16BIT Stop Section treatment */
   #elif defined   STOP_SEC_VAR_CLEARED_16BIT_CPU1_SECTION && defined  START_SEC_VAR_CLEARED_16BIT_CPU1_SECTION
	  

      #pragma section

      #undef START_SEC_VAR_CLEARED_16BIT_CPU1_SECTION
      #undef STOP_SEC_VAR_CLEARED_16BIT_CPU1_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_32BIT Stop Section treatment */
   #elif defined   STOP_SEC_VAR_CLEARED_32BIT_CPU1_SECTION && defined  START_SEC_VAR_CLEARED_32BIT_CPU1_SECTION
	  

      #pragma section

      #undef START_SEC_VAR_CLEARED_32BIT_CPU1_SECTION
      #undef STOP_SEC_VAR_CLEARED_32BIT_CPU1_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_RTMCLD_ENDLESS_LOOP_CODE Stop Section treatment */
   #elif defined   STOP_SEC_RTMCLD_ENDLESS_LOOP_CODE_CPU1_SECTION && defined  START_SEC_RTMCLD_ENDLESS_LOOP_CODE_CPU1_SECTION
	  

      #pragma section

      #undef START_SEC_RTMCLD_ENDLESS_LOOP_CODE_CPU1_SECTION
      #undef STOP_SEC_RTMCLD_ENDLESS_LOOP_CODE_CPU1_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE


   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into RTMCLD2_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

