/**********************************************************************************************************************/
/* !Layer           : SRVL                                                                                            */
/* !Component       : RTMCLD                                                                                          */
/* !Description     : Real time measurement of CPU load                                                               */
/*                                                                                                                    */
/* !File            : RTMCLD_EndlessLoop.h                                                                            */
/* !Description     : configurations of the RTMCLD component                                                          */
/*                                                                                                                    */
/* !Reference       : PTS_DOC_5385380                                                                                 */
/*                                                                                                                    */
/* Coding language  : C                                                                                               */
/*                                                                                                                    */
/* COPYRIGHT VALEO all rights reserved                                                                                */
/**********************************************************************************************************************/
/* 11/10/14, 10:16:19: generated by Genecode  v2.6.0.0                                                                */
/* From Source Template : RTMCLD_EndlessLoop_H.TPL                                                                    */
/**********************************************************************************************************************/

#include "RTMCLD_EndlessLoop_Tricore.h"

/*---------------------------------------------------- end of file ---------------------------------------------------*/
