/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : STARTUP_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : Valeo                                                   */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 VALEO                                                       */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* PVCS Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 11/10/14, 10:16:22: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: STARTUP Section allocation */
#elif defined   STARTUP_START_SEC_CODE
   #undef  STARTUP_START_SEC_CODE
   #define START_SEC_CODE_SECTION
#elif defined   STARTUP_STOP_SEC_CODE
   #undef  STARTUP_STOP_SEC_CODE
   #define STOP_SEC_CODE_SECTION

#elif defined   STARTUP_START_SEC_BMHD_0
   #undef  STARTUP_START_SEC_BMHD_0
   #define START_SEC_BMHD_0_SECTION
#elif defined   STARTUP_STOP_SEC_BMHD_0
   #undef  STARTUP_STOP_SEC_BMHD_0
   #define STOP_SEC_BMHD_0_SECTION

#elif defined   STARTUP_START_SEC_BMHD_1
   #undef  STARTUP_START_SEC_BMHD_1
   #define START_SEC_BMHD_1_SECTION
#elif defined   STARTUP_STOP_SEC_BMHD_1
   #undef  STARTUP_STOP_SEC_BMHD_1
   #define STOP_SEC_BMHD_1_SECTION

#elif defined   STARTUP_START_SEC_RESET_CODE
   #undef  STARTUP_START_SEC_RESET_CODE
   #define START_SEC_RESET_CODE_SECTION
#elif defined   STARTUP_STOP_SEC_RESET_CODE
   #undef  STARTUP_STOP_SEC_RESET_CODE
   #define STOP_SEC_RESET_CODE_SECTION


#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Start Section treatment */
   #elif defined   START_SEC_CODE_SECTION
	  

      #pragma section ".text" ax

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_BMHD_0 Start Section treatment */
   #elif defined   START_SEC_BMHD_0_SECTION
	  

      #pragma section ".bmhd_0" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_BMHD_1 Start Section treatment */
   #elif defined   START_SEC_BMHD_1_SECTION
	  

      #pragma section ".bmhd_1" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_RESET_CODE Start Section treatment */
   #elif defined   START_SEC_RESET_CODE_SECTION
	  

      #pragma section ".start" x

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE


   #endif

#else   /* if MEMMAP_START_DONE is not defined */

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Stop Section treatment */
   #elif defined   STOP_SEC_CODE_SECTION && defined  START_SEC_CODE_SECTION
	  

      #pragma section

      #undef START_SEC_CODE_SECTION
      #undef STOP_SEC_CODE_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_BMHD_0 Stop Section treatment */
   #elif defined   STOP_SEC_BMHD_0_SECTION && defined  START_SEC_BMHD_0_SECTION
	  

      #pragma section

      #undef START_SEC_BMHD_0_SECTION
      #undef STOP_SEC_BMHD_0_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_BMHD_1 Stop Section treatment */
   #elif defined   STOP_SEC_BMHD_1_SECTION && defined  START_SEC_BMHD_1_SECTION
	  

      #pragma section

      #undef START_SEC_BMHD_1_SECTION
      #undef STOP_SEC_BMHD_1_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_RESET_CODE Stop Section treatment */
   #elif defined   STOP_SEC_RESET_CODE_SECTION && defined  START_SEC_RESET_CODE_SECTION
	  

      #pragma section

      #undef START_SEC_RESET_CODE_SECTION
      #undef STOP_SEC_RESET_CODE_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE


   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into STARTUP_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

