/***************************************************************************
;**
;** FILE NAME      : IFRTE_L.H
;**
;** FILE AUTHOR    : ynicaise (VEES)
;**
;**************************************************************************/

#ifndef IFRTE_L_H
#define IFRTE_L_H

#include "MATHSRV_Portability.h"
#include "RTE_TYPE.h"
#include "STD_Types.h"
#include "Rte_Type.h"
/*-------------------------------------------------------------------------
    Defines
-------------------------------------------------------------------------*/


/*-------------------------------------------------------------------------
    Typedef
-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------
    Enums
-------------------------------------------------------------------------*/


/*-------------------------------------------------------------------------
    Calibrations
-------------------------------------------------------------------------*/
#pragma section ".calib" a

extern const uint8  ACCMD_u8Inhib;
extern const uint8  ADVCORDT_u8Inhib;
extern const uint8  ADVMAXT_u8Inhib;
extern const uint8  ADVMINT_u8Inhib;
extern const uint8  ADVOPTMT_u8Inhib;
extern const uint8  ADVPREVKNKT_u8Inhib;
extern const uint8  ADVSPT_u8Inhib;
extern const uint8  AFAMGTT_u8Inhib;
extern const uint8  AFAT_u8Inhib;
extern const uint8  AIRSYSAIR_u8Inhib;
extern const uint8  AIRSYSTRB_u8Inhib;
extern const uint8  ASE_u8Inhib;
extern const uint8  CatAcvDiagT_u8Inhib;
extern const uint8  CatPasDiagT_u8Inhib;
extern const uint8  COCLLASL_u8Inhib;
extern const uint8  COEMSTT_u8Inhib;
extern const uint8  COGBX_u8Inhib;
extern const uint8  COSTOPSTART_u8Inhib;
extern const uint8  COTQ_u8Inhib;
extern const uint8  CURDRIVFIL_u8Inhib;
extern const uint8  DCM_MANU_u8Inhib;
extern const uint8  DCM_u8Inhib;
extern const uint8  DFWCTL_u8Inhib;
extern const uint8  DMPVLV_H_u8Inhib;
extern const uint8  EBSTUB_u8Inhib;
extern const uint8  ENGLIM_u8Inhib;
extern const uint8  ENGLIMTQT_u8Inhib;
extern const uint8  ENGMGSLLIM_u8Inhib;
extern const uint8  ENGMGSLT_u8Inhib;
extern const uint8  EOMGSL_u8Inhib;
extern const uint8  EXMGSLT1_u8Inhib;
extern const uint8  EXMGSLT2_u8Inhib;
extern const uint8  FARSP_u8Inhib;
extern const uint8  FISA_u8Inhib;
extern const uint8  GSI_u8Inhib;
extern const uint8  INMDLT_u8Inhib;
extern const uint8  INTHMDLT_u8Inhib;
extern const uint8  MPM_u8Inhib;
extern const uint8  OILSYS_u8Inhib;
extern const uint8  PFILFAST_u8Inhib;
extern const uint8  PFILSLOW_u8Inhib;
extern const uint8  PNMACT_u8Inhib;
extern const uint8  PRODELEM_u8Inhib;
extern const uint8  PRODELENG_u8Inhib;
extern const uint8  RCD_u8Inhib;
extern const uint8  STOPSTRTEM_u8Inhib;
extern const uint8  STOPSTRTENG_u8Inhib;
extern const uint8  THMGT_u8Inhib;
extern const uint8  THRSPT_u8Inhib;
extern const uint8  TPM_u8Inhib;
extern const uint8  TQADPCMP_u8Inhib;
extern const uint8  TQDEM_u8Inhib;
extern const uint8  TQEM_u8Inhib;
extern const uint8  TQTREAT_u8Inhib;
extern const uint8  TRABVX_u8Inhib;
extern const uint8  TRBACTGSL_u8Inhib;
extern const uint8  TRBACTMGT_u8Inhib;
extern const uint8  TRBACTSYS_u8Inhib;
extern const uint8  USTHRMT_u8Inhib;
extern const uint8  VSCO_u8Inhib;
extern const uint8  VSINFO_u8Inhib;
extern const uint8  VSLIM_u8Inhib;
extern const uint8  VSMAX_u8Inhib;
extern const uint8  VSREG_u8Inhib;
extern const uint8  VSSP_u8Inhib;

#pragma section
/*-------------------------------------------------------------------------
    Variables
-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------
    Porteurs de bits
-------------------------------------------------------------------------*/


/*-------------------------------------------------------------------------
    Prototypes
-------------------------------------------------------------------------*/



#endif /* IFRTE_L_H */

/*-------------------------------- end of file -------------------------------*/
