/***************************************************************************
;**
;** FILE NAME      : NOPROD.C75
;**
;** FILE AUTHOR    : ynicaise (VEES)
;**
;**************************************************************************/

#include "MATHSRV_Portability.h"
#include "RTE_TYPE.h"
#include "STD_Types.h"
#include "NOPROD_FCTTFT.h"
#include "NOPROD_SAMPLETI.h"
#include "NOPROD_SW.h"
#include "NOPROD.H"
#include "NOPROD_L.H"
/*-------------------------------------------------------------------------
    Defines
-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------
    Typedef
-------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------
    Enums
-------------------------------------------------------------------------*/


/*-------------------------------------------------------------------------
    Calibrations
-------------------------------------------------------------------------*/

#pragma section ".calib" a
const boolean  Afts_bAcvHybMod_nTarIdl_BypC = 0;
const boolean  Afts_bRstMemFirstFillFuEng_BypC = 0;
const boolean  AirMon_bEnaIdlCtlAftsDiag_BypC = 0;
const boolean  Cf_bInhFlex_BypC = 0;
const boolean  Cf_bRvsFilConf_BypC = 0;
const boolean  Cl_presence_clim_bsi_BypC = 0;
const boolean  CoHVB_bMILReq_BypC = 0;
const boolean  CoPt_bTarIdlInc_BypC = 0;
const boolean  CoPTSt_bDgoSftyORngAM_BypC = 0;
const boolean  Ctrl_aLgtGearSen_BypC = 0;
const boolean  Ctrl_aVeh_BypC = 0;
const boolean  Ctrl_bABSReg_BypC = 0;
const boolean  Ctrl_bAccPTra_BypC = 0;
const boolean  Ctrl_bAcv_bAcvElCnsReq_BypC = 0;
const boolean  Ctrl_bAcv_bAcvSftyWarn_BypC = 0;
const boolean  Ctrl_bAcv_bBrkPark_BypC = 0;
const boolean  Ctrl_bAcv_bDftFctEM_BypC = 0;
const boolean  Ctrl_bAcv_bLiRegESPASR_BypC = 0;
const boolean  Ctrl_bAcv_bRCDLine_BypC = 0;
const boolean  Ctrl_bAcv_ctClcProc3B8_BypC = 0;
const boolean  Ctrl_bAcv_dstVehTotMesIS552_BypC = 0;
const boolean  Ctrl_bAcv_dstVehTotMesIS7F2_BypC = 0;
const boolean  Ctrl_bAcv_ECTReq_BypC = 0;
const boolean  Ctrl_bAcv_grdNegSlop_BypC = 0;
const boolean  Ctrl_bAcv_grdPosSlop_BypC = 0;
const boolean  Ctrl_bAcv_noIdFrame_BypC = 0;
const boolean  Ctrl_bAcv_noJDDKm_BypC = 0;
const boolean  Ctrl_bAcv_noNEngCplm_BypC = 0;
const boolean  Ctrl_bAcv_noRatDrvReqCplm_BypC = 0;
const boolean  Ctrl_bAcv_noTqAirDrvFilCplm_BypC = 0;
const boolean  Ctrl_bAcv_noTqCkEngRealCplm_BypC = 0;
const boolean  Ctrl_bAcv_noTqDrvFilCplm_BypC = 0;
const boolean  Ctrl_bAcv_noVDS1_BypC = 0;
const boolean  Ctrl_bAcv_noVDS2_BypC = 0;
const boolean  Ctrl_bAcv_noVDS3_BypC = 0;
const boolean  Ctrl_bAcv_noVDS4_BypC = 0;
const boolean  Ctrl_bAcv_noVDS5_BypC = 0;
const boolean  Ctrl_bAcv_noVDS6_BypC = 0;
const boolean  Ctrl_bAcv_noVIS1_BypC = 0;
const boolean  Ctrl_bAcv_noVIS2_BypC = 0;
const boolean  Ctrl_bAcv_noVIS3_BypC = 0;
const boolean  Ctrl_bAcv_noVIS4_BypC = 0;
const boolean  Ctrl_bAcv_noVIS5_BypC = 0;
const boolean  Ctrl_bAcv_noVIS6_BypC = 0;
const boolean  Ctrl_bAcv_noVIS7_BypC = 0;
const boolean  Ctrl_bAcv_noVIS8_BypC = 0;
const boolean  Ctrl_bAcv_noWMI1_BypC = 0;
const boolean  Ctrl_bAcv_noWMI2_BypC = 0;
const boolean  Ctrl_bAcv_noWMI3_BypC = 0;
const boolean  Ctrl_bagStrWhl_BypC = 0;
const boolean  Ctrl_bagvStrWhl_BypC = 0;
const boolean  Ctrl_bASRRegFirst_BypC = 0;
const boolean  Ctrl_bAuthCrawl_BypC = 0;
const boolean  Ctrl_bAuthWupElMgt_BypC = 0;
const boolean  Ctrl_bCmpReq_BypC = 0;
const boolean  Ctrl_bCntMILRst_BypC = 0;
const boolean  Ctrl_bctClcProc305_BypC = 0;
const boolean  Ctrl_bCtlEfc_tqWhlPt_BypC = 0;
const boolean  Ctrl_bDelDftReq_BypC = 0;
const boolean  Ctrl_bDft_bBrkPedPrss_BypC = 0;
const boolean  Ctrl_bDft_BypC = 0;
const boolean  Ctrl_bDgo_iBattMes_BypC = 0;
const boolean  Ctrl_bDgo_tBattMes_BypC = 0;
const boolean  Ctrl_bDgo_uBattClc_BypC = 0;
const boolean  Ctrl_bDiagMuxOn_BypC = 0;
const boolean  Ctrl_bDrvCyGlbl_BypC = 0;
const boolean  Ctrl_bEHRWaPmpReqRTE_BypC = 0;
const boolean  Ctrl_bElIntgDiag_BypC = 0;
const boolean  Ctrl_bElIntgDiagMod_BypC = 0;
const boolean  Ctrl_bEngRStrtReqAsiDir_BypC = 0;
const boolean  Ctrl_bEngRStrtReqGBx_BypC = 0;
const boolean  Ctrl_bEngStopAuthAsiDir_BypC = 0;
const boolean  Ctrl_bEngStopAuthGBx_BypC = 0;
const boolean  Ctrl_bEngStopReq_BypC = 0;
const boolean  Ctrl_bESPRegFirst_BypC = 0;
const boolean  Ctrl_bfAcvConstElMgt1_BypC = 0;
const boolean  Ctrl_bfAcvConstElMgt2_BypC = 0;
const boolean  Ctrl_bfAcvConstElMgt3_BypC = 0;
const boolean  Ctrl_bfAcvConstEm1_BypC = 0;
const boolean  Ctrl_bfAcvConstEng1_BypC = 0;
const boolean  Ctrl_bfAcvConstFrntTra1_BypC = 0;
const boolean  Ctrl_bfAcvConstReTra1_BypC = 0;
const boolean  Ctrl_bFlashLiMIL_BypC = 0;
const boolean  Ctrl_bFrzAC_BypC = 0;
const boolean  Ctrl_bGBxRdy_BypC = 0;
const boolean  Ctrl_bGearCtlFirst_BypC = 0;
const boolean  Ctrl_bImmoUnlockWkuReq_BypC = 0;
const boolean  Ctrl_bInhAcqESCFrnt_BypC = 0;
const boolean  Ctrl_bInhStrtAMT_BypC = 0;
const boolean  Ctrl_bInhVSCtl_BypC = 0;
const boolean  Ctrl_bKeyON_BypC = 0;
const boolean  Ctrl_bLevMod_BypC = 0;
const boolean  Ctrl_bLiIMIL_BypC = 0;
const boolean  Ctrl_bLiMILReq_BypC = 0;
const boolean  Ctrl_bnoCks305_BypC = 0;
const boolean  Ctrl_bNRegReq_BypC = 0;
const boolean  Ctrl_bOBDDftOnMIL_BypC = 0;
const boolean  Ctrl_bOilMesReq_BypC = 0;
const boolean  Ctrl_bOilWkuReq_BypC = 0;
const boolean  Ctrl_bOpDrvTraReq_BypC = 0;
const boolean  Ctrl_bPrepIgEngWkuReq_BypC = 0;
const boolean  Ctrl_bPresOilWarn_BypC = 0;
const boolean  Ctrl_bRStrtAuthTra_BypC = 0;
const boolean  Ctrl_bRstrtTypAT_BypC = 0;
const boolean  Ctrl_bSecBrkPedPrssMes_BypC = 0;
const boolean  Ctrl_bSIP_BypC = 0;
const boolean  Ctrl_bSIPPrep_BypC = 0;
const boolean  Ctrl_bSpdFanGBxReq_BypC = 0;
const boolean  Ctrl_bStaProt_BypC = 0;
const boolean  Ctrl_bStopEngCoWkuReq_BypC = 0;
const boolean  Ctrl_bSTTDft_BypC = 0;
const boolean  Ctrl_bTqTx_BypC = 0;
const boolean  Ctrl_bTraTqAuthRaw_BypC = 0;
const boolean  Ctrl_bTypMsg_BypC = 0;
const boolean  Ctrl_bWarn_tCo_BypC = 0;
const boolean  Ctrl_bWUC_BypC = 0;
const boolean  Ctrl_ctClcProc329_BypC = 0;
const boolean  Ctrl_ctClcProc349_BypC = 0;
const boolean  Ctrl_ctClcProc34D_BypC = 0;
const boolean  Ctrl_ctClcProc38D_BypC = 0;
const boolean  Ctrl_ctClcProc3AD_BypC = 0;
const boolean  Ctrl_ctClcProc3C9_BypC = 0;
const boolean  Ctrl_ctDayCAN_BypC = 0;
const boolean  Ctrl_CtRstCurVehTmr_BypC = 0;
const boolean  Ctrl_ctSecCAN_BypC = 0;
const boolean  Ctrl_ctYrCAN_BypC = 0;
const boolean  Ctrl_dstCntGearSen_BypC = 0;
const boolean  Ctrl_iBattMaxCkg_BypC = 0;
const boolean  Ctrl_idxPrfGBxMsg_BypC = 0;
const boolean  Ctrl_idxPtSpt_BypC = 0;
const boolean  Ctrl_IS_MAP_CMM_7A8_BypC = 0;
const boolean  Ctrl_mfAirMes_BypC = 0;
const boolean  Ctrl_nAvrFrntWhl_BypC = 0;
const boolean  Ctrl_nEng_BypC = 0;
const boolean  Ctrl_nEngAvr_BypC = 0;
const boolean  Ctrl_nEngSpdMaxTq_BypC = 0;
const boolean  Ctrl_noCks329_BypC = 0;
const boolean  Ctrl_noCks349_BypC = 0;
const boolean  Ctrl_noCks38D_BypC = 0;
const boolean  Ctrl_noCks3AD_BypC = 0;
const boolean  Ctrl_noCks3C9_BypC = 0;
const boolean  Ctrl_noCMMSeedImmo_BypC = 0;
const boolean  Ctrl_noDiag_BypC = 0;
const boolean  Ctrl_noEditCal_BypC = 0;
const boolean  Ctrl_noEditSw_BypC = 0;
const boolean  Ctrl_noEgdGear_BypC = 0;
const boolean  Ctrl_noEgdGearCord_BypC = 0;
const boolean  Ctrl_noGearReqMax_BypC = 0;
const boolean  Ctrl_noGearReqMin_BypC = 0;
const boolean  Ctrl_noTarGear_BypC = 0;
const boolean  Ctrl_noVersAdp_BypC = 0;
const boolean  Ctrl_noVersSw_BypC = 0;
const boolean  Ctrl_noVersSys_BypC = 0;
const boolean  Ctrl_noVersSysMnth_BypC = 0;
const boolean  Ctrl_noVersSysYr_BypC = 0;
const boolean  Ctrl_noVerSysDay_BypC = 0;
const boolean  Ctrl_nTar_BypC = 0;
const boolean  Ctrl_nTarIdl_BypC = 0;
const boolean  Ctrl_pAirExtMes_BypC = 0;
const boolean  Ctrl_pBrkAsi_BypC = 0;
const boolean  Ctrl_pDsEGRVlvMes_BypC = 0;
const boolean  Ctrl_posnATLev_BypC = 0;
const boolean  Ctrl_rBattSoCLoResl_BypC = 0;
const boolean  Ctrl_rDrvReq_BypC = 0;
const boolean  Ctrl_resBattItNorm_BypC = 0;
const boolean  Ctrl_rFuTnkPerc_BypC = 0;
const boolean  Ctrl_rSpdFanAct_BypC = 0;
const boolean  Ctrl_rSpdFanReq_BypC = 0;
const boolean  Ctrl_rtqOBD_BypC = 0;
const boolean  Ctrl_spdEspVeh_BypC = 0;
const boolean  Ctrl_spdFilGearSen_BypC = 0;
const boolean  Ctrl_spdLeFrntWhl_BypC = 0;
const boolean  Ctrl_spdLeReWhl_BypC = 0;
const boolean  Ctrl_spdRawGearSen_BypC = 0;
const boolean  Ctrl_spdRiFrntWhl_BypC = 0;
const boolean  Ctrl_spdRiReWhl_BypC = 0;
const boolean  Ctrl_spdVehAvrFrntWhl_BypC = 0;
const boolean  Ctrl_stBSIKeyImmo_BypC = 0;
const boolean  Ctrl_stCMMStImmoReq_BypC = 0;
const boolean  Ctrl_stCMMStImmoSnd_BypC = 0;
const boolean  Ctrl_stCnvClu_BypC = 0;
const boolean  Ctrl_stCpl_BypC = 0;
const boolean  Ctrl_stCtlModFSF_BypC = 0;
const boolean  Ctrl_stDftCod_BypC = 0;
const boolean  Ctrl_stDragRed_BypC = 0;
const boolean  Ctrl_stElLvlProd_BypC = 0;
const boolean  Ctrl_stEngOpm_BypC = 0;
const boolean  Ctrl_stEPB_BypC = 0;
const boolean  Ctrl_stFuLvlDft_BypC = 0;
const boolean  Ctrl_stFuSlowCorbank1_BypC = 0;
const boolean  Ctrl_stFuSpdCorbank1_BypC = 0;
const boolean  Ctrl_stGBxDft_BypC = 0;
const boolean  Ctrl_stGearCtlReq_BypC = 0;
const boolean  Ctrl_stGearRat_BypC = 0;
const boolean  Ctrl_stGSTyp_BypC = 0;
const boolean  Ctrl_stJDDEmi_BypC = 0;
const boolean  Ctrl_stNRegTyp_BypC = 0;
const boolean  Ctrl_stPosnCoVlvEstim_BypC = 0;
const boolean  Ctrl_stUCCKeyImmo_BypC = 0;
const boolean  Ctrl_stUnBlockAuthImmo_BypC = 0;
const boolean  Ctrl_stUnBlockReq_BypC = 0;
const boolean  Ctrl_stWkuMain_BypC = 0;
const boolean  Ctrl_tAirExtMes_BypC = 0;
const boolean  Ctrl_tAirExtMes5B2_BypC = 0;
const boolean  Ctrl_tBattMes_BypC = 0;
const boolean  Ctrl_tCoMesFineResl_BypC = 0;
const boolean  Ctrl_tDsThrMes_BypC = 0;
const boolean  Ctrl_tiCurVehTmr_BypC = 0;
const boolean  Ctrl_tiVehCnt_BypC = 0;
const boolean  Ctrl_tOilEstim_BypC = 0;
const boolean  Ctrl_tOilGBx_BypC = 0;
const boolean  Ctrl_tqAirASRReq_BypC = 0;
const boolean  Ctrl_tqAirDrvFil_BypC = 0;
const boolean  Ctrl_tqCkCAN_BypC = 0;
const boolean  Ctrl_tqCkEngReal_BypC = 0;
const boolean  Ctrl_tqEfcLim_BypC = 0;
const boolean  Ctrl_tqMaxGBx_BypC = 0;
const boolean  Ctrl_tqMinGBxMsg_BypC = 0;
const boolean  Ctrl_tqMSRReq_BypC = 0;
const boolean  Ctrl_tqReqGBx_BypC = 0;
const boolean  Ctrl_tqRevAcv_BypC = 0;
const boolean  Ctrl_tqSumLossCmp_BypC = 0;
const boolean  Ctrl_tqWhlPTPotReq_BypC = 0;
const boolean  Ctrl_uBattMinCkg_BypC = 0;
const boolean  Ctrl_uBattRstrt_BypC = 0;
const boolean  Ctrl_uEngOilLvl_BypC = 0;
const boolean  Ctrl_uReqProdElec_BypC = 0;
const boolean  Ctrl_vLeReWhlMes_BypC = 0;
const boolean  Ctrl_volFuCnsTot_BypC = 0;
const boolean  Ctrl_vRiReWhlMes_BypC = 0;
const boolean  EcuSt_bKeyOffForce_BypC = 0;
const boolean  EngReqH_bInhCanPurg_BypC = 0;
const boolean  EngReqH_bInhLrnAFA_BypC = 0;
const boolean  EOM_bInhTqSysRich_BypC = 0;
const boolean  Ext_bAcvProtBrk_BypC = 0;
const boolean  Ext_bAcvSpcInjModProtECU_BypC = 0;
const boolean  Ext_bCfDiagBit2StDftOBD_BypC = 0;
const boolean  Ext_bCfDiagBit3StDftOBD_BypC = 0;
const boolean  Ext_bCfDiagBit4StDftOBD_BypC = 0;
const boolean  Ext_bCfDiagBit7StDftOBD_BypC = 0;
const boolean  Ext_bFlexCf_BypC = 0;
const boolean  Ext_bLiMILReqHCU2_BypC = 0;
const boolean  Ext_bLiMILReqSCT_BypC = 0;
const boolean  Ext_bMILReqCntRstAR2S_BypC = 0;
const boolean  Ext_bMILReqCntRstHCU2_BypC = 0;
const boolean  Ext_bMILReqCntRstTBMU_BypC = 0;
const boolean  Ext_bPostRunReq_BypC = 0;
const boolean  FEI_bAcvNEngFEIAftsByp_BypC = 0;
const boolean  Flev_low_fuel_level_fil_BypC = 0;
const boolean  Flex_bInhDiagOBDAlcEst_BypC = 0;
const boolean  Flex_bInhDiagOBDAlcRate_BypC = 0;
const boolean  Flex_bInhDiagOBDBlby_BypC = 0;
const boolean  Gear_bRvsFil_BypC = 0;
const boolean  KnkTreat_bInhKnkDet_BypC = 0;
const boolean  NORIA_bNEngAftsReq_BypC = 0;
const boolean  PFlt_bAcvNTarIdlRgnAfts_BypC = 0;
const boolean  PredEs_bVldAgEsPred_BypC = 0;
const boolean  PredEs_bVldFastNPred_BypC = 0;
const boolean  Saf_power_latch_BypC = 0;
const boolean  SftyMgt_bDeacIrvVSReg_BypC = 0;
const boolean  Srv_bAcvExNormCln_BypC = 0;
const boolean  Srv_bAcvVlvActNormCln_BypC = 0;
const boolean  Sync_bBackUpCkSig_BypC = 0;
const boolean  Toil_power_latch_BypC = 0;
const boolean  TqRes_bCdnAC5Res_BypC = 0;
const boolean  TqSys_bAcvVlvSysOptmVac_BypC = 0;
const boolean  TqSys_bIniIdlReq_BypC = 0;
const boolean  TqSys_bInjCutProtAC_BypC = 0;
const boolean  TqSys_bSpcCmbSel_BypC = 0;
const boolean  UCE_bCAN1ComNd_BypC = 0;
const boolean  UCE_bCAN2ComNd_BypC = 0;
const boolean  UCE_bCAN3ComNd_BypC = 0;
const boolean  UCE_bLINComNd_BypC = 0;
const boolean  VSCtl_bKdAuthVSLim_BypC = 0;
const boolean  WaPmp_bAcvWaPmp_BypC = 0;
const uint32  EGRVlv_rOpClsEGRVlvBol_BypC = 0;
const uint32  Ext_stECUMiss_BypC = 0;
const uint32  Richesse_maximale_CMG_BypC = 0;
const uint32  Tra_spdVeh_nEng1000_BypC = 0;
const sint8  Lbda_lean_attenuation_gain_BypC = 0;
const sint8  Lbda_rich_attenuation_gain_BypC = 0;
const uint8  Afts_stBypTarIdl_BypC = 0;
const uint8  AirSys_effEGRFlex_BypC = 0;
const uint8  AirSys_effEGRGas_BypC = 0;
const uint8  Can_329ChkInit_C = 0;
const uint8  Can_349ChkInit_C = 0;
const uint8  Can_38DChkInit_C = 0;
const uint8  Cat_seuil_obd_flex_BypC = 0;
const uint8  DrvIf_stLevAuth_BypC = 0;
const uint8  Esp_proc_false_max = 0;
const uint8  Ext_bfMstPtlWkuHldReq_BypC = 0;
const uint8  Ext_bfMstPtlWkuNd_BypC = 0;
const uint8  Ext_iCtlAltBSSExct_BypC = 0;
const uint8  Ext_idxCtlAltBSSProvIdf_BypC = 0;
const uint8  Ext_noSupvDTC_BypC = 0;
const uint8  Ext_prm_idxFuTypCyl_BypC[EXT_PRM_IDXFUTYPCYL_BYPC_COLS] = {0};
const uint8  Ext_rCtlAltBSSCycOp_BypC = 0;
const uint8  Ext_rSpdFanPredB2_BypC = 0;
const uint8  Ext_rSpdFanPredC_BypC = 0;
const uint8  Ext_stAltClasBSSCf_BypC = 0;
const uint8  Ext_stFuSpdCorbank2_BypC = 0;
const uint8  Ext_stPwrSys2_BypC = 0;
const uint8  Ext_stSysGas_BypC = 0;
const uint8  Ext_tiMonRunDMTRtoCMM_C = 0;
const uint8  Ext_TrbAct_rCtl_CurMes_BypC = 0;
const uint8  Ext_uBattMaxDMTRtoCMM_C = 0;
const uint8  GSI_stDrvTraSys_BypC = 0;
const uint8  ISCAN_u8Compteur_RX_26C_BypC = 0;
const uint8  ISCAN_u8N2F50DPM1298_BypC = 0;
const uint8  Lbda_lg_lump_lean_idle_flex_BypC = 0;
const uint8  Lbda_lg_lump_non_idle_flex_BypC = 0;
const uint8  Lbda_lg_lump_rich_idle_flex_BypC = 0;
const uint8  Lbda_lump_lean_idle_flex_BypC = 0;
const uint8  Lbda_lump_lean_non_idle_fle_BypC = 0;
const uint8  Lbda_lump_rich_idle_flex_BypC = 0;
const uint8  Lbda_lump_rich_non_idle_fle_BypC = 0;
const uint8  Lbda_step_lean_non_idle_fle_BypC = 0;
const uint8  Lbda_step_rich_non_idle_fle_BypC = 0;
const uint8  Lffc_l_r_no_idle_dly_emis_f_BypC = 0;
const uint8  Lffc_l_r_no_idle_dly_neuf_f_BypC = 0;
const uint8  Lffc_r_l_no_idle_dly_emis_f_BypC = 0;
const uint8  Lffc_r_l_no_idle_dly_neuf_f_BypC = 0;
const uint8  Network_first_can_baudrate = 0;
const uint8  PaDyn_rBoostModSpt_BypC = 0;
const uint8  PredEs_agUncrtEsPred_BypC = 0;
const uint8  Srv_prm_nCornEngCyl1_eep_BypC[SRV_PRM_NCORNENGCYL1_EEP_BYPC_COLS] = {0};
const uint8  Srv_prm_nCornEngCyl2_eep_BypC[SRV_PRM_NCORNENGCYL2_EEP_BYPC_COLS] = {0};
const uint8  Srv_prm_nCornEngCyl3_eep_BypC[SRV_PRM_NCORNENGCYL3_EEP_BYPC_COLS] = {0};
const sint16  Afts_nBypTarIdl_BypC = 0;
const sint16  CoCha_tqEfcMSRReq_BypC = 0;
const sint16  CoPt_tqAirReqGBx_BypC = 0;
const sint16  CoPt_tqReqGBx_BypC = 0;
const sint16  Ext_tUcapMes_BypC = 0;
const sint16  IgSys_agIgCmbModOfsMinTherm_BypC = 0;
const sint16  PredEs_nFastPred_BypC = 0;
const sint16  Tde_torque_correction_BypC = 0;
const sint16  Tpac_measured_current_BypC = 0;
const sint16  Tpac_request_throttle_duty_BypC = 0;
const sint16  TqCmp_tqLossExtSpc_BypC = 0;
const sint16  TqSys_tqAdvAntiBoil_BypC = 0;
const sint16  TqSys_tqAdvOverSpdProt_BypC = 0;
const sint16  TqSys_tqAirAntiBoil_BypC = 0;
const sint16  TqSys_tqAirOverSpdProt_BypC = 0;
const sint16  TqSys_tqIniIdlReq_BypC = 0;
const sint16  Tra_tqReqClu_BypC = 0;
const uint16  Afts_nTarIdlHybMod_BypC = 0;
const uint16  AirMon_nEngAftsDiag_BypC = 0;
const uint16  AirSys_effCycFlex_BypC = 0;
const uint16  AirSys_effCycGas_BypC = 0;
const uint16  AirSys_prm_effAfrFlex_BypC[AIRSYS_PRM_EFFAFRFLEX_BYPC_COLS] = {0};
const uint16  AirSys_prm_effAfrGas_BypC[AIRSYS_PRM_EFFAFRGAS_BYPC_COLS] = {0};
const uint16  Cat_seuil_obd_pond_flex_BypC = 0;
const uint16  CoPt_nTarIdl_BypC = 0;
const uint16  ExM_cppIngFlex_BypC = 0;
const uint16  Ext_iCurMes_BypC = 0;
const uint16  Ext_rDuCyReqTestMod_BypC = 0;
const uint16  Ext_rOpTrbActMesSI_BypC = 0;
const uint16  FARSp_rMixtSpAntiStall_BypC = 0;
const uint16  FEI_nEngFEIAftsReq_BypC = 0;
const uint16  IdlSys_nSpcTarIdlDyn_BypC = 0;
const uint16  InjSys_facAstWupCmpAdpFlex_BypC = 0;
const uint16  InjSys_facInjResuAdpFlex_BypC = 0;
const uint16  InjSys_facStoichAdpFlex_BypC = 0;
const uint16  InjSys_facStrtCorFlex_BypC = 0;
const uint16  InjSys_facStrtCorGas_BypC = 0;
const uint16  InjSys_prm_facFlexResuCyl_BypC[INJSYS_PRM_FACFLEXRESUCYL_BYPC_COLS] = {0};
const uint16  InjSys_prm_facGasResuCyl_BypC[INJSYS_PRM_FACGASRESUCYL_BYPC_COLS] = {0};
const uint16  Lbda_attenuation_gain_pond_BypC = 0;
const uint16  Lbda_lump_non_idle_pond_fle_BypC = 0;
const uint16  Lbda_maint_att_dly_pond_fle_BypC = 0;
const uint16  Lbda_maintien_attenu_delay_BypC = 0;
const uint16  Lbda_step_non_idle_pond_fle_BypC = 0;
const uint16  Lffc_non_idle_dly_pond_flex_BypC = 0;
const uint16  NORIA_nEngAftsSp_BypC = 0;
const uint16  PaDyn_pBoostModSpt_BypC = 0;
const uint16  PFlt_nTarIdlRgnAftsReq_BypC = 0;
const uint16  PredEs_agEsPred_BypC = 0;
const uint16  Temps_injection_entre_pmh_BypC = 0;
const uint16  TqCmp_pwrAC5Loss_BypC = 0;
const uint16  TqRes_tqAC5Res_BypC = 0;
const uint16  TqRes_tqGasModRes_BypC = 0;
const uint16  TqSys_facTranSpcAirSys_BypC = 0;
const uint16  TqSys_nTarIdlGBxMax_BypC = 0;
const uint16  TqSys_nTarIdlGBxMin_BypC = 0;
const uint16  TqSys_nTarIdlStrt_BypC = 0;
#pragma section

/*-------------------------------------------------------------------------
    Variables
-------------------------------------------------------------------------*/

#define MEMSEC_START_SEC_VAR_UNSPECIFIED_CPU1
#include "MemMap.h"
uint16 OilSys_pOilReq;
uint8 Ext_stAltClasBSSCf;
uint8 Saf_status;
uint8 Ssm_pedal_pos_sensing_status;
boolean AC_bACCluDem;
boolean ActrTstHPPmp_bInjrFlowFail;
boolean Afa_panne_presente_adapt_inj;
boolean Afts_bAcvHybMod_nTarIdl;
boolean Afts_bRstMemFirstFillFuEng;
boolean AirMon_bEnaIdlCtlAftsDiag;
boolean Aux_air_pump_disabled;
boolean Cc_defaut_rvv_lvv_mux;
boolean Cf_bAcvLnrClimSenAcq;
boolean Cf_bRvsFilConf;
boolean Cipd_bAgDifPha;
boolean Cipd_phase_calculated_uncertain;
boolean Cipd_phase_terminated;
boolean Cl_presence_clim_bsi;
boolean CoHVB_bMILReq;
boolean CoPt_bTarIdlInc;
boolean CoPTSt_bDgoSftyORngAM;
boolean Ctrl_aLgtGearSen;
boolean Ctrl_aVeh;
boolean Ctrl_bABSReg;
boolean Ctrl_bAccPTra;
boolean Ctrl_bAcv_bAcvElCnsReq;
boolean Ctrl_bAcv_bAcvSftyWarn;
boolean Ctrl_bAcv_bBrkPark;
boolean Ctrl_bAcv_bDftFctEM;
boolean Ctrl_bAcv_bLiRegESPASR;
boolean Ctrl_bAcv_bRCDLine;
boolean Ctrl_bAcv_ctClcProc3B8;
boolean Ctrl_bAcv_dstVehTotMesIS552;
boolean Ctrl_bAcv_dstVehTotMesIS7F2;
boolean Ctrl_bAcv_grdNegSlop;
boolean Ctrl_bAcv_grdPosSlop;
boolean Ctrl_bAcv_noIdFrame;
boolean Ctrl_bAcv_noJDDKm;
boolean Ctrl_bAcv_noNEngCplm;
boolean Ctrl_bAcv_noRatDrvReqCplm;
boolean Ctrl_bAcv_noTqAirDrvFilCplm;
boolean Ctrl_bAcv_noTqCkEngRealCplm;
boolean Ctrl_bAcv_noTqDrvFilCplm;
boolean Ctrl_bAcv_noVDS1;
boolean Ctrl_bAcv_noVDS2;
boolean Ctrl_bAcv_noVDS3;
boolean Ctrl_bAcv_noVDS4;
boolean Ctrl_bAcv_noVDS5;
boolean Ctrl_bAcv_noVDS6;
boolean Ctrl_bAcv_noVIS1;
boolean Ctrl_bAcv_noVIS2;
boolean Ctrl_bAcv_noVIS3;
boolean Ctrl_bAcv_noVIS4;
boolean Ctrl_bAcv_noVIS5;
boolean Ctrl_bAcv_noVIS6;
boolean Ctrl_bAcv_noVIS7;
boolean Ctrl_bAcv_noVIS8;
boolean Ctrl_bAcv_noWMI1;
boolean Ctrl_bAcv_noWMI2;
boolean Ctrl_bAcv_noWMI3;
boolean Ctrl_bAcv_stDftOBDIS5B2;
boolean Ctrl_bAcv_stDftOBDIS7F2;
boolean Ctrl_bAcv_stEngCordThm;
boolean Ctrl_bAcv_stLifeJDD;
boolean Ctrl_bAcv_stNbFrame;
boolean Ctrl_bAcv_stPwrSys2;
boolean Ctrl_bAcv_stTqReq;
boolean Ctrl_bAcv_uMax;
boolean Ctrl_bAcv_uMinInc;
boolean Ctrl_bAcvWupMod;
boolean Ctrl_bagStrWhl;
boolean Ctrl_bagvStrWhl;
boolean Ctrl_bASRRegFirst;
boolean Ctrl_bAuthCrawl;
boolean Ctrl_bAuthWupElMgt;
boolean Ctrl_bCmpReq;
boolean Ctrl_bCntMILRst;
boolean Ctrl_bctClcProc305;
boolean Ctrl_bCtlEfc_tqWhlPt;
boolean Ctrl_bDelDftReq;
boolean Ctrl_bDft;
boolean Ctrl_bDft_bBrkPedPrss;
boolean Ctrl_bDgo_iBattMes;
boolean Ctrl_bDgo_tBattMes;
boolean Ctrl_bDgo_uBattClc;
boolean Ctrl_bDiagMuxOn;
boolean Ctrl_bDrvCyGlbl;
boolean Ctrl_bEHRWaPmpReqRTE;
boolean Ctrl_bElIntgDiag;
boolean Ctrl_bElIntgDiagMod;
boolean Ctrl_bEngRStrtReqAsiDir;
boolean Ctrl_bEngRStrtReqGBx;
boolean Ctrl_bEngStopAuthAsiDir;
boolean Ctrl_bEngStopAuthGBx;
boolean Ctrl_bEngStopReq;
boolean Ctrl_bESPRegFirst;
boolean Ctrl_bfAcvConstElMgt1;
boolean Ctrl_bfAcvConstElMgt2;
boolean Ctrl_bfAcvConstElMgt3;
boolean Ctrl_bfAcvConstEm1;
boolean Ctrl_bfAcvConstEng1;
boolean Ctrl_bfAcvConstFrntTra1;
boolean Ctrl_bfAcvConstReTra1;
boolean Ctrl_bFlashLiMIL;
boolean Ctrl_bFrzAC;
boolean Ctrl_bGBxRdy;
boolean Ctrl_bGearCtlFirst;
boolean Ctrl_bImmoUnlockWkuReq;
boolean Ctrl_bInhAcqESCFrnt;
boolean Ctrl_bInhStrtAMT;
boolean Ctrl_bInhVSCtl;
boolean Ctrl_bKeyON;
boolean Ctrl_bLevMod;
boolean Ctrl_bLiIMIL;
boolean Ctrl_bLiMILReq;
boolean Ctrl_bnoCks305;
boolean Ctrl_bNRegReq;
boolean Ctrl_bOBDDftOnMIL;
boolean Ctrl_bOilMesReq;
boolean Ctrl_bOilWkuReq;
boolean Ctrl_bOpDrvTraReq;
boolean Ctrl_bPrepIgEngWkuReq;
boolean Ctrl_bPresOilWarn;
boolean Ctrl_bRStrtAuthTra;
boolean Ctrl_bRstrtTypAT;
boolean Ctrl_bSecBrkPedPrssMes;
boolean Ctrl_bSIP;
boolean Ctrl_bSIPPrep;
boolean Ctrl_bSpdFanGBxReq;
boolean Ctrl_bStaProt;
boolean Ctrl_bStopEngCoWkuReq;
boolean Ctrl_bSTTDft;
boolean Ctrl_bTqTx;
boolean Ctrl_bTypMsg;
boolean Ctrl_bWarn_tCo;
boolean Ctrl_bWUC;
boolean Ctrl_CMM_7A8;
boolean Ctrl_ctClcProc329;
boolean Ctrl_ctClcProc349;
boolean Ctrl_ctClcProc34D;
boolean Ctrl_ctClcProc38D;
boolean Ctrl_ctClcProc3AD;
boolean Ctrl_ctClcProc3C9;
boolean Ctrl_ctDayCAN;
boolean Ctrl_CtRstCurVehTmr;
boolean Ctrl_ctSecCAN;
boolean Ctrl_ctYrCAN;
boolean Ctrl_dstCntGearSen;
boolean Ctrl_iBattMaxCkg;
boolean Ctrl_idxPrfGBxMsg;
boolean Ctrl_idxPtSpt;
boolean Ctrl_IS_MAP_CMM_7A8;
boolean Ctrl_mfAirMes;
boolean Ctrl_nAvrFrntWhl;
boolean Ctrl_nEng;
boolean Ctrl_nEngAvr;
boolean Ctrl_nEngSpdMaxTq;
boolean Ctrl_noCks329;
boolean Ctrl_noCks349;
boolean Ctrl_noCks38D;
boolean Ctrl_noCks3AD;
boolean Ctrl_noCks3C9;
boolean Ctrl_noCMMSeedImmo;
boolean Ctrl_noDiag;
boolean Ctrl_noEditCal;
boolean Ctrl_noEditSw;
boolean Ctrl_noEgdGear;
boolean Ctrl_noEgdGearCord;
boolean Ctrl_noGearReqMax;
boolean Ctrl_noGearReqMin;
boolean Ctrl_noTarGear;
boolean Ctrl_noVersAdp;
boolean Ctrl_noVersSw;
boolean Ctrl_noVersSys;
boolean Ctrl_noVersSysMnth;
boolean Ctrl_noVersSysYr;
boolean Ctrl_noVerSysDay;
boolean Ctrl_nTar;
boolean Ctrl_nTarIdl;
boolean Ctrl_pAirExtMes;
boolean Ctrl_pBrkAsi;
boolean Ctrl_pDsEGRVlvMes;
boolean Ctrl_posnATLev;
boolean Ctrl_rBattSoCLoResl;
boolean Ctrl_rDrvReq;
boolean Ctrl_resBattItNorm;
boolean Ctrl_rFuTnkPerc;
boolean Ctrl_rSpdFanAct;
boolean Ctrl_rSpdFanReq;
boolean Ctrl_rtqOBD;
boolean Ctrl_spdEspVeh;
boolean Ctrl_spdFilGearSen;
boolean Ctrl_spdLeFrntWhl;
boolean Ctrl_spdLeReWhl;
boolean Ctrl_spdRawGearSen;
boolean Ctrl_spdRiFrntWhl;
boolean Ctrl_spdRiReWhl;
boolean Ctrl_spdVehAvrFrntWhl;
boolean Ctrl_stBSIKeyImmo;
boolean Ctrl_stCMMStImmoReq;
boolean Ctrl_stCMMStImmoSnd;
boolean Ctrl_stCnvClu;
boolean Ctrl_stCpl;
boolean Ctrl_stCtlModFSF;
boolean Ctrl_stDftCod;
boolean Ctrl_stDragRed;
boolean Ctrl_stElLvlProd;
boolean Ctrl_stEngOpm;
boolean Ctrl_stEPB;
boolean Ctrl_stFuLvlDft;
boolean Ctrl_stFuSlowCorbank1;
boolean Ctrl_stFuSpdCorbank1;
boolean Ctrl_stGBxDft;
boolean Ctrl_stGearCtlReq;
boolean Ctrl_stGearRat;
boolean Ctrl_stGSTyp;
boolean Ctrl_stJDDEmi;
boolean Ctrl_stNRegTyp;
boolean Ctrl_stPosnCoVlvEstim;
boolean Ctrl_stProdMgtTyp;
boolean Ctrl_stUCCKeyImmo;
boolean Ctrl_stUnBlockAuthImmo;
boolean Ctrl_stUnBlockReq;
boolean Ctrl_stWkuMain;
boolean Ctrl_tAirExtMes;
boolean Ctrl_tAirExtMes5B2;
boolean Ctrl_tBattMes;
boolean Ctrl_tCoMesFineResl;
boolean Ctrl_tDsThrMes;
boolean Ctrl_tiCurVehTmr;
boolean Ctrl_tiVehCnt;
boolean Ctrl_tOilEstim;
boolean Ctrl_tOilGBx;
boolean Ctrl_tqAirASRReq;
boolean Ctrl_tqAirDrvFil;
boolean Ctrl_tqCkCAN;
boolean Ctrl_tqCkEngReal;
boolean Ctrl_tqDynASRReq;
boolean Ctrl_tqEfcLim;
boolean Ctrl_tqMaxGBx;
boolean Ctrl_tqMinGBxMsg;
boolean Ctrl_tqMSRReq;
boolean Ctrl_tqReqGBx;
boolean Ctrl_tqRevAcv;
boolean Ctrl_tqSumLossCmp;
boolean Ctrl_tqWhlPTPotReq;
boolean Ctrl_uBattMinCkg;
boolean Ctrl_uBattRstrt;
boolean Ctrl_uEngOilLvl;
boolean Ctrl_uReqProdElec;
boolean Ctrl_vLeReWhlMes;
boolean Ctrl_volFuCnsTot;
boolean Ctrl_vRiReWhlMes;
boolean Date_emf_available_mux;
boolean ECU_bStopEngCoWkuS;
boolean EcuSt_bKeyOffForce;
boolean EngReqH_bInhCanPurg;
boolean EngReqH_bInhLrnAFA;
boolean EOM_bInhTqSysRich;
boolean Ext_bAcvProtBrk;
boolean Ext_bAuthInj;
boolean Ext_bCfDiagBit2StDftOBD;
boolean Ext_bCfDiagBit3StDftOBD;
boolean Ext_bCfDiagBit4StDftOBD;
boolean Ext_bCfDiagBit7StDftOBD;
boolean Ext_bDiagMuxOn;
boolean Ext_bFlexCf;
boolean Ext_bGasQly;
boolean Ext_bInhAcqESCFrnt;
boolean Ext_bInhTqSysOvb;
boolean Ext_bLiMILReqHCU2;
boolean Ext_bLiMILReqSCT;
boolean Ext_bMILReqCntRstAR2S;
boolean Ext_bMILReqCntRstHCU2;
boolean Ext_bMILReqCntRstTBMU;
boolean Ext_bStHaltElPmpGrp;
boolean FEI_bAcvNEngFEIAftsByp;
boolean Flev_low_fuel_level_fil;
boolean Flex_alc_rate_diag_run_uavb0;
boolean Flex_alc_rate_est_needed_uavb0;
boolean FRM_Dis_PrmDftInitLoop;
boolean Gear_bRvsFil;
boolean Inj_bInjTestDone;
boolean ISCAN_bCopyF5B2Length;
boolean ISCAN_bCopyF7F2Length;
boolean ISCAN_bF30DP265Invld;
boolean ISCAN_bF30DP266Invld;
boolean ISCAN_bF38DP010Invld;
boolean ISCAN_bF50EP210Invld;
boolean ISCAN_bF552bisP325Invld;
boolean ISCAN_bF5B2P146Invld;
boolean ISCAN_bF7F2P146bisInvld;
boolean ISCAN_bN32F552bisP325NotAvl;
boolean ISCAN_bN9F4F2P437NotAvl;
boolean Jbsi_bFirstSyncRx;
boolean KnkTreat_bInhKnkDet;
boolean Mf_adap_lw_no_rlzd_UT_uavb0;
boolean Mf_adap_shrt_no_rlzd_UT_uavb0;
boolean NORIA_bNEngAftsReq;
boolean PFlt_bAcvNTarIdlRgnAfts;
boolean PFuCtl_bDiagAcvORngPos;
boolean PredEs_bVldAgEsPred;
boolean PredEs_bVldFastNPred;
boolean Rcd_preparation_moteur_mux;
boolean Rcd_reveil_princ_mux_default;
boolean Saf_diag_request;
boolean Saf_power_latch;
boolean Sfty_bRazCountComplet;
boolean Srv_bAcvExNormCln;
boolean Srv_bAcvPlaMod;
boolean Srv_bAcvVlvActNormCln;
boolean Sync_bAcvSyncBUMCamShaft;
boolean Sync_bBackUpCkSig;
boolean Toil_power_latch;
boolean TqRes_bCdnAC5Res;
boolean TqSys_bIniIdlReq;
boolean TqSys_bInjCutProtAC;
boolean TqSys_bSpcCmbSel;
boolean VSCtl_bKdAuthVSLim;
boolean WaPmp_bAcvWaPmp;
uint32 BoostAct_rDuCyReqWoutSat;
uint32 DmgBelt_noEngStrt;
uint32 Ext_noJDDKm;
uint32 Ext_stECUMiss;
uint32 Ext_stLifeJDD;
uint32 FuSysM_tiEngStopPwrl;
uint32 Jbsi_reference_horaire;
uint32 OilDsp_mFuInOilEstim;
uint32 PFuCtl_tiPrailOvrThd;
uint32 Richesse_maximale_CMG;
uint32 Sfty_prm_IdTaskOvrrunCnt[SFTY_PRM_IDTASKOVRRUNCNT_COLS];
uint32 Tra_spdVeh_nEng1000;
sint8 Delta_sonde_aval_gaz;
sint8 Lbda_lean_attenuation_gain_flex;
sint8 Lbda_rich_attenuation_gain_flex;
sint8 Tra_noTarGear_F349;
sint8 Tra_noTarGear_F3C9;
uint8 Afts_stBypTarIdl;
uint8 Air_density_gain_pres_crk_flex;
uint8 AirSys_effEGRFlex;
uint8 AirSys_effEGRGas;
uint8 Compteur_de_pmh_raw;
uint8 CoPt_stSIPTyp;
uint8 CoPTSt_stEngCordThm;
uint8 DrvIf_stLevAuth;
uint8 Dtc_first_crank_delay_flex;
uint8 Dtc_first_crank_delay_retry_flex;
uint8 Dtc_STT_crank_delay_retry_flex;
uint8 Ecut_ecu_temperature;
uint8 Ext_aLgtGearSen;
uint8 Ext_iCtlAltBSSExct;
uint8 Ext_idxCtlAltBSSProvIdf;
uint8 Ext_mfAirMes;
uint8 Ext_noCks228;
uint8 Ext_noEditCal;
uint8 Ext_noEditSw;
uint8 Ext_noGearTar;
uint8 Ext_noSupvDTC;
uint8 Ext_noVersAdp;
uint8 Ext_noVersSw;
uint8 Ext_noVersSys;
uint8 Ext_noVersSysMnth;
uint8 Ext_noVersSysYr;
uint8 Ext_noVerSysDay;
uint8 Ext_posnAMTLev;
uint8 Ext_prm_idxFuTypCyl[EXT_PRM_IDXFUTYPCYL_COLS];
uint8 Ext_rCtlAltBSSCycOp;
uint8 Ext_rSpdFanPredB2;
uint8 Ext_rSpdFanPredC;
uint8 Ext_stFuSpdCorbank2;
uint8 Ext_stJDDEmi[EXT_STJDDEMI_COLS];
uint8 Ext_stPosATLevExtdCAN;
uint8 Ext_stPwrSys2;
uint8 Ext_TrbAct_rCtl_CurMes;
uint8 FuSysM_tFuUsPmp_NV;
uint8 GasMgt_stTranTypIp;
uint8 GSI_stDrvTraSys;
uint8 InjSys_noInCylElCmdUpd;
uint8 InjSys_stTypElCmdInjrReqPrev;
uint8 ISCAN_u8Compteur_RX_26C;
uint8 ISCAN_u8Compteur_RX_552;
uint8 ISCAN_u8N2F50DPM1298;
uint8 ISCAN_u8N4F329P230bis;
uint8 ISCAN_u8N4F349P230;
uint8 ISCAN_u8N4F38DP606;
uint8 ISCAN_u8N8F7F2P301bis;
uint8 Jbsi_acq_trame55F;
uint8 Jbsi_etat_ppal_sev;
uint8 Jbsi_shunt_bsi;
uint8 KnkMgt_ctTotRbl[KNKMGT_CTTOTRBL_LNS];
uint8 Lambda_fb_for_saf_diag_thresh;
uint8 Lbda_lg_lump_lean_idle_flex;
uint8 Lbda_lg_lump_non_idle_flex;
uint8 Lbda_lg_lump_rich_idle_flex;
uint8 Lbda_lump_lean_idle_flex;
uint8 Lbda_lump_lean_non_idle_flex;
uint8 Lbda_lump_rich_idle_flex;
uint8 Lbda_lump_rich_non_idle_flex;
uint8 Lbda_step_lean_non_idle_flex;
uint8 Lbda_step_rich_non_idle_flex;
uint8 Lffc_l_r_no_idle_dly_emis_flx;
uint8 Lffc_l_r_no_idle_dly_neuf_flx;
uint8 Lffc_r_l_no_idle_dly_emis_flx;
uint8 Lffc_r_l_no_idle_dly_neuf_flx;
uint8 PaDyn_rBoostModSpt;
uint8 PredEs_agUncrtEsPred;
uint8 Srv_prm_nCornEngCyl1_eep[SRV_PRM_NCORNENGCYL1_EEP_COLS];
uint8 Srv_prm_nCornEngCyl2_eep[SRV_PRM_NCORNENGCYL2_EEP_COLS];
uint8 Srv_prm_nCornEngCyl3_eep[SRV_PRM_NCORNENGCYL3_EEP_COLS];
uint8 Tele_available_xvv;
uint8 TqLim_tqReqGlblTqRaw;
sint16 Afts_nBypTarIdl;
sint16 Cha_tqAirASRReq;
sint16 Cha_tqAirMSRReq;
sint16 CoCha_tqEfcMSRReq;
sint16 CoPt_tqAirReqGBx;
sint16 CoPt_tqReqGBx;
sint16 Delta_lam_gaz;
sint16 Dtc_first_crank_offset_crk;
sint16 Dtc_first_crank_offset_flex;
sint16 Dtc_first_crank_offset_rtry_flex;
sint16 Dtc_STT_crank_offset_retry_flex;
sint16 InjSys_InjClsRespCor_prmtiOfsH1[INJSYS_INJCLSRESPCOR_PRMTIOFSH1_COLS];
sint16 PredEs_nFastPred;
sint16 Tde_torque_correction;
sint16 Tpac_measured_current;
sint16 Tpac_request_throttle_duty_cycle;
sint16 TqCmp_tqLossExtSpc;
sint16 TqSys_tqAdvAntiBoil;
sint16 TqSys_tqAdvOverSpdProt;
sint16 TqSys_tqAirAntiBoil;
sint16 TqSys_tqAirOverSpdProt;
sint16 TqSys_tqIniIdlReq;
sint16 Wg_rWgServoElmAdpvCmd;
uint16 Afts_nTarIdlHybMod;
uint16 Air_density_gain_crk_pond_flex;
uint16 AirMon_nEngAftsDiag;
uint16 AirSys_effCycFlex;
uint16 AirSys_effCycGas;
uint16 AirSys_prm_effAfrFlex[AIRSYS_PRM_EFFAFRFLEX_COLS];
uint16 AirSys_prm_effAfrGas[AIRSYS_PRM_EFFAFRGAS_COLS];
uint16 Aps_1_filtered_position;
uint16 Aps_1_raw_filt_position;
uint16 Aps_2_formated_position;
uint16 Aps_2_raw_filt_position;
uint16 Bat_rBattSoC_4F2;
uint16 BoostAct_rDuCyReq;
uint16 CoPt_nEngSpdMaxTq;
uint16 CoPt_nTarIdl;
uint16 Dtc_crank_decay_pond_flex;
uint16 Dtc_crank_delay_pond_flex;
uint16 Dtc_crank_offset_pond_flex;
uint16 Dtc_first_crank_decay_flex;
uint16 Dtc_first_crank_decay_retry_flex;
uint16 Dtc_STT_crank_decay_retry_flex;
uint16 Dv_position_pedal_relative_aps;
uint16 Egr_relative_needle_pos;
uint16 Ext_iBrutMesOilPmp;
uint16 Ext_iCurMes;
uint16 Ext_rDuCyReqTestMod;
uint16 Ext_spdFilGearSen;
uint16 Ext_spdRawGearSen;
uint16 FARSp_rMixtSpAntiStall;
uint16 FEI_nEngFEIAftsReq;
uint16 Flex_tiDiagOBDAlcEst;
uint16 FuSysM_tFu_NV;
uint16 IdlSys_nSpcTarIdlDyn;
uint16 IgSys_facTarAgCorFlex;
uint16 IgSys_facTarAgCorGas;
uint16 IgSys_rMinThermoIgEfc;
uint16 InjSys_facAstWupCmpAdpFlex;
uint16 InjSys_facFuTranCor;
uint16 InjSys_facInjResuAdpFlex;
uint16 InjSys_facStoichAdpFlex;
uint16 InjSys_facStrtCorFlex;
uint16 InjSys_facStrtCorGas;
uint16 InjSys_prm_facFlexResuCyl[INJSYS_PRM_FACFLEXRESUCYL_COLS];
uint16 InjSys_prm_facGasResuCyl[INJSYS_PRM_FACGASRESUCYL_COLS];
uint16 KnkMgt_ctInjCutOffRbl[KNKMGT_CTINJCUTOFFRBL_COLS];
uint16 Lbda_attenuation_gain_pond_flex;
uint16 Lbda_lump_non_idle_pond_flex;
uint16 Lbda_maint_att_dly_pond_flex;
uint16 Lbda_maintien_attenu_delay_flex;
uint16 Lbda_step_non_idle_pond_flex;
uint16 Lffc_non_idle_dly_pond_flex;
uint16 NORIA_nEngAftsSp;
uint16 PaDyn_pBoostModSpt;
uint16 PFlt_nTarIdlRgnAftsReq;
uint16 PredEs_agEsPred;
uint16 Sfty_Count_TaskOvrrunCnt;
uint16 SftyMgt_rCluPHiFreq;
uint16 Temps_injection_entre_pmh;
uint16 Thr_ctAuthCloThr;
uint16 TqCmp_pwrAC5Loss;
uint16 TqRes_tqAC5Res;
uint16 TqRes_tqGasModRes;
uint16 TqSys_facTranSpcAirSys;
uint16 TqSys_nTarIdlGBxMax;
uint16 TqSys_nTarIdlGBxMin;
uint16 TqSys_nTarIdlStrt;
#define MEMSEC_STOP_SEC_VAR_UNSPECIFIED_CPU1
#include "MemMap.h"
/*-------------------------------------------------------------------------
    Porteurs de bits
-------------------------------------------------------------------------*/


/*-------------------------------------------------------------------------
    Prototypes
-------------------------------------------------------------------------*/

