/*******************************************************************************
*                    Delphi Diesel Systems
*
*                    This document is the property of
*                    Delphi Diesel Systems
*                    It must not be copied (in whole or in part)
*                    or disclosed without prior written consent
*                    of the company. Any copies by any method
*                    must also include a copy of this legend.
********************************************************************************
* Task File History: This comment block is automatically
*                    updated by the configuration management tool
*                    DO NOT Update manually
*------------------------------------------------------------------------------*
*
* Ref X:\integration_view_00PSASWC_D620D01\blois_psa_sstg\Software\Appli\VSMax\src\VSMax.c
* Version int :/main/00PSASWC_D6/5 Date: 6/1/2012 12 h 3 m User:meme 
*    TWK_model:NO_MODEL
*    comments :for VSMax 12.0
* Version dev :\main\branch_demezil_vsmax_view\1 Date: 5/1/2012 17 h 21 m User:demezil 
*    TWK_model:NO_MODEL
*    comments :for VSMax 12.0
* Version dev :\main\branch_halouane_vsmax_euro6\1 Date: 5/1/2012 14 h 33 m User:halouane
*    TWK_model:NO_MODEL
*    comments :For VSMax_12_0_e6
*
*******************************************************************************/

/*******************************************************************************
*  Tool Name: swc_main_code_generator Euro6
*  Tool Version: 1.01
*  Date : Tue Jan  3 11:20:25 2012
*  Prototype Generated by pztl10
*******************************************************************************/

/*******************************************************************************
*  Library Include Files
*******************************************************************************/

#include "dds_lib.h"

/*******************************************************************************
*  Software Component API Header File
*******************************************************************************/

#include "VSMax.h"

/*******************************************************************************
*  Check Library Version
*******************************************************************************/

#if VSMAX_DDS_LIB_VERSION_REQ > DDS_LIB_VERSION
dds_lib.* version is not compatible with current SWC version
#endif

/*******************************************************************************
*  File Macro Definitions
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  File Level Type Definitions
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  Software Component Level Variables: Inputs from other Files
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  Software Component Level Constants: Inputs from other Files
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  Software Component Level Calibration: Inputs from other Files
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  Software Component Level Scalar Calibration Definitions: Outputs to other Files
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  Software Component Level Map Calibration Definitions: Outputs to other Files
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  Software Component Level Non-displayable Variables: Outputs to other Files
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  Software Component Level Displayable Variables: Outputs to other Files
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  Software Component Level Constants: Outputs to other Files
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  File Scope Scalar Calibration Definitions
*******************************************************************************/

/* 32-bits scalar calibration definition */
#define VSMAX_START_SEC_CALIB_32BIT
#include "VSMax_MemMap.h"
STATIC volatile CONST(UInt32, AUTOMATIC) VSCtl_dstVehTotMes_DeacVSMax_B = (CONST(UInt32, AUTOMATIC))(0 * BIN0);
#define VSMAX_STOP_SEC_CALIB_32BIT
#include "VSMax_MemMap.h"

/* 16-bits scalar calibration definition */
#define VSMAX_START_SEC_CALIB_16BIT
#include "VSMax_MemMap.h"
STATIC volatile CONST(SInt16, AUTOMATIC) VSCtl_aVeh_DeacVSMax_B = (CONST(SInt16, AUTOMATIC))(0 * BIN10);
STATIC volatile CONST(SInt16, AUTOMATIC) VSCtl_aVehPotVSMaxReq_B = (CONST(SInt16, AUTOMATIC))(10 * BIN10);
STATIC volatile CONST(SInt16, AUTOMATIC) VSCtl_aVehVSMaxReq_B = (CONST(SInt16, AUTOMATIC))(10 * BIN10);
STATIC volatile CONST(SInt16, AUTOMATIC) VSCtl_aVehVSMaxReq_DeacVSMax_B = (CONST(SInt16, AUTOMATIC))(10 * BIN10);
STATIC volatile CONST(SInt16, AUTOMATIC) VSCtl_jrkVeh_DeacVSMax_B = (CONST(SInt16, AUTOMATIC))(0 * BIN7);
STATIC volatile CONST(SInt16, AUTOMATIC) VSCtl_jrkVehReqDeacVSMax_B = (CONST(SInt16, AUTOMATIC))(0 * BIN7);
STATIC volatile CONST(UInt16, AUTOMATIC) VSCtl_rAccP_DeacVSMax_B = (CONST(UInt16, AUTOMATIC))(100 * BIN7);
STATIC volatile CONST(UInt16, AUTOMATIC) VSCtl_rCtlTqWhlPTPotVSMax_B = (CONST(UInt16, AUTOMATIC))(0 * BIN4);
STATIC volatile CONST(SInt16, AUTOMATIC) VSCtl_rSlop_DeacVSMax_B = (CONST(SInt16, AUTOMATIC))(0 * BIN7);
STATIC volatile CONST(UInt16, AUTOMATIC) VSCtl_spdVeh_DeacVSMax_B = (CONST(UInt16, AUTOMATIC))(0 * BIN7);
STATIC volatile CONST(SInt16, AUTOMATIC) VSCtl_spdVehErrVSMax_B = (CONST(SInt16, AUTOMATIC))(0 * BIN7);
STATIC volatile CONST(UInt16, AUTOMATIC) VSCtl_spdVehVSMaxReq_B = (CONST(UInt16, AUTOMATIC))(255 * BIN7);
STATIC volatile CONST(UInt16, AUTOMATIC) VSCtl_spdVehReqDeacVSMax_B = (CONST(UInt16, AUTOMATIC))(0 * BIN7);
STATIC volatile CONST(UInt16, AUTOMATIC) VSCtl_stDeacVSMaxReq_no1_B = (CONST(UInt16, AUTOMATIC))(16383 * BIN0);
STATIC volatile CONST(UInt16, AUTOMATIC) VSCtl_stDeacVSMaxReq_no2_B = (CONST(UInt16, AUTOMATIC))(16383 * BIN0);
STATIC volatile CONST(UInt16, AUTOMATIC) VSCtl_tiCfmSdwnVSMaxReq_B = (CONST(UInt16, AUTOMATIC))(0 * DEC2);
STATIC volatile CONST(UInt16, AUTOMATIC) VSCtl_tiCfmSupVSMaxReq_B = (CONST(UInt16, AUTOMATIC))(0 * DEC2);
#define VSMAX_STOP_SEC_CALIB_16BIT
#include "VSMax_MemMap.h"

/* 8-bits scalar calibration definition */
#define VSMAX_START_SEC_CALIB_8BIT
#include "VSMax_MemMap.h"
STATIC volatile CONST(UInt8, AUTOMATIC) VSMAX_ACTIVE_BYP_C = DDS_FALSE;

STATIC volatile CONST(SInt8, AUTOMATIC) VSCtl_noGearEgd_DeacVSMax_B = VSCTL_NOGEAREGD_DEACVSMAX_NEUTRE;
STATIC volatile CONST(UInt8, AUTOMATIC) VSCtl_posnGBxDeacVSMax_B = (UInt8)VSMAX_COPT_NOEGDGEARCORDIT_NEUTRE;
STATIC volatile CONST(UInt8, AUTOMATIC) VSCtl_bCtl_aVehPotVSMax_B = VSCTL_BTCTL_AVEHPOTVSMAX_ARRET;
STATIC volatile CONST(UInt8, AUTOMATIC) VSCtl_stCtl_aVehVSMax_B = VSCTL_STCTL_AVEHVSMAX_ARRET;
STATIC volatile CONST(UInt8, AUTOMATIC) VSCtl_stRec_stDeacVSMaxReq1_B = VSCTL_STREC_STDEACVSMAXREQ1_ATTENTE;
STATIC volatile CONST(UInt8, AUTOMATIC) VSCtl_stRec_stDeacVSMaxReq2_B = VSCTL_STREC_STDEACVSMAXREQ1_ATTENTE;
STATIC volatile CONST(UInt8, AUTOMATIC) VSCtl_stVSMax_DeacVSMax_B = VSCTL_STVSMAX_DEACVSMAX_ARRET;
STATIC volatile CONST(UInt8, AUTOMATIC) VSCtl_stVSMaxExtd_B = VSCTL_STVSMAX_DEACVSMAX_ARRET;
STATIC volatile CONST(UInt8, AUTOMATIC) VSCtl_stVSMaxPrev_DeacVSMax_B = VSCTL_STVSMAX_DEACVSMAX_ARRET;
#define VSMAX_STOP_SEC_CALIB_8BIT
#include "VSMax_MemMap.h"

/*******************************************************************************
*  File Scope Map Calibration Definitions
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  File Scope Non-displayable Variable Definitions
*******************************************************************************/

/* 8-bits variables definition */
#define VSMAX_START_SEC_VAR_8BIT
#include "VSMax_MemMap.h"
/* prev for DEM used in SET_DEM_EVENT_STATUS */
STATIC VAR(UInt8, AUTOMATIC) vsctl_bmonrunvsmax_prev;
STATIC VAR(UInt8, AUTOMATIC) vsctl_bmonrunvsmaxp_prev;
#define VSMAX_STOP_SEC_VAR_8BIT
#include "VSMax_MemMap.h"

/*******************************************************************************
*  File Scope Displayable Variable Definitions
*******************************************************************************/

/*******************************************************************************
*  File Scope Constant Definitions
*******************************************************************************/

#define VSMAX_START_SEC_CONST_VERSION_MODULE_8BIT
#include "VSMax_MemMap.h"
/* <PRQA_COMMENT><3211> This constant has to be declared as if it is not used </3211></PRQA_COMMENT> */
_DDS_STATIC_ CONST(UInt8, AUTOMATIC) VSMax_ModuleVersion_Major_MP = (UInt8)12;
/* <PRQA_COMMENT><3211> This constant has to be declared as if it is not used </3211></PRQA_COMMENT> */
_DDS_STATIC_ CONST(UInt8, AUTOMATIC) VSMax_ModuleVersion_Minor_MP = (UInt8)0;
#define VSMAX_STOP_SEC_CONST_VERSION_MODULE_8BIT
#include "VSMax_MemMap.h"

/*******************************************************************************
*  File Local Function Prototypes
*******************************************************************************/

/* NONE */

/*******************************************************************************
*  Runnables Definition
*******************************************************************************/

#define VSMAX_START_SEC_CODE
#include "VSMax_MemMap.h"

/*******************************************************************************
*
*  Runnable Name    : RE_VSMax_001_MSE
*  Event            : on ECU power on
*  Description      : Call initialisation functions
*
*******************************************************************************/

FUNC(void, AUTOMATIC) RE_VSMax_001_MSE(void)
{
    /* OUTPUT */
    /* SWC OUT */
    SInt16 vsctl_aveh_deacvsmax_swc_out;
    SInt16 vsctl_avehpotvsmaxreq_swc_out;
    SInt16 vsctl_avehvsmaxreq_swc_out;
    SInt16 vsctl_avehvsmaxreq_deacvsmax_swc_out;
    UInt32 vsctl_dstvehtotmes_deacvsmax_swc_out;
    SInt16 vsctl_jrkveh_deacvsmax_swc_out;
    SInt16 vsctl_jrkvehreqdeacvsmax_swc_out;
    SInt8 vsctl_nogearegd_deacvsmax_swc_out;
    UInt8 vsctl_posngbxdeacvsmax_swc_out;
    UInt16 vsctl_raccp_deacvsmax_swc_out;
    UInt16 vsctl_rctltqwhlptpotvsmax_swc_out;
    SInt16 vsctl_rslop_deacvsmax_swc_out;
    UInt16 vsctl_spdveh_deacvsmax_swc_out;
    SInt16 vsctl_spdveherrvsmax_swc_out;
    UInt16 vsctl_spdvehvsmaxreq_swc_out;
    UInt16 vsctl_spdvehreqdeacvsmax_swc_out;
    UInt8 vsctl_bctl_avehpotvsmax_swc_out;
    UInt8 vsctl_stctl_avehvsmax_swc_out;
    UInt16 vsctl_stdeacvsmaxreq_no1_swc_out;
    UInt16 vsctl_stdeacvsmaxreq_no2_swc_out;
    UInt8 vsctl_strec_stdeacvsmaxreq1_swc_out;
    UInt8 vsctl_strec_stdeacvsmaxreq2_swc_out;
    UInt8 vsctl_stvsmax_deacvsmax_swc_out;
    UInt8 vsctl_stvsmaxextd_swc_out;
    UInt8 vsctl_stvsmaxprev_deacvsmax_swc_out;
    UInt16 vsctl_ticfmsdwnvsmaxreq_swc_out;
    UInt16 vsctl_ticfmsupvsmaxreq_swc_out;
    /* DEM (bDgo and bMonRun) */
    UInt8 vsctl_bmonrunvsmax_dem_out;
    UInt8 vsctl_bdgovsmax_dem_out;
    UInt8 vsctl_bmonrunvsmaxp_dem_out;
    UInt8 vsctl_bdgovsmaxp_dem_out;


 VSMAX_Re002tev_Sf_Init(&vsctl_avehvsmaxreq_deacvsmax_swc_out,                 /*BIN10*/
                            &vsctl_stdeacvsmaxreq_no1_swc_out,                     /*BIN0*/
                            &vsctl_stdeacvsmaxreq_no2_swc_out,                     /*BIN0*/
                            &vsctl_bdgovsmaxp_dem_out,
                            &vsctl_avehvsmaxreq_swc_out,                           /*BIN10*/
                            &vsctl_strec_stdeacvsmaxreq1_swc_out,
                            &vsctl_stctl_avehvsmax_swc_out,
                            &vsctl_strec_stdeacvsmaxreq2_swc_out,
                            &vsctl_posngbxdeacvsmax_swc_out,
                            &vsctl_aveh_deacvsmax_swc_out,                         /*BIN10*/
                            &vsctl_bmonrunvsmaxp_dem_out,
                            &vsctl_spdvehvsmaxreq_swc_out,                         /*BIN7*/
                            &vsctl_ticfmsupvsmaxreq_swc_out,                       /*DEC2*/
                            &vsctl_spdveherrvsmax_swc_out,                         /*BIN7*/
                            &vsctl_raccp_deacvsmax_swc_out,                        /*BIN7*/
                            &vsctl_dstvehtotmes_deacvsmax_swc_out,                 /*BIN0*/
                            &vsctl_jrkveh_deacvsmax_swc_out,                       /*BIN7*/
                            &vsctl_spdveh_deacvsmax_swc_out,                       /*BIN7*/
                            &vsctl_ticfmsdwnvsmaxreq_swc_out,                      /*DEC2*/
                            &vsctl_nogearegd_deacvsmax_swc_out,
                            &vsctl_bctl_avehpotvsmax_swc_out,
                            &vsctl_stvsmaxextd_swc_out,
                            &vsctl_bdgovsmax_dem_out,
                            &vsctl_rslop_deacvsmax_swc_out,                        /*BIN7*/
                            &vsctl_rctltqwhlptpotvsmax_swc_out,                    /*BIN4*/
                            &vsctl_stvsmaxprev_deacvsmax_swc_out,
                            &vsctl_jrkvehreqdeacvsmax_swc_out,                     /*BIN7*/
                            &vsctl_avehpotvsmaxreq_swc_out,                        /*BIN10*/
                            &vsctl_spdvehreqdeacvsmax_swc_out,                      /*BIN7*/
                            &vsctl_bmonrunvsmax_dem_out,
                            &vsctl_stvsmax_deacvsmax_swc_out);


    /* initialisation of DEM variables */
    vsctl_bmonrunvsmax_prev = DDS_FALSE;
    vsctl_bmonrunvsmaxp_prev = DDS_FALSE;

    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I038(0) */
    Rte_Write_P_VSCtl_aVehPotVSMaxReq_VSCtl_aVehPotVSMaxReq(vsctl_avehpotvsmaxreq_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I039(0) */
    Rte_Write_P_VSCtl_aVehVSMaxReq_VSCtl_aVehVSMaxReq(vsctl_avehvsmaxreq_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I040(0) */
    Rte_Write_P_VSCtl_aVehVSMaxReq_DeacVSMax_VSCtl_aVehVSMaxReq_DeacVSMax(vsctl_avehvsmaxreq_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I037(0) */
    Rte_Write_P_VSCtl_aVeh_DeacVSMax_VSCtl_aVeh_DeacVSMax(vsctl_aveh_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I053(2) */
    Rte_Write_P_VSCtl_bCtl_aVehPotVSMax_VSCtl_bCtl_aVehPotVSMax(vsctl_bctl_avehpotvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I041(0) */
    Rte_Write_P_VSCtl_dstVehTotMes_DeacVSMax_VSCtl_dstVehTotMes_DeacVSMax(vsctl_dstvehtotmes_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I043(0) */
    Rte_Write_P_VSCtl_jrkVehReqDeacVSMax_VSCtl_jrkVehReqDeacVSMax(vsctl_jrkvehreqdeacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I042(0) */
    Rte_Write_P_VSCtl_jrkVeh_DeacVSMax_VSCtl_jrkVeh_DeacVSMax(vsctl_jrkveh_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I044(1) */
    Rte_Write_P_VSCtl_noGearEgd_DeacVSMax_VSCtl_noGearEgd_DeacVSMax(vsctl_nogearegd_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I045(1) */
    Rte_Write_P_VSCtl_posnGBxDeacVSMax_VSCtl_posnGBxDeacVSMax(vsctl_posngbxdeacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I046(0) */
    Rte_Write_P_VSCtl_rAccP_DeacVSMax_VSCtl_rAccP_DeacVSMax(vsctl_raccp_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I047(0) */
    Rte_Write_P_VSCtl_rCtlTqWhlPTPotVSMax_VSCtl_rCtlTqWhlPTPotVSMax(vsctl_rctltqwhlptpotvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I048(0) */
    Rte_Write_P_VSCtl_rSlop_DeacVSMax_VSCtl_rSlop_DeacVSMax(vsctl_rslop_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I050(0) */
    Rte_Write_P_VSCtl_spdVehErrVSMax_VSCtl_spdVehErrVSMax(vsctl_spdveherrvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I052(0) */
    Rte_Write_P_VSCtl_spdVehReqDeacVSMax_VSCtl_spdVehReqDeacVSMax(vsctl_spdvehreqdeacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I051(0) */
    Rte_Write_P_VSCtl_spdVehVSMaxReq_VSCtl_spdVehVSMaxReq(vsctl_spdvehvsmaxreq_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I049(0) */
    Rte_Write_P_VSCtl_spdVeh_DeacVSMax_VSCtl_spdVeh_DeacVSMax(vsctl_spdveh_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I054(0) */
    Rte_Write_P_VSCtl_stCtl_aVehVSMax_VSCtl_stCtl_aVehVSMax(vsctl_stctl_avehvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I055(0) */
    Rte_Write_P_VSCtl_stDeacVSMaxReq_no1_VSCtl_stDeacVSMaxReq_no1(vsctl_stdeacvsmaxreq_no1_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I056(0) */
    Rte_Write_P_VSCtl_stDeacVSMaxReq_no2_VSCtl_stDeacVSMaxReq_no2(vsctl_stdeacvsmaxreq_no2_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I057(0) */
    Rte_Write_P_VSCtl_stRec_stDeacVSMaxReq1_VSCtl_stRec_stDeacVSMaxReq1(vsctl_strec_stdeacvsmaxreq1_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I058(0) */
    Rte_Write_P_VSCtl_stRec_stDeacVSMaxReq2_VSCtl_stRec_stDeacVSMaxReq2(vsctl_strec_stdeacvsmaxreq2_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I060(0) */
    Rte_Write_P_VSCtl_stVSMaxExtd_VSCtl_stVSMaxExtd(vsctl_stvsmaxextd_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I061(0) */
    Rte_Write_P_VSCtl_stVSMaxPrev_DeacVSMax_VSCtl_stVSMaxPrev_DeacVSMax(vsctl_stvsmaxprev_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I059(0) */
    Rte_Write_P_VSCtl_stVSMax_DeacVSMax_VSCtl_stVSMax_DeacVSMax(vsctl_stvsmax_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I062(0) */
    Rte_Write_P_VSCtl_tiCfmSdwnVSMaxReq_VSCtl_tiCfmSdwnVSMaxReq(vsctl_ticfmsdwnvsmaxreq_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I063(0) */
    Rte_Write_P_VSCtl_tiCfmSupVSMaxReq_VSCtl_tiCfmSupVSMaxReq(vsctl_ticfmsupvsmaxreq_swc_out);

}
/*******************************************************************************
*
*  Runnable Name    : RE_VSMax_002_TEV
*  Event            : Every 0.04
*  Description      : Call  scheduled functions
*
*******************************************************************************/

FUNC(void, AUTOMATIC) RE_VSMax_002_TEV(void)
{
    /* INPUT */
    /* SWC IN */
    UInt16 accp_raccp_swc_in;
    Boolean afts_brst_stdeacvsmaxreq1_swc_in;
    Boolean afts_brst_stdeacvsmaxreq2_swc_in;
    Boolean ecu_bauthvsctlini_swc_in;
    Boolean ext_bkeyoff_swc_in;
    Boolean ext_btyrewarn_swc_in;
    Boolean ext_btyrewarncf_swc_in;
    Boolean ext_bvsmaxfcf_swc_in;
    Boolean ext_bvsmaxpcf_swc_in;
    Boolean ext_bvsmaxscf_swc_in;
    UInt32 ext_dstvehtotmes_swc_in;
    UInt8 ext_spdvehvsmaxprmareq_swc_in;
    UInt8 ext_stctlcmdpttqpotcf_swc_in;
    UInt8 ext_stgbxcf_swc_in;
    UInt16 veh_spdveh_swc_in;
    UInt8 vehest_spdvehcrit_swc_in;
    SInt16 vsctl_aveh_swc_in;
    SInt16 vsctl_avehcordvslimreq_swc_in;
    SInt16 vsctl_avehptmax_swc_in;
    SInt16 vsctl_avehptmin_swc_in;
    SInt16 vsctl_avehptpotmaxctla_no1_swc_in;
    SInt16 vsctl_avehreq_swc_in;
    Boolean vsctl_bdrvovrdvsmax_aveh_swc_in;
    Boolean vsctl_bendtranvsmax_swc_in;
    SInt16 vsctl_jrkveh_swc_in;
    SInt16 vsctl_rslop_swc_in;
    UInt16 vsctl_rtqwhlptdrvreq_swc_in;
    UInt16 vsctl_spdveh_swc_in;
    UInt8 vsctl_stdeacvsctlinfo_swc_in;
    UInt8 vsctl_stdvsregextd_swc_in;
    UInt8 vsctl_stvsctlinfo_swc_in;
    UInt8 vsctl_stvslimextd_swc_in;
    UInt8 vsctl_stvsregextd_swc_in;
    UInt8 copt_posnlev_swc_in;
    SInt8 copt_noegdgearcordit_swc_in;
    /* FIM (FRM) */
    Boolean vsmax_bool_temp;
    Boolean frm_bacvvsmax_no1_fim_in;
    Boolean frm_bacvvsmax_no2_fim_in;
    Boolean frm_bdeacirvvsmax_fim_in;
    Boolean frm_bdeacrvvsmax_fim_in;
    Boolean frm_bdeacrvvsmaxc_fim_in;
    Boolean frm_bdeacrvvsmaxf_fim_in;
    Boolean frm_bdeacrvvsmaxp_fim_in;
    Boolean frm_bdeacrvvsmaxs_fim_in;
    Boolean frm_binhvsmax_fim_in;
    /* OUTPUT */
    /* SWC OUT */
    SInt16 vsctl_aveh_deacvsmax_swc_out;
    SInt16 vsctl_avehpotvsmaxreq_swc_out;
    SInt16 vsctl_avehvsmaxreq_swc_out;
    SInt16 vsctl_avehvsmaxreq_deacvsmax_swc_out;
    UInt32 vsctl_dstvehtotmes_deacvsmax_swc_out;
    SInt16 vsctl_jrkveh_deacvsmax_swc_out;
    SInt16 vsctl_jrkvehreqdeacvsmax_swc_out;
    SInt8 vsctl_nogearegd_deacvsmax_swc_out;
    UInt8 vsctl_posngbxdeacvsmax_swc_out;
    UInt16 vsctl_raccp_deacvsmax_swc_out;
    UInt16 vsctl_rctltqwhlptpotvsmax_swc_out;
    SInt16 vsctl_rslop_deacvsmax_swc_out;
    UInt16 vsctl_spdveh_deacvsmax_swc_out;
    SInt16 vsctl_spdveherrvsmax_swc_out;
    UInt16 vsctl_spdvehvsmaxreq_swc_out;
    UInt16 vsctl_spdvehreqdeacvsmax_swc_out;
    UInt8 vsctl_bctl_avehpotvsmax_swc_out;
    UInt8 vsctl_stctl_avehvsmax_swc_out;
    UInt16 vsctl_stdeacvsmaxreq_no1_swc_out;
    UInt16 vsctl_stdeacvsmaxreq_no2_swc_out;
    UInt8 vsctl_strec_stdeacvsmaxreq1_swc_out;
    UInt8 vsctl_strec_stdeacvsmaxreq2_swc_out;
    UInt8 vsctl_stvsmax_deacvsmax_swc_out;
    UInt8 vsctl_stvsmaxextd_swc_out;
    UInt8 vsctl_stvsmaxprev_deacvsmax_swc_out;
    UInt16 vsctl_ticfmsdwnvsmaxreq_swc_out;
    UInt16 vsctl_ticfmsupvsmaxreq_swc_out;
    /* DEM (bDgo and bMonRun) */
    UInt8 vsctl_bmonrunvsmax_dem_out;
    UInt8 vsctl_bdgovsmax_dem_out;
    UInt8 vsctl_bmonrunvsmaxp_dem_out;
    UInt8 vsctl_bdgovsmaxp_dem_out;

    if ((UInt32)DDS_FALSE == (UInt32)VSMAX_ACTIVE_BYP_C)
    {
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I001(1) */
        Rte_Read_R_AccP_rAccP_AccP_rAccP(&accp_raccp_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I002(0) */
        Rte_Read_R_Afts_bRst_stDeacVSMaxReq1_Afts_bRst_stDeacVSMaxReq1(&afts_brst_stdeacvsmaxreq1_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I003(0) */
        Rte_Read_R_Afts_bRst_stDeacVSMaxReq2_Afts_bRst_stDeacVSMaxReq2(&afts_brst_stdeacvsmaxreq2_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I089(0) */
        Rte_Read_R_CoPt_noEgdGearCordIt_CoPt_noEgdGearCordIt(&copt_noegdgearcordit_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I088(0) */
        Rte_Read_R_CoPt_posnLev_CoPt_posnLev(&copt_posnlev_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I004(0) */
        Rte_Read_R_ECU_bAuthVSCtlIni_ECU_bAuthVSCtlIni(&ecu_bauthvsctlini_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I006(0) */
        Rte_Read_R_Ext_bKeyOff_Ext_bKeyOff(&ext_bkeyoff_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I007(0) */
        Rte_Read_R_Ext_bTyreWarn_Ext_bTyreWarn(&ext_btyrewarn_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I008(0) */
        Rte_Read_R_Ext_bTyreWarnCf_Ext_bTyreWarnCf(&ext_btyrewarncf_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I009(0) */
        Rte_Read_R_Ext_bVSMaxfCf_Ext_bVSMaxfCf(&ext_bvsmaxfcf_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I010(0) */
        Rte_Read_R_Ext_bVSMaxpCf_Ext_bVSMaxpCf(&ext_bvsmaxpcf_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I011(0) */
        Rte_Read_R_Ext_bVSMaxsCf_Ext_bVSMaxsCf(&ext_bvsmaxscf_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I012(1) */
        Rte_Read_R_Ext_dstVehTotMes_Ext_dstVehTotMes(&ext_dstvehtotmes_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I015(0) */
        Rte_Read_R_Ext_spdVehVSMaxPrmaReq_Ext_spdVehVSMaxPrmaReq(&ext_spdvehvsmaxprmareq_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I016(0) */
        Rte_Read_R_Ext_stCtlCmdPTTqPotCf_Ext_stCtlCmdPTTqPotCf(&ext_stctlcmdpttqpotcf_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I017(1) */
        Rte_Read_R_Ext_stGBxCf_Ext_stGBxCf(&ext_stgbxcf_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I020(0) */
        Rte_Read_R_VSCtl_aVeh_VSCtl_aVeh(&vsctl_aveh_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I021(0) */
        Rte_Read_R_VSCtl_aVehCordVSLimReq_VSCtl_aVehCordVSLimReq(&vsctl_avehcordvslimreq_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I022(0) */
        Rte_Read_R_VSCtl_aVehPTMax_VSCtl_aVehPTMax(&vsctl_avehptmax_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I023(0) */
        Rte_Read_R_VSCtl_aVehPTMin_VSCtl_aVehPTMin(&vsctl_avehptmin_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I024(0) */
        Rte_Read_R_VSCtl_aVehPTPotMaxCtla_no1_VSCtl_aVehPTPotMaxCtla_no1(&vsctl_avehptpotmaxctla_no1_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I025(0) */
        Rte_Read_R_VSCtl_aVehReq_VSCtl_aVehReq(&vsctl_avehreq_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I026(0) */
        Rte_Read_R_VSCtl_bDrvOvrdVSMax_aVeh_VSCtl_bDrvOvrdVSMax_aVeh(&vsctl_bdrvovrdvsmax_aveh_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I027(0) */
        Rte_Read_R_VSCtl_bEndTranVSMax_VSCtl_bEndTranVSMax(&vsctl_bendtranvsmax_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I028(0) */
        Rte_Read_R_VSCtl_jrkVeh_VSCtl_jrkVeh(&vsctl_jrkveh_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I029(0) */
        Rte_Read_R_VSCtl_rSlop_VSCtl_rSlop(&vsctl_rslop_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I030(0) */
        Rte_Read_R_VSCtl_rTqWhlPTDrvReq_VSCtl_rTqWhlPTDrvReq(&vsctl_rtqwhlptdrvreq_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I031(0) */
        Rte_Read_R_VSCtl_spdVeh_VSCtl_spdVeh(&vsctl_spdveh_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I033(0) */
        Rte_Read_R_VSCtl_stDVSRegExtd_VSCtl_stDVSRegExtd(&vsctl_stdvsregextd_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I032(0) */
        Rte_Read_R_VSCtl_stDeacVSCtlInfo_VSCtl_stDeacVSCtlInfo(&vsctl_stdeacvsctlinfo_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I034(0) */
        Rte_Read_R_VSCtl_stVSCtlInfo_VSCtl_stVSCtlInfo(&vsctl_stvsctlinfo_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I035(0) */
        Rte_Read_R_VSCtl_stVSLimExtd_VSCtl_stVSLimExtd(&vsctl_stvslimextd_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I036(0) */
        Rte_Read_R_VSCtl_stVSRegExtd_VSCtl_stVSRegExtd(&vsctl_stvsregextd_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I019(0) */
        Rte_Read_R_VehEst_spdVehCrit_VehEst_spdVehCrit(&vehest_spdvehcrit_swc_in);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I018(0) */
        Rte_Read_R_Veh_spdVeh_Veh_spdVeh(&veh_spdveh_swc_in);

        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I077(0) */
        Rte_Call_R_FRM_bAcvVSMax_no1_GetFunctionPermission(&vsmax_bool_temp);
        frm_bacvvsmax_no1_fim_in = ((UInt32)vsmax_bool_temp == (UInt32)DDS_FALSE);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I078(0) */
        Rte_Call_R_FRM_bAcvVSMax_no2_GetFunctionPermission(&vsmax_bool_temp);
        frm_bacvvsmax_no2_fim_in = ((UInt32)vsmax_bool_temp == (UInt32)DDS_FALSE);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I079(0) */
        Rte_Call_R_FRM_bDeacIrvVSMax_GetFunctionPermission(&vsmax_bool_temp);
        frm_bdeacirvvsmax_fim_in = ((UInt32)vsmax_bool_temp == (UInt32)DDS_FALSE);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I080(0) */
        Rte_Call_R_FRM_bDeacRvVSMax_GetFunctionPermission(&vsmax_bool_temp);
        frm_bdeacrvvsmax_fim_in = ((UInt32)vsmax_bool_temp == (UInt32)DDS_FALSE);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I081(0) */
        Rte_Call_R_FRM_bDeacRvVSMaxc_GetFunctionPermission(&vsmax_bool_temp);
        frm_bdeacrvvsmaxc_fim_in = ((UInt32)vsmax_bool_temp == (UInt32)DDS_FALSE);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I082(0) */
        Rte_Call_R_FRM_bDeacRvVSMaxf_GetFunctionPermission(&vsmax_bool_temp);
        frm_bdeacrvvsmaxf_fim_in = ((UInt32)vsmax_bool_temp == (UInt32)DDS_FALSE);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I083(0) */
        Rte_Call_R_FRM_bDeacRvVSMaxp_GetFunctionPermission(&vsmax_bool_temp);
        frm_bdeacrvvsmaxp_fim_in = ((UInt32)vsmax_bool_temp == (UInt32)DDS_FALSE);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I084(0) */
        Rte_Call_R_FRM_bDeacRvVSMaxs_GetFunctionPermission(&vsmax_bool_temp);
        frm_bdeacrvvsmaxs_fim_in = ((UInt32)vsmax_bool_temp == (UInt32)DDS_FALSE);
        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I085(0) */
        Rte_Call_R_FRM_bInhVSMax_GetFunctionPermission(&vsmax_bool_temp);
        frm_binhvsmax_fim_in = ((UInt32)vsmax_bool_temp == (UInt32)DDS_FALSE);


VSMAX_Re002tev_Sf(ext_spdvehvsmaxprmareq_swc_in,                        /*BIN0*/
                copt_noegdgearcordit_swc_in,
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(frm_bdeacrvvsmax_fim_in),
                            vsctl_stvsregextd_swc_in,
                            vsctl_aveh_swc_in,                                   /*BIN10*/
                            vsctl_stdvsregextd_swc_in,
                            vsctl_stvslimextd_swc_in,
                            ext_stctlcmdpttqpotcf_swc_in,
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(frm_binhvsmax_fim_in),
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(ext_bkeyoff_swc_in),
                            vsctl_stdeacvsctlinfo_swc_in,                         /*BIN0*/
                            vsctl_avehptmin_swc_in,                              /*BIN10*/
                            vsctl_avehptmax_swc_in,                              /*BIN10*/
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(ecu_bauthvsctlini_swc_in),
                            accp_raccp_swc_in,                                   /*BIN7*/
                            ext_stgbxcf_swc_in,
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(afts_brst_stdeacvsmaxreq1_swc_in),
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(afts_brst_stdeacvsmaxreq2_swc_in),
                            vsctl_rtqwhlptdrvreq_swc_in,                         /*BIN7*/
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(vsctl_bdrvovrdvsmax_aveh_swc_in),
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(vsctl_bendtranvsmax_swc_in),
                            vsctl_stvsctlinfo_swc_in,
                            vsctl_avehcordvslimreq_swc_in,                       /*BIN10*/
                            vehest_spdvehcrit_swc_in,                             /*BIN0*/
                            veh_spdveh_swc_in,                            /*BIN7*/
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(frm_bdeacrvvsmaxc_fim_in),
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(ext_btyrewarn_swc_in),
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(frm_bdeacrvvsmaxf_fim_in),
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(ext_bvsmaxfcf_swc_in),
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(frm_bdeacirvvsmax_fim_in),
                            vsctl_jrkveh_swc_in,                                 /*BIN7*/
                            vsctl_spdveh_swc_in,                                 /*BIN7*/
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(ext_btyrewarncf_swc_in),
                            vsctl_avehreq_swc_in,
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(frm_bdeacrvvsmaxp_fim_in),
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(ext_bvsmaxpcf_swc_in),
                            ext_dstvehtotmes_swc_in,                             /*BIN0*/
                            vsctl_rslop_swc_in,                                  /*BIN7*/
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(frm_bacvvsmax_no1_fim_in),
                            copt_posnlev_swc_in,
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(frm_bacvvsmax_no2_fim_in),
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(ext_bvsmaxscf_swc_in),
                            vsctl_avehptpotmaxctla_no1_swc_in,            /*BIN10*/
        /* <PRQA_COMMENT><2100> Warning due to tool, conversion is ok </2100></PRQA_COMMENT> */
                            DDS_M_CONVERT_BOOL_TO_UINT8(frm_bdeacrvvsmaxs_fim_in),
                            &vsctl_avehvsmaxreq_deacvsmax_swc_out,                 /*BIN10*/
                            &vsctl_stdeacvsmaxreq_no1_swc_out,                     /*BIN0*/
                            &vsctl_stdeacvsmaxreq_no2_swc_out,                     /*BIN0*/
                            &vsctl_bdgovsmaxp_dem_out,
                            &vsctl_avehvsmaxreq_swc_out,                           /*BIN10*/
                            &vsctl_strec_stdeacvsmaxreq1_swc_out,
                            &vsctl_stctl_avehvsmax_swc_out,
                            &vsctl_strec_stdeacvsmaxreq2_swc_out,
                            &vsctl_posngbxdeacvsmax_swc_out,
                            &vsctl_aveh_deacvsmax_swc_out,                         /*BIN10*/
                            &vsctl_bmonrunvsmaxp_dem_out,
                            &vsctl_spdvehvsmaxreq_swc_out,                         /*BIN7*/
                            &vsctl_ticfmsupvsmaxreq_swc_out,                       /*DEC2*/
                            &vsctl_spdveherrvsmax_swc_out,                         /*BIN7*/
                            &vsctl_raccp_deacvsmax_swc_out,                        /*BIN7*/
                            &vsctl_dstvehtotmes_deacvsmax_swc_out,                 /*BIN0*/
                            &vsctl_jrkveh_deacvsmax_swc_out,                       /*BIN7*/
                            &vsctl_spdveh_deacvsmax_swc_out,                       /*BIN7*/
                            &vsctl_ticfmsdwnvsmaxreq_swc_out,                      /*DEC2*/
                            &vsctl_nogearegd_deacvsmax_swc_out,
                            &vsctl_bctl_avehpotvsmax_swc_out,
                            &vsctl_stvsmaxextd_swc_out,
                            &vsctl_bdgovsmax_dem_out,
                            &vsctl_rslop_deacvsmax_swc_out,                        /*BIN7*/
                            &vsctl_rctltqwhlptpotvsmax_swc_out,                    /*BIN4*/
                            &vsctl_stvsmaxprev_deacvsmax_swc_out,
                            &vsctl_jrkvehreqdeacvsmax_swc_out,                     /*BIN7*/
                            &vsctl_avehpotvsmaxreq_swc_out,                        /*BIN10*/
                            &vsctl_spdvehreqdeacvsmax_swc_out,                      /*BIN7*/
                            &vsctl_bmonrunvsmax_dem_out,
                            &vsctl_stvsmax_deacvsmax_swc_out);



        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I086(0) */
        /* Diag treatment : VSCtl_VSMax */
        if((UInt32)DDS_FALSE != (UInt32)vsctl_bmonrunvsmax_dem_out)
        {
            /* Diag activation */
            if((UInt32)DDS_FALSE != (UInt32)vsctl_bdgovsmax_dem_out)
            {
                Rte_Call_R_VSCtl_VSMax_SetEventStatus(DEM_EVENT_STATUS_PREFAILED);
            }
            else
            {
                Rte_Call_R_VSCtl_VSMax_SetEventStatus(DEM_EVENT_STATUS_PREPASSED);
            }
        }
        else
        {
            if ((UInt32)DDS_FALSE != (UInt32)vsctl_bmonrunvsmax_prev)
            {
                Rte_Call_R_VSCtl_VSMax_SetEventStatus(DEM_EVENT_STATUS_INIT);
            }
        }
        vsctl_bmonrunvsmax_prev = vsctl_bmonrunvsmax_dem_out;

        /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I087(0) */
        /* Diag treatment : VSCtl_VSMaxp */
        if((UInt32)DDS_FALSE != (UInt32)vsctl_bmonrunvsmaxp_dem_out)
        {
            /* Diag activation */
            if((UInt32)DDS_FALSE != (UInt32)vsctl_bdgovsmaxp_dem_out)
            {
                Rte_Call_R_VSCtl_VSMaxp_SetEventStatus(DEM_EVENT_STATUS_PREFAILED);
            }
            else
            {
                Rte_Call_R_VSCtl_VSMaxp_SetEventStatus(DEM_EVENT_STATUS_PREPASSED);
            }
        }
        else
        {
            if ((UInt32)DDS_FALSE != (UInt32)vsctl_bmonrunvsmaxp_prev)
            {
                Rte_Call_R_VSCtl_VSMaxp_SetEventStatus(DEM_EVENT_STATUS_INIT);
            }
        }
        vsctl_bmonrunvsmaxp_prev = vsctl_bmonrunvsmaxp_dem_out;

    }
    else
    {
        vsctl_avehpotvsmaxreq_swc_out = VSCtl_aVehPotVSMaxReq_B;
        vsctl_avehvsmaxreq_swc_out = VSCtl_aVehVSMaxReq_B;
        vsctl_avehvsmaxreq_deacvsmax_swc_out = VSCtl_aVehVSMaxReq_DeacVSMax_B;
        vsctl_aveh_deacvsmax_swc_out = VSCtl_aVeh_DeacVSMax_B;
        vsctl_bctl_avehpotvsmax_swc_out = VSCtl_bCtl_aVehPotVSMax_B;
        vsctl_dstvehtotmes_deacvsmax_swc_out = VSCtl_dstVehTotMes_DeacVSMax_B;
        vsctl_jrkvehreqdeacvsmax_swc_out = VSCtl_jrkVehReqDeacVSMax_B;
        vsctl_jrkveh_deacvsmax_swc_out = VSCtl_jrkVeh_DeacVSMax_B;
        vsctl_nogearegd_deacvsmax_swc_out = VSCtl_noGearEgd_DeacVSMax_B;
        vsctl_posngbxdeacvsmax_swc_out = VSCtl_posnGBxDeacVSMax_B;
        vsctl_raccp_deacvsmax_swc_out = VSCtl_rAccP_DeacVSMax_B;
        vsctl_rctltqwhlptpotvsmax_swc_out = VSCtl_rCtlTqWhlPTPotVSMax_B;
        vsctl_rslop_deacvsmax_swc_out = VSCtl_rSlop_DeacVSMax_B;
        vsctl_spdveherrvsmax_swc_out = VSCtl_spdVehErrVSMax_B;
        vsctl_spdvehreqdeacvsmax_swc_out = VSCtl_spdVehReqDeacVSMax_B;
        vsctl_spdvehvsmaxreq_swc_out = VSCtl_spdVehVSMaxReq_B;
        vsctl_spdveh_deacvsmax_swc_out = VSCtl_spdVeh_DeacVSMax_B;
        vsctl_stctl_avehvsmax_swc_out = VSCtl_stCtl_aVehVSMax_B;
        vsctl_stdeacvsmaxreq_no1_swc_out = VSCtl_stDeacVSMaxReq_no1_B;
        vsctl_stdeacvsmaxreq_no2_swc_out = VSCtl_stDeacVSMaxReq_no2_B;
        vsctl_strec_stdeacvsmaxreq1_swc_out = VSCtl_stRec_stDeacVSMaxReq1_B;
        vsctl_strec_stdeacvsmaxreq2_swc_out = VSCtl_stRec_stDeacVSMaxReq2_B;
        vsctl_stvsmaxextd_swc_out = VSCtl_stVSMaxExtd_B;
        vsctl_stvsmaxprev_deacvsmax_swc_out = VSCtl_stVSMaxPrev_DeacVSMax_B;
        vsctl_stvsmax_deacvsmax_swc_out = VSCtl_stVSMax_DeacVSMax_B;
        vsctl_ticfmsdwnvsmaxreq_swc_out = VSCtl_tiCfmSdwnVSMaxReq_B;
        vsctl_ticfmsupvsmaxreq_swc_out = VSCtl_tiCfmSupVSMaxReq_B;

    }


    /* SWC OUTPUT */
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I038(0) */
    Rte_Write_P_VSCtl_aVehPotVSMaxReq_VSCtl_aVehPotVSMaxReq(vsctl_avehpotvsmaxreq_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I039(0) */
    Rte_Write_P_VSCtl_aVehVSMaxReq_VSCtl_aVehVSMaxReq(vsctl_avehvsmaxreq_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I040(0) */
    Rte_Write_P_VSCtl_aVehVSMaxReq_DeacVSMax_VSCtl_aVehVSMaxReq_DeacVSMax(vsctl_avehvsmaxreq_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I037(0) */
    Rte_Write_P_VSCtl_aVeh_DeacVSMax_VSCtl_aVeh_DeacVSMax(vsctl_aveh_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I053(2) */
    Rte_Write_P_VSCtl_bCtl_aVehPotVSMax_VSCtl_bCtl_aVehPotVSMax(vsctl_bctl_avehpotvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I041(0) */
    Rte_Write_P_VSCtl_dstVehTotMes_DeacVSMax_VSCtl_dstVehTotMes_DeacVSMax(vsctl_dstvehtotmes_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I043(0) */
    Rte_Write_P_VSCtl_jrkVehReqDeacVSMax_VSCtl_jrkVehReqDeacVSMax(vsctl_jrkvehreqdeacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I042(0) */
    Rte_Write_P_VSCtl_jrkVeh_DeacVSMax_VSCtl_jrkVeh_DeacVSMax(vsctl_jrkveh_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I044(1) */
    Rte_Write_P_VSCtl_noGearEgd_DeacVSMax_VSCtl_noGearEgd_DeacVSMax(vsctl_nogearegd_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I045(1) */
    Rte_Write_P_VSCtl_posnGBxDeacVSMax_VSCtl_posnGBxDeacVSMax(vsctl_posngbxdeacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I046(0) */
    Rte_Write_P_VSCtl_rAccP_DeacVSMax_VSCtl_rAccP_DeacVSMax(vsctl_raccp_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I047(0) */
    Rte_Write_P_VSCtl_rCtlTqWhlPTPotVSMax_VSCtl_rCtlTqWhlPTPotVSMax(vsctl_rctltqwhlptpotvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I048(0) */
    Rte_Write_P_VSCtl_rSlop_DeacVSMax_VSCtl_rSlop_DeacVSMax(vsctl_rslop_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I050(0) */
    Rte_Write_P_VSCtl_spdVehErrVSMax_VSCtl_spdVehErrVSMax(vsctl_spdveherrvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I052(0) */
    Rte_Write_P_VSCtl_spdVehReqDeacVSMax_VSCtl_spdVehReqDeacVSMax(vsctl_spdvehreqdeacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I051(0) */
    Rte_Write_P_VSCtl_spdVehVSMaxReq_VSCtl_spdVehVSMaxReq(vsctl_spdvehvsmaxreq_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I049(0) */
    Rte_Write_P_VSCtl_spdVeh_DeacVSMax_VSCtl_spdVeh_DeacVSMax(vsctl_spdveh_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I054(0) */
    Rte_Write_P_VSCtl_stCtl_aVehVSMax_VSCtl_stCtl_aVehVSMax(vsctl_stctl_avehvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I055(0) */
    Rte_Write_P_VSCtl_stDeacVSMaxReq_no1_VSCtl_stDeacVSMaxReq_no1(vsctl_stdeacvsmaxreq_no1_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I056(0) */
    Rte_Write_P_VSCtl_stDeacVSMaxReq_no2_VSCtl_stDeacVSMaxReq_no2(vsctl_stdeacvsmaxreq_no2_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I057(0) */
    Rte_Write_P_VSCtl_stRec_stDeacVSMaxReq1_VSCtl_stRec_stDeacVSMaxReq1(vsctl_strec_stdeacvsmaxreq1_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I058(0) */
    Rte_Write_P_VSCtl_stRec_stDeacVSMaxReq2_VSCtl_stRec_stDeacVSMaxReq2(vsctl_strec_stdeacvsmaxreq2_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I060(0) */
    Rte_Write_P_VSCtl_stVSMaxExtd_VSCtl_stVSMaxExtd(vsctl_stvsmaxextd_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I061(0) */
    Rte_Write_P_VSCtl_stVSMaxPrev_DeacVSMax_VSCtl_stVSMaxPrev_DeacVSMax(vsctl_stvsmaxprev_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I059(0) */
    Rte_Write_P_VSCtl_stVSMax_DeacVSMax_VSCtl_stVSMax_DeacVSMax(vsctl_stvsmax_deacvsmax_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I062(0) */
    Rte_Write_P_VSCtl_tiCfmSdwnVSMaxReq_VSCtl_tiCfmSdwnVSMaxReq(vsctl_ticfmsdwnvsmaxreq_swc_out);
    /* SSTG_REQ_TAG: 01552_10_02849-VSMax-I063(0) */
    Rte_Write_P_VSCtl_tiCfmSupVSMaxReq_VSCtl_tiCfmSupVSMaxReq(vsctl_ticfmsupvsmaxreq_swc_out);

    /* IRV OUTPUT */
}

/*******************************************************************************
*  Function Definition for timers
*******************************************************************************/

/*******************************************************************************
*
*  Runnable Name   : VSMax_Timer_1ms_U32
*  Description     : Call RTE interface for 1ms timer
*
*******************************************************************************/
FUNC(UInt32, AUTOMATIC) VSMax_Timer_1ms_U32(void)
{
    UInt32 current_time;

    (void)Rte_Call_R_VSMax_GetTimer_1ms_U32_GetTimer_1ms_U32(&current_time);

    return current_time;
}

/*******************************************************************************
*  Local Task Function Definition
*******************************************************************************/

/* NONE */

#define VSMAX_STOP_SEC_CODE
#include "VSMax_MemMap.h"

