/*******************************************************************************
*                           P. C. A.
*
*                    Peugeot Citroen Automobile
*
*        This file is the property of PCA. All rights are reserved
*        by PCA and this file must not be copied or disclosed
*       (in whole or in part) without prior written consent of PCA.
*
********************************************************************************
*
* %name: AFAMgtT_Aftrs.h %
*
* %version: 1.1 %
*
* %date_modified: Thu Aug  2 14:24:41 2012 %
*
*
* %derived_by: u260001 %
* %release: EB2DT/SC3 %
* %full_filespec: AFAMgtT_Aftrs.h-1.1:incl:1 %
*
********************************************************************************
*
* generated by  %name: AFAMgtT_Aftrs.h %   %version: 1.1 %  the 2012-07-31 08:50:52.035000
*
*******************************************************************************/

#ifndef AFAMgtTAFTRS_H
#define AFAMgtTAFTRS_H


#include "Rte_AFAMgtT.h"
#include "AFAMgtT.h"
#include "psa_lib_apv.h"
#include "Rte_Type.h"
#include "PSA_afts.h"
#include "AFAMgtT_nvm.h"
#include "SC.h"
#include "tl_defines.h"


/* SSTG_REQ_TAG : 01552_09_00391-SSTG-C057(2) */
/* SSTG_REQ_TAG : 01552_09_00391-SSTG-C086(1) */
#define AFAMgtT_NVMID01 1    /* Reset request of the Nvm data of the SWC */
#define AFAMgtT_NVMID03 3    /* Reset request of the Nvm data of the SWC */

/* SSTG_REQ_TAG : 01552_09_00391-SSTG-C086(1) */
#define AFAMGTT_NVMID_START 1
#define AFAMGTT_NVMID_END 3
#define AFAMGTT_NVMID_RESERVED    0
#define NULL 0
#define LITTLEENDIAN 1


/* SSTG_REQ_TAG : 01552_09_00391-SSTG-C111(0) */

/* SSTG_REQ_TAG : 01552_09_00391-SSTG-C117(0) */


/* SSTG_REQ_TAG : 01552_09_00391-SSTG-C112(0) */
#define AFAMGTT_RAMID_START 10000
#define AFAMGTT_RAMID_END 0


/* SSTG_REQ_TAG : 01552_09_00391-SSTG-C118(1) */
#define AFAMGTT_EOBDRAMID_START 10000
#define AFAMGTT_EOBDRAMID_END 0


extern FUNC(void, AUTOMATIC) AFAMgtT_Nvm_To_Cpy(void);
extern FUNC(void, AUTOMATIC) AFAMgtT_Cpy_To_Nvm_And_Reinit(UInt8 AFAMgtT_Nvmid);
extern FUNC(void, AUTOMATIC) AFAMgtT_Recovery_To_Nvm_And_Reinit(UInt8 AFAMgtT_Nvmid);
extern FUNC(Std_ReturnType, AUTOMATIC) AFAMgtT_Aftrs_Init(void);


#endif
