/******************************************************************************/
/*                                                                            */
/* !Layer          : HAL                                                      */
/*                                                                            */
/* !Component      : MCWDG                                                    */
/*                                                                            */
/* !Module         : MCWDG_Typ                                                */
/* !Description    : Declaration of new types for MCWDG Component             */
/*                                                                            */                                                                         
/* !File           : MCWDG_Typ.H                                              */
/*                                                                            */
/* !Scope          : Public                                                   */
/*                                                                            */
/* !Target         : All                                                      */
/*                                                                            */
/* !Vendor         : Valeo                                                    */
/*                                                                            */
/* Coding language : C                                                        */
/*                                                                            */
/* COPYRIGHT 2011 VALEO                                                       */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* PVCS Information                                                           */
/* $Archive::   P:/EBx6_2/LOG/ASW/Ref/Main/PATCH/MCWDG_Typ.H_v               $*/
/* $Revision::   1.0      $$Author::   croche2        $$Date::   11 Mar 2014 $*/
/******************************************************************************/

#ifndef MCWDG_TYP_H
#define MCWDG_TYP_H 

#include "STD_TYPES.H"

/******************************************************************************/
/* TYPES                                                                      */
/******************************************************************************/
typedef uint8 MCWDG_tbfPrepInitStatus;


#endif /* MCWDG_TYP_H */

/*-------------------------------- end of file -------------------------------*/

