/******************************************************************************/
/*                                                                            */
/* !Layer           : MCAL                                                    */
/*                                                                            */
/* !Component       : HOOK                                                    */
/*                                                                            */
/* !Module          : HOOK_CFG_E                                              */
/* !Description     : HOOK Configuration                                      */
/*                                                                            */
/* !File            : HOOK_Cfg_E.H                                            */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : Valeo                                                   */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 VALEO                                                       */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* PVCS Information                                                           */
/* $Archive::   P:/EBx6_2/LOG/ASW/Ref/Main/CONFIG/APPLI_CONFIG/HOOK_Cfg_E.H_v$*/
/* $Revision::   1.1       $$Author::   croche2$$Date::   14 May 2014 13:31:0$*/
/******************************************************************************/

#ifndef HOOK_CFG_E_H
#define HOOK_CFG_E_H

#include "NOPROD.h"

/******************************************************************************/
/* MACRO FUNCTIONS                                                            */
/******************************************************************************/
#define HOOK_vidTASK_OVERRUN_ERROR(TaskId)

#endif /* HOOK_CFG_E_H */

/*------------------------------ end of file ---------------------------------*/

