/**************************************************************************************************\
 *** 
 ***                            P. C. A.
 *** 
 ***                     Peugeot Citroen Automobile
 *** 
 ***         This file is the property of PCA. All rights are reserved
 ***         by PCA and this file must not be copied or disclosed
 ***        (in whole or in part) without prior written consent of PCA.
 *** 
 *** *******************************************************************************
 *** 
 ***  %name: ASE_002_calibrations.h %
 *** 
 ***  %version: 3.1 %
 *** 
 ***  %date_modified: Thu Nov 17 17:46:08 2011 %
 *** 
 *** 
 ***  %derived_by: e378489 %
 ***  %release: ASE/3.0 %
 ***  %full_filespec: ASE_002_calibrations.h-3.1:incl:1 %
 *** 
 *** *******************************************************************************
 *** 
 *** Simulink model       : CoStall_01460_10_02170_TL
 *** TargetLink subsystem : CoStall_01460_10_02170_TL/ASE_002
 *** Codefile             : ase_002_calibrations.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2011-11-17 15:28:20
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : disabled
 *** Share fcns between TL subsystems    : enabled
 *** Generate 64bit functions            : enabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : enabled
 *** Style definition file               : C:\Dspace301\Matlab\Tl\config\codegen\cconfig.xml
 *** Root style sheet                    : C:\Dspace301\Matlab\Tl\XML\CodeGen\Stylesheets\TL_CSource
 ***                                       CodeSS.xsl
 *** Enable Multirate codegeneration     : disabled
 *** Add model checksum                  : disabled
 ***
 *** TargetLink version      : 3.0.1 from 26-May-2009
 *** Code generator version  : Build Id 3.0.1.7 from 2009-May-06 15:28:18
 *** Copyright (c) 2006 dSPACE GmbH
\**************************************************************************************************/

#ifndef _ASE_002_CALIBRATIONS_H_
#define _ASE_002_CALIBRATIONS_H_

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "tl_defines.h"
#include "tl_basetypes.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

#define ASE_START_SEC_CALIB_16BIT
#include "ASE_MemMap.h"
/******************************************************************************\
   AR_MERGEABLE_CALIB_16BIT: Mergeable Calib 16 bits for AUTOSAR modules | Width: 16
\******************************************************************************/
extern AR_MERGEABLE_CALIB_16BIT UInt16 CoStall_spdVehThdStallAuth_C /* 
   Unit       : km/h
   Description: Seuil de vitesse véhicule pour autoriser l'entrée en SCAr
   LSB: 2^-7 OFF:  0 MIN/MAX:  0 .. 50 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 CoStall_tiDlyOffStCutReq_C /* 
   Unit       : s
   Description: Durée de la Temporisation fenêtre SCAr
   LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 30 */;

#define ASE_STOP_SEC_CALIB_16BIT
#include "ASE_MemMap.h"

#define ASE_START_SEC_CALIB_8BIT
#include "ASE_MemMap.h"

/******************************************************************************\
   AR_MERGEABLE_CALIB_8BIT: Mergeable Calib 8 bits for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_spdASEAuth_C /* 
   Description: Seuil de vitesse pour autoriser l'entrée en SCAr lors d'une demande de classe 3
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 50 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModASEReqCha_C /* 
   Description: Traitement booléen de la demande de redémarrage  SCAr par sous-système Frein
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModASEReqCoEmSTT_C /* 
   Description: Traitement booléen de la demande de redémarrage  SCAr par Sous Ensemble Electro Mote
   ur
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModASEReqDgoBlt_C /* 
   Description: Traitement booléen de la demande de redémarrage  par FGC
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModASEReqStg_C /* 
   Description: Traitement booléen de la demande de redémarrage  SCAr par sous-système DA
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModASEReqVeh_C /* 
   Description: Traitement booléen de la demande de redémarrage  SCAr par sous-système Habitacle
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModAcvASE_C /* 
   Description: Traitement booléen de la reconfiguration type 2.1 (redémarrage classique)
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModAcvCutCoPtASE_C /* 
   Description: Traitement booléen de la demande de coupure si moteur en calé (FRM SCAr type 3)
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModAcvFastASE_C /* 
   Description: Traitement booléen de la reconfiguration type 2.2 (redémarrage urgent)
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModBltStopAuth_C /* 
   Description: Traitement booléen de l'autorisation d'arrêt par glissement façade
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModCompTqRstrt_C /* 
   Description: Traitement booléen du résultat de la comparaison des couples de redem nécessaire et 
   disponible
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModFbSpcFactSTTReq1_C /* 
   Description: Traitement booléen de la dmd des inhibitions des interdictions d'arrêt
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModFbSpcFactSTTReq2_C /* 
   Description: Traitement booléen de la dmd des inhibitions des interdictions d'arrêt
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModLimFreqStopInh_C /* 
   Description: Traitement booléen du besoin en limitation de fréquence d'arrêt
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModStallAuthCha_C /* 
   Description: Traitement booléen de l'autorisation d'entrée en SCAr par sous-système Frein
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModStallAuthDamp_C /* 
   Description: Traitement booléen de l'autorisation d'entrée en SCAr par sous-système Suspension
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModStallAuthEng_C /* 
   Description: Traitement booléen de l'autorisation d'entrée en SCAr par sous-système Moteur
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModStallAuthSTT_C /* 
   Description: Traitement booléen de la demande de redémarrage  SCAr par Sous Ensemble Electro Mote
   ur
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModStallAuthStg_C /* 
   Description: Traitement booléen de l'autorisation d'entrée en SCAr par sous-système DA
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModStallAuthVeh_C /* 
   Description: Traitement booléen de l'autorisation d'entrée en SCAr par sous-système Habitacle
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 CoStall_stModStallReqCoPtUH_C /* 
   Description: Traitement booléen de la demande d'entrée en SCA par STT
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 3 */;

#define ASE_STOP_SEC_CALIB_8BIT
#include "ASE_MemMap.h"

#define ASE_START_SEC_CALIB_BOOLEAN
#include "ASE_MemMap.h"

/******************************************************************************\
   AR_MERGEABLE_CALIB_BOOLEAN: Mergeable Calib 1 bit for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_MERGEABLE_CALIB_BOOLEAN Boolean CoStall_bCoPtASEAcv_C /* 
   Description: Activation de la fonction SCAr
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_MERGEABLE_CALIB_BOOLEAN Boolean CoStall_bDlyOffStCutReqAcv_C /* 
   Description: Activation de la fenêtre SCAr
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_MERGEABLE_CALIB_BOOLEAN Boolean CoStall_bEngStallAuthLimDVA_C /* 
   Description: Autorisation d'entrée en SCAr après limitation de fréquence de Stop DVA
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

#define ASE_STOP_SEC_CALIB_BOOLEAN
#include "ASE_MemMap.h"

#define ASE_START_SEC_INTERNAL_VAR_16BIT
#include "ASE_MemMap.h"

/******************************************************************************\
   AR_INTERNAL_VAR_DISP_16BIT: Display 16 bits for AUTOSAR modules | Width: 16
\******************************************************************************/
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 CoStall_bInhASEFirstStrt_MP /*
   Description: Inhibition fonction SCA lors d'un premier démarrage */;

#define ASE_STOP_SEC_INTERNAL_VAR_16BIT
#include "ASE_MemMap.h"

#define ASE_START_SEC_INTERNAL_VAR_BOOLEAN
#include "ASE_MemMap.h"

/******************************************************************************\
   AR_INTERNAL_VAR_DISP_BOOLEAN: Display Boolean for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bASEAuthSynt /*
   Description: Synthèse des autorisations d'entrer en SCAr */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bASEInhSynt /*
   Description: Synthèse des inhibitions d'entrer en SCAr */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bASEReqSynt /*
   Description: Synthèse des demandes d'entrer en SCAr */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bAcvCutCoPtASE /*
   Description: Demande de coupure si moteur en calé (FRM SCAr type 3) */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bAcvFastRstrtCoPtASE /*
   Description: Reconfiguration SCA type 2.2 (redémarrage urgent) */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bAcvRstrtCoPtASE /*
   Description: Reconfiguration SCA type 2.1 (redémarrage classique) */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bCompTqRstrt /*
   Description: Pour APV, Résultat de la comparaison des couples de redémarrage nécessaire et dispon
   ible */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bDlyOffStCutReq_MP /*
   Description: Fenêtre SCAr */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngASEReqCoEmSTT /*
   Description: Demande de redémarrage en SCAr par le Sous Ensemble Electro Moteur */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngASEReqCoReqCha /*
   Description: Demande de redémarrage en SCAr par le sous-système Frein */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngASEReqCoReqStg /*
   Description: Demande de redémarrage en SCAr par le sous-système DA */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngASEReqCoReqVeh /*
   Description: Demande de redémarrage en SCAr par le sous-système Habitacle */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngStallAuthBlt /*
   Description: Autorisation d'arrêt facade */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngStallAuthCha /*
   Description: Autorisation d'entrée en SCAr par sous-système Frein */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngStallAuthCoEmSTT /*
   Description: Autorisation d'entrée en SCAr par Sous Ensemble Electro Moteur */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngStallAuthDamp /*
   Description: Autorisation d'entrée en SCAr par sous-système Suspension */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngStallAuthEngReqH /*
   Description: Autorisation d'entrée en SCAr par sous-système Moteur */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngStallAuthStg /*
   Description: Autorisation d'entrée en SCAr par sous-système DA */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngStallAuthVeh /*
   Description: Autorisation d'entrée en SCAr par sous-système Habitacle */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bEngStallReqCoPtUH /*
   Description: Demande d'entrée en SCAr par STT */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bFbSpcFactSTTReq1 /*
   Description: Retour sur la demande des inhibitions des interdictions d'arrêt */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bFbSpcFactSTTReq2 /*
   Description: Retour sur la demande d'inhibition du stop */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bLimFreqStopInh /*
   Description: Besoin limitation de fréquence arrêt */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean CoStall_bRstrtReqDgoBlt /*
   Description: Demande de redémarrage par FGC */;

#define ASE_STOP_SEC_INTERNAL_VAR_BOOLEAN
#include "ASE_MemMap.h"

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

#endif/*_ASE_002_CALIBRATIONS_H_ */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
