/**************************************************************************************************\
 *** 
 ***                            P. C. A.
 *** 
 ***                     Peugeot Citroen Automobile
 *** 
 ***         This file is the property of PCA. All rights are reserved
 ***         by PCA and this file must not be copied or disclosed
 ***        (in whole or in part) without prior written consent of PCA.
 *** 
 *** *******************************************************************************
 *** 
 ***  %name: TqEM_006_lut.c %
 *** 
 ***  %version: 12.0.build2 %
 *** 
 ***  %date_modified: Thu Jun 28 14:30:56 2012 %
 *** 
 *** 
 ***  %derived_by: u169773 %
 ***  %release: TqEM/12.0 %
 ***  %full_filespec: TqEM_006_lut.c-12.0.build2:csrc:1 %
 *** 
 *** *******************************************************************************
 *** 
 *** Simulink model       : RE_TqEM_006_TL
 *** TargetLink subsystem : RE_TqEM_006_TL/TqEM_006
 *** Codefile             : tqem_006_lut.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2012-06-28 11:40:10
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : disabled
 *** Share fcns between TL subsystems    : enabled
 *** Generate 64bit functions            : enabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : disabled
 *** Style definition file               : C:\dSPACE\Matlab\Tl\config\codegen\cconfig.xml
 *** Root style sheet                    : C:\dSPACE\Matlab\Tl\XML\CodeGen\Stylesheets\TL_CSourceCod
 ***                                       eSS.xsl
 *** Enable Multirate codegeneration     : disabled
 *** Add model checksum                  : disabled
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** S0061                    RE_TqEM_006_TL/TqEM_006
 *** S0062                    TqEM_006/TqEM_006
 *** S0063                    TqEM_006/TqEM_006/Subsystem
 *** S0064                    TqEM_006/TqEM_006/Subsystem_1
 *** S0065                    TqEM_006/TqEM_006/Subsystem/Modulo
 *** S0066                    TqEM_006/TqEM_006/Subsystem_1/F03_Calculer_couple_DVA
 *** S0067                    TqEM_006/TqEM_006/Subsystem_1/F04_Calculer_couple_inertiel
 *** S0068                    TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move
 *** S0069                    TqEM_006/TqEM_006/Subsystem_1/F03_Calculer_couple_DVA/SecureDivi
 *** S00610                   TqEM_006/TqEM_006/Subsystem_1/F03_Calculer_couple_DVA/SecureDivi/Detec
 ***                          tSat
 *** S00611                   TqEM_006/TqEM_006/Subsystem_1/F03_Calculer_couple_DVA/SecureDivi/Secur
 ***                          eDivi_Part
 *** S00612                   TqEM_006/TqEM_006/Subsystem_1/F04_Calculer_couple_inertiel/Product
 *** S00613                   TqEM_006/TqEM_006/Subsystem_1/F04_Calculer_couple_inertiel/SecureDivi
 *** S00614                   TqEM_006/TqEM_006/Subsystem_1/F04_Calculer_couple_inertiel/SecureDivi/
 ***                          DetectSat
 *** S00615                   TqEM_006/TqEM_006/Subsystem_1/F04_Calculer_couple_inertiel/SecureDivi/
 ***                          SecureDivi_Part
 *** S00616                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 ***                          culer_couple_easy_move
 *** S00617                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_04_App
 ***                          liquer_couple_easy_move
 *** S00618                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 ***                          culer_couple_easy_move/F05_03_01_Selectionner_moyenne
 *** S00619                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 ***                          culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif
 *** S00620                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 ***                          culer_couple_easy_move/F05_03_04_Calculer_couple_recalage_pertes
 *** S00621                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 ***                          culer_couple_easy_move/F05_03_05_Calculer_couple_DVA
 *** S00622                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 ***                          culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel
 *** S00623                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 ***                          culer_couple_easy_move/F05_03_07_Calculer_couple_correction_CMF
 *** S00624                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 ***                          culer_couple_easy_move/F05_03_08_Coordonner_couple_easy_move
 *** S00625                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 ***                          5_03_02_01_Calculer_couple_easy_move_effectif_diesel
 *** S00626                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 ***                          5_03_02_02_Calculer_couple_easy_move_effectif_essence
 *** S00627                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 ***                          5_03_02_03_Determiner_couple_easy_move_effectif_applicable
 *** S00628                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 ***                          5_03_02_04_Moyenner_couple_easy_move_effectif
 *** S00629                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 ***                          5_03_02_05_Retarder_couple_easy_move_effectif
 *** S00630                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_01_Calculer_couple_easy_move_effectif_diesel/F05_03_02_01_01_D
 ***                          eterminer_constante_temps_filtre
 *** S00631                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_01_Calculer_couple_easy_move_effectif_diesel/F05_03_02_01_02_F
 ***                          iltrer_couple_easy_move_effectif
 *** S00632                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_01_Calculer_couple_easy_move_effectif_diesel/F05_03_02_01_02_F
 ***                          iltrer_couple_easy_move_effectif/DLowPassFilter_TypeT
 *** S00633                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_01_Calculer_couple_easy_move_effectif_diesel/F05_03_02_01_02_F
 ***                          iltrer_couple_easy_move_effectif/DLowPassFilter_TypeT/DLowPass_T_Part
 *** S00634                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_01_Calculer_couple_easy_move_effectif_diesel/F05_03_02_01_02_F
 ***                          iltrer_couple_easy_move_effectif/DLowPassFilter_TypeT/IniCdn
 *** S00635                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_01_Calculer_couple_easy_move_effectif_diesel/F05_03_02_01_02_F
 ***                          iltrer_couple_easy_move_effectif/DLowPassFilter_TypeT/UnitDly_ExtIni
 *** S00636                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_01_
 ***                          Estimer_CMI_transitoire
 *** S00637                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_02_
 ***                          Calculer_couple_easy_move_effectif
 *** S00638                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_01_
 ***                          Estimer_CMI_transitoire/SecureDivi
 *** S00639                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_01_
 ***                          Estimer_CMI_transitoire/SecureDivi/DetectSat
 *** S00640                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_01_
 ***                          Estimer_CMI_transitoire/SecureDivi/SecureDivi_Part
 *** S00641                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_02_
 ***                          Calculer_couple_easy_move_effectif/DLowPassFilter_TypeT
 *** S00642                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_02_
 ***                          Calculer_couple_easy_move_effectif/Product
 *** S00643                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_02_
 ***                          Calculer_couple_easy_move_effectif/SecureDivi
 *** S00644                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_02_
 *** Calculer_couple_easy_move_effectif/DLowPassFilter_TypeT/DLowPass_T_Par
 ***                          t
 *** S00645                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_02_
 ***                          Calculer_couple_easy_move_effectif/DLowPassFilter_TypeT/IniCdn
 *** S00646                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_02_
 ***                          Calculer_couple_easy_move_effectif/DLowPassFilter_TypeT/UnitDly_ExtIni
 *** S00647                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_02_
 ***                          Calculer_couple_easy_move_effectif/SecureDivi/DetectSat
 *** S00648                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_02_Calculer_couple_easy_move_effectif_essence/F05_03_02_02_02_
 ***                          Calculer_couple_easy_move_effectif/SecureDivi/SecureDivi_Part
 *** S00649                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_01_Moyenner
 ***                          _3_evenements
 *** S00650                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_02_Moyenner
 ***                          _4_evenements
 *** S00651                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_03_Moyenner
 ***                          _6_evenements
 *** S00652                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_04_Selectio
 ***                          nner_moyenne_couple_easy_move_effectif
 *** S00653                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_01_Moyenner
 ***                          _3_evenements/UnitDly_ExtIni
 *** S00654                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_01_Moyenner
 ***                          _3_evenements/UnitDly_ExtIni1
 *** S00655                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_02_Moyenner
 ***                          _4_evenements/UnitDly_ExtIni1
 *** S00656                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_02_Moyenner
 ***                          _4_evenements/UnitDly_ExtIni2
 *** S00657                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_02_Moyenner
 ***                          _4_evenements/UnitDly_ExtIni3
 *** S00658                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_03_Moyenner
 ***                          _6_evenements/UnitDly_ExtIni1
 *** S00659                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_03_Moyenner
 ***                          _6_evenements/UnitDly_ExtIni2
 *** S00660                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_03_Moyenner
 ***                          _6_evenements/UnitDly_ExtIni3
 *** S00661                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_03_Moyenner
 ***                          _6_evenements/UnitDly_ExtIni4
 *** S00662                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_02_Calculer_couple_easy_move_effectif/F0
 *** 5_03_02_04_Moyenner_couple_easy_move_effectif/F05_03_02_04_03_Moyenner
 ***                          _6_evenements/UnitDly_ExtIni5
 *** S00663                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_04_Calculer_couple_recalage_pertes/F05_0
 ***                          3_04_02_Calculer_couple_recalage_pertes
 *** S00664                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_04_Calculer_couple_recalage_pertes/F05_0
 *** 3_04_02_Calculer_couple_recalage_pertes/F05_03_04_02_01_Calculer_coupl
 ***                          e_recalage_pertes
 *** S00665                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_05_Calculer_couple_DVA/F05_03_05_01_Corr
 ***                          iger_couple_DVA
 *** S00666                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_05_Calculer_couple_DVA/F05_03_05_02_Filt
 ***                          rer_correction_couple_DVA
 *** S00667                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_05_Calculer_couple_DVA/F05_03_05_03_Calc
 ***                          uler_couple_DVA_corrige
 *** S00668                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_05_Calculer_couple_DVA/F05_03_05_02_Filt
 ***                          rer_correction_couple_DVA/DLowPassFilter_TypeT
 *** S00669                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_05_Calculer_couple_DVA/F05_03_05_02_Filt
 ***                          rer_correction_couple_DVA/DLowPassFilter_TypeT/IniCdn
 *** S00670                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_05_Calculer_couple_DVA/F05_03_05_02_Filt
 ***                          rer_correction_couple_DVA/DLowPassFilter_TypeT/UnitDly_ExtIni1
 *** S00671                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_05_Calculer_couple_DVA/F05_03_05_03_Calc
 ***                          uler_couple_DVA_corrige/DetectSat
 *** S00672                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 ***                          _Moyenner_couple_inertiel
 *** S00673                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_02
 ***                          _Saturer_couple_inertiel
 *** S00674                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 ***                          _Moyenner_couple_inertiel/F05_03_06_01_01_Moyenner_3_evenements
 *** S00675                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 ***                          _Moyenner_couple_inertiel/F05_03_06_01_02_Moyenner_4_evenements
 *** S00676                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 ***                          _Moyenner_couple_inertiel/F05_03_06_01_03_Moyenner_6_evenements
 *** S00677                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 *** _Moyenner_couple_inertiel/F05_03_06_01_04_Selectionner_moyenne_couple_
 ***                          inertiel
 *** S00678                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 *** _Moyenner_couple_inertiel/F05_03_06_01_01_Moyenner_3_evenements/UnitDl
 ***                          y_ExtIni
 *** S00679                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 *** _Moyenner_couple_inertiel/F05_03_06_01_01_Moyenner_3_evenements/UnitDl
 ***                          y_ExtIni1
 *** S00680                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 *** _Moyenner_couple_inertiel/F05_03_06_01_02_Moyenner_4_evenements/UnitDl
 ***                          y_ExtIni1
 *** S00681                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 *** _Moyenner_couple_inertiel/F05_03_06_01_02_Moyenner_4_evenements/UnitDl
 ***                          y_ExtIni2
 *** S00682                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 *** _Moyenner_couple_inertiel/F05_03_06_01_02_Moyenner_4_evenements/UnitDl
 ***                          y_ExtIni3
 *** S00683                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 *** _Moyenner_couple_inertiel/F05_03_06_01_03_Moyenner_6_evenements/UnitDl
 ***                          y_ExtIni1
 *** S00684                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 *** _Moyenner_couple_inertiel/F05_03_06_01_03_Moyenner_6_evenements/UnitDl
 ***                          y_ExtIni2
 *** S00685                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 *** _Moyenner_couple_inertiel/F05_03_06_01_03_Moyenner_6_evenements/UnitDl
 ***                          y_ExtIni3
 *** S00686                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 *** _Moyenner_couple_inertiel/F05_03_06_01_03_Moyenner_6_evenements/UnitDl
 ***                          y_ExtIni4
 *** S00687                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_01
 *** _Moyenner_couple_inertiel/F05_03_06_01_03_Moyenner_6_evenements/UnitDl
 ***                          y_ExtIni5
 *** S00688                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_06_Calculer_couple_inertiel/F05_03_06_02
 ***                          _Saturer_couple_inertiel/DetectSat
 *** S00689                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_07_Calculer_couple_correction_CMF/F05_03
 ***                          _07_01_Calculer_couple_correction_CMF
 *** S00690                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_07_Calculer_couple_correction_CMF/F05_03
 ***                          _07_02_Gerer_transition_apres_demarrage
 *** S00691                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_07_Calculer_couple_correction_CMF/F05_03
 ***                          _07_02_Gerer_transition_apres_demarrage/MltpSwRmpTran1
 *** S00692                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_07_Calculer_couple_correction_CMF/F05_03
 ***                          _07_02_Gerer_transition_apres_demarrage/MltpSwRmpTran1/MSW
 *** S00693                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_07_Calculer_couple_correction_CMF/F05_03
 ***                          _07_02_Gerer_transition_apres_demarrage/MltpSwRmpTran1/MSW_Sel
 *** S00694                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_07_Calculer_couple_correction_CMF/F05_03
 ***                          _07_02_Gerer_transition_apres_demarrage/MltpSwRmpTran1/MSW/DetectSat
 *** S00695                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_07_Calculer_couple_correction_CMF/F05_03
 ***                          _07_02_Gerer_transition_apres_demarrage/MltpSwRmpTran1/MSW/DetectSat1
 *** S00696                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_07_Calculer_couple_correction_CMF/F05_03
 *** _07_02_Gerer_transition_apres_demarrage/MltpSwRmpTran1/MSW_Sel/DetectS
 ***                          at
 *** S00697                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_07_Calculer_couple_correction_CMF/F05_03
 *** _07_02_Gerer_transition_apres_demarrage/MltpSwRmpTran1/MSW_Sel/UnitDly
 ***                          _ExtIni
 *** S00698                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_03_Cal
 *** culer_couple_easy_move/F05_03_07_Calculer_couple_correction_CMF/F05_03
 *** _07_02_Gerer_transition_apres_demarrage/MltpSwRmpTran1/MSW_Sel/UnitDly
 ***                          _ExtIni1
 *** S00699                   TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_04_App
 ***                          liquer_couple_easy_move/F05_04_01_Filtrer_saturer_couple_easy_move
 *** S006100                  TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_04_App
 ***                          liquer_couple_easy_move/F05_04_02_Gerer_coupure
 *** S006101                  TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_04_App
 *** liquer_couple_easy_move/F05_04_01_Filtrer_saturer_couple_easy_move/DLo
 ***                          wPassFilter_TypeT
 *** S006102                  TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_04_App
 *** liquer_couple_easy_move/F05_04_01_Filtrer_saturer_couple_easy_move/DLo
 ***                          wPassFilter_TypeT/DLowPass_T_Part
 *** S006103                  TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_04_App
 *** liquer_couple_easy_move/F05_04_01_Filtrer_saturer_couple_easy_move/DLo
 ***                          wPassFilter_TypeT/IniCdn
 *** S006104                  TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_04_App
 *** liquer_couple_easy_move/F05_04_01_Filtrer_saturer_couple_easy_move/DLo
 ***                          wPassFilter_TypeT/UnitDly_ExtIni
 *** S006105                  TqEM_006/TqEM_006/Subsystem_1/F05_Calculer_couple_easy_move/F05_04_App
 ***                          liquer_couple_easy_move/F05_04_02_Gerer_coupure/DetectSat
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** C0060     RE_TqEM_006_TL                                         
 *** C0061     TqEM_006/TqEM_006/Subsystem/Chart                      
 *** 
 *** TargetLink version      : 3.0.1 from 26-May-2009
 *** Code generator version  : Build Id 3.0.1.7 from 2009-May-06 15:28:18
 *** Copyright (c) 2006 dSPACE GmbH
\**************************************************************************************************/

#ifndef _TQEM_006_LUT_C_
#define _TQEM_006_LUT_C_

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "TqEM_006_lut.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/


/**************************************************************************************************\
 ***  FUNCTION:
 ***      TqEM_006_Tab1DS2I2T2084
 *** 
 ***  DESCRIPTION:
 ***      Generated function for look-up tables.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_TqEM_006_Tab1DS2I2T2084 *map                 data structure
 ***      SInt16             x                   table input
 ***      UInt8 *            local_xLow          table index found in previous search
 ***
 ***  RETURNS:
 ***      SInt16
 ***
 ***  SETTINGS:
 ***      Search algorithm...................: local search
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***      Behavior at boundaries.............: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***
\**************************************************************************************************/

#define TQEM_START_SEC_CODE
#include "TqEM_MemMap.h"
SInt16 TqEM_006_Tab1DS2I2T2084(const MAP_TqEM_006_Tab1DS2I2T2084 * map, SInt16 x, UInt8 *
  local_xLow)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   SInt16 Aux_I16;
   SInt16 Aux_I16_a;
   UInt16 Aux_U16;
   UInt16 Aux_U16_a;

   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const SInt16 * x_table /* Scaling may differ through function reuse. */;
   const SInt16 * z_table /* Scaling may differ through function reuse. */;

   x_table = map->x_table;
   z_table = map->z_table;
   if (x <= *(x_table)) {
      *(local_xLow) = 0;

      /* Saturation. */
      return z_table[0];
   }
   if (x >= x_table[(UInt8) (map->Nx - 1)]) {
      *(local_xLow) = (UInt8) (map->Nx - 2);
      return z_table[(UInt8) (map->Nx - 1)];
   }
   Aux_U8 = *(local_xLow);
   x_table += Aux_U8;

   /* Local search. */
   if (x < *(x_table)) {
      /* Linear search, start high. */
      do       {
         --(Aux_U8);
         --(x_table);
      }
      while (x < *(x_table));
   }
   else {
      /* Linear search, start low. */
      (x_table)++;
      while (x > *((x_table)++))       {
         (Aux_U8)++;
      }
      x_table -= 2 /* 2. */;
   }
   *(local_xLow) = Aux_U8;
   z_table += Aux_U8;
   Aux_I16 = *((z_table)++);
   Aux_I16_a = *(z_table);

   /* Interpolation. */
   Aux_U16 = (UInt16) (((UInt16) x) - ((UInt16) x_table[0]));
   Aux_U16_a = (UInt16) (((UInt16) x_table[1]) - ((UInt16) x_table[0]));
   if (Aux_I16 <= Aux_I16_a) {
      /* Positive slope. */
      Aux_I16 += ((SInt16) (UInt16) ((((UInt32) (UInt16) (((UInt16) Aux_I16_a) - ((UInt16)
       Aux_I16))) * ((UInt32) Aux_U16)) / Aux_U16_a));
   }
   else {
      /* Negative slope. */
      Aux_I16 -= ((SInt16) (UInt16) ((((UInt32) (UInt16) (((UInt16) Aux_I16) - ((UInt16)
       Aux_I16_a))) * ((UInt32) Aux_U16)) / Aux_U16_a));
   }
   return Aux_I16;
}

#define TQEM_STOP_SEC_CODE
#include "TqEM_MemMap.h"

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TqEM_006_Tab2DS34I2T16652
 *** 
 ***  DESCRIPTION:
 ***      Generated function for 2D look-up tables with common X- and Y-vectors.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_TqEM_006_Tab2DS34I2T16652 *map                 data structure
 ***      SInt16             x                   searching for f(X,y)
 ***      UInt16             y                   searching for f(x,Y
 ***      UInt8 *            local_xLow          last index of x-vector
 ***      UInt8 *            local_yLow          last index of y-vector
 ***
 ***  RETURNS:
 ***      SInt16
 ***
 ***  SETTINGS:
 ***      Row axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Column axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Interpolation
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/

#define TQEM_START_SEC_CODE
#include "TqEM_MemMap.h"
SInt16 TqEM_006_Tab2DS34I2T16652(const MAP_TqEM_006_Tab2DS34I2T16652 * map, SInt16 x, UInt16 y,
  UInt8 * local_xLow, UInt8 * local_yLow)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   SInt16 Aux_I16;
   SInt16 Aux_I16_a;
   SInt16 Aux_I16_b;
   SInt16 Aux_I16_c;
   UInt16 Aux_U16;
   UInt16 Aux_U16_a;

   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;
   UInt8 Aux_U8_a;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const SInt16 * x_table /* Scaling may differ through function reuse. */;
   const UInt16 * y_table /* Scaling may differ through function reuse. */;
   const SInt16 * z_table /* Scaling may differ through function reuse. */;

   x_table = map->x_table;
   y_table = map->y_table;
   z_table = map->z_table;
   Aux_U8 = map->Ny;

   /* Saturation. */
   if (x < *(x_table)) {
      x = x_table[0];
   }
   Aux_I16 = x_table[(UInt8) (map->Nx - 1)];
   if (x > Aux_I16) {
      x = Aux_I16;
   }
   Aux_U8_a = *(local_xLow);
   x_table += Aux_U8_a;

   /* Local search. */
   if (x < *(x_table)) {
      /* Search algorithm for row axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(x_table);
      }
      while (x < *(x_table));
   }
   else {
      /* Search algorithm for row axis. */
      (x_table)++;

      /* Linear search, start low. */
      while (x > *((x_table)++))       {
         (Aux_U8_a)++;
      }
      x_table -= 2 /* 2. */;
   }
   *(local_xLow) = Aux_U8_a;
   z_table += (((UInt16) Aux_U8) * ((UInt16) Aux_U8_a));

   /* Saturation. */
   if (y < *(y_table)) {
      y = y_table[0];
   }
   Aux_U16 = y_table[(UInt8) (Aux_U8 - 1)];
   if (y > Aux_U16) {
      y = Aux_U16;
   }
   Aux_U8_a = *(local_yLow);
   y_table += Aux_U8_a;

   /* Local search. */
   if (y < *(y_table)) {
      /* Search algorithm for column axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(y_table);
      }
      while (y < *(y_table));
   }
   else {
      /* Search algorithm for column axis. */
      (y_table)++;

      /* Linear search, start low. */
      while (y > *((y_table)++))       {
         (Aux_U8_a)++;
      }
      y_table -= 2 /* 2. */;
   }
   *(local_yLow) = Aux_U8_a;
   z_table += Aux_U8_a;

   /* Differences in column axis. */
   Aux_U16 = (UInt16) (y - y_table[0]);
   Aux_U16_a = (UInt16) (y_table[1] - y_table[0]);

   /* Interpolation. */
   if (Aux_U16 == 0) {
      Aux_I16 = z_table[0];
      Aux_I16_a = z_table[Aux_U8];
   }
   else {
      Aux_I16_b = z_table[0];

      /* 1. Y-Interpolation. */
      Aux_I16_c = z_table[1];
      if (Aux_I16_b < Aux_I16_c) {
         /* Positive slope. */
         Aux_I16 = (SInt16) (((UInt16) Aux_I16_b) + ((UInt16) ((((UInt32) (UInt16) (((UInt16)
          Aux_I16_c) - ((UInt16) Aux_I16_b))) * ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      else {
         /* Negative slope. */
         Aux_I16 = (SInt16) (((UInt16) Aux_I16_b) - ((UInt16) ((((UInt32) (UInt16) (((UInt16)
          Aux_I16_b) - ((UInt16) Aux_I16_c))) * ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      z_table += Aux_U8;
      Aux_I16_b = z_table[0];

      /* 2. Y-Interpolation. */
      Aux_I16_c = z_table[1];
      if (Aux_I16_b < Aux_I16_c) {
         /* Positive slope. */
         Aux_I16_a = (SInt16) (((UInt16) Aux_I16_b) + ((UInt16) ((((UInt32) (UInt16) (((UInt16)
          Aux_I16_c) - ((UInt16) Aux_I16_b))) * ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      else {
         /* Negative slope. */
         Aux_I16_a = (SInt16) (((UInt16) Aux_I16_b) - ((UInt16) ((((UInt32) (UInt16) (((UInt16)
          Aux_I16_b) - ((UInt16) Aux_I16_c))) * ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
   }

   /* Differences in row axis. */
   Aux_U16 = (UInt16) (((UInt16) x) - ((UInt16) x_table[0]));
   Aux_U16_a = (UInt16) (((UInt16) x_table[1]) - ((UInt16) x_table[0]));
   if (Aux_U16_a != 0) {
      if (Aux_I16 < Aux_I16_a) {
         /* Positive slope. */
         Aux_I16 += ((SInt16) (UInt16) ((((UInt32) (UInt16) (((UInt16) Aux_I16_a) - ((UInt16)
          Aux_I16))) * ((UInt32) Aux_U16)) / Aux_U16_a));
      }
      else {
         /* Negative slope. */
         Aux_I16 -= ((SInt16) (UInt16) ((((UInt32) (UInt16) (((UInt16) Aux_I16) - ((UInt16)
          Aux_I16_a))) * ((UInt32) Aux_U16)) / Aux_U16_a));
      }
   }
   return Aux_I16;
}

#define TQEM_STOP_SEC_CODE
#include "TqEM_MemMap.h"

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TqEM_006_Tab2DS34I2T4172
 *** 
 ***  DESCRIPTION:
 ***      Generated function for 2D look-up tables with common X- and Y-vectors.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_TqEM_006_Tab2DS34I2T4172 *map                 data structure
 ***      SInt16             x                   searching for f(X,y)
 ***      UInt16             y                   searching for f(x,Y
 ***      UInt8 *            local_xLow          last index of x-vector
 ***      UInt8 *            local_yLow          last index of y-vector
 ***
 ***  RETURNS:
 ***      UInt16
 ***
 ***  SETTINGS:
 ***      Row axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Column axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Interpolation
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/

#define TQEM_START_SEC_CODE
#include "TqEM_MemMap.h"
UInt16 TqEM_006_Tab2DS34I2T4172(const MAP_TqEM_006_Tab2DS34I2T4172 * map, SInt16 x, UInt16 y, UInt8
  * local_xLow, UInt8 * local_yLow)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   SInt16 Aux_I16;
   UInt16 Aux_U16;
   UInt16 Aux_U16_a;
   UInt16 Aux_U16_b;
   UInt16 Aux_U16_c;
   UInt16 Aux_U16_d;

   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;
   UInt8 Aux_U8_a;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const SInt16 * x_table /* Scaling may differ through function reuse. */;
   const UInt16 * y_table /* Scaling may differ through function reuse. */;
   const UInt16 * z_table /* Scaling may differ through function reuse. */;

   x_table = map->x_table;
   y_table = map->y_table;
   z_table = map->z_table;
   Aux_U8 = map->Ny;

   /* Saturation. */
   if (x < *(x_table)) {
      x = x_table[0];
   }
   Aux_I16 = x_table[(UInt8) (map->Nx - 1)];
   if (x > Aux_I16) {
      x = Aux_I16;
   }
   Aux_U8_a = *(local_xLow);
   x_table += Aux_U8_a;

   /* Local search. */
   if (x < *(x_table)) {
      /* Search algorithm for row axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(x_table);
      }
      while (x < *(x_table));
   }
   else {
      /* Search algorithm for row axis. */
      (x_table)++;

      /* Linear search, start low. */
      while (x > *((x_table)++))       {
         (Aux_U8_a)++;
      }
      x_table -= 2 /* 2. */;
   }
   *(local_xLow) = Aux_U8_a;
   z_table += (((UInt16) Aux_U8) * ((UInt16) Aux_U8_a));

   /* Saturation. */
   if (y < *(y_table)) {
      y = y_table[0];
   }
   Aux_U16 = y_table[(UInt8) (Aux_U8 - 1)];
   if (y > Aux_U16) {
      y = Aux_U16;
   }
   Aux_U8_a = *(local_yLow);
   y_table += Aux_U8_a;

   /* Local search. */
   if (y < *(y_table)) {
      /* Search algorithm for column axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(y_table);
      }
      while (y < *(y_table));
   }
   else {
      /* Search algorithm for column axis. */
      (y_table)++;

      /* Linear search, start low. */
      while (y > *((y_table)++))       {
         (Aux_U8_a)++;
      }
      y_table -= 2 /* 2. */;
   }
   *(local_yLow) = Aux_U8_a;
   z_table += Aux_U8_a;

   /* Differences in column axis. */
   Aux_U16 = (UInt16) (y - y_table[0]);
   Aux_U16_a = (UInt16) (y_table[1] - y);
   Aux_U16_b = (UInt16) (Aux_U16 + Aux_U16_a);

   /* Interpolation. */
   if (Aux_U16_b == 0) {
      Aux_U16_c = z_table[0];
      Aux_U16_d = z_table[Aux_U8];
   }
   else {
      /* 1. Y-Interpolation. */
      Aux_U16_c = (UInt16) ((((UInt32) (((UInt32) Aux_U16_a) * ((UInt32) z_table[0]))) + ((UInt32)
       (((UInt32) Aux_U16) * ((UInt32) z_table[1])))) / Aux_U16_b);
      z_table += Aux_U8;

      /* 2. Y-Interpolation. */
      Aux_U16_d = (UInt16) ((((UInt32) (((UInt32) Aux_U16_a) * ((UInt32) z_table[0]))) + ((UInt32)
       (((UInt32) Aux_U16) * ((UInt32) z_table[1])))) / Aux_U16_b);
   }

   /* Differences in row axis. */
   Aux_U16 = (UInt16) (((UInt16) x) - ((UInt16) x_table[0]));
   Aux_U16_a = (UInt16) (((UInt16) x_table[1]) - ((UInt16) x_table[0]));
   if (Aux_U16_a != 0) {
      if (Aux_U16_c < Aux_U16_d) {
         /* Positive slope. */
         Aux_U16_c += ((UInt16) ((((UInt32) (UInt16) (Aux_U16_d - Aux_U16_c)) * ((UInt32) Aux_U16))
          / Aux_U16_a));
      }
      else {
         /* Negative slope. */
         Aux_U16_c -= ((UInt16) ((((UInt32) (UInt16) (Aux_U16_c - Aux_U16_d)) * ((UInt32) Aux_U16))
          / Aux_U16_a));
      }
   }
   return Aux_U16_c;
}

#define TQEM_STOP_SEC_CODE
#include "TqEM_MemMap.h"

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TqEM_006_Tab2DS34I2T4193
 *** 
 ***  DESCRIPTION:
 ***      Generated function for 2D look-up tables with common X- and Y-vectors.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_TqEM_006_Tab2DS34I2T4193 *map                 data structure
 ***      UInt16             x                   searching for f(X,y)
 ***      SInt16             y                   searching for f(x,Y
 ***      UInt8 *            local_xLow          last index of x-vector
 ***      UInt8 *            local_yLow          last index of y-vector
 ***
 ***  RETURNS:
 ***      UInt16
 ***
 ***  SETTINGS:
 ***      Row axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Column axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Interpolation
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/

#define TQEM_START_SEC_CODE
#include "TqEM_MemMap.h"
UInt16 TqEM_006_Tab2DS34I2T4193(const MAP_TqEM_006_Tab2DS34I2T4193 * map, UInt16 x, SInt16 y, UInt8
  * local_xLow, UInt8 * local_yLow)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   SInt16 Aux_I16;
   UInt16 Aux_U16;
   UInt16 Aux_U16_a;
   UInt16 Aux_U16_b;
   UInt16 Aux_U16_c;
   UInt16 Aux_U16_d;
   UInt16 Aux_U16_e;

   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;
   UInt8 Aux_U8_a;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const UInt16 * x_table /* Scaling may differ through function reuse. */;
   const SInt16 * y_table /* Scaling may differ through function reuse. */;
   const UInt16 * z_table /* Scaling may differ through function reuse. */;

   x_table = map->x_table;
   y_table = map->y_table;
   z_table = map->z_table;
   Aux_U8 = map->Ny;

   /* Saturation. */
   if (x < *(x_table)) {
      x = x_table[0];
   }
   Aux_U16 = x_table[(UInt8) (map->Nx - 1)];
   if (x > Aux_U16) {
      x = Aux_U16;
   }
   Aux_U8_a = *(local_xLow);
   x_table += Aux_U8_a;

   /* Local search. */
   if (x < *(x_table)) {
      /* Search algorithm for row axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(x_table);
      }
      while (x < *(x_table));
   }
   else {
      /* Search algorithm for row axis. */
      (x_table)++;

      /* Linear search, start low. */
      while (x > *((x_table)++))       {
         (Aux_U8_a)++;
      }
      x_table -= 2 /* 2. */;
   }
   *(local_xLow) = Aux_U8_a;
   z_table += (((UInt16) Aux_U8) * ((UInt16) Aux_U8_a));

   /* Saturation. */
   if (y < *(y_table)) {
      y = y_table[0];
   }
   Aux_I16 = y_table[(UInt8) (Aux_U8 - 1)];
   if (y > Aux_I16) {
      y = Aux_I16;
   }
   Aux_U8_a = *(local_yLow);
   y_table += Aux_U8_a;

   /* Local search. */
   if (y < *(y_table)) {
      /* Search algorithm for column axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(y_table);
      }
      while (y < *(y_table));
   }
   else {
      /* Search algorithm for column axis. */
      (y_table)++;

      /* Linear search, start low. */
      while (y > *((y_table)++))       {
         (Aux_U8_a)++;
      }
      y_table -= 2 /* 2. */;
   }
   *(local_yLow) = Aux_U8_a;
   z_table += Aux_U8_a;

   /* Differences in column axis. */
   Aux_U16 = (UInt16) (((UInt16) y) - ((UInt16) y_table[0]));
   Aux_U16_a = (UInt16) (((UInt16) y_table[1]) - ((UInt16) y_table[0]));

   /* Interpolation. */
   if (Aux_U16 == 0) {
      Aux_U16_b = z_table[0];
      Aux_U16_c = z_table[Aux_U8];
   }
   else {
      Aux_U16_d = z_table[0];

      /* 1. Y-Interpolation. */
      Aux_U16_e = z_table[1];
      if (Aux_U16_d < Aux_U16_e) {
         /* Positive slope. */
         Aux_U16_b = (UInt16) (Aux_U16_d + ((UInt16) ((((UInt32) (UInt16) (Aux_U16_e - Aux_U16_d)) *
           ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      else {
         /* Negative slope. */
         Aux_U16_b = (UInt16) (Aux_U16_d - ((UInt16) ((((UInt32) (UInt16) (Aux_U16_d - Aux_U16_e)) *
           ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      z_table += Aux_U8;
      Aux_U16_d = z_table[0];

      /* 2. Y-Interpolation. */
      Aux_U16_e = z_table[1];
      if (Aux_U16_d < Aux_U16_e) {
         /* Positive slope. */
         Aux_U16_c = (UInt16) (Aux_U16_d + ((UInt16) ((((UInt32) (UInt16) (Aux_U16_e - Aux_U16_d)) *
           ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      else {
         /* Negative slope. */
         Aux_U16_c = (UInt16) (Aux_U16_d - ((UInt16) ((((UInt32) (UInt16) (Aux_U16_d - Aux_U16_e)) *
           ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
   }

   /* Differences in row axis. */
   Aux_U16 = (UInt16) (x - x_table[0]);
   Aux_U16_a = (UInt16) (x_table[1] - x);
   Aux_U16_d = (UInt16) (Aux_U16 + Aux_U16_a);
   if (Aux_U16_d != 0) {
      /* X-Interpolation. */
      Aux_U16_b = (UInt16) ((((UInt32) (((UInt32) Aux_U16_a) * ((UInt32) Aux_U16_b))) + ((UInt32)
       (((UInt32) Aux_U16) * ((UInt32) Aux_U16_c)))) / Aux_U16_d);
   }
   return Aux_U16_b;
}

#define TQEM_STOP_SEC_CODE
#include "TqEM_MemMap.h"

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TqEM_006_Tab1DS2I2T1
 *** 
 ***  DESCRIPTION:
 ***      Generated function for look-up tables.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_TqEM_006_Tab1DS2I2T1 *map                 data structure
 ***      UInt16             x                   table input
 ***      UInt8 *            local_xLow          table index found in previous search
 ***
 ***  RETURNS:
 ***      UInt8
 ***
 ***  SETTINGS:
 ***      Search algorithm...................: local search
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***      Behavior at boundaries.............: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***
\**************************************************************************************************/

#define TQEM_START_SEC_CODE
#include "TqEM_MemMap.h"
UInt8 TqEM_006_Tab1DS2I2T1(const MAP_TqEM_006_Tab1DS2I2T1 * map, UInt16 x, UInt8 * local_xLow)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   UInt16 Aux_U16;
   UInt16 Aux_U16_a;

   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const UInt16 * x_table /* Scaling may differ through function reuse. */;
   const UInt8 * z_table /* Scaling may differ through function reuse. */;

   x_table = map->x_table;
   z_table = map->z_table;
   if (x <= *(x_table)) {
      *(local_xLow) = 0;

      /* Saturation. */
      return z_table[0];
   }
   if (x >= x_table[(UInt8) (map->Nx - 1)]) {
      *(local_xLow) = (UInt8) (map->Nx - 2);
      return z_table[(UInt8) (map->Nx - 1)];
   }
   Aux_U8 = *(local_xLow);
   x_table += Aux_U8;

   /* Local search. */
   if (x < *(x_table)) {
      /* Linear search, start high. */
      do       {
         --(Aux_U8);
         --(x_table);
      }
      while (x < *(x_table));
   }
   else {
      /* Linear search, start low. */
      (x_table)++;
      while (x > *((x_table)++))       {
         (Aux_U8)++;
      }
      x_table -= 2 /* 2. */;
   }
   *(local_xLow) = Aux_U8;
   z_table += Aux_U8;

   /* Interpolation. */
   Aux_U16 = (UInt16) (x - x_table[0]);
   Aux_U16_a = (UInt16) (x_table[1] - x);
   return ((UInt8) ((((UInt32) (((UInt32) Aux_U16) * ((UInt32) z_table[1]))) + ((UInt32) (((UInt32)
    Aux_U16_a) * ((UInt32) z_table[0])))) / ((UInt16) (Aux_U16 + Aux_U16_a))));
}

#define TQEM_STOP_SEC_CODE
#include "TqEM_MemMap.h"

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TqEM_006_Tab1DS2I2T4
 *** 
 ***  DESCRIPTION:
 ***      Generated function for look-up tables.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_TqEM_006_Tab1DS2I2T4 *map                 data structure
 ***      SInt16             x                   table input
 ***      UInt8 *            local_xLow          table index found in previous search
 ***
 ***  RETURNS:
 ***      UInt8
 ***
 ***  SETTINGS:
 ***      Search algorithm...................: local search
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***      Behavior at boundaries.............: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***
\**************************************************************************************************/

#define TQEM_START_SEC_CODE
#include "TqEM_MemMap.h"
UInt8 TqEM_006_Tab1DS2I2T4(const MAP_TqEM_006_Tab1DS2I2T4 * map, SInt16 x, UInt8 * local_xLow)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   UInt16 Aux_U16;
   UInt16 Aux_U16_a;

   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;
   UInt8 Aux_U8_a;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const SInt16 * x_table /* Scaling may differ through function reuse. */;
   const UInt8 * z_table /* Scaling may differ through function reuse. */;

   x_table = map->x_table;
   z_table = map->z_table;
   if (x <= *(x_table)) {
      *(local_xLow) = 0;

      /* Saturation. */
      return z_table[0];
   }
   if (x >= x_table[(UInt8) (map->Nx - 1)]) {
      *(local_xLow) = (UInt8) (map->Nx - 2);
      return z_table[(UInt8) (map->Nx - 1)];
   }
   Aux_U8 = *(local_xLow);
   x_table += Aux_U8;

   /* Local search. */
   if (x < *(x_table)) {
      /* Linear search, start high. */
      do       {
         --(Aux_U8);
         --(x_table);
      }
      while (x < *(x_table));
   }
   else {
      /* Linear search, start low. */
      (x_table)++;
      while (x > *((x_table)++))       {
         (Aux_U8)++;
      }
      x_table -= 2 /* 2. */;
   }
   *(local_xLow) = Aux_U8;
   z_table += Aux_U8;
   Aux_U8 = *((z_table)++);
   Aux_U8_a = *(z_table);

   /* Interpolation. */
   Aux_U16 = (UInt16) (((UInt16) x) - ((UInt16) x_table[0]));
   Aux_U16_a = (UInt16) (((UInt16) x_table[1]) - ((UInt16) x_table[0]));
   if (Aux_U8 <= Aux_U8_a) {
      /* Positive slope. */
      Aux_U8 += ((UInt8) ((((UInt32) (UInt8) (Aux_U8_a - Aux_U8)) * ((UInt32) Aux_U16)) / 
       Aux_U16_a));
   }
   else {
      /* Negative slope. */
      Aux_U8 -= ((UInt8) ((((UInt32) (UInt8) (Aux_U8 - Aux_U8_a)) * ((UInt32) Aux_U16)) / 
       Aux_U16_a));
   }
   return Aux_U8;
}

#define TQEM_STOP_SEC_CODE
#include "TqEM_MemMap.h"

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TqEM_006_Tab1DS2I4T0
 *** 
 ***  DESCRIPTION:
 ***      Generated function for look-up tables.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_TqEM_006_Tab1DS2I4T0 *map                 data structure
 ***      UInt8              x                   table input
 ***      UInt8 *            local_xLow          table index found in previous search
 ***
 ***  RETURNS:
 ***      UInt8
 ***
 ***  SETTINGS:
 ***      Search algorithm...................: local search
 ***      Look-up method.....................: Use input nearest
 ***      Distances fit into given bitlengths: - (no interpolation)
 ***      Behavior at boundaries.............: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***
\**************************************************************************************************/

#define TQEM_START_SEC_CODE
#include "TqEM_MemMap.h"
UInt8 TqEM_006_Tab1DS2I4T0(const MAP_TqEM_006_Tab1DS2I4T0 * map, UInt8 x, UInt8 * local_xLow)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const UInt8 * x_table /* Scaling may differ through function reuse. */;
   const UInt8 * z_table /* Scaling may differ through function reuse. */;

   x_table = map->x_table;
   z_table = map->z_table;
   if (x <= *(x_table)) {
      *(local_xLow) = 0;

      /* Saturation. */
      return z_table[0];
   }
   if (x >= x_table[(UInt8) (map->Nx - 1)]) {
      *(local_xLow) = (UInt8) (map->Nx - 2);
      return z_table[(UInt8) (map->Nx - 1)];
   }
   Aux_U8 = *(local_xLow);
   x_table += Aux_U8;

   /* Local search. */
   if (x < *(x_table)) {
      /* Linear search, start high. */
      do       {
         --(Aux_U8);
         --(x_table);
      }
      while (x < *(x_table));
   }
   else {
      /* Linear search, start low. */
      (x_table)++;
      while (x > *((x_table)++))       {
         (Aux_U8)++;
      }
      x_table -= 2 /* 2. */;
   }
   *(local_xLow) = Aux_U8;
   z_table += Aux_U8;

   /* Look-up method: Use Input Nearest */
   return ((((UInt8) (x - x_table[0])) < ((UInt8) (x_table[1] - x))) ? z_table[0] : z_table[1]);
}

#define TQEM_STOP_SEC_CODE
#include "TqEM_MemMap.h"

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TqEM_006_Tab2DS34I2T32
 *** 
 ***  DESCRIPTION:
 ***      Generated function for 2D look-up tables with common X- and Y-vectors.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_TqEM_006_Tab2DS34I2T32 *map                 data structure
 ***      UInt8              x                   searching for f(X,y)
 ***      SInt16             y                   searching for f(x,Y
 ***      UInt8 *            local_xLow          last index of x-vector
 ***      UInt8 *            local_yLow          last index of y-vector
 ***
 ***  RETURNS:
 ***      UInt8
 ***
 ***  SETTINGS:
 ***      Row axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Column axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Interpolation
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/

#define TQEM_START_SEC_CODE
#include "TqEM_MemMap.h"
UInt8 TqEM_006_Tab2DS34I2T32(const MAP_TqEM_006_Tab2DS34I2T32 * map, UInt8 x, SInt16 y, UInt8 *
  local_xLow, UInt8 * local_yLow)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   SInt16 Aux_I16;
   UInt16 Aux_U16;
   UInt16 Aux_U16_a;

   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;
   UInt8 Aux_U8_a;
   UInt8 Aux_U8_b;
   UInt8 Aux_U8_c;
   UInt8 Aux_U8_d;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const UInt8 * x_table /* Scaling may differ through function reuse. */;
   const SInt16 * y_table /* Scaling may differ through function reuse. */;
   const UInt8 * z_table /* Scaling may differ through function reuse. */;

   x_table = map->x_table;
   y_table = map->y_table;
   z_table = map->z_table;
   Aux_U8 = map->Ny;

   /* Saturation. */
   if (x < *(x_table)) {
      x = x_table[0];
   }
   Aux_U8_a = x_table[(UInt8) (map->Nx - 1)];
   if (x > Aux_U8_a) {
      x = Aux_U8_a;
   }
   Aux_U8_a = *(local_xLow);
   x_table += Aux_U8_a;

   /* Local search. */
   if (x < *(x_table)) {
      /* Search algorithm for row axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(x_table);
      }
      while (x < *(x_table));
   }
   else {
      /* Search algorithm for row axis. */
      (x_table)++;

      /* Linear search, start low. */
      while (x > *((x_table)++))       {
         (Aux_U8_a)++;
      }
      x_table -= 2 /* 2. */;
   }
   *(local_xLow) = Aux_U8_a;
   z_table += (((UInt16) Aux_U8) * ((UInt16) Aux_U8_a));

   /* Saturation. */
   if (y < *(y_table)) {
      y = y_table[0];
   }
   Aux_I16 = y_table[(UInt8) (Aux_U8 - 1)];
   if (y > Aux_I16) {
      y = Aux_I16;
   }
   Aux_U8_a = *(local_yLow);
   y_table += Aux_U8_a;

   /* Local search. */
   if (y < *(y_table)) {
      /* Search algorithm for column axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(y_table);
      }
      while (y < *(y_table));
   }
   else {
      /* Search algorithm for column axis. */
      (y_table)++;

      /* Linear search, start low. */
      while (y > *((y_table)++))       {
         (Aux_U8_a)++;
      }
      y_table -= 2 /* 2. */;
   }
   *(local_yLow) = Aux_U8_a;
   z_table += Aux_U8_a;

   /* Differences in column axis. */
   Aux_U16 = (UInt16) (((UInt16) y) - ((UInt16) y_table[0]));
   Aux_U16_a = (UInt16) (((UInt16) y_table[1]) - ((UInt16) y_table[0]));

   /* Interpolation. */
   if (Aux_U16 == 0) {
      Aux_U8_a = z_table[0];
      Aux_U8_b = z_table[Aux_U8];
   }
   else {
      Aux_U8_c = z_table[0];

      /* 1. Y-Interpolation. */
      Aux_U8_d = z_table[1];
      if (Aux_U8_c < Aux_U8_d) {
         /* Positive slope. */
         Aux_U8_a = (UInt8) (Aux_U8_c + ((UInt8) ((((UInt32) (UInt8) (Aux_U8_d - Aux_U8_c)) *
          ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      else {
         /* Negative slope. */
         Aux_U8_a = (UInt8) (Aux_U8_c - ((UInt8) ((((UInt32) (UInt8) (Aux_U8_c - Aux_U8_d)) *
          ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      z_table += Aux_U8;
      Aux_U8_c = z_table[0];

      /* 2. Y-Interpolation. */
      Aux_U8_d = z_table[1];
      if (Aux_U8_c < Aux_U8_d) {
         /* Positive slope. */
         Aux_U8_b = (UInt8) (Aux_U8_c + ((UInt8) ((((UInt32) (UInt8) (Aux_U8_d - Aux_U8_c)) *
          ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      else {
         /* Negative slope. */
         Aux_U8_b = (UInt8) (Aux_U8_c - ((UInt8) ((((UInt32) (UInt8) (Aux_U8_c - Aux_U8_d)) *
          ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
   }

   /* Differences in row axis. */
   Aux_U8 = (UInt8) (x - x_table[0]);
   Aux_U8_c = (UInt8) (x_table[1] - x);
   Aux_U8_d = (UInt8) (Aux_U8 + Aux_U8_c);
   if (Aux_U8_d != 0) {
      /* X-Interpolation. */
      Aux_U8_a = (UInt8) (((UInt16) (((UInt16) (((UInt16) Aux_U8_c) * ((UInt16) Aux_U8_a))) +
       ((UInt16) (((UInt16) Aux_U8) * ((UInt16) Aux_U8_b))))) / Aux_U8_d);
   }
   return Aux_U8_a;
}

#define TQEM_STOP_SEC_CODE
#include "TqEM_MemMap.h"

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TqEM_006_Tab2DS34I2T36
 *** 
 ***  DESCRIPTION:
 ***      Generated function for 2D look-up tables with common X- and Y-vectors.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_TqEM_006_Tab2DS34I2T36 *map                 data structure
 ***      SInt16             x                   searching for f(X,y)
 ***      SInt16             y                   searching for f(x,Y
 ***      UInt8 *            local_xLow          last index of x-vector
 ***      UInt8 *            local_yLow          last index of y-vector
 ***
 ***  RETURNS:
 ***      UInt8
 ***
 ***  SETTINGS:
 ***      Row axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Column axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Interpolation
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/

#define TQEM_START_SEC_CODE
#include "TqEM_MemMap.h"
UInt8 TqEM_006_Tab2DS34I2T36(const MAP_TqEM_006_Tab2DS34I2T36 * map, SInt16 x, SInt16 y, UInt8 *
  local_xLow, UInt8 * local_yLow)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   SInt16 Aux_I16;
   UInt16 Aux_U16;
   UInt16 Aux_U16_a;

   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;
   UInt8 Aux_U8_a;
   UInt8 Aux_U8_b;
   UInt8 Aux_U8_c;
   UInt8 Aux_U8_d;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const SInt16 * x_table /* Scaling may differ through function reuse. */;
   const SInt16 * y_table /* Scaling may differ through function reuse. */;
   const UInt8 * z_table /* Scaling may differ through function reuse. */;

   x_table = map->x_table;
   y_table = map->y_table;
   z_table = map->z_table;
   Aux_U8 = map->Ny;

   /* Saturation. */
   if (x < *(x_table)) {
      x = x_table[0];
   }
   Aux_I16 = x_table[(UInt8) (map->Nx - 1)];
   if (x > Aux_I16) {
      x = Aux_I16;
   }
   Aux_U8_a = *(local_xLow);
   x_table += Aux_U8_a;

   /* Local search. */
   if (x < *(x_table)) {
      /* Search algorithm for row axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(x_table);
      }
      while (x < *(x_table));
   }
   else {
      /* Search algorithm for row axis. */
      (x_table)++;

      /* Linear search, start low. */
      while (x > *((x_table)++))       {
         (Aux_U8_a)++;
      }
      x_table -= 2 /* 2. */;
   }
   *(local_xLow) = Aux_U8_a;
   z_table += (((UInt16) Aux_U8) * ((UInt16) Aux_U8_a));

   /* Saturation. */
   if (y < *(y_table)) {
      y = y_table[0];
   }
   Aux_I16 = y_table[(UInt8) (Aux_U8 - 1)];
   if (y > Aux_I16) {
      y = Aux_I16;
   }
   Aux_U8_a = *(local_yLow);
   y_table += Aux_U8_a;

   /* Local search. */
   if (y < *(y_table)) {
      /* Search algorithm for column axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(y_table);
      }
      while (y < *(y_table));
   }
   else {
      /* Search algorithm for column axis. */
      (y_table)++;

      /* Linear search, start low. */
      while (y > *((y_table)++))       {
         (Aux_U8_a)++;
      }
      y_table -= 2 /* 2. */;
   }
   *(local_yLow) = Aux_U8_a;
   z_table += Aux_U8_a;

   /* Differences in column axis. */
   Aux_U16 = (UInt16) (((UInt16) y) - ((UInt16) y_table[0]));
   Aux_U16_a = (UInt16) (((UInt16) y_table[1]) - ((UInt16) y_table[0]));

   /* Interpolation. */
   if (Aux_U16 == 0) {
      Aux_U8_a = z_table[0];
      Aux_U8_b = z_table[Aux_U8];
   }
   else {
      Aux_U8_c = z_table[0];

      /* 1. Y-Interpolation. */
      Aux_U8_d = z_table[1];
      if (Aux_U8_c < Aux_U8_d) {
         /* Positive slope. */
         Aux_U8_a = (UInt8) (Aux_U8_c + ((UInt8) ((((UInt32) (UInt8) (Aux_U8_d - Aux_U8_c)) *
          ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      else {
         /* Negative slope. */
         Aux_U8_a = (UInt8) (Aux_U8_c - ((UInt8) ((((UInt32) (UInt8) (Aux_U8_c - Aux_U8_d)) *
          ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      z_table += Aux_U8;
      Aux_U8_c = z_table[0];

      /* 2. Y-Interpolation. */
      Aux_U8_d = z_table[1];
      if (Aux_U8_c < Aux_U8_d) {
         /* Positive slope. */
         Aux_U8_b = (UInt8) (Aux_U8_c + ((UInt8) ((((UInt32) (UInt8) (Aux_U8_d - Aux_U8_c)) *
          ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
      else {
         /* Negative slope. */
         Aux_U8_b = (UInt8) (Aux_U8_c - ((UInt8) ((((UInt32) (UInt8) (Aux_U8_c - Aux_U8_d)) *
          ((UInt32) Aux_U16)) / Aux_U16_a)));
      }
   }

   /* Differences in row axis. */
   Aux_U16 = (UInt16) (((UInt16) x) - ((UInt16) x_table[0]));
   Aux_U16_a = (UInt16) (((UInt16) x_table[1]) - ((UInt16) x_table[0]));
   if (Aux_U16_a != 0) {
      if (Aux_U8_a < Aux_U8_b) {
         /* Positive slope. */
         Aux_U8_a += ((UInt8) ((((UInt32) (UInt8) (Aux_U8_b - Aux_U8_a)) * ((UInt32) Aux_U16)) / 
          Aux_U16_a));
      }
      else {
         /* Negative slope. */
         Aux_U8_a -= ((UInt8) ((((UInt32) (UInt8) (Aux_U8_a - Aux_U8_b)) * ((UInt32) Aux_U16)) / 
          Aux_U16_a));
      }
   }
   return Aux_U8_a;
}

#define TQEM_STOP_SEC_CODE
#include "TqEM_MemMap.h"

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TqEM_006_Tab2DS34I2T8
 *** 
 ***  DESCRIPTION:
 ***      Generated function for 2D look-up tables with common X- and Y-vectors.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_TqEM_006_Tab2DS34I2T8 *map                 data structure
 ***      UInt8              x                   searching for f(X,y)
 ***      UInt16             y                   searching for f(x,Y
 ***      UInt8 *            local_xLow          last index of x-vector
 ***      UInt8 *            local_yLow          last index of y-vector
 ***
 ***  RETURNS:
 ***      UInt8
 ***
 ***  SETTINGS:
 ***      Row axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Column axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Interpolation
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/

#define TQEM_START_SEC_CODE
#include "TqEM_MemMap.h"
UInt8 TqEM_006_Tab2DS34I2T8(const MAP_TqEM_006_Tab2DS34I2T8 * map, UInt8 x, UInt16 y, UInt8 *
  local_xLow, UInt8 * local_yLow)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   UInt16 Aux_U16;
   UInt16 Aux_U16_a;
   UInt16 Aux_U16_b;

   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;
   UInt8 Aux_U8_a;
   UInt8 Aux_U8_b;
   UInt8 Aux_U8_c;
   UInt8 Aux_U8_d;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const UInt8 * x_table /* Scaling may differ through function reuse. */;
   const UInt16 * y_table /* Scaling may differ through function reuse. */;
   const UInt8 * z_table /* Scaling may differ through function reuse. */;

   x_table = map->x_table;
   y_table = map->y_table;
   z_table = map->z_table;
   Aux_U8 = map->Ny;

   /* Saturation. */
   if (x < *(x_table)) {
      x = x_table[0];
   }
   Aux_U8_a = x_table[(UInt8) (map->Nx - 1)];
   if (x > Aux_U8_a) {
      x = Aux_U8_a;
   }
   Aux_U8_a = *(local_xLow);
   x_table += Aux_U8_a;

   /* Local search. */
   if (x < *(x_table)) {
      /* Search algorithm for row axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(x_table);
      }
      while (x < *(x_table));
   }
   else {
      /* Search algorithm for row axis. */
      (x_table)++;

      /* Linear search, start low. */
      while (x > *((x_table)++))       {
         (Aux_U8_a)++;
      }
      x_table -= 2 /* 2. */;
   }
   *(local_xLow) = Aux_U8_a;
   z_table += (((UInt16) Aux_U8) * ((UInt16) Aux_U8_a));

   /* Saturation. */
   if (y < *(y_table)) {
      y = y_table[0];
   }
   Aux_U16 = y_table[(UInt8) (Aux_U8 - 1)];
   if (y > Aux_U16) {
      y = Aux_U16;
   }
   Aux_U8_a = *(local_yLow);
   y_table += Aux_U8_a;

   /* Local search. */
   if (y < *(y_table)) {
      /* Search algorithm for column axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(y_table);
      }
      while (y < *(y_table));
   }
   else {
      /* Search algorithm for column axis. */
      (y_table)++;

      /* Linear search, start low. */
      while (y > *((y_table)++))       {
         (Aux_U8_a)++;
      }
      y_table -= 2 /* 2. */;
   }
   *(local_yLow) = Aux_U8_a;
   z_table += Aux_U8_a;

   /* Differences in column axis. */
   Aux_U16 = (UInt16) (y - y_table[0]);
   Aux_U16_a = (UInt16) (y_table[1] - y);
   Aux_U16_b = (UInt16) (Aux_U16 + Aux_U16_a);

   /* Interpolation. */
   if (Aux_U16_b == 0) {
      Aux_U8_a = z_table[0];
      Aux_U8_b = z_table[Aux_U8];
   }
   else {
      /* 1. Y-Interpolation. */
      Aux_U8_a = (UInt8) ((((UInt32) (((UInt32) Aux_U16_a) * ((UInt32) z_table[0]))) + ((UInt32)
       (((UInt32) Aux_U16) * ((UInt32) z_table[1])))) / Aux_U16_b);
      z_table += Aux_U8;

      /* 2. Y-Interpolation. */
      Aux_U8_b = (UInt8) ((((UInt32) (((UInt32) Aux_U16_a) * ((UInt32) z_table[0]))) + ((UInt32)
       (((UInt32) Aux_U16) * ((UInt32) z_table[1])))) / Aux_U16_b);
   }

   /* Differences in row axis. */
   Aux_U8 = (UInt8) (x - x_table[0]);
   Aux_U8_c = (UInt8) (x_table[1] - x);
   Aux_U8_d = (UInt8) (Aux_U8 + Aux_U8_c);
   if (Aux_U8_d != 0) {
      /* X-Interpolation. */
      Aux_U8_a = (UInt8) (((UInt16) (((UInt16) (((UInt16) Aux_U8_c) * ((UInt16) Aux_U8_a))) +
       ((UInt16) (((UInt16) Aux_U8) * ((UInt16) Aux_U8_b))))) / Aux_U8_d);
   }
   return Aux_U8_a;
}

#define TQEM_STOP_SEC_CODE
#include "TqEM_MemMap.h"

/**************************************************************************************************\
 ***  FUNCTION:
 ***      TqEM_006_Tab2DS34I2T9
 *** 
 ***  DESCRIPTION:
 ***      Generated function for 2D look-up tables with common X- and Y-vectors.
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      const MAP_TqEM_006_Tab2DS34I2T9 *map                 data structure
 ***      UInt16             x                   searching for f(X,y)
 ***      UInt16             y                   searching for f(x,Y
 ***      UInt8 *            local_xLow          last index of x-vector
 ***      UInt8 *            local_yLow          last index of y-vector
 ***
 ***  RETURNS:
 ***      UInt8
 ***
 ***  SETTINGS:
 ***      Row axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Column axis
 ***      Search algorithm...................: local search
 ***      Boundary points....................: no
 ***      Starting point.....................: - (non-equidistant implementation)
 ***      Scaling unit.......................: - (non-equidistant implementation)
 ***      Interpolation
 ***      Look-up method.....................: Interpolation - Use end values
 ***      Distances fit into given bitlengths: no
 ***
\**************************************************************************************************/

#define TQEM_START_SEC_CODE
#include "TqEM_MemMap.h"
UInt8 TqEM_006_Tab2DS34I2T9(const MAP_TqEM_006_Tab2DS34I2T9 * map, UInt16 x, UInt16 y, UInt8 *
  local_xLow, UInt8 * local_yLow)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   UInt16 Aux_U16;
   UInt16 Aux_U16_a;
   UInt16 Aux_U16_b;

   /* SLLocal: Default storage class for local variables | Width: 8 */
   UInt8 Aux_U8;
   UInt8 Aux_U8_a;
   UInt8 Aux_U8_b;

   /* SLLutLocalConst: Default storage class for local variables | Width: 32 */
   const UInt16 * x_table /* Scaling may differ through function reuse. */;
   const UInt16 * y_table /* Scaling may differ through function reuse. */;
   const UInt8 * z_table /* Scaling may differ through function reuse. */;

   x_table = map->x_table;
   y_table = map->y_table;
   z_table = map->z_table;
   Aux_U8 = map->Ny;

   /* Saturation. */
   if (x < *(x_table)) {
      x = x_table[0];
   }
   Aux_U16 = x_table[(UInt8) (map->Nx - 1)];
   if (x > Aux_U16) {
      x = Aux_U16;
   }
   Aux_U8_a = *(local_xLow);
   x_table += Aux_U8_a;

   /* Local search. */
   if (x < *(x_table)) {
      /* Search algorithm for row axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(x_table);
      }
      while (x < *(x_table));
   }
   else {
      /* Search algorithm for row axis. */
      (x_table)++;

      /* Linear search, start low. */
      while (x > *((x_table)++))       {
         (Aux_U8_a)++;
      }
      x_table -= 2 /* 2. */;
   }
   *(local_xLow) = Aux_U8_a;
   z_table += (((UInt16) Aux_U8) * ((UInt16) Aux_U8_a));

   /* Saturation. */
   if (y < *(y_table)) {
      y = y_table[0];
   }
   Aux_U16 = y_table[(UInt8) (Aux_U8 - 1)];
   if (y > Aux_U16) {
      y = Aux_U16;
   }
   Aux_U8_a = *(local_yLow);
   y_table += Aux_U8_a;

   /* Local search. */
   if (y < *(y_table)) {
      /* Search algorithm for column axis.
         Linear search, start high. */
      do       {
         --(Aux_U8_a);
         --(y_table);
      }
      while (y < *(y_table));
   }
   else {
      /* Search algorithm for column axis. */
      (y_table)++;

      /* Linear search, start low. */
      while (y > *((y_table)++))       {
         (Aux_U8_a)++;
      }
      y_table -= 2 /* 2. */;
   }
   *(local_yLow) = Aux_U8_a;
   z_table += Aux_U8_a;

   /* Differences in column axis. */
   Aux_U16 = (UInt16) (y - y_table[0]);
   Aux_U16_a = (UInt16) (y_table[1] - y);
   Aux_U16_b = (UInt16) (Aux_U16 + Aux_U16_a);

   /* Interpolation. */
   if (Aux_U16_b == 0) {
      Aux_U8_a = z_table[0];
      Aux_U8_b = z_table[Aux_U8];
   }
   else {
      /* 1. Y-Interpolation. */
      Aux_U8_a = (UInt8) ((((UInt32) (((UInt32) Aux_U16_a) * ((UInt32) z_table[0]))) + ((UInt32)
       (((UInt32) Aux_U16) * ((UInt32) z_table[1])))) / Aux_U16_b);
      z_table += Aux_U8;

      /* 2. Y-Interpolation. */
      Aux_U8_b = (UInt8) ((((UInt32) (((UInt32) Aux_U16_a) * ((UInt32) z_table[0]))) + ((UInt32)
       (((UInt32) Aux_U16) * ((UInt32) z_table[1])))) / Aux_U16_b);
   }

   /* Differences in row axis. */
   Aux_U16 = (UInt16) (x - x_table[0]);
   Aux_U16_a = (UInt16) (x_table[1] - x);
   Aux_U16_b = (UInt16) (Aux_U16 + Aux_U16_a);
   if (Aux_U16_b != 0) {
      /* X-Interpolation. */
      Aux_U8_a = (UInt8) ((((UInt32) (((UInt32) Aux_U16_a) * ((UInt32) Aux_U8_a))) + ((UInt32)
       (((UInt32) Aux_U16) * ((UInt32) Aux_U8_b)))) / Aux_U16_b);
   }
   return Aux_U8_a;
}

#define TQEM_STOP_SEC_CODE
#include "TqEM_MemMap.h"

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

#endif/*_TQEM_006_LUT_C_ */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
