/* Auto-Code from ISFHCAN_ut8.xml, project.xml and Adaptations.xml files */
/* 13/10/2014 16:01:16 */
/* File: FHCANF4B2_PRIVATE.H */

#ifndef FHCANF4B2_PRIVATE_H
#define FHCANF4B2_PRIVATE_H

#include "STD_TYPES.H"
/******************************************************************************/
/* FUNCTIONS                                                                  */
/******************************************************************************/
#define ISFHCAN_START_SEC_CODE
#include "ISFHCAN_MemMap.h"

extern void FHCAN4B2_vidCalcMonWindow(void);
extern void FHCANF4B2_vidUpdateSignalPM1481(void);
extern void FHCANF4B2_vidUpdateSignalPM1482(void);
extern void FHCANF4B2_vidUpdateSignalPM1483(void);
extern void FHCANF4B2_vidUpdateSignalPM1484(void);
extern void FHCANF4B2_vidUpdateSignalPM1485(void);
extern void FHCANF4B2_vidUpdateSignalPM1486(void);
extern void FHCANF4B2_vidUpdateSignalPM1487(void);
extern void FHCANF4B2_vidUpdateSignalPM1488(void);

#define ISFHCAN_STOP_SEC_CODE
#include "ISFHCAN_MemMap.h"
#endif
