/* Auto-Code from ISFHCAN_ut8.xml, project.xml and Adaptations.xml files */
/* 08/10/2014 15:03:49 */
/* File: ISCANF608.H */
#ifndef ISCANF608_H
#define ISCANF608_H

#include "STD_TYPES.H"

/******************************************************************************/
/* FUNCTIONS                                                                  */
/******************************************************************************/
#define ISFHCAN_START_SEC_CODE
#include "ISFHCAN_MemMap.h"

extern void ISCAN_vidInit_Tx_608(void);
extern void ISCAN_vidEve_Tx_608(void);

#define ISFHCAN_STOP_SEC_CODE
#include "ISFHCAN_MemMap.h"

/******************************************************************************/
/* DATAS                                                                      */
/******************************************************************************/

#endif
