/**************************************************************************************************\
 *** 
 ***                            P. C. A.
 *** 
 ***                     Peugeot Citroen Automobile
 *** 
 ***         This file is the property of PCA. All rights are reserved
 ***         by PCA and this file must not be copied or disclosed
 ***        (in whole or in part) without prior written consent of PCA.
 *** 
 *** *******************************************************************************
 *** 
 ***  %name: EngLim_calibrations.h %
 *** 
 ***  %version: 11.0.build3 %
 *** 
 ***  %date_modified: Wed Feb 15 10:52:40 2012 %
 *** 
 *** 
 ***  %derived_by: e343811 %
 ***  %release: TqStruct/10.0 %
 ***  %full_filespec: EngLim_calibrations.h-11.0.build3:incl:1 %
 *** 
 *** *******************************************************************************
 *** 
 *** Simulink model       : CSMT_CGMT06_2193
 *** TargetLink subsystem : CSMT_CGMT06_2193/F0_Limitation_Couple_Inertiel_MAV_MAR
 *** Codefile             : englim_calibrations.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2012-01-23 16:25:35
 ***
 *** CODE GENERATOR OPTIONS:
 *** Compiler                            : <unknown>
 *** Target                              : Generic
 *** ANSI-C compatible code              : yes
 *** Optimization level                  : 2
 *** Constant style                      : decimal
 *** Clean code option                   : enabled
 *** Logging mode                        : Do not log anything
 *** Linker sections                     : enabled
 *** Assembler statements                : disabled
 *** Variable name length                : 31 chars
 *** Use global bitfields                : disabled
 *** Stateflow: use of bitfields         : enabled
 *** State activity encoding limit       : 5
 *** Omit zero inits in restart function : disabled
 *** Share fcns between TL subsystems    : disabled
 *** Generate 64bit functions            : enabled
 *** Inlining Threshold                  : 6
 *** Line break limit                    : 100
 *** Target optimized boolean data type  : enabled
 *** Keep saturation elements            : disabled
 *** Extended variable sharing           : disabled
 *** Style definition file               : C:\dSPACE\Matlab\Tl\config\codegen\cconfig.xml
 *** Root style sheet                    : C:\dSPACE\Matlab\Tl\XML\CodeGen\Stylesheets\TL_CSourceCod
 ***                                       eSS.xsl
 *** Enable Multirate codegeneration     : disabled
 *** Add model checksum                  : disabled
 ***
 *** TargetLink version      : 3.0.1 from 26-May-2009
 *** Code generator version  : Build Id 3.0.1.7 from 2009-May-06 15:28:18
 *** Copyright (c) 2006 dSPACE GmbH
\**************************************************************************************************/

#ifndef _ENGLIM_CALIBRATIONS_H_
#define _ENGLIM_CALIBRATIONS_H_

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "tl_defines.h"
#include "tl_basetypes.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

#define ENGLIM_START_SEC_CALIB_16BIT
#include "EngLim_MemMap.h"
/******************************************************************************\
   AR_MERGEABLE_CALIB_16BIT: Mergeable Calib 16 bits for AUTOSAR modules | Width: 16
\******************************************************************************/
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiTranStatLimDft_C /* 
   Unit       : s
   Description: Temps de transition du couple limité en cas de défaut
   LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 5 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_nIdlHys_C /* 
   Unit       : RPM
   Description: Seuil de régime calibrable par rapport à la consigne de ralenti
   LSB: 2^-2 OFF:  0 MIN/MAX:  0 .. 8000 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_spdVehDft_C /* 
   Unit       : km/h
   Description: Valeur de recouvrement de la vitesse vehicule en cas de défaut
   LSB: 2^-7 OFF:  0 MIN/MAX:  0 .. 500 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_spdVehHysLoNotRvs_C /* 
   Unit       : km/h
   Description: Hystérésis  sur seuil de vitesse véhicule EngLim_spdVehLoNotRvs_C
   LSB: 2^-7 OFF:  0 MIN/MAX:  0 .. 500 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_spdVehHysLoRvs_C /* 
   Unit       : km/h
   Description: Hystérésis  sur seuil de vitesse véhicule EngLim_spdVehLoRvs_C
   LSB: 2^-7 OFF:  0 MIN/MAX:  0 .. 500 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_spdVehLoNotRvs_C /* 
   Unit       : km/h
   Description: Seuil de vitesse bas de limitation en marche avant
   LSB: 2^-7 OFF:  0 MIN/MAX:  0 .. 500 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_spdVehLoRvs_C /* 
   Unit       : km/h
   Description: Seuil de vitesse bas de limitation en marche arrière
   LSB: 2^-7 OFF:  0 MIN/MAX:  0 .. 500 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiCluOffNotRvs_C /* 
   Unit       : s
   Description: Temporisation de confirmation de passage à 0 du switch embrayage dans la condition d
   e transition de l'état de limitation marche avant vers l'état de transition temporelle marche ava
   nt
   LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 20 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiCluOffRvs_C /* 
   Unit       : s
   Description: Temporisation de confirmation de passage à 0 du switch embrayage dans la condition d
   e transition de l'état de limitation marche arrière vers l'état de transition temporelle marche a
   rrière
   LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 20 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiCluOff_C /* 
   Unit       : s
   Description: Temporisation de confirmation du passage de l'information Ext_bCluPedPrss de 1 à 0
   LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 20 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiCluOn_C /* 
   Unit       : s
   Description: Temporisation de confirmation du passage de l'information Ext_bCluPedPrss de 0 à 1
   LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 20 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiRvsStOff_C /* 
   Unit       : s
   Description: Temporisation de confirmation du passage de l'information Ext_bRvs de 1 à 0
   LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 20 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiRvsStOn_C /* 
   Unit       : s
   Description: Temporisation de confirmation du passage de l'information Ext_bRvs de 0 à 1
   LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 20 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiSdl_tqLimJ_SC /* LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 65
   5.35 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiTqCkEfcNotRvsCfm_C /* 
   Unit       : s
   Description: Temporisation de confirmation pour condition TqSys_tqCkEfcFil >= EngLim_tqCkEfcNotRv
   s
   LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 20 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiTqCkEfcRvsCfm_C /* 
   Unit       : s
   Description: Temporisation de confirmation pour condition TqSys_tqCkEfcFil >= EngLim_tqCkEfcRvs
   LSB: 0.01 OFF:  0 MIN/MAX:  0 .. 20 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiTranNotRvs_C /* 
   Unit       : s
   Description: Durée de la transition temporelle de l'état de limitation marche avant de vers l'éta
   t non limité
   LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 10 */;
extern AR_MERGEABLE_CALIB_16BIT UInt16 EngLim_tiTranRvs_C /* 
   Unit       : s
   Description: Durée de la transition temporelle de l'état de limitation marche arrière de vers l'é
   tat non limité
   LSB: 0.1 OFF:  0 MIN/MAX:  0 .. 10 */;
extern AR_MERGEABLE_CALIB_16BIT SInt16 EngLim_tqCkEfcDft_C /* 
   Unit       : N.m
   Description: Seuil de couple  CME quand la température d'eau est en défaut
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_MERGEABLE_CALIB_16BIT SInt16 EngLim_tqCkEfcInRtMax_C /* 
   Unit       : N.m
   Description: Couple maxi de limitation dans l'état non limité
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;

#define ENGLIM_STOP_SEC_CALIB_16BIT
#include "EngLim_MemMap.h"

#define ENGLIM_START_SEC_CALIB_8BIT
#include "EngLim_MemMap.h"

/******************************************************************************\
   AR_MERGEABLE_CALIB_8BIT: Mergeable Calib 8 bits for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_MERGEABLE_CALIB_8BIT UInt8 EngLim_stTranNotRvs_C /* 
   Description: Flag de configuration pour le choix de la transition de l'état de limitation de coup
   le vers l'état non limité :
   LSB: 2^0 OFF:  0 MIN/MAX:  1 .. 3 */;
extern AR_MERGEABLE_CALIB_8BIT UInt8 EngLim_stTranRvs_C /* 
   Description: Flag de configuration pour le choix de la transition de l'état de limitation de coup
   le vers l'état non limité :
   LSB: 2^0 OFF:  0 MIN/MAX:  1 .. 3 */;

#define ENGLIM_STOP_SEC_CALIB_8BIT
#include "EngLim_MemMap.h"

#define ENGLIM_START_SEC_CALIB_BOOLEAN
#include "EngLim_MemMap.h"

/******************************************************************************\
   AR_MERGEABLE_CALIB_BOOLEAN: Mergeable Calib 1 bit for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_MERGEABLE_CALIB_BOOLEAN Boolean EngLim_bCluStDft_C /* 
   Description: Valeur de EngLim_bCluFil en cas de défaut de l'information embrayage et à l'initiali
   sation
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_MERGEABLE_CALIB_BOOLEAN Boolean EngLim_bManEna_C /* 
   Description: Flag de présence BVM et d'inhibition de la fonction
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_MERGEABLE_CALIB_BOOLEAN Boolean EngLim_bNotRvsLim_C /* 
   Description: Bit de configuration d'inhibition de la limitation en marche avant
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_MERGEABLE_CALIB_BOOLEAN Boolean EngLim_bRvsStDft_C /* 
   Description: Valeur de EngLim_RvsStFil en cas de défaut de l'information marche arrière et à l'in
   itialisation
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

#define ENGLIM_STOP_SEC_CALIB_BOOLEAN
#include "EngLim_MemMap.h"

#define ENGLIM_START_SEC_CARTO_16BIT
#include "EngLim_MemMap.h"

/******************************************************************************\
   AR_MERGEABLE_CARTO_16BIT: Mergeable Carto 16 bits for AUTOSAR modules | Width: 16
\******************************************************************************/
extern AR_MERGEABLE_CARTO_16BIT SInt16 EngLim_tqCkEfcStatLimAMT_M[16][10] /* 
   Unit       : N.m
   Description: Carto de couple effectif de limitation BVMP
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_MERGEABLE_CARTO_16BIT SInt16 EngLim_tqCkEfcStatLimAT_M[16][10] /* 
   Unit       : N.m
   Description: Carto de couple effectif de limitation BVA
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_MERGEABLE_CARTO_16BIT SInt16 EngLim_tqCkEfcStatLimDft_T[16] /* 
   Unit       : N.m
   Description: Carto de couple effectif de limitation dans le cas où l'information rapport de boite
    n'est pas disponible.
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_MERGEABLE_CARTO_16BIT SInt16 EngLim_tqCkEfcStatLimMT_M[16][10] /* 
   Unit       : N.m
   Description: Carto de couple effectif de limitation BVM
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_MERGEABLE_CARTO_16BIT UInt16 EngLim_tqCkEfcStatLimX_A[16] /* 
   Unit       : RPM
   Description: Point d'appuis en régime commun à tous les cartographies
   LSB: 2^-2 OFF:  0 MIN/MAX:  0 .. 8000 */;
extern AR_MERGEABLE_CARTO_16BIT UInt16 EngLim_nEngTqLim_A[16] /* 
   Unit       : RPM
   Description: Vecteur de points d'appui en régime pour la cartographie de couple
   LSB: 2^-2 OFF:  0 MIN/MAX:  0 .. 8000 */;
extern AR_MERGEABLE_CARTO_16BIT SInt16 EngLim_tCoMesTqLim_A[5] /* 
   Unit       : °C
   Description: Points d'appui en température d'eau
   LSB: 2^-2 OFF:  0 MIN/MAX:  -50 .. 200 */;
extern AR_MERGEABLE_CARTO_16BIT SInt16 EngLim_tqCkEfcMaxHiNotRvs_T[16] /* 
   Unit       : N.m
   Description: Vecteur de valeurs de couple de limitation, fonction du régime moteur en marche avan
   t.  De manière à calibrer finement le régime de limitation pour éviter les pompages, les breakpoi
   nts de régimes sont spécifiques à la fonction
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_MERGEABLE_CARTO_16BIT SInt16 EngLim_tqCkEfcMaxHiRvs_T[16] /* 
   Unit       : N.m
   Description: Vecteur de valeurs de couple de limitation, fonction du régime moteur en marche arri
   ère. De manière à calibrer finement le régime de limitation pour éviter les pompages, les breakpo
   ints de régimes sont spécifiques à la fonction
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_MERGEABLE_CARTO_16BIT SInt16 EngLim_tqCkEfcMaxLoNotRvs_T[16] /* 
   Unit       : N.m
   Description: Vecteur de valeurs de couple de limitation, fonction du régime moteur en marche avan
   t. De manière à calibrer finement le régime de limitation pour éviter les pompages, les breakpoin
   ts de régimes sont spécifiques à la fonction
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_MERGEABLE_CARTO_16BIT SInt16 EngLim_tqCkEfcMaxLoRvs_T[16] /* 
   Unit       : N.m
   Description: Vecteur de valeurs de couple de limitation, fonction du régime moteur en marche arri
   ère. De manière à calibrer finement le régime de limitation pour éviter les pompages, les breakpo
   ints de régimes sont spécifiques à la fonction
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_MERGEABLE_CARTO_16BIT SInt16 EngLim_tqCkEfcNotRvs_T[5] /* 
   Unit       : N.m
   Description: Vecteur de seuil de CME fonction de la température d'eau, pour condition de transiti
   on de l'état Limité marche avant vers un état de transition
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_MERGEABLE_CARTO_16BIT SInt16 EngLim_tqCkEfcRvs_T[5] /* 
   Unit       : N.m
   Description: Vecteur de seuil de CME fonction de la température d'eau, pour condition de transiti
   on de l'état Limité marche arrière vers un état de transition
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;

#define ENGLIM_STOP_SEC_CARTO_16BIT
#include "EngLim_MemMap.h"

#define ENGLIM_START_SEC_CARTO_8BIT
#include "EngLim_MemMap.h"

/******************************************************************************\
   AR_MERGEABLE_CARTO_8BIT: Mergeable Carto 8 bits for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_MERGEABLE_CARTO_8BIT SInt8 EngLim_tqCkEfcStatLimY_A[10] /* 
   Description: Point d'appuis en rapport de boite commun à tous les cartographies
   LSB: 2^0 OFF:  0 MIN/MAX:  -1 .. 8 */;

#define ENGLIM_STOP_SEC_CARTO_8BIT
#include "EngLim_MemMap.h"

#define ENGLIM_START_SEC_INTERNAL_VAR_16BIT
#include "EngLim_MemMap.h"

/******************************************************************************\
   AR_INTERNAL_VAR_DISP_16BIT: Display 16 bits for AUTOSAR modules | Width: 16
\******************************************************************************/
extern AR_INTERNAL_VAR_DISP_16BIT UInt16 EngLim_spdVehFil /* 
   Unit       : km/h
   Description: Vitesse Véhicule avec une valeur par défaut en mode défaut
   LSB: 2^-7 OFF:  0 MIN/MAX:  0 .. 500 */;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 EngLim_tqCkEfcMaxHiNotRvs /* 
   Unit       : N.m
   Description: Couple moteur effectif maximum haut en MAV
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2048 .. 2047.9375 */;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 EngLim_tqCkEfcMaxHiRvs /* 
   Description: Couple moteur effectif maximum haut en MAR
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2048 .. 2047.9375 */;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 EngLim_tqCkEfcMaxLoNotRvs /* 
   Description: Couple moteur effectif maximum bas en MAV
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2048 .. 2047.9375 */;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 EngLim_tqCkEfcMaxLoRvs /* 
   Description: Couple moteur effectif maximum bas en MAR
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2048 .. 2047.9375 */;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 EngLim_tqCkEfcNotRvs /* 
   Description: Couple moteur effectif en MAV
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 EngLim_tqCkEfcRvs /* 
   Description: Couple moteur effectif en MAR
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 EngLim_tqCkMaxNotRvsTTran /* 
   Description: Couple de limitation en MAV
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 EngLim_tqCkMaxRvsTTran /* 
   Description: Couple de limitation en MAR en transition temporelle
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;
extern AR_INTERNAL_VAR_DISP_16BIT SInt16 EngLim_tqCkMaxRvsVehTran /* 
   Description: Couple de limitation en MAR en transition par la vitesse
   LSB: 2^-4 OFF:  0 MIN/MAX:  -2000 .. 2000 */;

#define ENGLIM_STOP_SEC_INTERNAL_VAR_16BIT
#include "EngLim_MemMap.h"

#define ENGLIM_START_SEC_INTERNAL_VAR_BOOLEAN
#include "EngLim_MemMap.h"

/******************************************************************************\
   AR_INTERNAL_VAR_DISP_BOOLEAN: Display Boolean for AUTOSAR modules | Width: 8
\******************************************************************************/
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bCluFil /* 
   Description: Booléen indiquant l'état d'embrayage :
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bEndTTranNotRvs /*
   Description: Flag de fin de transition temporelle en marche avant */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bEndTTranRvs /* 
   Description: Flag de fin de transition temporelle en marche arrière
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bEndVehSpdTranRvs /*
   Description: Flag de fin de transition en vitesse en marche arrière */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bIdl /*
   Description: Flag de detection de seuil de régime ralenti */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bLimNotRvs /* 
   Description: Condition MAV
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bLimRvs /* 
   Description: Condition limitation MAR
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bNotRvsLim;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bNotRvsTTran /* 
   Description: Condition correspondant à l'activation de la transition  de l'état de limitation mar
   che avant vers l'état de transition temporelle marche avant
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bNotRvsTiTran;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bRvsFil /* 
   Description: Flag indiquant si la marche arrière est engagée ou non(Si Information Marche Arrière
    disponible sur le CAN)
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bRvsLim /*
   Description: Condition correspondant à l'activation de l'état de limitation en MAR */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bRvsTTran /* 
   Description: Condition correspondant à l'activation de  la transition de l'état de limitation mar
   che arrière vers l'état de transition temporelle marche arrière
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bRvsTiTran;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bRvsVehSpdTran /* 
   Description: Condition correspondant à l'activation de la transition entre l'état de limitation m
   arche arrière vers l'état de transition en vitesse
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bTqCkNotRvs /* 
   Description: Condition de seuil de couple pour transition de l'état de limitation marche avant ve
   rs l'état non limité
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
extern AR_INTERNAL_VAR_DISP_BOOLEAN Boolean EngLim_bTqCkRvs /* 
   Description: Condition de seuil de couple pour transition de l'état de limitation marche arrière 
   vers l'état non limité
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

#define ENGLIM_STOP_SEC_INTERNAL_VAR_BOOLEAN
#include "EngLim_MemMap.h"

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

#endif/*_ENGLIM_CALIBRATIONS_H_ */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
